Repository Snapmaker/Luban, pull requests merged in 2020-09, with the labels that each got.

#428 Improvement: Fix dwell time unit for laser greyscale mode
  src/app/widgets/CncLaserShared/GcodeParameters.jsx
Labels: Type: Improvement

#433 Fix: Fix parse of SVG <pattern> to avoid extra parsed shapes
  src/shared/lib/SVGParser/Parser.js
Labels: Type: Fix

#430 Fix: Fix SVG numeric parsing
  src/shared/lib/SVGParser/AttributesParser.js
Labels: Type: Fix

#426 Fix: Fix the bug for tool path render
  src/app/widgets/ToolPathRenderer.js
Labels: Type: Fix

#434 Improvement: Improve project saving pop-up window (button order and copywriting)
  src/app/containers/App.jsx
  src/app/flux/project/index.js
Labels: Type: Improvement

#432 Refactor: Refactor behavior of single-select operators (3DP)
  src/app/components/SMCanvas/Controls.jsx
  src/app/components/SMCanvas/TransformControls.js
  src/app/flux/keyboardShortcut/index.js
  src/app/flux/models/Model.js
  src/app/flux/models/ModelGroup.js
  src/app/flux/printing/index.js
  src/app/widgets/CncLaserShared/styles.styl
  src/app/widgets/PrintingObjectList/PrintingObjectListBox.jsx
  src/app/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/widgets/PrintingVisualizer/VisualizerModelTransformation.jsx
Labels: Type: Improvement

#435 Feature: Add multi-select operation to editor (Laser & CNC)
  src/app/components/SMCanvas/Controls.jsx
  src/app/components/SMCanvas/TransformControls2D.js
  src/app/flux/editor/index.js
  src/app/flux/editor/svg-model.js
  src/app/flux/editor/threejs-model.js
  src/app/flux/models/Model.js
  src/app/flux/models/ModelGroup.js
  src/app/flux/models/SvgModel.js
  src/app/flux/models/SvgModelGroup.js
  src/app/flux/models/ToolPathModel.js
  src/app/flux/models/ToolPathModelGroup.js
  src/app/widgets/CNCPath/CNCPath.jsx
  src/app/widgets/CNCVisualizer/Visualizer.jsx
  src/app/widgets/CncLaserObjectList/ObjectListBox.jsx
  src/app/widgets/CncLaserShared/GcodeParameters.jsx
  src/app/widgets/CncLaserShared/TextParameters.jsx
  src/app/widgets/CncLaserShared/Transformation.jsx
  src/app/widgets/CncLaserSvgEditor/SVGCanvas.jsx
  src/app/widgets/CncLaserSvgEditor/SVGEditor.jsx
  src/app/widgets/CncLaserSvgEditor/SvgTool.jsx
  src/app/widgets/CncLaserSvgEditor/svg-content/OperatorPoints.js
  src/app/widgets/CncLaserSvgEditor/svg-content/SVGContentGroup.js
  src/app/widgets/CncLaserSvgEditor/svg-content/SelectorManager.js
  src/app/widgets/CncLaserSvgEditor/text-actions.js
  src/app/widgets/LaserParams/LaserParameters.jsx
  src/app/widgets/LaserParams/config/ConfigGreyscale.jsx
  src/app/widgets/LaserParams/config/ConfigRasterBW.jsx
  src/app/widgets/LaserParams/config/ConfigRasterVector.jsx
  src/app/widgets/LaserParams/gcodeconfig/GcodeConfigGreyscale.jsx
  src/app/widgets/LaserParams/gcodeconfig/GcodeConfigRasterBW.jsx
  src/app/widgets/LaserVisualizer/Visualizer.jsx
  src/app/widgets/PrintingVisualizer/VisualizerModelTransformation.jsx
Labels: Type: Feature

#425 Fix: Fix bugs for SVG Editor
  src/app/flux/models/Model.js
  src/app/flux/models/SvgModel.js
  src/app/widgets/CncLaserShared/TextParameters.jsx
  src/app/widgets/CncLaserShared/Transformation.jsx
  src/app/widgets/CncLaserSvgEditor/SVGCanvas.jsx
  src/app/widgets/CncLaserSvgEditor/SVGEditor.jsx
  src/server/DataStorage.js
Labels: Category: Editor, Type: Fix

#449 Fix: Fix offscreen canvas undefined in electron
  src/app/flux/models/SvgModel.js
Labels: Type: Fix

#443 Fix: Fix long file name hide button in objectlist
  src/app/components/SMCanvas/Controls.jsx
  src/app/components/SMCanvas/TransformControls.js
  src/app/flux/models/ModelGroup.js
  src/app/widgets/PrintingObjectList/PrintingObjectListBox.jsx
Labels: Type: Fix

#444 Fix: Fix jump to the corresponding page when saving file
  src/app/containers/App.jsx
Labels: Type: Fix

#457 Build: Add support for RPM packages
  .travis.yml
  README.md
  package.json
Labels: Type: Build

#456 Bugfix: Bugfixes for v3.9.0-beta.5
  .travis.yml
  package-lock.json
  src/app/containers/Header/QuickAccessToolbar.jsx
  src/app/flux/editor/index.js
  src/app/flux/models/Model.js
  src/app/flux/models/SvgModel.js
  src/app/flux/models/SvgModelGroup.js
  src/app/widgets/CncLaserShared/Transformation.jsx
Labels: Type: Fix

#441 Improvement: Be able to create new file
  src/app/containers/App.jsx
  src/app/flux/project/index.js
  src/app/lib/uni-api.js
  src/electron-app/Menu.js
Labels: Category: Editor, Type: Feature

#442 Fix: Fix application window position when reopening in external window
  src/main.js
Labels: Category: UX, Type: Improvement

#459 Improvement: Change style of 3DP transformation reset-button
  src/app/widgets/PrintingVisualizer/styles.styl
Labels: Type: Improvement

#462 Fix: OnToggleExpand is not defined in cnc relief
  src/app/widgets/CNCPath/gcodeconfig/ReliefGcodeParameters.jsx
Labels: Type: Fix

#463 Fix: Hide the operation grips in laser|cnc after init
  src/app/widgets/CncLaserSvgEditor/svg-content/OperatorPoints.js
Labels: Type: Fix

#466 Fix: Fix config file not found err when open file
  src/server/services/api/api-file.js
Labels: Type: Fix

#460 Improvement: Change copywriting of switches in workspace
  src/app/widgets/Connection/WifiConnection.jsx
  src/app/widgets/Enclosure/Enclosure.jsx
  src/app/widgets/Marlin/CNC.jsx
  src/app/widgets/Marlin/Laser.jsx
Labels: Type: Improvement

#461 Feature: Add newsprint process mode for svg image
  package.json
  src/app/flux/models/ModelInfoUtils.js
  src/app/images/cnc-laser/laser-mode-newsprint-88x88.png
  src/app/widgets/CncLaserShared/styles.styl
  src/app/widgets/CncLaserSvgEditor/PrintableArea.js
  src/app/widgets/LaserParams/ImageProcessMode.jsx
  src/app/widgets/LaserParams/LaserParameters.jsx
  src/app/widgets/LaserParams/config/ConfigNewsprint.jsx
  src/package.json
  src/server/lib/ToolPathGenerator/LaserToolPathGenerator.js
  src/server/lib/image-process.js
Labels: Category: Editor, Category: Laser, Type: Feature
