Repository Snapmaker/Luban, pull requests merged in 2020-11, with the labels that each got.

#486 Improvement: Optimize file drop area; Make pictures undraggable
  src/app/components/Dropzone/index.jsx
  src/app/components/Dropzone/index.styl
  src/app/components/OptionalDropdown/OptionalDropdown.jsx
  src/app/containers/Cnc/Cnc.jsx
  src/app/containers/Header/Header.jsx
  src/app/containers/Header/QuickAccessToolbar.jsx
  src/app/containers/Laser/Laser.jsx
  src/app/containers/Printing/Printing.jsx
  src/app/containers/Sidebar/Sidebar.jsx
  src/app/containers/Workspace/Workspace.jsx
  src/app/widgets/CNCPath/ImageProcessMode.jsx
  src/app/widgets/CNCTool/ToolParameters.jsx
  src/app/widgets/CncLaserObjectList/ObjectListBox.jsx
  src/app/widgets/CncLaserObjectList/styles.styl
  src/app/widgets/CncLaserShared/Transformation.jsx
  src/app/widgets/LaserParams/ImageProcessMode.jsx
  src/app/widgets/PrintingConfigurations/Configurations.jsx
  src/app/widgets/PrintingMaterial/Material.jsx
  src/app/widgets/PrintingObjectList/images/list_ic_3d_18x18.png
  src/app/widgets/PrintingObjectList/styles.styl
  src/app/widgets/PrintingVisualizer/VisualizerCameraOperations.jsx
  src/app/widgets/WifiTransport/WifiTransport.jsx
Labels: Type: Improvement

#492 Fix: Actions has wrong disabled state in laser and cnc
  src/app/flux/editor/index.js
Labels: Type: Fix

#524 Feature: Add firmware tool for package firmare on settings
  src/app/api/index.js
  src/app/containers/App.jsx
  src/app/containers/Settings/FirmwareTool/FirmwareTool.jsx
  src/app/containers/Settings/FirmwareTool/index.js
  src/app/containers/Settings/FirmwareTool/index.styl
  src/app/containers/Settings/Settings.jsx
  src/server/lib/firmware-build.js
  src/server/services/api/api-file.js
  src/server/services/index.js
Labels: Type: Feature

#527 Improvement: Set cura config support_wall_count
  resources/CuraEngine/Config/snapmaker.def.json
  src/app/flux/printing/DefinitionManager.js
Labels: Category: 3DP

#521 Improvement: Hide configuration widget when nothing selected in laser…
  src/app/widgets/CNCPath/CNCPath.jsx
  src/app/widgets/LaserParams/LaserParameters.jsx
Labels: Type: Improvement

#526 Improvement: Add threshold param for laser halftone effect
  package.json
  src/app/images/cnc-laser/laser-mode-halftone-88x88.png
  src/app/models/ModelInfoUtils.js
  src/app/widgets/CncLaserShared/styles.styl
  src/app/widgets/LaserParams/ImageProcessMode.jsx
  src/app/widgets/LaserParams/LaserParameters.jsx
  src/app/widgets/LaserParams/config/ConfigHalftone.jsx
  src/package.json
  src/server/index.js
  src/server/lib/ToolPathGenerator/LaserToolPathGenerator.js
  src/server/lib/image-process.js
  src/server/lib/jimp/index.js
  src/server/lib/jimp/jimp-plugin-alphaToWhite.js
  src/server/lib/jimp/jimp-plugin-bw.js
  src/server/lib/jimp/jimp-plugin-greyscale.js
  src/server/lib/jimp/jimp-plugin-halftone.js
  src/server/lib/jimp/jimp-plugin-threshold.js
  src/server/services/task-manager/generateToolPath.js
Labels: Type: Improvement

#530 Feature: Add Z axis setting for Snapmaker Original (M1025)
  src/app/containers/Settings/MachineSettings/MachineSettings.jsx
  src/app/flux/develop-tools/index.js
  src/app/flux/machine/index.js
  src/app/models/SvgModel.js
  src/server/controllers/Marlin/Marlin.js
Labels: Type: Feature

#514 Feature: Emergency stop module in serial port and wifi
  src/app/constants/index.js
  src/app/flux/machine/Server.js
  src/app/flux/machine/index.js
  src/app/images/connection/ic_emergency_stop.png
  src/app/lib/controller.js
  src/app/widgets/WorkspaceVisualizer/Visualizer.jsx
  src/server/controllers/Marlin/Marlin.js
  src/server/controllers/Marlin/MarlinController.js
Labels: Type: Feature

#531 Improvement: Modify some unreasonable English term description
  resources/CuraEngine/Config/snapmaker.def.json
  src/app/containers/Settings/MachineSettings/MachineSettings.jsx
  src/app/flux/printing/index.js
  src/app/i18n/cs/resource.json
  src/app/i18n/de/resource.json
  src/app/i18n/en/resource.json
  src/app/i18n/es/resource.json
  src/app/i18n/fr/resource.json
  src/app/i18n/hu/resource.json
  src/app/i18n/it/resource.json
  src/app/i18n/ja/resource.json
  src/app/i18n/ko/resource.json
  src/app/i18n/pt-br/resource.json
  src/app/i18n/ru/resource.json
  src/app/i18n/uk/resource.json
  src/app/i18n/zh-cn/resource.json
  src/app/i18n/zh-tw/resource.json
  src/app/widgets/CNCPath/ImageProcessMode.jsx
  src/app/widgets/CNCPath/VectorParameters.jsx
  src/app/widgets/CNCTool/ToolParameters.jsx
  src/app/widgets/CncLaserOutput/Output.jsx
  src/app/widgets/CncLaserShared/GcodeParameters.jsx
  src/app/widgets/Connection/LaserState.jsx
  src/app/widgets/Enclosure/Enclosure.jsx
  src/app/widgets/LaserParams/ImageProcessMode.jsx
  src/app/widgets/PrintingConfigurations/Configurations.jsx
  src/app/widgets/PrintingOutput/Output.jsx
  src/app/widgets/PrintingVisualizer/Visualizer.jsx
Labels: Type: Improvement

#533 Fix: Fix uploaded file with uppercase suffix cannot be recognized
  src/server/services/api/api-image.js
Labels: Type: Fix

#532 Feature: Add autoupdate feature and modify package.json to support autoupdate
  appveyor.yml
  package.json
  src/app/containers/App.jsx
  src/app/containers/Settings/General/General.jsx
  src/app/containers/Settings/General/index.styl
  src/app/flux/machine/index.js
  src/app/lib/uni-api.js
  src/main.js
  src/package.json
Labels: Type: Build

#536 Fix: Show progress error in 3dp Gcode previewing
  src/app/flux/machine/index.js
  src/app/flux/printing/index.js
Labels: Type: Fix

#538 Fix: Show progress error in 3DP G-code previewing
  src/app/flux/cnc/index.js
  src/app/flux/laser/index.js
  src/app/flux/printing/index.js
  src/app/flux/project/index.js
Labels: Category: 3DP, Type: Fix

#537 Improvement: Optimize English terms and descriptions
  resources/CuraEngine/Config/snapmaker.def.json
  src/app/i18n/de/resource.json
  src/app/i18n/en/resource.json
  src/app/i18n/es/resource.json
  src/app/i18n/fr/resource.json
  src/app/i18n/hu/resource.json
  src/app/i18n/it/resource.json
  src/app/i18n/ja/resource.json
  src/app/i18n/ko/resource.json
  src/app/i18n/pt-br/resource.json
  src/app/i18n/ru/resource.json
  src/app/i18n/uk/resource.json
  src/app/i18n/zh-cn/resource.json
  src/app/i18n/zh-tw/resource.json
  src/app/widgets/CNCPath/VectorParameters.jsx
Labels: Type: Improvement

#539 Fix: Fix drop area and make Anchor component undraggable
  package.json
  src/app/components/Anchor/AnchorUndraggable.jsx
  src/app/components/Anchor/index.js
  src/app/components/Dropzone/index.jsx
Labels: Category: UX, Type: Improvement

#541 Fix: Fix wrong positioning of selector of multiple models rotation
  src/app/components/Input/DegreeInput.jsx
  src/app/models/SVGActionsFactory.js
  src/app/ui/SVGEditor/svg-content/SVGContentGroup.js
Labels: Type: Fix

#543 Fix: Fix bugs for v3.11.0-alpha.3
  src/app/flux/printing/index.js
  src/app/flux/project/index.js
  src/app/widgets/CaseLibrary/index.jsx
  src/app/widgets/PrintingConfigurations/Configurations.jsx
  src/server/lib/image-process.js
  src/server/lib/svg-convert.js
Labels: Type: Fix

#544 Fix show progress error in 3dp g code previewing
  src/app/flux/project/index.js
Labels: Category: 3DP, Type: Fix

#547 Fix: Fix G-code display date; Parse thumbnail header of G-code
  src/app/flux/editor/index.js
  src/app/flux/printing/index.js
  src/app/flux/workspace/index.js
  src/app/widgets/WifiTransport/WifiTransport.jsx
  src/app/widgets/WorkspaceVisualizer/Visualizer.jsx
  src/server/lib/parseGcodeHeader.js
  src/server/services/api/api-file.js
  src/server/services/task-manager/generateGcode.js
Labels: Type: Fix

#548 Improvement: Add message for autoupdate
  src/app/containers/App.jsx
  src/app/containers/Settings/General/General.jsx
  src/app/containers/Settings/General/index.styl
  src/app/flux/machine/index.js
  src/main.js
Labels: Type: Improvement

#551 Fix: Fix window title not update on switching tab
  src/app/containers/App.jsx
  src/app/flux/project/index.js
Labels: Type: Fix

#553 Fix: Fix gcode export file suffix-type error
  src/app/lib/uni-api.js
  src/server/services/task-manager/generateGcode.js
  src/server/services/task-manager/generateToolPath.js
Labels: Type: Fix

#556 Fix: Fix loading case bug
  src/app/widgets/CaseLibrary/index.jsx
  src/app/widgets/PrintingConfigurations/Configurations.jsx
Labels: Type: Fix

#529 Build: Build alpha versions of v3.11
  package-lock.json
  package.json
  src/app/widgets/WifiTransport/WifiTransport.jsx
  src/package.json
  src/server/lib/firmware-build.js
Labels: Type: Build

#550 Improvement: Set laser text process mode to vector
  package.json
  src/app/api/index.js
  src/app/flux/editor/index.js
  src/app/models/SVGActionsFactory.js
  src/app/models/SvgModel.js
  src/app/widgets/LaserParams/LaserParameters.jsx
  src/package.json
  src/server/lib/FontManager.js
  src/server/lib/svg-convert.js
  src/server/services/api/api-svg.js
  src/server/services/api/api-utils.js
  src/server/services/index.js
  src/server/services/task-manager/generateToolPath.js
Labels: Type: Improvement

#558 Fix: Change object name in object list
  src/app/models/Model.js
  src/app/models/ModelGroup.js
  src/app/widgets/PrintingObjectList/PrintingObjectListBox.jsx
Labels: Type: Fix

#563 Improvement: Change right click interaction on printing
  src/app/components/SMCanvas/Controls.jsx
  src/server/lib/FontManager.js
Labels: Category: UX, Type: Improvement

#546 Improvement: Add progress for image processing
  src/app/flux/cnc/index.js
  src/app/flux/editor/index.js
  src/app/flux/laser/index.js
  src/app/flux/printing/index.js
  src/app/lib/controller.js
  src/app/widgets/CNCVisualizer/Visualizer.jsx
  src/app/widgets/LaserVisualizer/Visualizer.jsx
  src/app/workers/LoadModel.worker.js
  src/server/lib/image-process.js
  src/server/services/index.js
  src/server/services/task-manager/TaskManager.js
  src/server/services/task-manager/index.js
  src/server/services/task-manager/processImage.js
Labels: Category: Editor, Type: Improvement

#566 Improvement: Not process model after translate and rotate in svgEditor
  src/app/flux/cnc/index.js
  src/app/flux/editor/index.js
  src/app/flux/laser/index.js
  src/app/flux/project/index.js
  src/app/models/SVGActionsFactory.js
Labels: Category: Editor, Type: Improvement

#565 Fix: Fix print order display bug on laser/cnc
  src/app/flux/editor/index.js
Labels: Type: Fix

#568 Fix: Fix font-manager cannot electron-rebuild when packaging
  package.json
  src/server/lib/FontManager.js
Labels: Type: Fix

#570 Fix: Fix right click interaction on printing
  src/app/components/SMCanvas/Canvas.jsx
  src/app/components/SMCanvas/Controls.jsx
  src/app/constants/index.js
  src/app/flux/printing/index.js
  src/app/models/ModelGroup.js
  src/app/widgets/PrintingVisualizer/Visualizer.jsx
Labels: Type: Fix

#555 Improvement: Improve console widgets in workspace
  src/app/lib/uni-api.js
  src/app/widgets/Console/Console.jsx
  src/app/widgets/Console/Terminal.jsx
  src/package.json
Labels: Type: Fix

#571 Fix text process image bug
  src/app/flux/editor/index.js
  src/app/models/Model.js
  src/app/models/SVGActionsFactory.js
  src/app/models/SvgModel.js
  src/app/widgets/CNCVisualizer/Visualizer.jsx
  src/app/widgets/LaserVisualizer/Visualizer.jsx
  src/server/lib/ToolPathGenerator/CncToolPathGenerator.js
  src/server/lib/ToolPathGenerator/LaserToolPathGenerator.js
  src/server/services/task-manager/generateToolPath.js
Labels: Category: CNC, Category: Laser, Type: Fix

#575 Fix: Fix style in object list
  src/app/widgets/CncLaserObjectList/ObjectListBox.jsx
  src/app/widgets/PrintingObjectList/PrintingObjectListBox.jsx
  src/app/widgets/PrintingObjectList/styles.styl
  src/package.json
Labels: Type: Improvement

#576 Fix: Get processed model by modelId but not selected
  src/app/flux/editor/index.js
Labels: Category: Editor, Type: Fix

#582 Fix: Fix the problem of long parsing time of gcode headers
  src/app/containers/DevelopTools/GcodeFile.jsx
  src/server/lib/parseGcodeHeader.js
  src/server/services/api/api-file.js
Labels: Type: Fix

#581 Fix: Fix 3dp peripherals position after arrange models
  src/app/models/ModelGroup.js
Labels: Category: 3DP, Type: Fix

#584 Fix: Fix not selecting toolpathmodel when selecting elements on edit
  src/app/flux/editor/index.js
  src/app/flux/laser/index.js
Labels: Type: Fix

#572 Build: Build alpha versions for v3.12
  package-lock.json
  package.json
  src/package.json
Labels: Type: Build

#592 Fix: Correct G-code header parsing forloop
  package-lock.json
  package.json
  src/package.json
  src/server/lib/parseGcodeHeader.js
Labels: Type: Fix

#587 Fix: Fix error when connect fabscreen without config and open-file error
  src/app/flux/laser/index.js
  src/app/flux/machine/index.js
  src/app/widgets/Marlin/Laser.jsx
  src/main.js
Labels: Type: Fix

#588 Feature: Add process modes for SVG images
  src/app/flux/editor/index.js
  src/app/models/Model.js
  src/app/models/SvgModel.js
  src/app/widgets/CNCPath/CNCPath.jsx
  src/app/widgets/CNCPath/ImageProcessMode.jsx
  src/app/widgets/LaserParams/ImageProcessMode.jsx
  src/app/widgets/LaserParams/LaserParameters.jsx
  src/app/widgets/LaserParams/gcodeconfig/GcodeConfigRasterVector.jsx
  src/app/widgets/LaserParams/gcodeconfig/GcodeConfigVector.jsx
  src/server/lib/image-process.js
  src/server/lib/svg-convert.js
  src/server/services/task-manager/generateToolPath.js
Labels: Type: Feature

#580 Improvement: Disable generate gcode button when models are all hidden
  src/app/models/ModelGroup.js
  src/app/widgets/PrintingOutput/Output.jsx
Labels: Type: Improvement

#586 Improvement: Limit scale value in 3DP to avoid object dimension setting to 0
  src/app/components/SMCanvas/TransformControls.js
  src/app/widgets/PrintingVisualizer/VisualizerModelTransformation.jsx
Labels: Type: Improvement
