Repository Snapmaker/Luban, pull requests merged in 2020-10, with the labels that each got.

#474 Improvement: Unselect all models when slice completed
  src/app/flux/printing/index.js
Labels: Category: UX

#472 Improvement: convert svg's component paths one at a time
  src/server/lib/ToolPathGenerator/SVGFill.js
Labels: Type: Improvement

#475 Fix: Fix issue on svg text generate gcode
  src/app/flux/models/SvgModelGroup.js
  src/app/widgets/CNCPath/CNCPath.jsx
  src/app/widgets/LaserParams/LaserParameters.jsx
Labels: Category: Editor, Type: Fix

#476 Refactor: Refactor file format to be related with software
  package.json
  src/app/containers/App.jsx
  src/app/flux/project/index.js
  src/app/lib/uni-api.js
  src/electron-app/Menu.js
  src/main.js
Labels: Type: Improvement

#454 Improvement: Remember last Wi-Fi connection
  src/app/components/Modal/ModalSmallInput.jsx
  src/app/flux/machine/index.js
  src/app/widgets/Connection/WifiConnection.jsx
Labels: Type: Improvement

#467 Refactor: Refactor DegreeInput to make it work
  src/app/components/Input/DegreeInput.jsx
  src/app/widgets/CncLaserShared/Transformation.jsx
Labels: Type: Fix

#481 Fix: Fix macos cannot copy in input and bugfixs
  src/app/flux/machine/index.js
  src/app/widgets/CncLaserShared/TextParameters.jsx
  src/electron-app/Menu.js
  src/main.js
Labels: Type: Fix

#483 Fix: Fix wrong JSON.parse usage
  src/app/flux/machine/index.js
  src/main.js
Labels: Type: Fix

#488 Fix: Fix mode error of svg element caused by svg text changing
  src/app/models/SVGActionsFactory.js
  src/app/widgets/CNCPath/CNCPath.jsx
Labels: Type: Fix

#489 Fix: Fix editor not able to continuously create shapes
  src/app/ui/SVGEditor/SVGCanvas.jsx
Labels: Type: Fix

#440 Improvement: Synchronise zoom action
  src/app/components/SMCanvas/Canvas.jsx
  src/app/components/SMCanvas/Controls.jsx
  src/app/containers/App.jsx
  src/app/flux/cnc/index.js
  src/app/flux/laser/index.js
  src/app/flux/machine/index.js
  src/app/ui/SVGEditor/SVGCanvas.jsx
  src/app/ui/SVGEditor/SVGEditor.jsx
  src/app/widgets/CNCVisualizer/Visualizer.jsx
  src/app/widgets/LaserVisualizer/Visualizer.jsx
  src/app/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/widgets/WorkspaceVisualizer/Visualizer.jsx
Labels: Type: Improvement

#490 Fix: Unselect all models when slice complete
  src/app/flux/printing/index.js
Labels: Type: Fix

#482 Feature: Show 3DP model size information in canvas
  src/app/components/SMCanvas/TransformControls.js
  src/app/models/ModelGroup.js
  src/app/widgets/PrintingVisualizer/VisualizerInfo.jsx
Labels: Type: Feature

#491 Fix: Fix bug after rotate multi models in SVGEditor
  src/app/models/SVGActionsFactory.js
Labels: Type: Fix

#494 Fix: Fix error getting matching display
  src/main.js
Labels: Type: Fix

#496 Fix: Fix printing canvas camera position error
  src/app/components/SMCanvas/Canvas.jsx
  src/app/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/widgets/WorkspaceVisualizer/Visualizer.jsx
Labels: Type: Fix

#495 Improvement: Display long file name properly in Object List
  src/app/widgets/CncLaserObjectList/ObjectListBox.jsx
  src/app/widgets/PrintingObjectList/PrintingObjectListBox.jsx
Labels: Type: Fix

#499 Fix: Fix bugs for 3.10
  src/app/flux/project/index.js
  src/app/widgets/CNCVisualizer/Visualizer.jsx
  src/app/widgets/LaserVisualizer/Visualizer.jsx
  src/server/lib/image-process.js
Labels: Type: Fix

#498 Fix: Fix cnc warning modal not show when app updated
  src/app/flux/machine/index.js
Labels: Type: Fix

#504 Fix: Fix bugs for 3.10
  src/server/services/task-manager/generateToolPath.js
Labels: Type: Fix

#505 Fix: Fix bugs for v3.10 (alpha6)
  src/app/models/ModelInfoUtils.js
  src/app/ui/SVGEditor/SvgTool.jsx
  src/app/ui/SVGEditor/constants.js
  src/app/widgets/CNCPath/config/ReliefParameters.jsx
  src/app/widgets/CNCPath/gcodeconfig/ReliefGcodeParameters.jsx
  src/app/widgets/CncLaserObjectList/ObjectListBox.jsx
  src/app/widgets/CncLaserObjectList/styles.styl
  src/app/widgets/PrintingObjectList/PrintingObjectListBox.jsx
  src/app/widgets/PrintingObjectList/styles.styl
Labels: Type: Fix

#506 Fix: Fix CNC tool path bugs
  src/app/models/SVGActionsFactory.js
  src/app/models/SvgModel.js
  src/app/ui/SVGEditor/TextActions.js
  src/server/lib/ToolPathGenerator/CncReliefToolPathGenerator.js
  src/server/services/task-manager/generateToolPath.js
Labels: Type: Fix

#507 Fix: Fix preview model size error in cnc image
  src/app/flux/editor/index.js
Labels: Type: Fix

#511 Build: Add latest.yml file to github releases (for Auto Update)
  .travis.yml
  appveyor.yml
  package.json
Labels: Type: Build

#515 Build: Upload Windows builds YAML files to github release
  .travis.yml
  appveyor.yml
  package.json
Labels: Type: Build

#517 Fix: Fix last display id missing caused application failure
  src/main.js
Labels: Type: Fix

#519 Added new German translation to i18n file
  src/app/i18n/de/resource.json
Labels: Type: Improvement

#520 Fix: Fix configuration widget empty content
  package.json
  src/app/widgets/CaseLibrary/index.jsx
  src/app/widgets/PrintingConfigurations/Configurations.jsx
  src/package.json
Labels: Type: Fix
