Repository Snapmaker/Luban, pull requests merged in 2020-05, with the labels that each got.

#312 Fix: Fix lay flat not working on duplicate model
  src/app/flux/models/ModelGroup.js
Labels: Type: Fix

#305 Feature: Add enclosure feature
  src/app/components/Modal/ModalSmall.jsx
  src/app/components/Modal/modal-small.jsx
  src/app/constants/index.js
  src/app/containers/Settings/MachineSettings/MachineSettings.jsx
  src/app/containers/Workspace/SecondaryWidgets.jsx
  src/app/flux/machine/Server.js
  src/app/flux/machine/index.js
  src/app/flux/widget/WidgetState.js
  src/app/images/connection/ic_WI-FI_64x64.png
  src/app/widgets/Connection/EnclosureState.jsx
  src/app/widgets/Connection/SerialConnection.jsx
  src/app/widgets/Enclosure/Enclosure.jsx
  src/app/widgets/Enclosure/EnclosureDisplay.jsx
  src/app/widgets/Enclosure/index.jsx
  src/app/widgets/Widget.jsx
  src/app/widgets/WorkspaceVisualizer/Visualizer.jsx
  src/main.js
  src/server/controllers/Marlin/Marlin.js
  src/server/controllers/Marlin/MarlinController.js
Labels: Type: Feature

#321 Fix: Fix the bug for STOP button not stop printing when printing via Wi-Fi
  src/app/containers/Header/QuickAccessToolbar.jsx
  src/app/flux/machine/index.js
Labels: Type: Fix

#322 Style: Hide auto preview and generate gcode button when page is editor
  src/app/widgets/CNCOutput/Output.jsx
  src/app/widgets/LaserOutput/Output.jsx
Labels: Category: Editor, Type: Improvement

#324 Fix: Fix bug for Machine custom
  resources/CuraEngine/Config/Custom/quality.fast_print.def.json
  resources/CuraEngine/Config/Custom/quality.high_quality.def.json
  resources/CuraEngine/Config/Custom/quality.normal_quality.def.json
  src/app/constants/index.js
  src/app/containers/Settings/MachineSettings/MachineSettings.jsx
  src/app/flux/machine/index.js
Labels: Type: Fix

#320 Fix: Fix bug that Luban will send G54 when 3dp serial connect
  src/app/flux/machine/index.js
  src/app/widgets/Connection/SerialConnection.jsx
  src/app/widgets/LaserCameraAidBackground/ExtractSquareTrace/index.jsx
Labels: Type: Fix

#325 Fix: Fix local storage data issues for software upgrades and downgrades
  src/app/containers/Workspace/PrimaryWidgets.jsx
  src/app/containers/Workspace/SecondaryWidgets.jsx
  src/app/containers/Workspace/WidgetManager/WidgetManager.jsx
  src/app/containers/Workspace/Workspace.jsx
  src/app/flux/widget/WidgetState.js
Labels: Type: Fix

#326 Fix: Fix 100% filling density does not work
  src/app/flux/printing/DefinitionManager.js
Labels: Category: 3DP, Type: Fix

#327 Fix: Inactive marco button unless connection is open
  src/app/widgets/Macro/Macro.jsx
Labels: Type: Fix

#328 Fix: Fix case path for 250
  src/app/widgets/CaseLibrary/CaseConfig.js
Labels: Type: Fix

#329 Fix: Fix bug for Snapmaker Luban 3.5.0
  src/app/containers/Settings/MachineSettings/MachineSettings.jsx
  src/app/flux/printing/DefinitionManager.js
  src/app/widgets/CNCOutput/Output.jsx
  src/app/widgets/LaserOutput/Output.jsx
  src/app/widgets/PrintingOutput/Output.jsx
Labels: Type: Fix

#331 Feature: Add Ukrainian language support
  gulp/tasks/i18next.js
  scripts/i18n-export-excel.js
  scripts/i18n-import-cura-translations.js
  scripts/i18n-import-excel.js
  src/app/config/settings.js
  src/app/containers/Settings/General/General.jsx
  src/app/i18n/cs/resource.json
  src/app/i18n/de/resource.json
  src/app/i18n/en/resource.json
  src/app/i18n/es/resource.json
  src/app/i18n/fr/resource.json
  src/app/i18n/hu/resource.json
  src/app/i18n/it/resource.json
  src/app/i18n/ja/resource.json
  src/app/i18n/ko/resource.json
  src/app/i18n/pt-br/resource.json
  src/app/i18n/ru/resource.json
  src/app/i18n/uk/controller.json
  src/app/i18n/uk/gcode.json
  src/app/i18n/uk/resource.json
  src/app/i18n/zh-cn/resource.json
  src/app/i18n/zh-tw/resource.json
  src/server/config/settings.base.js
  src/server/config/settings.development.js
  webpack.config.app-i18n.js
Labels: Category: UX, Type: Feature

#332 Build: Update package-lock.json
  package-lock.json
Labels: Type: Build

#334 Fix: Fix bug that ShaderMaterial cant set gl_PointSize
  src/app/workers/ShaderMaterial/workspace-shader-meterial.js
Labels: Category: 3DP, Type: Fix

#335 Fix: Fix the remembering size does not work on windows
  src/main.js
Labels: Category: UX, Type: Fix
