Repository Snapmaker/Luban, pull requests merged in 2020-04, with the labels that each got.

#273 Fix: Fix custom configuration file missing error caused by software upgrade
  package.json
  src/package.json
  src/server/DataStorage.js
Labels: Type: Fix

#256 Feature: Add dxf support for laser and cnc
  src/app/containers/Cnc/Cnc.jsx
  src/app/containers/Laser/Laser.jsx
  src/app/flux/cncLaserShared/index.js
  src/app/flux/generator.js
  src/app/flux/models/Model.js
  src/app/flux/models/ModelInfoUtils.js
  src/app/flux/models/ToolPathModelGroup.js
  src/app/lib/threejs/DxfShaderLine.js
  src/app/lib/threejs/ThreeDxfLoader.js
  src/app/widgets/CNCPath/CNCPath.jsx
  src/app/widgets/LaserParams/LaserParameters.jsx
  src/app/widgets/ToolPathRenderer.js
  src/server/lib/DXFParser/AutoCadColorIndex.js
  src/server/lib/DXFParser/DxfArrayScanner.js
  src/server/lib/DXFParser/DxfParser.js
  src/server/lib/DXFParser/ParseHelpers.js
  src/server/lib/DXFParser/Parser.js
  src/server/lib/DXFParser/entities/3dface.js
  src/server/lib/DXFParser/entities/arc.js
  src/server/lib/DXFParser/entities/attdef.js
  src/server/lib/DXFParser/entities/circle.js
  src/server/lib/DXFParser/entities/dimension.js
  src/server/lib/DXFParser/entities/ellipse.js
  src/server/lib/DXFParser/entities/insert.js
  src/server/lib/DXFParser/entities/line.js
  src/server/lib/DXFParser/entities/lwpolyline.js
  src/server/lib/DXFParser/entities/mtext.js
  src/server/lib/DXFParser/entities/point.js
  src/server/lib/DXFParser/entities/polyline.js
  src/server/lib/DXFParser/entities/solid.js
  src/server/lib/DXFParser/entities/spline.js
  src/server/lib/DXFParser/entities/text.js
  src/server/lib/DXFParser/entities/vertex.js
  src/server/lib/DXFParser/index.js
  src/server/lib/SVGParser/Parser.js
  src/server/lib/ToolPathGenerator/CncToolPathGenerator.js
  src/server/lib/ToolPathGenerator/LaserToolPathGenerator.js
  src/server/services/api/api-image.js
  src/server/services/task-manager/generateToolPath.js
Labels: Category: Editor, Type: Feature

#275 Improvement: Fix copy/paste when using the console
  .eslintignore
  package-lock.json
  package.json
  src/app/styles/xterm.styl
  src/app/widgets/Console/Terminal.jsx
Labels: Category: UX, Type: Fix, Type: Improvement

#282 Fix: Fix a SVG calculation error when unfold arc (A) in <path>
  src/server/lib/SVGParser/BaseTagParser.js
  src/server/lib/SVGParser/Parser.js
Labels: Category: G-code Generator, Type: Fix

#279 Fix: Solve G-code parsing issue on Windows, that extra carriage return is parsed which cause line type not working
  src/shared/lib/gcodeToolPath.js
Labels: Category: 3DP, Priority: High, Type: Fix

#280 Fix: Solve the problem that marco has only a maximum of 10
  src/app/widgets/Macro/Macro.jsx
  src/app/widgets/Macro/index.jsx
  src/server/services/api/api-macros.js
Labels: Type: Fix

#281 Fix: Fix the bug that click camera capture will cause the software to crash
  src/app/constants/index.js
  src/app/flux/machine/index.js
Labels: Type: Fix

#276 Feature: Add import and export to 3DP configuration
  src/app/api/index.js
  src/app/flux/printing/DefinitionManager.js
  src/app/flux/printing/index.js
  src/app/widgets/PrintingConfigurations/Configurations.jsx
  src/server/services/api/api-printing-definition.js
  src/server/services/index.js
  src/server/slicer/definition.js
Labels: Category: 3DP, Type: Feature

#286 Build: Bump version to v3.4.0
  package-lock.json
  package.json
  src/package.json
Labels: Type: Build

#288 Fix: Fix DXF parser import issues
  package.json
  src/app/lib/threejs/ThreeDxfLoader.js
  src/package.json
  src/server/lib/ToolPathGenerator/LaserToolPathGenerator.js
  src/server/services/api/api-image.js
  src/server/services/task-manager/generateToolPath.js
  src/shared/lib/DXFParser/AutoCadColorIndex.js
  src/shared/lib/DXFParser/DxfArrayScanner.js
  src/shared/lib/DXFParser/DxfParser.js
  src/shared/lib/DXFParser/ParseHelpers.js
  src/shared/lib/DXFParser/Parser.js
  src/shared/lib/DXFParser/entities/3dface.js
  src/shared/lib/DXFParser/entities/arc.js
  src/shared/lib/DXFParser/entities/attdef.js
  src/shared/lib/DXFParser/entities/circle.js
  src/shared/lib/DXFParser/entities/dimension.js
  src/shared/lib/DXFParser/entities/ellipse.js
  src/shared/lib/DXFParser/entities/insert.js
  src/shared/lib/DXFParser/entities/line.js
  src/shared/lib/DXFParser/entities/lwpolyline.js
  src/shared/lib/DXFParser/entities/mtext.js
  src/shared/lib/DXFParser/entities/point.js
  src/shared/lib/DXFParser/entities/polyline.js
  src/shared/lib/DXFParser/entities/solid.js
  src/shared/lib/DXFParser/entities/spline.js
  src/shared/lib/DXFParser/entities/text.js
  src/shared/lib/DXFParser/entities/vertex.js
  src/shared/lib/DXFParser/index.js
Labels: Type: Fix

#291 Build: Increate macOS build time to 60 minutes
  .travis.yml
  package-lock.json
  package.json
  src/package.json
Labels: Type: Build

#296 Build: Bump version to 3.5.0
  package-lock.json
  package.json
  src/package.json
Labels: Type: Build

#301 Build: Bump static-eval from 1.1.1 to 2.0.5
  package-lock.json
  package.json
  src/package.json
Labels: Type: Build

#307 Fix: Fix that speed_infill is not displayed due to enabled calculatio…
  src/app/widgets/PrintingConfigurations/Configurations.jsx
Labels: Type: Fix

#308 Feature: Add electron-store to remember size and position
  package-lock.json
  package.json
  src/main.js
  src/package.json
Labels: Category: UX, Type: Feature

#311 Fix: Fix greyscale image process (missing green and blue channels)
  src/server/lib/image-process.js
Labels: Type: Improvement
