Repository Snapmaker/Luban, pull requests merged in 2020-03, with the labels that each got.

#232 Fix: FIx camera capture
  src/app/flux/machine/index.js
  src/app/widgets/LaserCameraAidBackground/ExtractSquareTrace/index.jsx
  src/app/widgets/LaserCameraAidBackground/ManualCalibration/index.jsx
  src/app/widgets/LaserCameraAidBackground/SetBackground.jsx
  src/app/widgets/WifiTransport/WifiTransport.jsx
Labels: fix

#233 Fix: Fix minor bugs on material thickness, CNC spindle speed, etc.
  examples/.cncrc
  src/app/widgets/Marlin/Laser.jsx
  src/server/lib/ToolPath/index.js
  src/server/services/socket/socket-serial.js
Labels: fix

#235 Fix: Fix the problem that the drop-down box is too long to be selected
  src/app/widgets/Connection/SerialConnection.jsx
Labels: fix

#238 Build: Remove package-lock.json from .gitignore
  .gitignore
  package-lock.json
Labels: build

#234 Build: Migrate gulp to ~4.0.2 and simplify gulp scripts
  README.md
  gulp/tasks/app.js
  gulp/tasks/clean.js
  gulp/tasks/i18next.js
  gulp/tasks/server.js
  gulp/tasks/web.js
  gulpfile.babel.js
  package.json
  src/server/index.js
  webpack.config.app.development.js
  webpack.config.app.production.js
  webpack.config.server.development.js
  webpack.config.server.production.js
Labels: build

#240 Improvement: complete german translation
  src/app/i18n/de/gcode.json
  src/app/i18n/de/resource.json
Labels: improvement

#242 Docs: Add commitlint in replace of git-cz as githook
  .commitlintrc.js
  CONTRIBUTING.md
  package-lock.json
  package.json
Labels: docs

#243 Fix: Fix bug for CNC relief pattern boundary calculation error
  src/app/widgets/Marlin/JogDistance.jsx
  src/server/lib/ToolPathGenerator/CncReliefToolPathGenerator.js
Labels: fix

#244 Refactor: Advance file transfer and change the way files are named
  src/app/components/Modal/modal-small.jsx
  src/app/constants/index.js
  src/app/containers/Workspace/Workspace.jsx
  src/app/flux/cncLaserShared/index.js
  src/app/flux/models/ModelInfoUtils.js
  src/app/flux/printing/index.js
  src/app/flux/workspace/index.js
  src/app/images/24x24/ic_wifi_remove_straight.jpg
  src/app/images/connection/ic_waiting-64x64.png
  src/app/widgets/CNCOutput/Output.jsx
  src/app/widgets/CaseLibrary/CaseConfig.js
  src/app/widgets/LaserOutput/Output.jsx
  src/app/widgets/PrintingOutput/Output.jsx
  src/app/widgets/WifiTransport/WifiTransport.jsx
  src/app/widgets/WifiTransport/index.styl
  src/app/workers/GcodeToBufferGeometry.worker.js
  src/server/lib/svg-convert.js
  src/server/services/api/api-file.js
  src/server/slicer/slice.js
  src/shared/lib/random-utils.js
Labels: Type: Improvement

#257 Docs: Add CI badges to README.md
  README.md
Labels: Type: Docs

#261 Fix: Fix bug that multi-window cannot preview correctly
  src/app/flux/laser/index.js
  src/server/lib/ServerManager/index.js
  src/server/lib/SocketManager/index.js
  src/server/services/index.js
  src/server/services/socket/WifiServerManager.js
  src/server/services/socket/socket-http.js
  src/server/services/task-manager/TaskManager.js
  src/server/services/task-manager/index.js
Labels: Category: Communication, Category: UX, Type: Fix

#264 Improvement: Unify confuse terms "Upload" and "Load"
  package.json
  resources/CuraEngine/Config/Original/quality.fast_print.def.json
  resources/CuraEngine/Config/Original/quality.high_quality.def.json
  resources/CuraEngine/Config/Original/quality.normal_quality.def.json
  src/app/constants/index.js
  src/app/containers/Printing/Printing.jsx
  src/app/widgets/CNCPath/CNCPath.jsx
  src/app/widgets/LaserParams/LaserParameters.jsx
  src/app/widgets/PrintingVisualizer/VisualizerTopLeft.jsx
  src/app/widgets/WifiTransport/WifiTransport.jsx
  src/app/widgets/WifiTransport/index.styl
  src/app/widgets/WorkspaceVisualizer/WorkflowControl.jsx
  src/package.json
Labels: Category: UX, Type: Improvement

#271 Fix: Fix bug for reset text error
  package.json
  src/app/flux/cncLaserShared/index.js
  src/app/flux/models/ModelInfoUtils.js
  src/app/widgets/WifiTransport/WifiTransport.jsx
  src/package.json
  src/server/lib/svg-convert.js
Labels: Type: Fix

#272 Fix: Fix bug for opengl precision
  package.json
  src/app/workers/ShaderMaterial/print3d-shader-meterial.js
  src/package.json
Labels: Category: 3DP, Type: Fix
