Repository Snapmaker/Luban, pull requests merged in 2020-06, with the labels that each got.

#319 Fix: Fix dxf arc's missing line
  src/app/lib/threejs/ThreeDxfLoader.js
  src/shared/lib/DXFParser/Parser.js
Labels: Category: Editor, Type: Fix

#342 Fix: Fix DXF LWPOLYLINE first and last point not connect
  src/app/lib/threejs/ThreeDxfLoader.js
  src/shared/lib/DXFParser/Parser.js
Labels: Category: Editor, Type: Fix

#337 Improvement set canvas camera position appropriate
  src/app/components/SMCanvas/Canvas.jsx
  src/app/components/SMCanvas/Controls.jsx
  src/app/widgets/CNCVisualizer/Visualizer.jsx
  src/app/widgets/LaserVisualizer/Visualizer.jsx
  src/app/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/widgets/WorkspaceVisualizer/Visualizer.jsx
  src/app/workers/GcodeToBufferGeometry/GcodeToBufferGeometryWorkspace.js
Labels: Category: UX, Type: Improvement

#344 Refactor: Refactor camera position code in #337
  src/app/components/SMCanvas/Canvas.jsx
  src/app/components/SMCanvas/Controls.jsx
  src/app/components/three-extensions/MSRControls.js
  src/app/widgets/PrintingVisualizer/Visualizer.jsx
Labels: Type: Refactor

#345 Improvement: Improve select on click ux
  src/app/components/SMCanvas/Controls.jsx
Labels: Category: UX, Type: Improvement

#336 Refactor: And caselibrary config for original
  resources/user-case/Origin/3DP_test_Origin.stl
  resources/user-case/Origin/CNC_test_Origin.svg
  resources/user-case/Origin/Laser_test_Origin.jpg
  src/app/images/user-case/Origin/3D-Origin.jpg
  src/app/images/user-case/Origin/CNC-Origin.jpg
  src/app/images/user-case/Origin/Laser-Origin.jpg
  src/app/widgets/CaseLibrary/CaseConfig.js
  src/app/widgets/CaseLibrary/index.jsx
  src/server/DataStorage.js
Labels: Category: UX, Priority: High, Type: Improvement

#349 Improvement: Improvements on menu
  package-lock.json
  package.json
  src/electron-app/Menu.js
  src/electron-app/window.js
  src/main.js
  src/package.json
  src/server/DataStorage.js
Labels: Category: UX, Type: Improvement

#348 Fix: Fix bugs for 3.6.0
  src/app/constants/svg-constatns.js
  src/app/flux/editor/base.js
  src/app/flux/editor/index.js
  src/app/flux/editor/svg-model.js
  src/app/flux/editor/threejs-model.js
  src/app/flux/models/ModelGroup.js
  src/app/flux/models/SvgModelGroup.js
  src/app/flux/printing/index.js
  src/app/widgets/CNCVisualizer/Visualizer.jsx
  src/app/widgets/CncLaserSvgEditor/SVGCanvas.jsx
  src/app/widgets/CncLaserSvgEditor/element-utils.js
  src/app/widgets/CncLaserSvgEditor/svg-content/SVGContentGroup.js
  src/app/widgets/LaserVisualizer/Visualizer.jsx
  src/server/lib/SVGParser/BaseTagParser.js
  src/server/lib/SVGParser/SvgToString.js
  src/server/lib/image-process.js
  src/server/lib/svg-convert.js
Labels: Type: Fix

#347 Build: Build branch for building v3.6.0
  package-lock.json
  package.json
Labels: Type: Fix

#356 Fix: Rename Pentagram.png to pentagram.png, Trapezoid.png to trapezoid.png
  package.json
  src/app/images/svg-ext/small/pentagram.png
  src/app/images/svg-ext/small/trapezoid.png
Labels: Type: Fix

#354 Refactor: Refactor three.js code to make XYZ directions the as natura…
  src/app/components/SMCanvas/ArcGeometry.js
  src/app/components/SMCanvas/Canvas.jsx
  src/app/components/SMCanvas/Controls.jsx
  src/app/components/SMCanvas/TransformControls.js
  src/app/components/three-extensions/OBJExporter.js
  src/app/components/three-extensions/STLBinaryExporter.js
  src/app/components/three-extensions/STLExporter.js
  src/app/flux/models/Model.js
  src/app/flux/models/ModelGroup.js
  src/app/flux/printing/index.js
  src/app/three-extensions/objects/Grid.js
  src/app/three-extensions/objects/Rectangle.js
  src/app/widgets/CNCVisualizer/Visualizer.jsx
  src/app/widgets/CncLaserShared/PrintablePlate/PrintablePlate.jsx
  src/app/widgets/LaserVisualizer/Visualizer.jsx
  src/app/widgets/PrintingVisualizer/PrintableCube.jsx
  src/app/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/widgets/PrintingVisualizer/VisualizerModelTransformation.jsx
  src/app/widgets/WorkspaceVisualizer/Visualizer.jsx
  src/app/workers/GcodeToBufferGeometry/GcodeToBufferGeometryPrint3d.js
  src/app/workers/LoadModel.worker.js
Labels: Type: Refactor

#357 Feature: Allow manual IP input for WiFi connection
  src/app/components/Modal/ModalSmallInput.jsx
  src/app/i18n/de/resource.json
  src/app/i18n/en/resource.json
  src/app/widgets/Connection/WifiConnection.jsx
  src/package.json
Labels: Type: Improvement

#360 Improvement: Improve user experience when using manual Wi-Fi connection
  src/app/widgets/Connection/LaserState.jsx
  src/app/widgets/Connection/SerialConnection.jsx
  src/app/widgets/Connection/WifiConnection.jsx
Labels: Category: UX, Type: Improvement

#361 Improvement: Increase SVG view translation
  src/app/flux/laser/index.js
  src/app/flux/models/SvgModelGroup.js
  src/app/widgets/CncLaserSvgEditor/SVGCanvas.jsx
  src/app/widgets/CncLaserSvgEditor/svg-content/SVGContentGroup.js
Labels: Category: Editor, Type: Improvement
