Repository Snapmaker/Luban, pull requests merged in 2020-08, with the labels that each got.

#379 Feature: Disable model operating in process tab (Laser and CNC)
  src/app/components/SMCanvas/Canvas.jsx
  src/app/components/SMCanvas/Controls.jsx
  src/app/components/SMCanvas/TransformControls2D.js
  src/app/widgets/CNCVisualizer/Visualizer.jsx
  src/app/widgets/LaserVisualizer/Visualizer.jsx
Labels: Type: Improvement

#391 Improve: Change landing page to 3dp
  src/app/containers/App.jsx
  src/app/flux/editor/index.js
  src/app/flux/project/index.js
  src/app/lib/uni-api.js
  src/app/modals/modal-recover-environment.jsx
  src/app/widgets/PrintingConfigurations/Configurations.jsx
  src/app/widgets/PrintingMaterial/Material.jsx
  src/server/services/api/api-file.js
Labels: Category: UX

#403 Fix: Change save prompt text
  src/app/constants/index.js
  src/app/containers/App.jsx
  src/app/flux/models/ModelGroup.js
  src/app/flux/project/index.js
  src/app/lib/uni-api.js
  src/electron-app/Menu.js
  src/server/services/api/api-file.js
Labels: Category: UX, Type: Style

#409 Fix: Fix bug for snapmaker2.def.json
  resources/CuraEngine/Config/snapmaker2.def.json
Labels: Type: Fix

#410 Fix: Fix bugs & remove console logs
  src/app/flux/models/Model.js
  src/app/flux/models/ModelGroup.js
  src/app/flux/models/SvgModel.js
  src/app/flux/models/SvgModelGroup.js
  src/app/widgets/CNCPath/CNCPath.jsx
  src/app/widgets/CNCPath/gcodeconfig/ReliefGcodeParameters.jsx
  src/app/widgets/CncLaserObjectList/ObjectListBox.jsx
  src/app/widgets/CncLaserShared/TextParameters.jsx
  src/app/widgets/CncLaserSvgEditor/svg-content/SelectorManager.js
  src/app/widgets/CncLaserSvgEditor/text-actions.js
  src/app/widgets/LaserParams/LaserParameters.jsx
  src/app/widgets/PrintingConfigurations/Configurations.jsx
Labels: Type: Fix

#414 Fix: Fix bugs for SVG Editor
  src/app/flux/editor/index.js
  src/app/flux/models/Model.js
  src/app/flux/models/ModelGroup.js
  src/app/flux/models/SvgModel.js
  src/app/flux/models/SvgModelGroup.js
  src/app/flux/models/ToolPathModelGroup.js
  src/app/widgets/CNCPath/CNCPath.jsx
  src/app/widgets/CncLaserShared/Transformation.jsx
  src/app/widgets/CncLaserSvgEditor/SVGCanvas.jsx
  src/app/widgets/CncLaserSvgEditor/SVGEditor.jsx
  src/app/widgets/CncLaserSvgEditor/text-actions.js
  src/app/widgets/LaserParams/gcodeconfig/GcodeConfigRasterVector.jsx
Labels: Category: Editor, Type: Fix

#416 Improvement: Change style for transformation
  src/app/widgets/CncLaserShared/Transformation.jsx
  src/app/widgets/CncLaserShared/styles.styl
Labels: Type: Style

#417 Improvement: Add Snapmaker Luban version to Gcode File
  src/server/lib/ToolPathGenerator/LaserToolPathGenerator.js
  src/server/slicer/slice.js
Labels: Type: Improvement

#406 Improvement: Refactor CNC tool path generation and parameter adjustments
  src/app/flux/models/ModelInfoUtils.js
  src/app/widgets/CNCPath/gcodeconfig/ReliefGcodeParameters.jsx
  src/app/widgets/ToolPathRenderer.js
  src/server/lib/ToolPath/index.js
  src/server/lib/ToolPathGenerator/CncReliefToolPathGenerator.js
  src/server/lib/ToolPathGenerator/CncToolPathGenerator.js
  src/server/services/task-manager/generateGcode.js
Labels: Category: CNC, Type: Refactor

#420 Fix: Fix the 3D printing configuration upload folder
  src/app/flux/printing/DefinitionManager.js
  src/app/widgets/CncLaserShared/Transformation.jsx
  src/server/services/api/api-printing-definition.js
Labels: Type: Fix

#411 Fix: Fix the progress bar does not show when 3dp model slice
  src/app/components/ProgressBar/index.jsx
Labels: Type: Fix

#421 Fix: Fix enclosure state for Snapmaker Original
  src/server/controllers/Marlin/Marlin.js
Labels: Type: Fix

#413 Feature: add multiselect in 3D printing
  src/app/components/Input/NumberInput.jsx
  src/app/components/SMCanvas/Canvas.jsx
  src/app/components/SMCanvas/Controls.jsx
  src/app/components/SMCanvas/TransformControls.js
  src/app/flux/keyboardShortcut/index.js
  src/app/flux/models/Model.js
  src/app/flux/models/ModelGroup.js
  src/app/flux/printing/index.js
  src/app/lib/combokeys.js
  src/app/widgets/CNCPath/CNCPath.jsx
  src/app/widgets/CNCVisualizer/Visualizer.jsx
  src/app/widgets/CncLaserSvgEditor/svg-content/SVGContentGroup.js
  src/app/widgets/LaserVisualizer/Visualizer.jsx
  src/app/widgets/PrintingObjectList/PrintingObjectListBox.jsx
  src/app/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/widgets/PrintingVisualizer/VisualizerModelTransformation.jsx
  src/app/widgets/PrintingVisualizer/styles.styl
  src/app/widgets/WorkspaceVisualizer/Visualizer.jsx
  src/package.json
Labels: Type: Feature

#427 Fix: Fix failling to generate gcode in outline mode and jogSpeed para…
  src/server/lib/ToolPathGenerator/CncToolPathGenerator.js
Labels: Type: Fix
