Repository Snapmaker/Luban, pull requests merged in 2020-07, with the labels that each got.

#370 Build: Build br for v3.7.0
  package-lock.json
  package.json
  src/app/widgets/CNCVisualizer/styles.styl
  src/app/widgets/CncLaserObjectList/styles.styl
  src/app/widgets/CncLaserSvgEditor/index.styl
  src/app/widgets/LaserVisualizer/styles.styl
  src/package.json
  src/server/lib/ToolPathGenerator/LaserToolPathGenerator.js
  src/server/slicer/slice.js
Labels: Category: Editor, Type: Fix

#369 Feature: Add uniform/proportional scaling on selected model
  src/app/components/OptionalDropdown/styles.styl
  src/app/components/SMCanvas/TransformControls.js
  src/app/flux/models/Model.js
  src/app/flux/printing/index.js
  src/app/images/checked-off-14x14.png
  src/app/images/checked-on-14x14.png
  src/app/widgets/PrintingVisualizer/VisualizerModelTransformation.jsx
  src/app/widgets/PrintingVisualizer/styles.styl
Labels: Type: Feature

#374 Feature: Open and save file in Luban App
  package-lock.json
  package.json
  src/app/api/index.js
  src/app/containers/App.jsx
  src/app/flux/editor/index.js
  src/app/flux/index.js
  src/app/flux/printing/index.js
  src/app/flux/project/index.js
  src/app/flux/workspace/index.js
  src/app/lib/uni-api.js
  src/app/widgets/CNCVisualizer/VisualizerTopLeft.jsx
  src/app/widgets/CncLaserSvgEditor/svg-content/SVGContentGroup.js
  src/app/widgets/CncLaserSvgEditor/svg-content/SelectorManager.js
  src/app/widgets/LaserVisualizer/VisualizerTopLeft.jsx
  src/app/widgets/PrintingConfigurations/Configurations.jsx
  src/app/widgets/PrintingMaterial/Material.jsx
  src/app/widgets/PrintingVisualizer/VisualizerTopLeft.jsx
  src/app/widgets/WifiTransport/WifiTransport.jsx
  src/electron-app/Menu.js
  src/main.js
  src/package.json
  src/server/DataStorage.js
  src/server/lib/archive.js
  src/server/services/api/api-file.js
  src/server/services/api/api-printing-definition.js
  src/server/services/index.js
  src/server/slicer/definition.js
Labels: Type: Feature

#387 Build: Fix windows build issues
  package-lock.json
Labels: Type: Build

#377 Improvement: Improve to adapt fontsize to text's height
  package.json
  src/app/flux/editor/threejs-model.js
  src/app/widgets/CncLaserShared/TextParameters.jsx
  src/app/widgets/CncLaserShared/styles.styl
Labels: Type: Improvement

#388 Fix: Fix "optimize path" not working in v3.7.0
  src/server/lib/ToolPathGenerator/LaserToolPathGenerator.js
Labels: Type: Fix

#353 Fix: Fix the problem that the gcode file cannot be loaded if it is la…
  src/app/workers/GcodeToBufferGeometry/GcodeToBufferGeometryWorkspace.js
  src/app/workers/GcodeToBufferGeometry/index.js
  src/shared/lib/gcodeInterpreter.js
Labels: Type: Perf

#392 Fix: Fix bug that active_final.def.json error
  src/app/flux/printing/index.js
  src/app/widgets/PrintingConfigurations/Configurations.jsx
  test/testActiveFinalDef.js
Labels: Category: 3DP

#400 Build: Build v3.8.0 and bugfixes
  package-lock.json
  package.json
  src/app/components/ProgressBar/index.jsx
  src/app/components/ProgressBar/styles.styl
  src/app/widgets/PrintingOutput/Thumbnail.jsx
  src/app/widgets/PrintingVisualizer/VisualizerInfo.jsx
  src/app/widgets/WorkspaceVisualizer/Visualizer.jsx
  src/app/widgets/styles.styl
  src/package.json
Labels: Type: Build
