Repository Snapmaker/Luban, pull requests merged in 2020-12, with the labels that each got.

#596 Fix: Fix applying scale to objects's condition
  src/app/components/SMCanvas/TransformControls.js
Labels: Type: Fix

#600 Fix: Fix not working on changing materialThickness
  src/app/widgets/Marlin/Laser.jsx
Labels: Type: Fix

#603 Improvement: Make click trigger unselect event in four-axis mode on laser/cnc
  src/app/components/SMCanvas/Controls.jsx
  src/app/flux/editor/index.js
  src/app/widgets/CNCVisualizer/Visualizer.jsx
Labels: Type: Fix

#595 Improvement: Quit application when all windows closed
  src/main.js
Labels: Category: UX

#608 Fix: Remove gcode line after new file in 3dp
  src/app/flux/project/index.js
Labels: Category: 3DP, Type: Fix

#604 Feature: Add arrow key event for moving models in editor
  src/app/flux/editor/index.js
  src/app/flux/keyboardShortcut/index.js
  src/app/lib/combokeys.js
Labels: Category: Editor, Type: Feature

#615 Fix: Not to save when no models in modelGroup
  src/app/flux/project/index.js
Labels: Type: Fix

#610 Feature: Being able to add support for 3D model
  resources/CuraEngine/Config/support.def.json
  src/app/components/SMCanvas/Canvas.jsx
  src/app/components/SMCanvas/Controls.jsx
  src/app/components/SMCanvas/SupportControls.js
  src/app/components/SMCanvas/TransformControls.js
  src/app/components/three-extensions/ThreeUtils.js
  src/app/flux/printing/DefinitionManager.js
  src/app/flux/printing/index.js
  src/app/images/48x48/icon-support-disabled-48x48.png
  src/app/images/48x48/icon-support-hover-48x48.png
  src/app/images/48x48/icon-support-normal-48x48.png
  src/app/lib/support-helper.js
  src/app/models/Model.js
  src/app/models/ModelGroup.js
  src/app/widgets/PrintingConfigurations/Configurations.jsx
  src/app/widgets/PrintingObjectList/PrintingObjectListBox.jsx
  src/app/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/widgets/PrintingVisualizer/VisualizerModelTransformation.jsx
  src/app/widgets/PrintingVisualizer/styles.styl
  src/server/slicer/slice.js
Labels: Type: Feature

#613 Feature: Add printing manager on printing
  src/app/constants/index.js
  src/app/containers/Printing/Printing.jsx
  src/app/flux/printing/index.js
  src/app/flux/project/index.js
  src/app/images/18x18/printing-manager_18x18@2x.png
  src/app/views/PrintingManager/PrintingManager.jsx
  src/app/views/PrintingManager/index.jsx
  src/app/views/PrintingManager/styles.styl
  src/app/widgets/PrintingConfigurations/Configurations.jsx
  src/app/widgets/PrintingConfigurations/styles.styl
  src/app/widgets/PrintingMaterial/Material.jsx
  src/app/widgets/PrintingMaterial/styles.styl
Labels: Category: 3DP, Type: Feature

#585 Improvement: Reset all user settings
  src/app/api/index.js
  src/app/containers/App.jsx
  src/app/containers/Settings/Settings.jsx
  src/app/containers/Settings/Workspace/Workspace.jsx
  src/app/flux/printing/index.js
  src/app/flux/project/index.js
  src/app/flux/setting/index.js
  src/app/lib/uni-api.js
  src/electron-app/Menu.js
  src/main.js
Labels: Type: Feature

#619 Fix: Fix wrong value in reseting material definitions
  src/app/flux/printing/index.js
Labels: Type: Fix

#623 Fix: Limit scale on widget on printing
  src/app/models/ModelGroup.js
  src/app/widgets/PrintingVisualizer/VisualizerModelTransformation.jsx
Labels: Type: Fix

#621 Fix: Not correctly destroy gcode line
  src/app/containers/App.jsx
  src/app/flux/project/index.js
Labels: Type: Fix

#624 Fix: Fixed bugs in 3.13
  resources/CuraEngine/Config/snapmaker2.def.json
  src/app/components/SMCanvas/Controls.jsx
  src/app/components/SMCanvas/SupportControls.js
  src/app/components/SMCanvas/TransformControls.js
  src/app/flux/editor/index.js
  src/app/flux/printing/DefinitionManager.js
  src/app/flux/printing/index.js
  src/app/lib/support-helper.js
  src/app/models/Model.js
  src/app/models/ModelGroup.js
  src/app/widgets/LaserParams/LaserParameters.jsx
  src/app/widgets/PrintingVisualizer/Visualizer.jsx
  src/server/lib/editor/process.js
  src/server/lib/svg-convert.js
Labels: Type: Fix

#625 Fix: Fix the bug about 4 axis merging after
  src/app/constants/svg.js
  src/app/flux/editor/index.js
  src/app/flux/machine/index.js
  src/app/ui/SVGEditor/SVGCanvas.jsx
  src/app/ui/SVGEditor/element-utils.js
  src/app/widgets/CncLaserShared/Thumbnail.jsx
  src/app/widgets/Control/JogDistance.jsx
  src/app/widgets/JobType/JobType.jsx
  src/app/widgets/LaserVisualizer/Visualizer.jsx
  src/server/services/api/api-image.js
  src/shared/lib/utils.js
Labels: Type: Fix

#622 Fix: Fix bug that the select element can't change the value on PrintngManager
  src/app/constants/index.js
  src/app/flux/printing/index.js
  src/app/views/PrintingManager/PrintingManager.jsx
  src/app/widgets/PrintingConfigurations/Configurations.jsx
  src/app/widgets/PrintingMaterial/Material.jsx
Labels: Type: Fix

#627 Fix: Limit moving actions in process page
  src/app/flux/editor/index.js
Labels: Type: Fix

#628 Improvement: Add STL cnc 4 axis linkage algorithm
  src/app/constants/index.js
  src/app/models/ModelInfoUtils.js
  src/app/widgets/CNCPath/CNCPath.jsx
  src/app/widgets/CNCPath/Image3dParameters.jsx
  src/app/widgets/CNCPath/gcodeconfig/Image3DGcodeParameters.jsx
  src/server/constants/index.js
  src/server/lib/MeshProcess/Mesh.js
  src/server/lib/MeshProcess/MeshProcess.js
  src/server/lib/MeshProcess/Polygons.js
  src/server/lib/ToolPathGenerator/MeshToolPath/CncMeshLinkageToolPathGenerator.js
  src/server/lib/ToolPathGenerator/MeshToolPath/CncMeshToolPathGenerator.js
  test/cnc-mesh-slice/main.js
Labels: Type: Improvement

#629 Refactor: Refactor workflow of manual support
  src/app/components/SMCanvas/Canvas.jsx
  src/app/components/SMCanvas/Controls.jsx
  src/app/components/SMCanvas/SupportControls.js
  src/app/components/three-extensions/ThreeUtils.js
  src/app/flux/keyboardShortcut/index.js
  src/app/lib/combokeys.js
  src/app/lib/support-helper.js
  src/app/models/Model.js
  src/app/models/ModelGroup.js
  src/app/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/widgets/PrintingVisualizer/VisualizerModelTransformation.jsx
Labels: Type: Refactor

#630 Fix: Fix trying to parse some entities that do not need to be parsed on dxf-parser
  src/shared/lib/DXFParser/DxfParser.js
Labels: Type: Fix

#631 Improvement: Re-check copywriting
  src/app/components/SMWidget/SMDropdownButton.jsx
  src/app/components/SMWidget/index.jsx
  src/app/containers/App.jsx
  src/app/containers/DevelopTools/DeveloperPanel.jsx
  src/app/containers/DevelopTools/Firmware.jsx
  src/app/containers/DevelopTools/HeaterControl.jsx
  src/app/containers/DevelopTools/Lamp.jsx
  src/app/containers/DevelopTools/Laser.jsx
  src/app/containers/DevelopTools/Setting.jsx
  src/app/containers/Settings/MachineSettings/MachineSettings.jsx
  src/app/containers/Sidebar/Sidebar.jsx
  src/app/containers/Workspace/PrimaryWidgets.jsx
  src/app/containers/Workspace/SecondaryWidgets.jsx
  src/app/containers/Workspace/Workspace.jsx
  src/app/flux/widget/WidgetState.js
  src/app/widgets/CanvasToolbar/PrimaryToolbar.jsx
  src/app/widgets/CanvasToolbar/primary-toolbar.styl
  src/app/widgets/CncLaserShared/TextParameters.jsx
  src/app/widgets/Connection/PrintingState.jsx
  src/app/widgets/Control/ShuttleSettings.jsx
  src/app/widgets/DevelopAxes/DisplayPanel.jsx
  src/app/widgets/DevelopAxes/ShuttleSettings.jsx
  src/app/widgets/LaserParams/config/ConfigGreyscale.jsx
  src/app/widgets/LaserParams/gcodeconfig/GcodeConfigRasterBW.jsx
  src/app/widgets/Webcam/index.jsx
  src/app/widgets/WorkspaceVisualizer/PrimaryToolbar.jsx
  src/app/widgets/WorkspaceVisualizer/Visualizer.jsx
  src/app/widgets/WorkspaceVisualizer/primary-toolbar.styl
Labels: Type: Improvement

#641 Fix: Fix printing manager bug when saving
  src/app/flux/printing/index.js
  src/app/views/PrintingManager/PrintingManager.jsx
Labels: Type: Fix

#639 Fix bugs in 3.13-alpha.4
  src/app/flux/printing/index.js
  src/app/models/Model.js
  src/app/models/ModelGroup.js
  src/app/models/SvgModel.js
  src/app/widgets/CNCPath/CNCPath.jsx
  src/app/widgets/PrintingVisualizer/Visualizer.jsx
Labels: Type: Fix

#634 Fix: Add toFront instead of autoFocus for 3dp
  src/app/components/SMCanvas/Canvas.jsx
  src/app/widgets/CanvasToolbar/SecondaryToolbar.jsx
  src/app/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/widgets/PrintingVisualizer/VisualizerCameraOperations.jsx
Labels: Category: 3DP, Type: Fix

#644 Improvement: Use Trans component to write i18n content with HTML tags
  gulp/tasks/i18next.js
  package-lock.json
  package.json
  src/app/containers/App.jsx
  src/app/containers/Workspace/index.styl
  src/app/i18n/cs/gcode.json
  src/app/i18n/cs/resource.json
  src/app/i18n/de/gcode.json
  src/app/i18n/de/resource.json
  src/app/i18n/en/gcode.json
  src/app/i18n/en/resource.json
  src/app/i18n/es/gcode.json
  src/app/i18n/es/resource.json
  src/app/i18n/fr/gcode.json
  src/app/i18n/fr/resource.json
  src/app/i18n/hu/gcode.json
  src/app/i18n/hu/resource.json
  src/app/i18n/it/gcode.json
  src/app/i18n/it/resource.json
  src/app/i18n/ja/gcode.json
  src/app/i18n/ja/resource.json
  src/app/i18n/ko/gcode.json
  src/app/i18n/ko/resource.json
  src/app/i18n/pt-br/gcode.json
  src/app/i18n/pt-br/resource.json
  src/app/i18n/ru/gcode.json
  src/app/i18n/ru/resource.json
  src/app/i18n/uk/gcode.json
  src/app/i18n/uk/resource.json
  src/app/i18n/zh-cn/gcode.json
  src/app/i18n/zh-cn/resource.json
  src/app/i18n/zh-tw/gcode.json
  src/app/i18n/zh-tw/resource.json
  src/app/views/PrintingManager/styles.styl
  src/app/widgets/CNCTool/ToolParameters.jsx
  src/app/widgets/CncLaserShared/styles.styl
  src/app/widgets/Control/MotionButtonGroup.jsx
  src/app/widgets/JobType/styles.styl
  src/app/widgets/LaserCameraAidBackground/Instructions.jsx
  src/app/widgets/LaserSetBackground/Instructions.jsx
  src/app/widgets/LaserSetBackground/styles.styl
  src/app/widgets/LaserTestFocus/TestFocus.jsx
  src/app/widgets/LaserTestFocus/styles.styl
  src/app/widgets/PrintingConfigurations/styles.styl
  src/app/widgets/PrintingVisualizer/styles.styl
  src/app/widgets/WorkspaceVisualizer/Visualizer.jsx
Labels: Type: Improvement

#643 Fix: Fix issue of remove all manual support
  src/app/flux/printing/index.js
  src/app/widgets/PrintingVisualizer/Visualizer.jsx
Labels: Type: Fix

#646 Improvement: Add stew down for CncMeshLinkageToolPathGenerator
  src/app/flux/editor/index.js
  src/app/models/ModelInfoUtils.js
  src/server/lib/MeshProcess/Polygons.js
  src/server/lib/MeshProcess/Slicer.js
  src/server/lib/ToolPath/index.js
  src/server/lib/ToolPathGenerator/MeshToolPath/CncMeshLinkageToolPathGenerator.js
  test/cnc-mesh-slice/complexity-analysis/martinez-polygon-clipping/main.js
  test/cnc-mesh-slice/main.js
Labels: Type: Improvement

#642 Improvement: Add checkbox on autoupdate popup
  src/app/containers/App.jsx
  src/app/lib/uni-api.js
  src/main.js
Labels: Type: Improvement

#637 Fix: Reset macros in config settings
  src/app/containers/Settings/Settings.jsx
  src/app/flux/setting/index.js
Labels: Type: Fix

#645 Improvement: Improve model moving on arrow keys
  src/app/flux/editor/index.js
  src/app/flux/keyboardShortcut/index.js
  src/app/models/SVGActionsFactory.js
  src/app/ui/SVGEditor/SVGCanvas.jsx
  src/app/ui/SVGEditor/SVGEditor.jsx
  src/app/widgets/CNCVisualizer/Visualizer.jsx
  src/app/widgets/LaserVisualizer/Visualizer.jsx
Labels: Category: Editor, Type: Improvement

#647 Fix: Not move models in process page
  src/app/flux/editor/index.js
Labels: Type: Fix

#649 Fix: Fix scale limition on printing
  src/app/models/ModelGroup.js
Labels: Type: Fix

#648 Improvement: Add a resolve value for promise function to confirm
  src/app/containers/Settings/Settings.jsx
  src/app/lib/confirm.jsx
  src/app/views/PrintingManager/PrintingManager.jsx
Labels: Type: Improvement

#650 Fix: Reserve matrix after rotation when multi model selected in 3dp
  src/app/components/SMCanvas/TransformControls.js
  src/app/models/ModelGroup.js
  src/app/widgets/CNCPath/CNCPath.jsx
Labels: Type: Fix

#655 Feature: Add config to hide 4 axis
  src/app/flux/machine/index.js
  src/app/widgets/CaseLibrary/index.jsx
  src/app/widgets/JobType/JobType.jsx
Labels: Type: Feature

#656 Fix: Fix bug for hide 4 axis
  src/app/widgets/CNCPath/CNCPath.jsx
  src/app/widgets/JobType/JobType.jsx
Labels: Type: Fix

#658 Fix: Fix bug for laser estimatedTime error
  src/server/lib/ToolPath/index.js
Labels: Type: Fix

#659 Build: Bump version to v3.13.0
  package-lock.json
  package.json
  src/package.json
Labels: Type: Build

#662 Feature: Add async array
  src/app/flux/machine/index.js
  src/server/lib/ToolPathGenerator/CncReliefToolPathGenerator.js
  src/server/lib/ToolPathGenerator/LaserToolPathGenerator.js
  src/server/lib/ToolPathGenerator/MeshToolPath/CncMeshLinkageToolPathGenerator.js
  src/server/lib/ToolPathGenerator/MeshToolPath/CncMeshToolPathGenerator.js
  src/shared/lib/array-async.js
Labels: Type: Perf

#661 Improvement: Improve light in 3D scene
  src/app/components/SMCanvas/Canvas.jsx
  src/app/models/Model.js
Labels: Category: 3DP, Type: Improvement

#663 Refactor: Refactor compute model bounding box
  src/app/components/SMCanvas/TransformControls.js
  src/app/components/three-extensions/ThreeUtils.js
  src/app/models/Model.js
  src/app/models/ModelGroup.js
  src/app/widgets/PrintingVisualizer/VisualizerModelTransformation.jsx
  src/server/lib/ToolPathGenerator/LaserToolPathGenerator.js
Labels: Type: Fix, Type: Refactor

#669 Feature: Add parameter manager for cnc
  resources/CuraEngine/Config/cncConfig/Default.def.json
  resources/CuraEngine/Config/cncConfig/active.def.json
  src/app/api/index.js
  src/app/containers/Cnc/Cnc.jsx
  src/app/flux/cnc/DefinitionManager.js
  src/app/flux/cnc/index.js
  src/app/flux/project/index.js
  src/app/models/ToolPathModel.js
  src/app/views/CncToolManager/CncToolManager.jsx
  src/app/views/CncToolManager/index.jsx
  src/app/views/CncToolManager/styles.styl
  src/app/views/PrintingManager/PrintingManager.jsx
  src/app/widgets/CNCPath/CNCPath.jsx
  src/app/widgets/CNCPath/VectorParameters.jsx
  src/app/widgets/CNCPath/gcodeconfig/Image3DGcodeParameters.jsx
  src/app/widgets/CNCPath/gcodeconfig/ReliefGcodeParameters.jsx
  src/app/widgets/CNCPath/styles.styl
  src/app/widgets/CNCTool/ToolParameters.jsx
  src/app/widgets/CNCTool/styles.styl
  src/app/widgets/CncLaserShared/GcodeParametersForCnc.jsx
  src/server/DataStorage.js
  src/server/constants/index.js
  src/server/services/api/api-cnc-definition.js
  src/server/services/api/api-file.js
  src/server/services/api/index.js
  src/server/services/index.js
Labels: Type: Feature

#675 Fix: Fix computeBoundingBox bug for support mesh
  src/app/components/three-extensions/ThreeUtils.js
  src/app/models/Model.js
  src/app/models/ModelGroup.js
  src/app/widgets/PrintingVisualizer/VisualizerModelTransformation.jsx
Labels: Type: Fix

#676 Improvement: Set the way to go to origin
  src/app/flux/machine/index.js
  src/app/widgets/Control/MotionButtonGroup.jsx
Labels: Category: Control, Type: Improvement

#671 Feature: Stop the previous task when the next task comes over
  src/server/lib/ToolPathGenerator/CncReliefToolPathGenerator.js
  src/server/lib/ToolPathGenerator/LaserToolPathGenerator.js
  src/server/lib/ToolPathGenerator/MeshToolPath/CncMeshLinkageToolPathGenerator.js
  src/server/services/task-manager/TaskManager.js
  src/shared/lib/array-async.js
Labels: Type: Perf

#665 Fix: Fix bug for materials storage problem
  src/app/flux/cnc/index.js
  src/app/flux/editor/index.js
  src/app/flux/laser/index.js
  src/app/flux/machine/index.js
  src/app/widgets/JobType/JobType.jsx
Labels: Type: Fix

#670 Feature: Add 3d visualizer for cnc stl models
  resources/CuraEngine/Config/snapmaker.def.json
  src/app/containers/Cnc/Cnc.jsx
  src/app/flux/cnc/index.js
  src/app/flux/editor/index.js
  src/app/models/Model.js
  src/app/ui/SVGEditor/SVGEditor.jsx
  src/app/views/Cnc3DVisualizer/Canvas/Canvas.jsx
  src/app/views/Cnc3DVisualizer/Canvas/Controls.jsx
  src/app/views/Cnc3DVisualizer/Canvas/index.js
  src/app/views/Cnc3DVisualizer/Cnc3DVisualizer.jsx
  src/app/views/Cnc3DVisualizer/CylinderJob.jsx
  src/app/views/Cnc3DVisualizer/Env3Axis.jsx
  src/app/views/Cnc3DVisualizer/Env4Axis.jsx
  src/app/views/Cnc3DVisualizer/index.jsx
  src/app/views/Cnc3DVisualizer/styles.styl
Labels: Type: Feature
