Repository Snapmaker/Luban, pull requests merged in 2021-08, with the labels that each got.

#1099 Fix: Open file in workspace filter project extensions
  src/app/lib/uni-api.js
Labels: Type: Fix

#1096 Fix: Not to return model view after undo redo
  src/app/flux/editor/actions-process.js
  src/app/flux/editor/index.js
  src/app/flux/printing/index.js
  src/app/lib/controller.js
  src/app/toolpaths/ToolPathGroup.js
  src/app/ui/pages/Cnc.jsx
  src/app/ui/pages/Laser.jsx
  src/app/ui/widgets/CncLaserOutput/Output.jsx
  src/app/ui/widgets/PrintingMaterial/Material.jsx
  src/server/lib/ToolPathGenerator/CncReliefToolPathGenerator.js
Labels: Type: Fix

#1101 Fix: Fix simulation not change error
  src/app/flux/editor/actions-process.js
  src/app/ui/views/CncToolManager/CncToolManager.jsx
Labels: Type: Fix

#1108 Fix: Home page laser&cnc button click inaccurate
  src/app/ui/pages/HomePage/Begin.jsx
  src/app/ui/pages/HomePage/styles.styl
Labels: Type: Fix

#1105 Fix: Fix 3dp bottom-left camera change position
  src/app/flux/editor/index.js
  src/app/resources/images/snapmaker-logo-1024x256.png
  src/app/styles/global-border.styl
  src/app/ui/SVGEditor/PrintableArea.js
  src/app/ui/SVGEditor/SVGCanvas.jsx
  src/app/ui/SVGEditor/svg-content/OperatorPoints.js
  src/app/ui/SVGEditor/svg-content/SVGContentGroup.js
  src/app/ui/components/SMCanvas/Canvas.jsx
  src/app/ui/widgets/PrintingVisualizer/PrintableCube.jsx
  src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerBottomLeft.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerPreviewControl.jsx
Labels: Type: Fix

#1109 Fix: Fix purifier not connect error in console
  src/server/controllers/Marlin/Marlin.js
Labels: Type: Fix

#1087 Fix: Fix alpha4 bugfix
  src/app/flux/editor/actions-process.js
  src/app/flux/printing/index.js
  src/app/flux/project/index.js
  src/app/models/ThreeModel.js
  src/app/ui/widgets/CncLaserOutput/Output.jsx
  src/app/ui/widgets/PrintingOutput/Output.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
Labels: Type: Fix

#1110 Fix: New file from appbar menu incorrect
  src/app/lib/redux-middleware.js
  src/app/lib/uni-api.js
  src/app/ui/layouts/AppLayout.jsx
  src/app/ui/pages/HomePage/Begin.jsx
  src/electron-app/Menu.js
Labels: Type: Fix

#1111 Fix: Fix some laser|cnc canvas error and serial port connection error
  src/app/flux/cnc/index.js
  src/app/flux/editor/index.js
  src/app/flux/laser/index.js
  src/app/flux/printing/index.js
  src/app/lib/controller.js
  src/app/three-extensions/STLExporter.js
  src/app/ui/SVGEditor/SVGCanvas.jsx
  src/app/ui/pages/Laser.jsx
  src/app/ui/widgets/CNCPath/CNCPath.jsx
  src/app/ui/widgets/CNCPath/ImageProcessMode.jsx
  src/app/ui/widgets/LaserParams/ImageProcessMode.jsx
  src/app/ui/widgets/LaserParams/LaserParameters.jsx
  src/app/ui/widgets/LaserVisualizer/Visualizer.jsx
Labels: Type: Fix

#1118 Improvement: Update snapmaker-luban-engine to 0.4.0
  package.json
  src/app/flux/editor/actions-process.js
  src/app/flux/workspace/index.js
  src/app/toolpaths/ToolPath.js
  src/app/toolpaths/ToolPathGroup.js
  src/app/ui/views/Cnc3DVisualizer/Cnc3DVisualizer.jsx
  src/app/ui/widgets/CncLaserOutput/Output.jsx
  src/server/services/api/api-file.js
  src/server/services/api/api-image.js
  src/server/slicer/slice.js
  src/shared/lib/random-utils.js
Labels: Type: Improvement, luban-engine

#1114 Improvement: Improve laser slider moving actions
  src/app/config/menu/fileMenu.js
  src/app/config/menu/helpMenu.js
  src/app/constants/index.js
  src/app/flux/editor/actions-process.js
  src/app/flux/project/index.js
  src/app/lib/uni-api.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/layouts/AppLayout.jsx
  src/app/ui/modals/modal-machine-select.jsx
  src/app/ui/pages/Cnc.jsx
  src/app/ui/pages/HomePage/Begin.jsx
  src/app/ui/pages/HomePage/MoreInfo.jsx
  src/app/ui/pages/HomePage/SettingGuideModal.jsx
  src/app/ui/pages/Laser.jsx
  src/app/ui/utils/renderRecoveryModal.jsx
  src/app/ui/views/CncToolManager/CncToolManager.jsx
  src/app/ui/views/DefinitionCreator.jsx
  src/app/ui/views/ToolPathConfigurations/ToolPathConfigurations.jsx
  src/app/ui/widgets/CNCPath/CNCPath.jsx
  src/app/ui/widgets/CNCVisualizer/Visualizer.jsx
  src/app/ui/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx
  src/app/ui/widgets/Connection/Connection.jsx
  src/app/ui/widgets/Connection/WifiConnection.jsx
  src/app/ui/widgets/LaserCameraAidBackground/ExtractSquareTrace/index.jsx
  src/app/ui/widgets/LaserCameraAidBackground/ManualCalibration/index.jsx
  src/app/ui/widgets/LaserParams/ImageProcessMode.jsx
  src/app/ui/widgets/LaserParams/LaserParameters.jsx
  src/app/ui/widgets/LaserParams/config/ConfigGreyscale.jsx
  src/app/ui/widgets/LaserParams/config/ConfigHalftone.jsx
  src/app/ui/widgets/LaserParams/config/ConfigRasterBW.jsx
  src/app/ui/widgets/LaserParams/config/ConfigRasterVector.jsx
  src/app/ui/widgets/LaserSetBackground/ExtractSquareTrace/index.jsx
  src/app/ui/widgets/LaserSetBackground/PrintSquareTrace/index.jsx
  src/app/ui/widgets/LaserSetBackground/SetBackground.jsx
  src/app/ui/widgets/LaserTestFocus/TestFocus.jsx
  src/app/ui/widgets/LaserVisualizer/Visualizer.jsx
  src/app/ui/widgets/Macro/AddMacro.jsx
  src/app/ui/widgets/Macro/EditMacro.jsx
  src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/ui/widgets/WifiTransport/WifiTransport.jsx
  src/app/ui/widgets/WorkspaceVisualizer/Visualizer.jsx
  src/server/services/api/api-cnc-definition.js
Labels: Type: Improvement

#1121 Fix: SVG parse and render related issues
  src/app/flux/editor/actions-process.js
  src/app/flux/editor/index.js
  src/app/flux/printing/index.js
  src/app/lib/renderer/ViewPathRenderer.js
  src/app/models/ModelInfoUtils.js
  src/app/models/SVGActionsFactory.js
  src/app/models/SvgModel.js
  src/app/resources/i18n/zh-cn/resource.json
  src/app/toolpaths/ToolPathGroup.js
  src/app/ui/components/Input/NumberInput.jsx
  src/app/ui/widgets/CNCVisualizer/Visualizer.jsx
  src/app/ui/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx
  src/app/ui/widgets/LaserVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
  src/package.json
  src/server/services/api/api-image.js
  src/shared/lib/SVGParser/AttributesParser.js
  src/shared/lib/SVGParser/Parser.js
  src/shared/lib/SVGParser/PolylineTagParser.js
Labels: Type: Fix

#1128 Improvement change words
  src/app/constants/index.js
  src/app/ui/views/ToolPathConfigurations/cnc/CncParameters.jsx
  src/app/ui/views/ToolPathConfigurations/cnc/GcodeParameters.jsx
  src/app/ui/views/ToolPathConfigurations/laser/LaserParameters.jsx
  src/app/ui/widgets/CNCPath/Image3dParameters.jsx
  src/app/ui/widgets/CNCPath/ImageProcessMode.jsx
  src/app/ui/widgets/CNCPath/config/ReliefParameters.jsx
  src/app/ui/widgets/CncLaserShared/GcodeParameters.jsx
  src/app/ui/widgets/CncLaserShared/TextParameters.jsx
  src/app/ui/widgets/CncLaserShared/TransformationSection.jsx
  src/app/ui/widgets/LaserParams/ImageProcessMode.jsx
  src/app/ui/widgets/LaserParams/config/ConfigGreyscale.jsx
  src/app/ui/widgets/LaserParams/config/ConfigHalftone.jsx
  src/app/ui/widgets/LaserParams/config/ConfigRasterBW.jsx
  src/app/ui/widgets/LaserParams/config/ConfigRasterVector.jsx
  src/app/ui/widgets/LaserTestFocus/TestFocus.jsx
  src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
  src/server/lib/profile/cnc-uniform-profile.js
Labels: Type: Improvement

#1127 Fix: Toolpath update in preview mode
  src/app/flux/cnc/index.js
  src/app/flux/editor/actions-process.js
  src/app/flux/editor/index.js
  src/app/flux/laser/index.js
  src/app/flux/project/index.js
  src/app/toolpaths/ToolPath.js
  src/app/toolpaths/ToolPathGroup.js
  src/app/ui/SVGEditor/SVGCanvas.jsx
  src/app/ui/SVGEditor/index.styl
  src/app/ui/pages/Cnc.jsx
  src/app/ui/pages/Laser.jsx
  src/app/ui/views/CncToolManager/CncToolManager.jsx
  src/app/ui/views/ToolPathConfigurations/ToolPathConfigurations.jsx
  src/app/ui/views/ToolPathConfigurations/ToolPathFastConfigurations.jsx
  src/app/ui/widgets/CNCVisualizer/Visualizer.jsx
  src/app/ui/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx
  src/app/ui/widgets/CncLaserOutput/Output.jsx
  src/app/ui/widgets/LaserVisualizer/Visualizer.jsx
  src/shared/lib/SVGParser/AttributesParser.js
Labels: Type: Fix

#1122 Build: Move Linux builds to Github Actions and drop Linux 32-bit support
  .github/workflows/build-on-create-release.yml
  .travis.yml
  0
  README.md
  docs/Development.md
  package.json
Labels: Type: Build

#1133 Improvement: Change method description
  src/app/ui/views/ToolPathConfigurations/laser/LaserParameters.jsx
Labels: Type: Improvement

#1135 Fix: Set fixed power enabled when change fixed power
  src/app/models/ModelInfoUtils.js
  src/app/ui/views/ToolPathConfigurations/ToolPathFastConfigurations.jsx
  src/app/ui/views/ToolPathConfigurations/laser/LaserParameters.jsx
Labels: Type: Fix

#1138 Refactor: Change some English words
  resources/CuraEngine/Config/CncConfig/DefaultCVbit.defv2.json
  resources/CuraEngine/Config/CncConfig/DefaultFEM.defv2.json
  resources/CuraEngine/Config/CncConfig/DefaultMBEM.defv2.json
  resources/CuraEngine/Config/CncConfig/DefaultSGVbit.defv2.json
  resources/CuraEngine/Config/CncConfig/RAcrylicFEM.defv2.json
  resources/CuraEngine/Config/CncConfig/REpoxySGVbit.defv2.json
  resources/CuraEngine/Config/CncConfig/active.defv2.json
  resources/CuraEngine/Config/Default/CncConfig/DefaultCVbit.defv2.json
  resources/CuraEngine/Config/Default/CncConfig/DefaultFEM.defv2.json
  resources/CuraEngine/Config/Default/CncConfig/DefaultMBEM.defv2.json
  resources/CuraEngine/Config/Default/CncConfig/DefaultSGVbit.defv2.json
  resources/CuraEngine/Config/Default/CncConfig/RAcrylicFEM.defv2.json
  resources/CuraEngine/Config/Default/CncConfig/REpoxySGVbit.defv2.json
  resources/CuraEngine/Config/Default/CncConfig/active.defv2.json
  resources/CuraEngine/Config/fdmprinter.def.json
  resources/CuraEngine/Config/snapmaker.def.json
  src/app/config/menu/fileMenu.js
  src/app/config/menu/helpMenu.js
  src/app/constants/index.js
  src/app/resources/i18n/en/resource.json
  src/app/ui/SVGEditor/SVGCanvas.jsx
  src/app/ui/SVGEditor/svg-content/SVGContentGroup.js
  src/app/ui/components/SMCanvas/Canvas.jsx
  src/app/ui/pages/HomePage/MoreInfo.jsx
  src/app/ui/pages/Settings/General/General.jsx
  src/app/ui/widgets/CNCVisualizer/Visualizer.jsx
  src/app/ui/widgets/LaserVisualizer/Visualizer.jsx
  src/package.json
  src/server/lib/profile/cnc-uniform-profile.js
Labels: Type: Refactor

#1139 Fix: Big model moves a little pause
  src/app/flux/editor/actions-process.js
  src/app/flux/printing/index.js
  src/app/lib/uni-api.js
  src/app/resources/images/24x24/ic_right_arrow.png
  src/app/styles/contextmenu.styl
  src/app/toolpaths/ToolPath.js
  src/app/toolpaths/ToolPathGroup.js
  src/app/ui/App.jsx
  src/app/ui/components/ContextMenu/index.jsx
  src/app/ui/layouts/AppLayout.jsx
  src/app/ui/pages/Printing.jsx
  src/app/ui/views/model-item.jsx
  src/app/ui/widgets/CNCVisualizer/Visualizer.jsx
  src/app/ui/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx
  src/app/ui/widgets/CncLaserList/styles.styl
  src/app/ui/widgets/CncLaserOutput/Output.jsx
  src/app/ui/widgets/LaserVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingObjectList/styles.styl
  src/app/ui/widgets/PrintingOutput/Output.jsx
  src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
  src/shared/lib/SVGParser/AttributesParser.js
Labels: Type: Fix

#1147 Fix: Add Chinese words and fix profile manager error
  scripts/i18n-import-excel.js
  src/app/constants/copy.js
  src/app/constants/index.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/pages/HomePage/QuickStart.jsx
  src/app/ui/views/ProfileManager/index.jsx
Labels: Type: Fix

#1144 Fix: Show loading window only on windows
  src/main.js
Labels: Type: Improvement

#1151 Fix: bug fix 816
  src/app/config/menu/editMenu.js
  src/app/ui/pages/Laser.jsx
  src/app/ui/views/ToolPathConfigurations/ToolPathFastConfigurations.jsx
  src/app/ui/widgets/CNCVisualizer/Visualizer.jsx
  src/app/ui/widgets/Control/Control.jsx
  src/app/ui/widgets/LaserVisualizer/Visualizer.jsx
  src/server/constants/index.js
  src/server/services/task-manager/TaskManager.js
Labels: Type: Fix

#1160 Fix: Adjust stroke width of parsed SVG
  src/shared/lib/SVGParser/AttributesParser.js
Labels: Type: Fix

#1163 Fix: Fix enclosure error and update i18n Chinese words
  src/app/resources/i18n/zh-cn/resource.json
  src/app/ui/widgets/Enclosure/EnclosureDisplay.jsx
Labels: Type: Fix

#1167 Refactor: Change English words
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/pages/Cnc.jsx
  src/app/ui/pages/Laser.jsx
Labels: Type: Refactor

#1169 Fix: Set material settings default value
  src/app/ui/widgets/PrintingMaterial/Material.jsx
Labels: Type: Fix

#1172 Fix: Fix 3dp non-uniformscale error in left bar
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
Labels: Type: Fix

#1174 Fix: Fix cnc tool path config error
  src/app/ui/views/ToolPathConfigurations/ToolPathConfigurations.jsx
Labels: Type: Fix

#1177 Fix: Fix autoUpdater fail on windows
  .github/workflows/build-on-create-release.yml
Labels: Type: Fix
