Repository Snapmaker/Luban, pull requests merged in 2021-04, with the labels that each got.

#903 Fix: Fix Canvas display when WebGL is not usable (re-work on #841)
  src/app/components/SMCanvas/Canvas.jsx
  src/app/components/three-extensions/TransformControls2D.js
  src/app/three-extensions/Detector.jsx
  src/app/three-extensions/WebGLRenderer.js
  src/app/widgets/CNCVisualizer/Visualizer.jsx
  src/app/widgets/LaserVisualizer/Visualizer.jsx
  src/app/widgets/PrintingVisualizer/Visualizer.jsx
  src/main.js
Labels: Type: Fix

#904 Fix: Fix false calculation of ETA 3D printing time
  src/app/lib/time-utils.js
  src/app/widgets/CNCVisualizer/Visualizer.jsx
  src/app/widgets/LaserVisualizer/Visualizer.jsx
  src/app/widgets/PrintingVisualizer/VisualizerInfo.jsx
  src/shared/lib/SVGParser/AttributesParser.js
Labels: Type: Fix

#908 Improvement: Show modal before recovering environment
  src/app/containers/App.jsx
  src/app/flux/project/index.js
  src/app/lib/modal.jsx
Labels: Type: Improvement

#906 Improvement: Improve tool path list
  package.json
  src/app/components/SMCanvas/Canvas.jsx
  src/app/components/Select/ChangedReactSelect.jsx
  src/app/components/TipTrigger/index.jsx
  src/app/toolpaths/ToolPathGroup.js
  src/app/views/ToolPathConfigurations/ToolPathConfigurations.jsx
  src/app/widgets/CncLaserList/ToolPathList/ToolPathFooter.jsx
  src/app/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx
  src/app/widgets/CncLaserList/styles.styl
  src/app/widgets/PrintingObjectList/PrintingObjectListBox.jsx
Labels: Type: Improvement

#913 Improvement: Improve interaction of configuration library
  package.json
  src/app/components/Radio/index.js
  src/app/components/Select/ChangedReactSelect.jsx
  src/app/constants/index.js
  src/app/containers/App.jsx
  src/app/flux/editor/actions-process.js
  src/app/lib/modal.jsx
  src/app/styles/vendor.styl
  src/app/views/CncToolManager/CncToolManager.jsx
  src/app/views/CncToolManager/CreateModal.jsx
  src/app/views/CncToolManager/styles.styl
  src/app/views/PrintingManager/PrintingManager.jsx
  src/app/views/PrintingManager/styles.styl
  src/app/views/ToolPathConfigurations/cnc/ToolParameters.jsx
  src/app/widgets/CNCPath/CNCPath.jsx
Labels: Type: Improvement

#909 Fix: Fix object layer problem and selection probelem on process part
  src/app/components/SMCanvas/Peripheral.js
  src/app/components/SMCanvas/TransformControls2D.js
  src/app/flux/cnc/index.js
  src/app/flux/editor/actions-process.js
  src/app/flux/editor/index.js
  src/app/flux/laser/index.js
  src/app/flux/project/index.js
  src/app/lib/numeric-utils.js
  src/app/models/BaseModel.js
  src/app/models/ModelGroup.js
  src/app/models/SvgModel.js
  src/app/models/ThreeModel.js
  src/app/ui/SVGEditor/constants.js
  src/app/ui/SVGEditor/svg-content/OperatorPoints.js
  src/app/ui/SVGEditor/svg-content/SVGContentGroup.js
  src/app/widgets/CNCVisualizer/Visualizer.jsx
  src/app/widgets/LaserVisualizer/Visualizer.jsx
  src/server/services/task-manager/generateGcode.js
Labels: Type: Fix

#885 Refactor: Remove variable "flip"
  src/app/models/BaseModel.js
  src/app/models/ModelGroup.js
  src/app/models/SVGActionsFactory.js
  src/app/models/SvgModel.js
  src/app/ui/SVGEditor/svg-content/SVGContentGroup.js
  src/app/widgets/CaseLibrary/CaseConfig.js
  src/app/widgets/Webcam/index.jsx
  src/server/lib/ToolPathGenerator/CncReliefToolPathGenerator.js
  src/server/lib/editor/image-process.js
Labels: Type: Refactor

#907 Improvement: Change style of material and printing settings in 3DP
  src/app/images/56x56/btn_checked@56x56.png
  src/app/images/56x56/btn_unchecked@56x56.png
  src/app/widgets/Control/Control.jsx
  src/app/widgets/PrintingConfigurations/Configurations.jsx
  src/app/widgets/PrintingConfigurations/styles.styl
  src/app/widgets/PrintingMaterial/Material.jsx
  src/app/widgets/PrintingMaterial/styles.styl
Labels: Category: 3DP, Type: Improvement

#910 Improvement: Add to show notice in "Create Toolpath" when no models selected
  src/app/images/cnc-laser/ic_warning_20x20.png
  src/app/widgets/CncLaserToolPath/CreateToolPath.jsx
Labels: Type: Improvement

#915 Feature: Add dot movement mode for laser bw and halftone
  src/app/lib/renderer/ToolPathRenderer.js
  src/server/lib/ToolPathGenerator/LaserToolPathGenerator.js
Labels: Category: Laser, Type: Feature

#916 Fix: Fix bug on extra toolpath and other bugs
  src/app/components/SMCanvas/Controls.jsx
  src/app/components/SMCanvas/TransformControls2D.js
  src/app/components/Select/ChangedReactSelect.jsx
  src/app/constants/index.js
  src/app/flux/editor/actions-process.js
  src/app/flux/project/index.js
  src/app/models/ModelGroup.js
  src/app/models/ThreeModel.js
  src/app/toolpaths/ToolPath.js
  src/app/views/ToolPathConfigurations/ToolPathConfigurations.jsx
  src/app/widgets/CncLaserList/ToolPathList/ToolPathFooter.jsx
  src/app/widgets/PrintingVisualizer/VisualizerInfo.jsx
  src/server/controllers/Marlin/Marlin.js
Labels: Type: Fix

#922 Fix: Fix right control bar twitch in laser and cnc
  src/app/widgets/JobType/JobType.jsx
Labels: Type: Fix

#918 Improvement: Add Object/Toolpath switch display interaction
  src/app/flux/cnc/index.js
  src/app/flux/editor/actions-process.js
  src/app/flux/editor/index.js
  src/app/flux/laser/index.js
  src/app/images/18x18/ic_back_normal_18x18.png
  src/app/toolpaths/ToolPathGroup.js
  src/app/widgets/CNCVisualizer/Visualizer.jsx
  src/app/widgets/CNCVisualizer/styles.styl
  src/app/widgets/CncLaserOutput/Output.jsx
  src/app/widgets/CncLaserTopRight/VisualizerTopRight.jsx
  src/app/widgets/CncLaserTopRight/styles.styl
  src/app/widgets/LaserVisualizer/Visualizer.jsx
Labels: Type: Improvement

#921 Fix: Fix process image err on un-uniform scaling of SVG Text
  src/app/constants/index.js
  src/app/models/SvgModel.js
  src/server/lib/svg-convert.js
Labels: Type: Fix

#925 Fix: Fix bugs of 3dp profile manger & cnc tool manger
  resources/CuraEngine/Config/snapmaker.def.json
  src/app/components/Select/ChangedReactSelect.jsx
  src/app/components/three-extensions/OBJExporter.js
  src/app/models/ThreeModel.js
  src/app/views/CncToolManager/CncToolManager.jsx
  src/app/views/CncToolManager/styles.styl
  src/app/views/PrintingManager/PrintingManager.jsx
  src/app/views/PrintingManager/styles.styl
  src/app/widgets/CNCVisualizer/Visualizer.jsx
  src/app/widgets/LaserVisualizer/Visualizer.jsx
  src/app/widgets/PrintingMaterial/Material.jsx
  src/electron-app/Menu.js
Labels: Type: Fix

#927 Fix: Fix model positionZ changed when moving model
  src/app/flux/project/index.js
  src/app/lib/numeric-utils.js
  src/app/models/ModelGroup.js
  src/app/models/SvgModel.js
Labels: Type: Fix

#926 Fix: Fix select showing the empty option on WifiConnection widget
  src/app/components/SMCanvas/Peripheral.js
  src/app/components/Select/ChangedReactSelect.jsx
  src/app/flux/machine/action-discover.js
  src/app/views/CncToolManager/CncToolManager.jsx
  src/app/widgets/Connection/WifiConnection.jsx
Labels: Type: Fix

#932 Fix: Fix bug for cnc stl size
  src/app/flux/editor/index.js
  src/app/widgets/CaseLibrary/CaseConfig.js
  src/server/services/api/api-image.js
Labels: Type: Fix

#933 Fix: Fix process bug in laser and cnc
  resources/CuraEngine/Config/material.abs.def.json
  resources/CuraEngine/Config/material.pla.def.json
  src/app/containers/App.jsx
  src/app/flux/printing/index.js
  src/app/lib/modal.jsx
  src/app/views/ToolPathConfigurations/ToolPathConfigurations.jsx
  src/app/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx
  src/app/widgets/CncLaserTopRight/VisualizerTopRight.jsx
  src/app/widgets/PrintingConfigurations/Configurations.jsx
  src/app/widgets/PrintingMaterial/Material.jsx
Labels: Type: Fix

#934 Fix: Fix door detection error in workspace
  src/app/widgets/Enclosure/Enclosure.jsx
Labels: Type: Fix

#936 Fix: Fix cnc toolpath list type error
  src/app/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx
Labels: Type: Fix

#935 Fix: Fix bug of toolpath regeneration
  src/app/flux/editor/actions-process.js
  src/app/flux/editor/index.js
  src/app/toolpaths/ToolPath.js
  src/app/toolpaths/ToolPathGroup.js
Labels: Type: Fix

#941 Fix: Fix toolpath error
  src/app/i18n/cs/resource.json
  src/app/i18n/de/resource.json
  src/app/i18n/en/resource.json
  src/app/i18n/es/resource.json
  src/app/i18n/fr/resource.json
  src/app/i18n/hu/resource.json
  src/app/i18n/it/resource.json
  src/app/i18n/ja/resource.json
  src/app/i18n/ko/resource.json
  src/app/i18n/pt-br/resource.json
  src/app/i18n/ru/resource.json
  src/app/i18n/uk/resource.json
  src/app/i18n/zh-cn/resource.json
  src/app/i18n/zh-tw/resource.json
  src/app/models/ModelGroup.js
  src/app/toolpaths/ToolPath.js
  src/app/toolpaths/ToolPathGroup.js
  src/app/views/ToolPathConfigurations/cnc/CncParameters.jsx
  src/app/widgets/CNCVisualizer/Visualizer.jsx
  src/app/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx
  src/app/widgets/CncLaserOutput/Output.jsx
  src/app/widgets/LaserVisualizer/Visualizer.jsx
Labels: Type: Fix

#905 Improvement: Upgrade to lockfileVersion 2 using npm v7
  .github/workflows/build-on-create-release.yml
  package-lock.json
  package.json
  src/package.json
Labels: Type: Build

#948 Improvement: Upgrade to lockfileVersion 2 using npm v7
  package-lock.json
  package.json
Labels: Type: Build, dependencies

#947 Refactor: Change styles and i18n words
  src/app/containers/App.jsx
  src/app/i18n/cs/resource.json
  src/app/i18n/de/resource.json
  src/app/i18n/en/resource.json
  src/app/i18n/es/resource.json
  src/app/i18n/fr/resource.json
  src/app/i18n/hu/resource.json
  src/app/i18n/it/resource.json
  src/app/i18n/ja/resource.json
  src/app/i18n/ko/resource.json
  src/app/i18n/pt-br/resource.json
  src/app/i18n/ru/resource.json
  src/app/i18n/uk/resource.json
  src/app/i18n/zh-cn/resource.json
  src/app/i18n/zh-tw/resource.json
  src/app/toolpaths/utils.js
  src/app/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx
  src/app/widgets/CncLaserShared/TransformationSection.jsx
  src/app/widgets/PrintingConfigurations/Configurations.jsx
  src/app/widgets/PrintingMaterial/Material.jsx
Labels: Type: Refactor

#949 Fix: Fix door detection error and new file error in 3.14
  src/app/flux/project/index.js
  src/app/widgets/Enclosure/Enclosure.jsx
Labels: Type: Fix

#950 Fix: Fix bugs for 3.15-alpha.28
  resources/CuraEngine/Config/snapmaker.def.json
  src/app/models/SVGActionsFactory.js
Labels: Type: Fix

#951 Improvement: Add simulation need to preview flag in cnc state
  src/app/flux/cnc/index.js
  src/app/flux/editor/actions-process.js
  src/app/widgets/CncLaserTopRight/VisualizerTopRight.jsx
Labels: Category: CNC, Type: Improvement

#952 Fix: Fix bugs related case and toolpath
  resources/CuraEngine/Config/CncConfig/Default.def.json
  resources/CuraEngine/Config/CncConfig/active.def.json
  src/app/components/SvgIcon/SvgIcon.jsx
  src/app/containers/App.jsx
  src/app/flux/project/index.js
  src/app/models/ModelInfoUtils.js
  src/app/models/SvgModel.js
  src/app/styles/vendor.styl
  src/app/toolpaths/ToolPath.js
  src/app/toolpaths/ToolPathGroup.js
  src/app/views/ToolPathConfigurations/ToolPathConfigurations.jsx
  src/app/views/ToolPathConfigurations/cnc/CncParameters.jsx
  src/app/views/ToolPathConfigurations/styles.styl
  src/app/widgets/CaseLibrary/CaseConfig.js
  src/app/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx
  src/app/widgets/CncLaserList/styles.styl
  src/server/DataStorage.js
Labels: Type: Fix

#955 Fix: Fix the parameter bug in svg black and white mode
  src/app/constants/index.js
  src/app/containers/Cnc/Cnc.jsx
  src/app/models/ModelInfoUtils.js
  src/app/toolpaths/utils.js
  src/app/widgets/CNCVisualizer/VisualizerTopLeft.jsx
  src/server/constants/index.js
  src/server/services/task-manager/generateToolPath.js
  src/server/services/task-manager/generateViewPath.js
Labels: Type: Fix

#953 Fix: Fix bug of toolpath regeneration
  src/app/toolpaths/ToolPath.js
Labels: Type: Fix

#956 Refactor: Change style in 3DP settings details
  src/app/views/CncToolManager/CncToolManager.jsx
  src/app/widgets/PrintingConfigurations/Configurations.jsx
  src/app/widgets/PrintingMaterial/Material.jsx
Labels: Category: 3DP, Type: Refactor

#959 Fix: Compatible with cnc stl mode modification
  src/app/flux/project/index.js
Labels: Type: Fix

#961 Fix: Fix dxf process view scaled twice
  src/app/models/SvgModel.js
Labels: Type: Fix

#962 Fix: Fix toolpath manager tool params wrong value
  src/app/views/CncToolManager/CncToolManager.jsx
  src/app/views/ToolPathConfigurations/ToolPathConfigurations.jsx
  src/app/views/ToolPathConfigurations/cnc/ToolParameters.jsx
  src/app/widgets/CncLaserShared/TransformationSection.jsx
Labels: Category: CNC, Type: Fix

#967 Improvement: Improve selection on tool managaer
  src/app/views/CncToolManager/CncToolManager.jsx
Labels: Type: Improvement

#968 Fix: Fix change height function in editor
  src/app/widgets/CncLaserShared/TransformationSection.jsx
Labels: Category: Editor, Type: Fix

#979 Fix: Remove environment when recovery being canceled
  src/app/containers/App.jsx
Labels: Type: Fix

#984 Fix: Catch M1011 not found error
  src/server/controllers/Marlin/Marlin.js
Labels: Type: Fix

#985 Improvement: Change create toolpath button state
  package.json
  src/app/widgets/CncLaserToolPath/CreateToolPath.jsx
  src/app/widgets/CncLaserToolPath/styles.styl
Labels: Type: Improvement
