Repository Snapmaker/Luban, pull requests merged in 2021-11, with the labels that each got.

#1255 Fix: Fix camera capture position error in A250
  src/app/ui/widgets/LaserCameraAidBackground/ExtractSquareTrace/index.jsx
Labels: Type: Fix

#1253 Fix: Fix generating toolpath error
  src/app/flux/editor/actions-process.js
Labels: Type: Fix

#1249 Fix: Fix job setting error
  src/app/flux/editor/index.js
  src/app/ui/widgets/JobType/JobType.jsx
Labels: Type: Fix

#1256 Fix: Fix original laser print square trace
  src/app/ui/widgets/LaserSetBackground/PrintSquareTrace/index.jsx
  src/app/ui/widgets/WifiTransport/WifiTransport.jsx
Labels: Type: Fix

#1257 Fix: Fix large model placement
  package.json
  src/app/flux/printing/index.js
  src/app/models/ModelGroup.js
  src/app/models/SVGActionsFactory.js
  src/app/models/ThreeModel.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/three-extensions/ThreeUtils.js
  src/app/three-extensions/TransformControls.js
  src/app/ui/components/Buttons/button.jsx
  src/app/ui/components/SMCanvas/Canvas.jsx
  src/app/ui/components/SMCanvas/Peripheral.js
  src/app/ui/components/SMCanvas/TransformControls.js
  src/app/ui/layouts/AppLayout.jsx
  src/app/ui/pages/Settings/Settings.jsx
  src/app/ui/views/Cnc3DVisualizer/Canvas/Canvas.jsx
  src/app/ui/views/Cnc3DVisualizer/Cnc3DVisualizer.jsx
  src/app/ui/widgets/WifiTransport/WifiTransport.jsx
  src/app/ui/widgets/WorkspaceVisualizer/Visualizer.jsx
  src/package.json
  src/server/services/api/api-image.js
  src/shared/lib/SVGParser/SvgToString.js
Labels: Type: Fix

#1258 Refactor: change i18n keys and values
  gulp/tasks/i18next.js
  resources/CuraEngine/Config/printing/a150_single/quality.fast_print.def.json
  resources/CuraEngine/Config/printing/a150_single/quality.high_quality.def.json
  resources/CuraEngine/Config/printing/a150_single/quality.normal_quality.def.json
  resources/CuraEngine/Config/printing/a250_single/quality.fast_print.def.json
  resources/CuraEngine/Config/printing/a250_single/quality.high_quality.def.json
  resources/CuraEngine/Config/printing/a250_single/quality.normal_quality.def.json
  resources/CuraEngine/Config/printing/a350_single/quality.fast_print.def.json
  resources/CuraEngine/Config/printing/a350_single/quality.high_quality.def.json
  resources/CuraEngine/Config/printing/a350_single/quality.normal_quality.def.json
  resources/CuraEngine/Config/printing/fdmprinter.def.json
  resources/CuraEngine/Config/printing/snapmaker.def.json
  scripts/swap2.js
  src/app/constants/copy.js
  src/app/constants/copy.jsx
  src/app/constants/index.js
  src/app/lib/manager/ProgressManager.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/layouts/AppLayout.jsx
  src/app/ui/pages/HomePage/SettingGuideModal.jsx
  src/app/ui/pages/Laser.jsx
  src/app/ui/views/DefinitionCreator.jsx
  src/app/ui/views/ProfileManager/index.jsx
  src/app/ui/views/ToolPathConfigurations/cnc/CncParameters.jsx
  src/app/ui/views/ToolPathConfigurations/laser/GcodeParameters.jsx
  src/app/ui/views/ToolPathConfigurations/laser/PresentSelector.jsx
  src/app/ui/widgets/CNCPath/Image3dParameters.jsx
  src/app/ui/widgets/CncLaserShared/TextParameters.jsx
  src/app/ui/widgets/Connection/PrintingState.jsx
  src/app/ui/widgets/LaserCameraAidBackground/ExtractSquareTrace/index.jsx
  src/app/ui/widgets/LaserCameraAidBackground/ManualCalibration/index.jsx
  src/app/ui/widgets/LaserCameraAidBackground/SetBackground.jsx
  src/app/ui/widgets/LaserSetBackground/ExtractSquareTrace/index.jsx
  src/app/ui/widgets/LaserSetBackground/Instructions.jsx
  src/app/ui/widgets/LaserSetBackground/PrintSquareTrace/index.jsx
  src/app/ui/widgets/LaserSetBackground/SetBackground.jsx
  src/app/ui/widgets/LaserStackedModel/index.jsx
  src/app/ui/widgets/Marlin/Laser.jsx
  src/app/ui/widgets/Marlin/Printing.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/RotationAnalysisOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
  src/app/ui/widgets/WifiTransport/WifiTransport.jsx
  src/app/ui/widgets/WorkspaceVisualizer/Visualizer.jsx
  src/shared/lib/SVGParser/SvgToString.js
Labels: Type: Refactor

#1259 Improvement: Update model cut UI & decrease CPU usage
  src/app/ui/widgets/LaserStackedModel/Canvas/index.jsx
  src/app/ui/widgets/LaserStackedModel/Canvas/styles.styl
  src/app/ui/widgets/LaserStackedModel/index.jsx
  src/app/ui/widgets/LaserStackedModel/styles.styl
Labels: Type: Improvement

#1267 Refactor: Change words layers to number of layers
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
Labels: Type: Refactor

#1265 Feature: Add shortcut for reset user config
  src/app/api/index.js
  src/app/flux/setting/index.js
  src/app/lib/i18n.js
  src/app/ui/App.jsx
  src/server/DataStorage.js
  src/server/services/api/api-users.js
  src/server/services/index.js
Labels: Type: Feature

#1266 Feature: Change text path parsing and fix unable to save project file in linux
  resources/fonts/Arial Black.woff
  src/app/lib/uni-api.js
  src/app/models/ModelInfoUtils.js
  src/app/models/SVGActionsFactory.js
  src/app/models/SvgModel.js
  src/app/ui/components/Input/TextArea.jsx
  src/app/ui/components/Input/styles.styl
  src/app/ui/components/Select/ChangedReactSelect.jsx
  src/app/ui/layouts/AppLayout.jsx
  src/app/ui/widgets/CncLaserShared/TextParameters.jsx
  src/app/ui/widgets/CncLaserShared/TransformationSection.jsx
  src/server/lib/MeshProcess/STLToSvgStack.js
  src/server/lib/clipper/cLipper-adapter.js
  src/server/lib/svg-convert.js
  src/server/services/api/api-utils.js
  src/shared/lib/FontManager.js
  src/shared/lib/SVGParser/Parser.js
  src/shared/lib/SVGParser/SvgToString.js
  src/shared/lib/math/Vector2.js
  src/shared/lib/union-shapes.js
Labels: Type: Feature

#1272 Fix: Bugfix workspace macro input
  src/app/models/SVGActionsFactory.js
  src/app/ui/widgets/Macro/Macro.jsx
  src/app/ui/widgets/Macro/index.jsx
  src/app/ui/widgets/WorkspaceVisualizer/Visualizer.jsx
Labels: Type: Fix

#1275 Fix: Workspace bugs fix
  src/app/flux/project/index.js
  src/app/flux/workspace/index.js
  src/app/styles/global.styl
  src/app/ui/components/SMCanvas/Canvas.jsx
  src/app/ui/pages/Cnc.jsx
  src/app/ui/pages/Laser.jsx
  src/app/ui/pages/Printing.jsx
  src/app/ui/widgets/Control/Control.jsx
  src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
  src/app/ui/widgets/WifiTransport/WifiTransport.jsx
  src/app/ui/widgets/WifiTransport/index.styl
  src/app/ui/widgets/WorkspaceVisualizer/Visualizer.jsx
Labels: Type: Fix

#1271 Improvement: Improve workspace state
  src/app/flux/machine/Server.js
  src/app/flux/machine/index.js
  src/app/flux/workspace/index.js
  src/app/ui/modals/modal-machine-select.jsx
  src/app/ui/pages/CncLaserShared/MainToolBar.jsx
  src/app/ui/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx
  src/app/ui/widgets/Connection/SerialConnection.jsx
  src/app/ui/widgets/Connection/WifiConnection.jsx
  src/app/ui/widgets/Marlin/Marlin.jsx
  src/app/ui/widgets/WifiTransport/WifiTransport.jsx
  src/app/ui/widgets/WorkspaceVisualizer/Visualizer.jsx
  src/server/controllers/Marlin/Marlin.js
  src/server/controllers/constants.js
Labels: Type: Improvement

#1277 Refactor: Change i18n translations
  resources/CuraEngine/Config/printing/snapmaker.def.json
  src/app/constants/copy.js
  src/app/constants/index.js
  src/app/flux/machine/Server.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/pages/HomePage/index.jsx
  src/app/ui/pages/Workspace.jsx
  src/app/ui/views/LaserPresentManager/LaserPresentManager.jsx
  src/app/ui/views/PrintingManager/PrintingManager.jsx
  src/app/ui/views/ToolPathConfigurations/laser/GcodeParameters.jsx
  src/app/ui/widgets/MachineSetting/machineSetting.jsx
  src/app/ui/widgets/Marlin/Marlin.jsx
  src/app/ui/widgets/WifiTransport/WifiTransport.jsx
  src/server/services/task-manager/generateGcode.js
Labels: Type: Refactor

#1279 Refactor change UI
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/resources/images/machine/function-laser-10w.jpg
  src/app/resources/images/machine/size-1.0-original.jpg
  src/app/resources/images/machine/size-2.0-A150.jpg
  src/app/resources/images/machine/size-2.0-A150.png
  src/app/resources/images/machine/size-2.0-A250.jpg
  src/app/resources/images/machine/size-2.0-A250.png
  src/app/resources/images/machine/size-2.0-A350.jpg
  src/app/ui/components/Select/ChangedReactSelect.jsx
  src/app/ui/modals/modal-machine-select.jsx
  src/app/ui/pages/CncLaserShared/MainToolBar.jsx
  src/app/ui/pages/HomePage/SettingGuideModal.jsx
  src/app/ui/pages/HomePage/styles.styl
  src/app/ui/widgets/LaserCameraAidBackground/ExtractSquareTrace/index.jsx
  src/app/ui/widgets/LaserCameraAidBackground/styles.styl
  src/app/ui/widgets/WorkspaceVisualizer/Visualizer.jsx
Labels: Type: Style

#1280 Fix: Fix translation error
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/ui/views/ProfileManager/ConfigValueBox.jsx
  src/app/ui/views/ProfileManager/index.jsx
  src/app/ui/widgets/Marlin/Laser.jsx
  src/app/ui/widgets/PrintingConfigurations/Configurations.jsx
Labels: Type: Fix

#1285 Fix: Bugfix v4.1-beta4
  src/app/flux/editor/index.js
  src/app/flux/manager/DefinitionManager.js
  src/app/flux/operation-history/ScaleOperation2D.js
  src/app/ui/SVGEditor/svg-content/SVGContentGroup.js
  src/app/ui/views/ToolPathConfigurations/cnc/CncParameters.jsx
  src/app/ui/widgets/Marlin/Laser.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
Labels: Type: Fix

#1282 Fix: Fix workspace error
  src/app/flux/workspace/index.js
  src/app/resources/i18n/zh-cn/resource.json
  src/app/ui/modals/modal-machine-select.jsx
  src/app/ui/views/ToolPathConfigurations/ToolPathConfigurations.jsx
  src/app/ui/widgets/Connection/SerialConnection.jsx
  src/app/ui/widgets/Marlin/CNC.jsx
  src/app/ui/widgets/Marlin/Laser.jsx
  src/app/ui/widgets/Marlin/Printing.jsx
  src/app/ui/widgets/WifiTransport/WifiTransport.jsx
  src/app/ui/widgets/WorkspaceVisualizer/Visualizer.jsx
Labels: Type: Fix

#1287 Style: Change UI
  src/app/resources/images/machine/size-1.0-original2.jpg
  src/app/resources/images/machine/size-2.0-A1502.jpg
  src/app/resources/images/machine/size-2.0-A2502.jpg
  src/app/resources/images/machine/size-2.0-A3502.jpg
  src/app/styles/sm-flex.styl
  src/app/ui/components/Modal/ModalSmall.jsx
  src/app/ui/modals/modal-machine-select.jsx
  src/app/ui/modals/styles.styl
  src/app/ui/pages/CncLaserShared/MainToolBar.jsx
  src/app/ui/pages/HomePage/SettingGuideModal.jsx
  src/app/ui/pages/HomePage/styles.styl
  src/app/ui/widgets/LaserCameraAidBackground/ExtractSquareTrace/index.jsx
  src/app/ui/widgets/WorkspaceVisualizer/Visualizer.jsx
Labels: Type: Style

#1297 Fix: Bugfix v4.1 release 1
  src/app/flux/editor/index.js
  src/app/models/ModelGroup.js
  src/app/ui/components/SMCanvas/TransformControls.js
  src/app/ui/widgets/WorkingProgress/WorkingProgress.jsx
Labels: Type: Fix

#1298 Improvement: Improve rotation placement plane
  src/app/models/ModelGroup.js
  src/app/three-extensions/ThreeUtils.js
Labels: Type: Improvement

#1291 Fix: Fix marlin laser widget error
  src/app/flux/machine/index.js
  src/app/flux/workspace/index.js
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/ui/views/ProfileManager/ConfigValueBox.jsx
  src/app/ui/views/ProfileManager/index.jsx
  src/app/ui/widgets/Control/Control.jsx
  src/app/ui/widgets/Marlin/Laser.jsx
  src/app/ui/widgets/WifiTransport/WifiTransport.jsx
  src/app/ui/widgets/WorkspaceVisualizer/Visualizer.jsx
Labels: Type: Fix

#1300 Feature: Introduce Typescript
  .eslintrc.js
  gulp/tasks/i18next.js
  gulp/tasks/server.js
  package.json
  src/app/flux/editor/index.js
  src/app/lib/confirm.jsx
  src/app/models/Resource.ts
  src/app/models/SvgModel.js
  src/app/models/ThreeModel.js
  src/app/toolpaths/ToolPathGroup.js
  src/app/ui/SVGEditor/SVGCanvas.jsx
  src/app/ui/SVGEditor/SVGLeftBar.jsx
  src/app/ui/SVGEditor/lib/path.js
  src/app/ui/components/Card/CardWrapper.jsx
  src/app/ui/components/SvgIcon/SvgIcon.jsx
  src/app/ui/components/TipTrigger/index.jsx
  src/app/ui/pages/HomePage/Begin.jsx
  src/app/ui/pages/HomePage/QuickStart.jsx
  src/app/ui/pages/HomePage/index.jsx
  src/app/ui/utils/renderModal.jsx
  src/app/ui/views/ProfileManager/ConfigValueBox.jsx
  src/app/ui/views/ToolPathConfigurations/laser/LaserParameters.jsx
  src/server/controllers/index.js
  src/server/services/index.js
  tsconfig.json
  webpack.config.app.development.js
  webpack.config.app.production.js
  webpack.config.server.development.js
  webpack.config.server.production.js
Labels: Type: Feature

#1312 Fix: bugfix v4.1 left issue-1
  src/app/flux/editor/index.js
  src/app/flux/printing/index.js
  src/app/ui/SVGEditor/SVGCanvas.jsx
  src/app/ui/pages/HomePage/QuickStart.jsx
  src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
Labels: Type: Fix

#1315 Fix: Fix translation error
  resources/CuraEngine/Config/laser/a150_1600mw/present.default_CUT.def.json
  resources/CuraEngine/Config/laser/a150_1600mw/present.default_HDFill.def.json
  resources/CuraEngine/Config/laser/a150_1600mw/present.default_PathEngrave.def.json
  resources/CuraEngine/Config/laser/a150_1600mw/present.default_SDFill.def.json
  resources/CuraEngine/Config/laser/a250_1600mw/present.default_CUT.def.json
  resources/CuraEngine/Config/laser/a250_1600mw/present.default_HDFill.def.json
  resources/CuraEngine/Config/laser/a250_1600mw/present.default_PathEngrave.def.json
  resources/CuraEngine/Config/laser/a250_1600mw/present.default_SDFill.def.json
  resources/CuraEngine/Config/laser/a350_1600mw/present.default_CUT.def.json
  resources/CuraEngine/Config/laser/a350_1600mw/present.default_HDFill.def.json
  resources/CuraEngine/Config/laser/a350_1600mw/present.default_PathEngrave.def.json
  resources/CuraEngine/Config/laser/a350_1600mw/present.default_SDFill.def.json
  src/app/constants/copy.js
  src/app/constants/index.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/modals/modal-machine-select.jsx
Labels: Type: Fix

#1319 Fix fix v4.1 error
  src/app/ui/widgets/Console/Console.jsx
  src/app/ui/widgets/Marlin/Laser.jsx
  src/app/ui/widgets/WifiTransport/WifiTransport.jsx
  src/server/controllers/Marlin/MarlinController.js
Labels: Type: Fix
