Repository Snapmaker/Luban, pull requests merged in 2021-07, with the labels that each got.

#1014 added german translation for 3.15.1
  src/app/resources/i18n/de/resource.json
Labels: Type: Improvement

#1046 Improvement improve tool path config for laser and cnc
  src/app/constants/index.js
  src/app/flux/widget/WidgetState.js
  src/app/models/ModelInfoUtils.js
  src/app/ui/views/ToolPathConfigurations/ToolPathConfigurations.jsx
  src/app/ui/views/ToolPathConfigurations/cnc/CncParameters.jsx
  src/app/ui/views/ToolPathConfigurations/cnc/ToolParameters.jsx
  src/app/ui/views/ToolPathConfigurations/cnc/ToolSelection.jsx
  src/app/ui/views/ToolPathConfigurations/laser/GcodeParameters.jsx
  src/app/ui/views/ToolPathConfigurations/laser/LaserParameters.jsx
  src/app/ui/views/ToolPathConfigurations/styles.styl
  src/app/ui/widgets/CNCPath/CNCPath.jsx
  src/app/ui/widgets/CNCPath/VectorParameters.jsx
  src/app/ui/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx
  src/app/ui/widgets/CncLaserOutput/Output.jsx
  src/app/ui/widgets/CncLaserShared/GcodeParameters.jsx
  src/app/ui/widgets/CncLaserShared/TransformationSection.jsx
  src/app/ui/widgets/LaserParams/LaserParameters.jsx
Labels: Type: Improvement

#1048 Fix: Fix saving project error and coordinate mode error
  src/app/constants/index.js
  src/app/flux/appbar-menu/index.js
  src/app/flux/editor/actions-process.js
  src/app/flux/editor/index.js
  src/app/flux/project/index.js
  src/app/toolpaths/ToolPathGroup.js
  src/app/ui/pages/Cnc.jsx
  src/app/ui/pages/HomePage/Begin.jsx
  src/app/ui/pages/Laser.jsx
  src/app/ui/views/Cnc3DVisualizer/Cnc3DVisualizer.jsx
  src/app/ui/views/ToolPathConfigurations/cnc/CncParameters.jsx
  src/app/ui/views/ToolPathConfigurations/cnc/ToolSelector.jsx
  src/app/ui/views/ToolPathConfigurations/laser/LaserParameters.jsx
  src/app/ui/widgets/CNCVisualizer/Visualizer.jsx
  src/app/ui/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx
  src/app/ui/widgets/CncLaserList/styles.styl
  src/app/ui/widgets/PrintingObjectList/styles.styl
  src/server/controllers/Marlin/Marlin.js
Labels: Type: Fix

#1050 Fix: Fix v3.15 left issues
  src/app/flux/appbar-menu/index.js
  src/app/flux/printing/index.js
  src/app/lib/normalize-range.js
  src/app/ui/SVGEditor/SVGCanvas.jsx
  src/app/ui/components/SMCanvas/Controls.jsx
  src/app/ui/layouts/AppLayout.jsx
  src/app/ui/utils/renderRecoveryModal.jsx
  src/app/ui/views/AppBar/AppBar.jsx
  src/app/ui/views/model-item.jsx
  src/app/ui/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx
  src/app/ui/widgets/CncLaserList/styles.styl
  src/app/ui/widgets/JobType/JobType.jsx
  src/app/ui/widgets/PrintingObjectList/styles.styl
  src/app/ui/widgets/PrintingVisualizer/VisualizerPreviewControl.jsx
  src/shared/lib/gcodeToolPath.js
Labels: Type: Fix

#1052 Fix: bugfix alpha-2
  src/app/flux/project/index.js
  src/app/lib/numeric-utils.js
  src/app/ui/pages/Laser.jsx
  src/app/ui/widgets/CncLaserOutput/Output.jsx
Labels: Type: Fix

#1055 Refactor: Refactor appbar UI in browser & electron
  src/app/ui/App.styl
  src/app/ui/SVGEditor/index.styl
  src/app/ui/layouts/AppLayout.jsx
  src/app/ui/layouts/styles/appbar.styl
  src/app/ui/layouts/styles/homepage.styl
  src/app/ui/layouts/styles/maintoolbar.styl
  src/app/ui/layouts/styles/project.styl
  src/app/ui/layouts/styles/workspace.styl
  src/app/ui/widgets/WorkspaceVisualizer/Visualizer.jsx
  src/app/ui/widgets/WorkspaceVisualizer/index.styl
  src/app/ui/widgets/styles.styl
Labels: Type: Improvement

#1056 Fix: Fix next disabled error
  src/app/ui/widgets/CncLaserOutput/Output.jsx
Labels: Type: Fix

#1054 Feature: Add toolPath model relation color
  src/app/flux/editor/actions-process.js
  src/app/flux/printing/index.js
  src/app/flux/project/index.js
  src/app/models/SVGActionsFactory.js
  src/app/models/SvgModel.js
  src/app/toolpaths/ToolPathGroup.js
  src/app/ui/SVGEditor/PrintableArea.js
  src/app/ui/SVGEditor/element-utils.js
  src/app/ui/SVGEditor/svg-content/SVGContentGroup.js
  src/app/ui/widgets/CncLaserList/ToolPathList/ToolPathFooter.jsx
  src/app/ui/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx
Labels: Type: Feature

#1060 Feature: Add luban engine
  package.json
  src/app/flux/machine/index.js
  src/app/models/ModelInfoUtils.js
  src/app/toolpaths/ToolPath.js
  src/app/ui/App.jsx
  src/app/ui/views/ToolPathConfigurations/cnc/CncParameters.jsx
  src/app/ui/views/ToolPathConfigurations/laser/LaserParameters.jsx
  src/package.json
  src/server/lib/ToolPathGenerator/CncReliefToolPathGenerator.js
  src/server/lib/ToolPathGenerator/CncToolPathGenerator.js
  src/server/lib/ToolPathGenerator/LaserToolPathGenerator.js
  src/server/lib/ToolPathGenerator/MeshToolPath/CncMeshLinkageToolPathGenerator.js
  src/server/services/task-manager/generateGcode.js
  src/server/services/task-manager/generateToolPath.js
  src/server/slicer/call-engine.js
  src/shared/lib/random-utils.js
Labels: Category: CNC, Category: Laser, Type: Feature

#1062 Feature: Add undo & redo
  src/app/flux/appbar-menu/index.js
  src/app/flux/cnc/index.js
  src/app/flux/editor/actions-process.js
  src/app/flux/editor/index.js
  src/app/flux/laser/index.js
  src/app/flux/operation-history/AddOperation2D.js
  src/app/flux/operation-history/AddOperation3D.js
  src/app/flux/operation-history/DeleteOperation2D.js
  src/app/flux/operation-history/DeleteOperation3D.js
  src/app/flux/operation-history/DeleteToolPathOperation.js
  src/app/flux/operation-history/MoveOperation2D.js
  src/app/flux/operation-history/MoveOperation3D.js
  src/app/flux/operation-history/Operation.js
  src/app/flux/operation-history/OperationHistory.js
  src/app/flux/operation-history/Operations.js
  src/app/flux/operation-history/RotateOperation2D.js
  src/app/flux/operation-history/RotateOperation3D.js
  src/app/flux/operation-history/ScaleOperation2D.js
  src/app/flux/operation-history/ScaleOperation3D.js
  src/app/flux/operation-history/VisibleOperation2D.js
  src/app/flux/operation-history/VisibleOperation3D.js
  src/app/flux/operation-history/index.js
  src/app/flux/printing/actions-base.js
  src/app/flux/printing/index.js
  src/app/flux/project/index.js
  src/app/models/ModelGroup.js
  src/app/models/SVGActionsFactory.js
  src/app/models/ThreeModel.js
  src/app/ui/SVGEditor/SVGEditor.jsx
  src/app/ui/components/SMCanvas/Canvas.jsx
  src/app/ui/components/SMCanvas/Controls.jsx
  src/app/ui/layouts/AppLayout.jsx
  src/app/ui/pages/Cnc.jsx
  src/app/ui/pages/Laser.jsx
  src/app/ui/pages/Printing.jsx
  src/app/ui/widgets/CNCVisualizer/Visualizer.jsx
  src/app/ui/widgets/CncLaserList/ObjectList/ObjectListBox.jsx
  src/app/ui/widgets/LaserVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingObjectList/PrintingObjectListBox.jsx
  src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
Labels: Type: Feature

#1064 Fix: Fix profile manager reset error after restart Luban
  src/app/styles/global-edge-distance.styl
  src/app/styles/global-layout.styl
  src/app/styles/global-var.styl
  src/app/ui/pages/Cnc.jsx
  src/app/ui/pages/Laser.jsx
  src/app/ui/views/ProfileManager/ConfigValueBox.jsx
  src/app/ui/views/ProfileManager/SettingItem.jsx
  src/app/ui/views/ProfileManager/index.jsx
  src/app/ui/views/ToolPathConfigurations/cnc/CncParameters.jsx
  src/app/ui/views/ToolPathConfigurations/cnc/GcodeParameters.jsx
  src/app/ui/views/ToolPathConfigurations/cnc/ToolParameters.jsx
  src/app/ui/views/ToolPathConfigurations/cnc/ToolSelector.jsx
  src/app/ui/views/ToolPathConfigurations/laser/GcodeParameters.jsx
  src/app/ui/views/ToolPathConfigurations/laser/LaserParameters.jsx
  src/app/ui/widgets/CNCPath/Image3dParameters.jsx
  src/app/ui/widgets/CNCPath/ImageProcessMode.jsx
  src/app/ui/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx
  src/app/ui/widgets/CncLaserList/styles.styl
  src/app/ui/widgets/PrintingConfigurations/Configurations.jsx
  src/server/DataStorage.js
Labels: Type: Fix

#1067 Refactor: Change 3dp UI
  src/app/styles/global-background.styl
  src/app/styles/global-edge-distance.styl
  src/app/styles/global-layout.styl
  src/app/styles/global-var.styl
  src/app/ui/views/model-item.jsx
  src/app/ui/widgets/CNCPath/ImageProcessMode.jsx
  src/app/ui/widgets/PrintingObjectList/PrintingObjectListBox.jsx
  src/app/ui/widgets/PrintingObjectList/styles.styl
  src/app/ui/widgets/PrintingVisualizer/VisualizerBottomLeft.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
  src/app/ui/widgets/PrintingVisualizer/styles.styl
Labels: Type: Refactor

#1065 Refactor: Appbar & maintoolbar styles
  src/app/config/menu/connectionMenu.js
  src/app/config/menu/fileMenu.js
  src/app/config/menu/index.js
  src/app/flux/editor/actions-process.js
  src/app/flux/project/index.js
  src/app/styles/global-var.styl
  src/app/toolpaths/ToolPathGroup.js
  src/app/ui/SVGEditor/SVGCanvas.jsx
  src/app/ui/SVGEditor/index.styl
  src/app/ui/layouts/styles/appbar.styl
  src/app/ui/layouts/styles/project.styl
  src/app/ui/layouts/styles/workspace.styl
  src/app/ui/pages/Cnc.jsx
  src/app/ui/pages/HomePage/styles.styl
  src/app/ui/pages/Laser.jsx
  src/app/ui/pages/Printing.jsx
  src/app/ui/views/AppBar/appbar.styl
  src/app/ui/views/AppBar/styles.styl
  src/app/ui/views/Cnc3DVisualizer/CylinderJob.jsx
  src/app/ui/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx
  src/app/ui/widgets/LaserSetBackground/ExtractSquareTrace/ExtractPreview.jsx
  src/app/ui/widgets/LaserSetBackground/PrintSquareTrace/PrintPreview.jsx
  src/app/ui/widgets/PrintingVisualizer/PrintableCube.jsx
  src/app/ui/widgets/styles.styl
Labels: Type: Refactor

#1076 Refactor: Show recovery modal on home page
  package.json
  src/app/constants/index.js
  src/app/lib/uni-api.js
  src/app/ui/pages/Cnc.jsx
  src/app/ui/pages/HomePage/index.jsx
  src/app/ui/pages/Laser.jsx
  src/app/ui/pages/Printing.jsx
  src/app/ui/pages/Settings/MachineSettings/MachineSettings.jsx
  src/app/ui/utils/renderRecoveryModal.jsx
Labels: Type: Improvement

#1077 Fix: Change SMCanvas and SVGCanvas UI, and bug fix
  src/app/resources/images/cnc-laser/pic_4-axis_stop_bg.png
  src/app/resources/images/cnc-laser/working-origin-3-bottom-left.png
  src/app/resources/images/cnc-laser/working-origin-3-bottom-right.png
  src/app/resources/images/cnc-laser/working-origin-3-center.png
  src/app/resources/images/cnc-laser/working-origin-3-top-left.png
  src/app/resources/images/cnc-laser/working-origin-3-top-right.png
  src/app/ui/SVGEditor/PrintableArea.js
  src/app/ui/components/SMCanvas/TransformControls.js
  src/app/ui/pages/Settings/MachineSettings/MachineSettings.jsx
  src/app/ui/views/ProfileManager/SettingItem.jsx
  src/app/ui/views/ToolPathConfigurations/cnc/ToolParameters.jsx
  src/app/ui/views/ToolPathConfigurations/laser/GcodeParameters.jsx
  src/app/ui/widgets/CncLaserShared/TextParameters.jsx
  src/app/ui/widgets/CncLaserShared/TransformationSection.jsx
  src/app/ui/widgets/Control/DisplayPanel.jsx
  src/app/ui/widgets/JobType/JobType.jsx
  src/app/ui/widgets/LaserTestFocus/TestFocus.jsx
  src/app/ui/widgets/Marlin/Laser.jsx
  src/app/ui/widgets/Marlin/Printing.jsx
  src/app/ui/widgets/Marlin/WorkSpeed.jsx
  src/app/ui/widgets/PrintingVisualizer/PrintableCube.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
Labels: Type: Fix, Type: Style

#1073 Feature: Add shortcuts in 3dp & laser & cnc & appbar
  src/app/config/menu/editMenu.js
  src/app/config/menu/fileMenu.js
  src/app/flux/appbar-menu/index.js
  src/app/flux/editor/index.js
  src/app/flux/printing/index.js
  src/app/lib/shortcut/constants.js
  src/app/lib/shortcut/manager.js
  src/app/lib/uni-api.js
  src/app/models/ModelGroup.js
  src/app/models/SVGActionsFactory.js
  src/app/models/SvgModel.js
  src/app/ui/App.jsx
  src/app/ui/SVGEditor/SVGEditor.jsx
  src/app/ui/SVGEditor/svg-content/SVGContentGroup.js
  src/app/ui/components/Modal/tileModal.jsx
  src/app/ui/layouts/AppLayout.jsx
  src/app/ui/views/AppBar/AppBar.jsx
  src/app/ui/views/model-item.jsx
  src/app/ui/widgets/CNCVisualizer/Visualizer.jsx
  src/app/ui/widgets/CncLaserList/ObjectList/ObjectListBox.jsx
  src/app/ui/widgets/LaserVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingObjectList/PrintingObjectListBox.jsx
  src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
Labels: Type: Feature

#1078 Feature: Undo & redo support scaling and moving
  src/app/flux/editor/index.js
  src/app/flux/operation-history/MoveOperation3D.js
  src/app/flux/operation-history/ScaleOperation3D.js
  src/app/flux/printing/index.js
  src/app/models/ModelGroup.js
  src/app/ui/components/SvgIcon/SvgIcon.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
Labels: Type: Feature

#1072 Fix: Fix laser cnc tool path manager error
  resources/CuraEngine/Config/CncConfig/DefaultCVbit.defv2.json
  resources/CuraEngine/Config/CncConfig/DefaultFEM.defv2.json
  resources/CuraEngine/Config/CncConfig/DefaultMBEM.defv2.json
  resources/CuraEngine/Config/CncConfig/DefaultSGVbit.defv2.json
  resources/CuraEngine/Config/CncConfig/RAcrylicFEM.defv2.json
  resources/CuraEngine/Config/CncConfig/REpoxySGVbit.defv2.json
  resources/CuraEngine/Config/CncConfig/active.defv2.json
  resources/CuraEngine/Config/Default/CncConfig/DefaultCVbit.defv2.json
  resources/CuraEngine/Config/Default/CncConfig/DefaultFEM.defv2.json
  resources/CuraEngine/Config/Default/CncConfig/DefaultMBEM.defv2.json
  resources/CuraEngine/Config/Default/CncConfig/DefaultSGVbit.defv2.json
  resources/CuraEngine/Config/Default/CncConfig/RAcrylicFEM.defv2.json
  resources/CuraEngine/Config/Default/CncConfig/REpoxySGVbit.defv2.json
  resources/CuraEngine/Config/Default/CncConfig/active.defv2.json
  src/app/constants/index.js
  src/app/models/ModelInfoUtils.js
  src/app/ui/views/Cnc3DVisualizer/Cnc3DVisualizer.jsx
  src/app/ui/views/ToolPathConfigurations/cnc/CncParameters.jsx
  src/app/ui/views/ToolPathConfigurations/cnc/ToolParameters.jsx
  src/app/ui/views/ToolPathConfigurations/laser/GcodeParameters.jsx
  src/app/ui/views/ToolPathConfigurations/laser/LaserParameters.jsx
  src/app/ui/widgets/CNCPath/VectorParameters.jsx
  src/app/ui/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx
  src/server/lib/ToolPathGenerator/CncToolPathGenerator.js
  src/server/lib/ToolPathGenerator/LaserToolPathGenerator.js
  src/server/lib/ToolPathGenerator/MeshToolPath/CncMeshLinkageToolPathGenerator.js
  src/server/services/api/api-cnc-definition.js
Labels: Type: Fix

#1083 Fix: Fix laser cnc error
  src/app/flux/cnc/index.js
  src/app/flux/editor/actions-process.js
  src/app/flux/editor/index.js
  src/app/flux/laser/index.js
  src/app/toolpaths/ToolPathGroup.js
  src/app/ui/SVGEditor/PrintableArea.js
  src/app/ui/widgets/CncLaserOutput/Output.jsx
  src/app/ui/widgets/CncLaserShared/PrintablePlate/GridLine.js
  src/app/ui/widgets/CncLaserShared/PrintablePlate/PrintablePlate.jsx
  src/app/ui/widgets/JobType/JobType.jsx
  src/app/ui/widgets/LaserSetBackground/ExtractSquareTrace/index.jsx
Labels: Type: Fix

#1089 Fix: Fix Canvas and fill interval value error
  src/app/constants/index.js
  src/app/ui/pages/HomePage/SettingGuideModal.jsx
  src/app/ui/views/PrintingManager/PrintingManager.jsx
  src/app/ui/widgets/CncLaserShared/PrintablePlate/PrintablePlate.jsx
  src/server/services/task-manager/generateToolPath.js
Labels: Type: Fix

#1092 Fix: Remove camera capture in 4-axis
  src/app/ui/pages/Laser.jsx
Labels: Type: Fix
