Repository Snapmaker/Luban, pull requests merged in 2021-09, with the labels that each got.

#1178 Refactor: Refactor workspace hooks
  src/app/flux/cnc/index.js
  src/app/flux/editor/index.js
  src/app/flux/laser/index.js
  src/app/flux/printing/index.js
  src/app/lib/hooks/previous.jsx
  src/app/ui/components/Modal/modalBody.jsx
  src/app/ui/layouts/WorkspaceLayout.jsx
  src/app/ui/pages/Cnc.jsx
  src/app/ui/pages/Laser.jsx
  src/app/ui/pages/Workspace.jsx
  src/app/ui/widgets/Connection/Connection.jsx
  src/app/ui/widgets/Connection/SerialConnection.jsx
  src/app/ui/widgets/Connection/WifiConnection.jsx
  src/app/ui/widgets/Console/Console.jsx
  src/app/ui/widgets/Console/Terminal.jsx
  src/app/ui/widgets/Control/Control.jsx
  src/app/ui/widgets/Enclosure/Enclosure.jsx
  src/app/ui/widgets/Enclosure/EnclosureDisplay.jsx
  src/app/ui/widgets/GCode/GCode.jsx
  src/app/ui/widgets/JobType/JobType.jsx
  src/app/ui/widgets/Macro/Macro.jsx
  src/app/ui/widgets/Macro/index.jsx
  src/app/ui/widgets/Marlin/Marlin.jsx
  src/app/ui/widgets/Purifier/Purifier.jsx
  src/app/ui/widgets/WifiTransport/WifiTransport.jsx
  src/app/ui/widgets/WifiTransport/index.styl
  src/app/ui/widgets/WorkspaceVisualizer/Visualizer.jsx
Labels: Type: Refactor

#1176 Refactor: Refactor to change class components related 3D printing to hooks
  src/app/models/ModelGroup.js
  src/app/ui/components/Buttons/button.jsx
  src/app/ui/components/Card/CardWrapper.jsx
  src/app/ui/components/Checkbox/CheckboxWrapper.jsx
  src/app/ui/components/Confirm/index.jsx
  src/app/ui/components/Dropdown/dropdown.jsx
  src/app/ui/components/Input/DegreeInput.jsx
  src/app/ui/components/Input/NumberInput.jsx
  src/app/ui/components/Modal/index.jsx
  src/app/ui/pages/Cnc.jsx
  src/app/ui/pages/Laser.jsx
  src/app/ui/pages/Printing.jsx
  src/app/ui/pages/Workspace.jsx
  src/app/ui/widgets/DevelopAxes/Axes.jsx
  src/app/ui/widgets/DevelopAxes/ControlPanel.jsx
  src/app/ui/widgets/DevelopAxes/DisplayPanel.jsx
  src/app/ui/widgets/DevelopAxes/JogDistance.jsx
  src/app/ui/widgets/DevelopAxes/JogPad.jsx
  src/app/ui/widgets/DevelopAxes/KeypadOverlay.jsx
  src/app/ui/widgets/DevelopAxes/MotionButtonGroup.jsx
  src/app/ui/widgets/DevelopAxes/constants.js
  src/app/ui/widgets/DevelopAxes/index.jsx
  src/app/ui/widgets/DevelopAxes/index.styl
  src/app/ui/widgets/PrintingConfigurations/Configurations.jsx
  src/app/ui/widgets/PrintingOutput/Output.jsx
  src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerBottomLeft.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerInfo.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerPreviewControl.jsx
  src/app/ui/widgets/PrintingVisualizer/styles.styl
Labels: Category: 3DP

#1175 Refactor: Change laser cnc hooks
  src/app/constants/index.js
  src/app/flux/editor/index.js
  src/app/models/SVGActionsFactory.js
  src/app/models/SvgModel.js
  src/app/ui/layouts/AppLayout.jsx
  src/app/ui/pages/Cnc.jsx
  src/app/ui/pages/Laser.jsx
  src/app/ui/pages/Printing.jsx
  src/app/ui/pages/Workspace.jsx
  src/app/ui/widgets/CNCPath/CNCPath.jsx
  src/app/ui/widgets/CNCPath/Image3dParameters.jsx
  src/app/ui/widgets/CNCPath/ImageProcessMode.jsx
  src/app/ui/widgets/CNCPath/config/ReliefParameters.jsx
  src/app/ui/widgets/CncLaserList/ToolPathList/ToolPathFooter.jsx
  src/app/ui/widgets/CncLaserList/index.jsx
  src/app/ui/widgets/CncLaserOutput/Output.jsx
  src/app/ui/widgets/CncLaserShared/TextParameters.jsx
  src/app/ui/widgets/CncLaserShared/TransformationSection.jsx
  src/app/ui/widgets/CncLaserShared/VisualizerBottomLeft.jsx
  src/app/ui/widgets/CncLaserTopRight/VisualizerTopRight.jsx
  src/app/ui/widgets/LaserCameraAidBackground/SetBackground.jsx
  src/app/ui/widgets/LaserParams/ImageProcessMode.jsx
  src/app/ui/widgets/LaserParams/LaserParameters.jsx
  src/app/ui/widgets/LaserParams/config/ConfigGreyscale.jsx
  src/app/ui/widgets/LaserParams/config/ConfigHalftone.jsx
  src/app/ui/widgets/LaserParams/config/ConfigRasterBW.jsx
  src/app/ui/widgets/LaserParams/config/ConfigRasterVector.jsx
  src/app/ui/widgets/PrintingOutput/Output.jsx
Labels: Type: Refactor, Category: Laser, Category: CNC

#1188 Feature: 3DP manual placement
  src/app/flux/printing/index.js
  src/app/lib/manager/ProgressManager.js
  src/app/models/ModelGroup.js
  src/app/models/ThreeModel.js
  src/app/three-extensions/ThreeUtils.js
  src/app/ui/App.jsx
  src/app/ui/components/SMCanvas/Canvas.jsx
  src/app/ui/components/SMCanvas/Controls.jsx
  src/app/ui/components/SMCanvas/TransformControls.js
  src/app/ui/pages/Printing.jsx
  src/app/ui/views/model-item.jsx
  src/app/ui/widgets/PrintingObjectList/PrintingObjectListBox.jsx
  src/app/ui/widgets/PrintingOutput/Output.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/RotationAnalysisOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/styles.styl
  src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
Labels: Type: Feature

#1187 Refactor: Change headType from 3dp to printing
  src/app/config/menu/fileMenu.js
  src/app/constants/index.js
  src/app/flux/appbar-menu/index.js
  src/app/flux/editor/actions-process.js
  src/app/flux/editor/index.js
  src/app/flux/machine/Server.js
  src/app/flux/machine/index.js
  src/app/flux/printing/index.js
  src/app/flux/project/index.js
  src/app/flux/setting/index.js
  src/app/flux/widget/WidgetState.js
  src/app/lib/manager/ProgressManager.js
  src/app/lib/uni-api.js
  src/app/models/ModelInfoUtils.js
  src/app/ui/App.jsx
  src/app/ui/components/SMCanvas/Canvas.jsx
  src/app/ui/components/SMCanvas/Controls.jsx
  src/app/ui/layouts/AppLayout.jsx
  src/app/ui/modals/modal-machine-select.jsx
  src/app/ui/pages/HomePage/Begin.jsx
  src/app/ui/pages/HomePage/CaseConfig.js
  src/app/ui/pages/HomePage/index.jsx
  src/app/ui/pages/Printing.jsx
  src/app/ui/utils/gaEvent.js
  src/app/ui/utils/renderRecoveryModal.jsx
  src/app/ui/views/ProfileManager/CheckboxItem.jsx
  src/app/ui/views/ProfileManager/ConfigValueBox.jsx
  src/app/ui/views/ToolPathConfigurations/ToolPathConfigurations.jsx
  src/app/ui/views/ToolPathConfigurations/ToolPathFastConfigurations.jsx
  src/app/ui/views/ToolPathConfigurations/cnc/ToolParameters.jsx
  src/app/ui/views/model-item.jsx
  src/app/ui/widgets/CNCVisualizer/Visualizer.jsx
  src/app/ui/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx
  src/app/ui/widgets/Connection/CNCState.jsx
  src/app/ui/widgets/Connection/SerialConnection.jsx
  src/app/ui/widgets/Connection/WifiConnection.jsx
  src/app/ui/widgets/Control/Control.jsx
  src/app/ui/widgets/Control/DisplayPanel.jsx
  src/app/ui/widgets/LaserSetBackground/index.jsx
  src/app/ui/widgets/LaserTestFocus/index.jsx
  src/app/ui/widgets/LaserVisualizer/Visualizer.jsx
  src/app/ui/widgets/Marlin/Marlin.jsx
  src/app/ui/widgets/PrintingConfigurations/Configurations.jsx
  src/app/ui/widgets/PrintingMaterial/Material.jsx
  src/app/ui/widgets/PrintingObjectList/PrintingObjectListBox.jsx
  src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerBottomLeft.jsx
  src/app/ui/widgets/WifiTransport/WifiTransport.jsx
  src/app/ui/widgets/WorkspaceVisualizer/Visualizer.jsx
  src/server/DataStorage.js
  src/server/constants/index.js
  src/server/lib/GcodeGenerator/GcodeGenerator.js
  src/server/services/api/api-file.js
  src/server/services/api/api-profile-definitions.js
Labels: Type: Refactor

#1197 Fix: Fix laser multi pass param error in fill method
  src/app/ui/views/ToolPathConfigurations/ToolPathFastConfigurations.jsx
  src/app/ui/views/ToolPathConfigurations/laser/LaserParameters.jsx
Labels: Type: Fix, Category: Laser

#1199 Fix: Same position trigger click & UI improvement
  src/app/models/ModelGroup.js
  src/app/ui/components/SMCanvas/Controls.jsx
  src/app/ui/components/SMCanvas/TransformControls.js
  src/app/ui/widgets/PrintingVisualizer/Overlay/RotationAnalysisOverlay.jsx
Labels: Type: Fix

#1196 Fix: Bugfix v4.0 png process
  package.json
  src/app/flux/editor/index.js
  src/app/lib/numeral.js
  src/package.json
Labels: Type: Fix

#1215 Fix: Fix generate code disabled after rotation
  src/app/models/ThreeModel.js
Labels: Type: Fix
