Repository Snapmaker/Luban, pull requests merged in 2021-05, with the labels that each got.

#988 Refactor: Add windows & linux distros developer instructions
  README.md
Labels: Type: Docs

#992 Feature: Refactor svg/dxf import and add svg parser for text
  src/app/constants/index.js
  src/app/flux/editor/index.js
  src/app/models/ModelInfoUtils.js
  src/app/models/SvgModel.js
  src/server/DataStorage.js
  src/server/constants/index.js
  src/server/lib/ToolPathGenerator/CncToolPathGenerator.js
  src/server/lib/ToolPathGenerator/LaserToolPathGenerator.js
  src/server/lib/editor/image-process.js
  src/server/lib/editor/process.js
  src/server/lib/svg-convert.js
  src/server/services/api/api-image.js
  src/server/services/api/api-utils.js
  src/server/services/task-manager/generateToolPath.js
  src/server/services/task-manager/generateViewPath.js
  src/shared/lib/DXFParser/Parser.js
  src/shared/lib/FontManager.js
  src/shared/lib/SVGParser/AttributesParser.js
  src/shared/lib/SVGParser/Parser.js
  src/shared/lib/SVGParser/TextParser.js
Labels: Type: Feature

#993 Improvement: Add canvas size setting in job type
  src/app/components/SMCanvas/Canvas.jsx
  src/app/constants/index.js
  src/app/flux/cnc/index.js
  src/app/flux/editor/index.js
  src/app/flux/laser/index.js
  src/app/flux/project/index.js
  src/app/models/SVGActionsFactory.js
  src/app/ui/SVGEditor/PrintableArea.js
  src/app/ui/SVGEditor/SVGCanvas.jsx
  src/app/ui/SVGEditor/SVGEditor.jsx
  src/app/widgets/CNCVisualizer/Visualizer.jsx
  src/app/widgets/CncLaserShared/PrintablePlate/CoordinateAxes.js
  src/app/widgets/CncLaserShared/PrintablePlate/GridLine.js
  src/app/widgets/CncLaserShared/PrintablePlate/PrintablePlate.jsx
  src/app/widgets/JobType/JobType.jsx
  src/app/widgets/LaserVisualizer/Visualizer.jsx
  src/app/widgets/WorkspaceVisualizer/Visualizer.jsx
Labels: Category: Editor, Type: Improvement

#917 Refactor: Replace class to hooks on object list component
  .eslintrc.js
  babel.config.js
  package.json
  src/app/flux/editor/actions-process.js
  src/app/rehooks/model-item.jsx
  src/app/rehooks/widget-title.jsx
  src/app/toolpaths/ToolPathGroup.js
  src/app/toolpaths/utils.js
  src/app/views/ToolPathConfigurations/ToolPathConfigurations.jsx
  src/app/views/ToolPathConfigurations/cnc/ToolParameters.jsx
  src/app/widgets/CaseLibrary/CaseConfig.js
  src/app/widgets/CaseLibrary/index.jsx
  src/app/widgets/CncLaserList/ObjectList/ObjectListBox.jsx
  src/app/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx
  src/app/widgets/CncLaserToolPath/CreateToolPath.jsx
  src/app/widgets/PrintingObjectList/PrintingObjectListBox.jsx
  src/server/DataStorage.js
  src/server/services/api/api-file.js
Labels: Type: Improvement

#1000 Improvement: Use SVGCanvas in Process page instead of SMCanvas
  src/app/flux/editor/actions-process.js
  src/app/flux/editor/index.js
  src/app/toolpaths/ToolPathGroup.js
  src/app/ui/SVGEditor/SVGCanvas.jsx
  src/app/ui/SVGEditor/SVGEditor.jsx
  src/app/ui/SVGEditor/svg-content/OperatorPoints.js
  src/app/ui/SVGEditor/svg-content/SVGContentGroup.js
  src/app/ui/SVGEditor/svg-content/SelectorManager.js
  src/app/widgets/CNCVisualizer/Visualizer.jsx
  src/app/widgets/LaserVisualizer/Visualizer.jsx
Labels: Type: Improvement

#999 Refactor: Add shortcut manager to replace shortcut callbacks in flux
  src/app/containers/App.jsx
  src/app/containers/Header/Header.jsx
  src/app/flux/index.js
  src/app/flux/keyboardShortcut/index.js
  src/app/flux/printing/index.js
  src/app/lib/combokeys.js
  src/app/lib/shortcut/constants.js
  src/app/lib/shortcut/index.js
  src/app/lib/shortcut/manager.js
  src/app/ui/SVGEditor/SVGEditor.jsx
  src/app/widgets/CNCVisualizer/Visualizer.jsx
  src/app/widgets/Control/Control.jsx
  src/app/widgets/LaserVisualizer/Visualizer.jsx
  src/app/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/widgets/PrintingVisualizer/VisualizerPreviewControl.jsx
  src/app/widgets/Widget.jsx
Labels: Type: Refactor

#1002 Refactor: Refactor profile manager
  src/app/flux/cnc/index.js
  src/app/flux/printing/index.js
  src/app/lib/hooks/set-state.jsx
  src/app/lib/hooks/widget-title.jsx
  src/app/views/CncToolManager/CncToolManager.jsx
  src/app/views/CncToolManager/CreateModal.jsx
  src/app/views/CreateModal.jsx
  src/app/views/PrintingManager/PrintingManager.jsx
  src/app/views/ToolPathConfigurations/cnc/ToolParameters.jsx
  src/app/views/model-item.jsx
  src/app/views/profile-manager.jsx
  src/app/widgets/CncLaserList/ObjectList/ObjectListBox.jsx
  src/app/widgets/PrintingObjectList/PrintingObjectListBox.jsx
Labels: Type: Improvement
