Repository Snapmaker/Luban, pull requests merged in 2021-03, with the labels that each got.

#785 Fix: Fix only displaying color of the last tool path
  src/app/toolpaths/ToolPathGroup.js
Labels: Type: Fix

#802 Fix: Make project file compatible with old version
  src/app/flux/project/index.js
  src/app/views/CncToolManager/CncToolManager.jsx
  test/cnc-mesh-slice/complexity-analysis/martinez-polygon-clipping/main.js
Labels: Type: Fix

#796 Fix: Fix the widgets warning in enclosure and purifier
  src/app/flux/machine/index.js
  src/app/widgets/Enclosure/Enclosure.jsx
  src/app/widgets/Enclosure/EnclosureDisplay.jsx
  src/app/widgets/Purifier/Purifier.jsx
  src/app/widgets/Purifier/index.jsx
Labels: Type: Fix

#791 Fix: Fix text transformation being reset when changing text parameters
  src/app/models/SVGActionsFactory.js
  src/app/models/SvgModel.js
  src/app/widgets/CncLaserShared/TextParameters.jsx
Labels: Type: Fix

#807 Fix: Fix the bug of fill parameter in laser case
  resources/user-case/A150/Laser_test_A150.svg
  resources/user-case/A250/Laser_test_A250.svg
  resources/user-case/A350/Laser_test_A350.svg
  src/server/lib/ToolPathGenerator/SVGFill.js
Labels: Type: Fix

#812 Fix: Disable Enter key of SVG text
  src/app/widgets/CncLaserShared/TextParameters.jsx
Labels: Type: Fix

#804 Fix: Fix SVG uniform scale and enlarge text size
  src/app/flux/editor/index.js
  src/app/models/SVGActionsFactory.js
  src/app/models/SvgModel.js
  src/app/ui/SVGEditor/SVGCanvas.jsx
  src/app/ui/SVGEditor/SVGEditor.jsx
  src/app/widgets/CNCVisualizer/Visualizer.jsx
  src/app/widgets/CncLaserShared/TransformationSection.jsx
  src/app/widgets/LaserVisualizer/Visualizer.jsx
Labels: Category: Editor, Type: Fix

#813 Fix: Destroy Gcodeline when starting support mode
  src/app/widgets/PrintingVisualizer/Visualizer.jsx
Labels: Type: Fix

#819 Fix: Limit the maximum speed of B
  src/server/lib/ToolPath/index.js
Labels: Type: Fix

#820 Fix: Disable automatic recovery when double-clicking the project file to start the software (#774)
  src/app/containers/App.jsx
  src/app/flux/project/index.js
  src/app/lib/uni-api.js
  src/main.js
Labels: Type: Fix

#827 Build: Migrate Windows and macOS builds to Github Actions
  .github/workflows/build-on-create-release.yml
  .travis.yml
  appveyor.yml
  build/notarize.js
Labels: Type: Build

#825 Refactor: Change style on cnc tool
  src/app/widgets/CNCTool/styles.styl
Labels: Type: Style

#809 Fix: Fix the suffix capital parsing bug of CNC STL file
  src/server/lib/MeshProcess/MeshProcess.js
Labels: Type: Fix

#815 Improvement: The first lap speed is set to 1/2 of normal
  src/server/lib/ToolPathGenerator/CncReliefToolPathGenerator.js
  src/server/lib/ToolPathGenerator/MeshToolPath/CncMeshLinkageToolPathGenerator.js
Labels: Type: Improvement

#823 Fix: Fix the value of some parameters in laser state has too many decimal places
  src/app/widgets/Marlin/Laser.jsx
Labels: Type: Fix

#826 Fix: Fix bugs for v3.14
  src/app/models/SVGActionsFactory.js
  src/app/models/SvgModel.js
Labels: Type: Fix

#832 Fix: Click on the area outside the element to unselect it
  src/app/ui/SVGEditor/SVGCanvas.jsx
Labels: Type: Fix

#817 Fix: Fix the rendering image abnormality during the STL loading process
  src/app/images/loading.gif
  src/app/models/SvgModel.js
  src/app/workers/GcodeToBufferGeometry/GcodeToBufferGeometryWorkspace.js
  src/shared/lib/utils.js
Labels: Type: Fix, Type: Improvement

#837 Fix: Remove code set element transform list incorrectly
  src/app/ui/SVGEditor/SVGCanvas.jsx
Labels: Type: Fix

#830 Fix: Fix cnc stl 3 axis loading bugs
  src/app/flux/editor/index.js
Labels: Type: Fix

#834 Fix: Fix the bug that the button 'preview tool path' cannot be clicked
  src/app/widgets/CncLaserOutput/Output.jsx
Labels: Type: Fix

#838 Improvement: Change style in transformation of laser and cnc
  src/app/styles/sm-parameter.styl
  src/app/widgets/CncLaserShared/Transformation.jsx
  src/app/widgets/CncLaserShared/styles.styl
  src/app/widgets/JobType/styles.styl
Labels: Type: Improvement

#841 Fix: Fix bugs on v3.14
  src/app/components/SMCanvas/Canvas.jsx
  src/app/components/SMCanvas/Controls.jsx
  src/app/flux/machine/index.js
  src/app/widgets/Control/Control.jsx
  src/app/widgets/Control/DisplayPanel.jsx
  src/app/widgets/Control/JogDistance.jsx
  src/app/widgets/Control/index.styl
  src/app/widgets/GCode/GCode.jsx
  src/app/widgets/LaserCameraAidBackground/SetBackground.jsx
  src/app/widgets/Marlin/Laser.jsx
  src/server/services/api/api-file.js
Labels: Type: Fix

#833 Fix: Add isConnected flag to control machine size setting button
  src/app/containers/Header/MachineSelection.jsx
Labels: Type: Fix

#836 Fix: Fix bug for CNC relief tool path
  src/server/lib/ToolPathGenerator/CncReliefToolPathGenerator.js
Labels: Type: Fix

#844 Fix: Add Z min/max (bounding box) for G-code header
  src/server/lib/ToolPath/index.js
  src/server/services/task-manager/generateGcode.js
Labels: Type: Fix

#845 Fix: Fix state updating bug when reconnecting the software
  src/app/flux/machine/index.js
Labels: Type: Fix

#843 Improvement: Increase the distance between the vertices allowed by the polygon
  src/server/lib/MeshProcess/MeshProcess.js
  src/server/lib/MeshProcess/Polygons.js
  src/server/lib/ToolPathGenerator/CncReliefToolPathGenerator.js
  src/server/lib/ToolPathGenerator/MeshToolPath/CncMeshToolPathGenerator.js
  src/server/services/task-manager/generateToolPath.js
  src/server/services/task-manager/generateViewPath.js
Labels: Type: Fix, Type: Improvement

#849 Fix: Load 3DP case model error after reset config
  src/app/flux/setting/index.js
Labels: Type: Fix

#842 Improvement: Add issue templates for github issues
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Type: Docs

#846 Improvement: Reset to zero at the end of 4-axis printing b
  src/server/lib/ToolPath/XToBToolPath.js
  src/server/lib/ToolPath/index.js
  src/server/lib/ToolPathGenerator/CncReliefToolPathGenerator.js
  src/server/lib/ToolPathGenerator/CncToolPathGenerator.js
  src/server/lib/ToolPathGenerator/LaserToolPathGenerator.js
  src/server/lib/ToolPathGenerator/MeshToolPath/CncMeshLinkageToolPathGenerator.js
Labels: Type: Improvement

#852 Fix: Fix slicing with wrong size after switching machine size
  src/app/flux/machine/index.js
  src/app/flux/printing/index.js
Labels: Type: Fix

#855 Fix: Fix selector offset after model duplicated
  src/app/flux/editor/index.js
Labels: Type: Fix

#818 Fix: Fix exporting file crash in 3DP
  src/app/components/three-extensions/STLBinaryExporter.js
  src/app/components/three-extensions/STLExporter.js
  src/app/widgets/PrintingVisualizer/ModelExporter.js
Labels: Type: Fix

#856 Fix: Fix the size bug of stl 3-axis ball knife
  src/server/lib/ToolPathGenerator/MeshToolPath/CncMeshToolPathGenerator.js
Labels: Type: Fix

#854 Fix: Change the material of modelObject3D
  src/app/models/Model.js
Labels: Type: Fix

#851 Fix: Change i18n config and update translations
  src/app/config/settings.js
  src/app/containers/App.jsx
  src/app/i18n/cs/resource.json
  src/app/i18n/de/resource.json
  src/app/i18n/en/resource.json
  src/app/i18n/es/resource.json
  src/app/i18n/fr/resource.json
  src/app/i18n/hu/resource.json
  src/app/i18n/it/resource.json
  src/app/i18n/ja/resource.json
  src/app/i18n/ko/resource.json
  src/app/i18n/pt-br/resource.json
  src/app/i18n/ru/resource.json
  src/app/i18n/uk/resource.json
  src/app/i18n/zh-cn/resource.json
  src/app/i18n/zh-tw/resource.json
  src/app/index.jsx
  src/app/lib/i18n.js
  src/app/widgets/Control/MotionButtonGroup.jsx
  src/app/widgets/LaserSetBackground/Instructions.jsx
  src/app/widgets/LaserSetBackground/SetBackground.jsx
  src/app/widgets/LaserTestFocus/TestFocus.jsx
Labels: Type: Fix

#858 Fix: Fix remaining time displayed error
  src/app/flux/machine/Server.js
Labels: Type: Fix

#861 Improvement: Optimize stl size analysis time
  src/server/lib/MeshProcess/Mesh.js
  src/server/lib/MeshProcess/MeshProcess.js
  src/server/lib/MeshProcess/Slicer.js
  src/server/lib/ToolPathGenerator/MeshToolPath/CncMeshLinkageToolPathGenerator.js
  src/server/lib/ToolPathGenerator/MeshToolPath/CncMeshToolPathGenerator.js
  src/server/services/api/api-image.js
Labels: Type: Fix, Type: Improvement

#862 Fix: Fix undo-redo action causes model disapear
  src/app/models/Model.js
Labels: Type: Fix

#865 Fix: Fix CNC STL slice interpolation bug
  src/server/lib/ToolPathGenerator/MeshToolPath/CncMeshLinkageToolPathGenerator.js
Labels: Type: Fix

#863 Fix: Workspace style error and change some translation
  src/app/i18n/de/resource.json
  src/app/i18n/fr/resource.json
  src/app/styles/sm-parameter.styl
  src/app/widgets/Control/Control.jsx
Labels: Type: Fix

#866 Fix: Remove application edit menu temporarily
  src/electron-app/Menu.js
Labels: Type: Fix

#867 Fix: Fix bug related case and blanl
  src/app/models/ModelGroup.js
  src/app/widgets/CaseLibrary/CaseConfig.js
  src/app/widgets/CaseLibrary/index.jsx
Labels: Type: Fix

#871 Fix: Fix bug for CNC STL linkage bounding box
  src/server/lib/ToolPathGenerator/MeshToolPath/CncMeshLinkageToolPathGenerator.js
Labels: Type: Fix

#872 Improvement: Recalculate STL model size
  src/app/flux/editor/index.js
Labels: Type: Improvement

#875 Fix: Fix bug for CNC relief rotation bug
  src/server/lib/ToolPathGenerator/CncReliefToolPathGenerator.js
Labels: Type: Fix

#876 Fix: Fix bug for 3D printing bounding box
  src/app/flux/printing/index.js
Labels: Type: Fix

#795 Changed/Added German translations for v3.13.1
  src/app/i18n/de/gcode.json
  src/app/i18n/de/resource.json
Labels: Type: Improvement

#877 Fix: Fix transformation style error after pick from 3.14
  src/app/widgets/CncLaserShared/TransformationSection.jsx
Labels: Type: Fix

#879 Fix: Update i18n translation after 3/15
  src/app/i18n/de/resource.json
  src/app/i18n/en/resource.json
  src/app/i18n/fr/resource.json
  src/app/i18n/zh-cn/resource.json
Labels: Type: Fix

#884 Fix: Hide B axis log in console when connected by serial port 3.15
  src/server/controllers/Marlin/Marlin.js
Labels: Type: Fix

#883 Fix: Fix reset transformation error when multiselected
  src/app/models/ModelGroup.js
Labels: Category: 3DP, Type: Fix

#892 Fix: Fix error window position on reopen
  src/main.js
Labels: Type: Fix

#878 Feature: Add scale to fit action for 3dp model
  src/app/flux/printing/index.js
  src/app/lib/modal.jsx
  src/app/models/ModelGroup.js
  src/app/models/ThreeModel.js
  src/app/widgets/PrintingVisualizer/Visualizer.jsx
Labels: Type: Feature

#897 Fix: Fix description error in cnc tool path
  resources/CuraEngine/Config/CncConfig/Default.def.json
  resources/CuraEngine/Config/CncConfig/active.def.json
Labels: Type: Fix

#901 Feature: Add feature for adding tool config for current params
  package.json
  resources/CuraEngine/Config/CncConfig/Default.def.json
  resources/CuraEngine/Config/CncConfig/active.def.json
  src/app/components/SMCanvas/Canvas.jsx
  src/app/components/Select/ChangedReactSelect.jsx
  src/app/components/Select/index.jsx
  src/app/containers/DevelopTools/Firmware.jsx
  src/app/containers/Settings/MachineSettings/MachineSettings.jsx
  src/app/lib/modal.jsx
  src/app/styles/sm-parameter.styl
  src/app/styles/vendor.styl
  src/app/ui/SVGEditor/SVGCanvas.jsx
  src/app/views/CncToolManager/CncToolManager.jsx
  src/app/views/PrintingManager/PrintingManager.jsx
  src/app/views/PrintingManager/styles.styl
  src/app/views/ToolPathConfigurations/ToolPathConfigurations.jsx
  src/app/views/ToolPathConfigurations/cnc/CncParameters.jsx
  src/app/views/ToolPathConfigurations/cnc/ToolParameters.jsx
  src/app/views/ToolPathConfigurations/laser/LaserParameters.jsx
  src/app/views/ToolPathConfigurations/styles.styl
  src/app/widgets/CNCPath/Image3dParameters.jsx
  src/app/widgets/CNCPath/VectorParameters.jsx
  src/app/widgets/CncLaserShared/SvgTrace/TracePreview.jsx
  src/app/widgets/CncLaserShared/TextParameters.jsx
  src/app/widgets/Connection/SerialConnection.jsx
  src/app/widgets/Connection/WifiConnection.jsx
  src/app/widgets/LaserParams/config/ConfigGreyscale.jsx
  src/app/widgets/LaserParams/config/ConfigHalftone.jsx
  src/app/widgets/PrintingConfigurations/Configurations.jsx
  src/app/widgets/PrintingMaterial/Material.jsx
  src/app/widgets/PrintingOutput/Output.jsx
  src/app/widgets/Webcam/Settings.jsx
Labels: Type: Feature

#894 Improvement: Disable multi-select models of different toolpath types
  package.json
  src/app/components/SMCanvas/Controls.jsx
  src/app/components/Toast/index.js
  src/app/containers/App.jsx
  src/app/flux/editor/actions-process.js
  src/app/styles/vendor.styl
  src/app/widgets/LaserVisualizer/Visualizer.jsx
Labels: Type: Improvement

#895 Improvement: Show modal before recovering environment
  src/app/components/SMCanvas/Canvas.jsx
  src/app/containers/App.jsx
  src/app/flux/project/index.js
  src/app/lib/modal.jsx
  src/app/models/ModelGroup.js
  src/app/models/ThreeModel.js
  src/app/ui/SVGEditor/SVGCanvas.jsx
  src/app/ui/SVGEditor/TextActions.js
Labels: Type: Improvement

#902 Fix: Switch description of work speed and plunge speed for 3.14
  src/app/widgets/CNCPath/CNCPath.jsx
Labels: Category: CNC, Type: Fix

#896 Improvement: Add configuration "Infill Pattern" and "Fan Speed" to 3DP settings
  gulp/tasks/i18next.js
  resources/CuraEngine/Config/snapmaker.def.json
  src/app/constants/index.js
  src/app/flux/printing/DefinitionManager.js
  src/app/i18n/cs/resource.json
  src/app/i18n/de/gcode.json
  src/app/i18n/de/resource.json
  src/app/i18n/en/resource.json
  src/app/i18n/es/resource.json
  src/app/i18n/fr/resource.json
  src/app/i18n/hu/resource.json
  src/app/i18n/it/resource.json
  src/app/i18n/ja/resource.json
  src/app/i18n/ko/resource.json
  src/app/i18n/pt-br/resource.json
  src/app/i18n/ru/resource.json
  src/app/i18n/uk/resource.json
  src/app/i18n/zh-cn/resource.json
  src/app/i18n/zh-tw/resource.json
  src/app/views/PrintingManager/PrintingManager.jsx
  src/app/widgets/PrintingMaterial/Material.jsx
  src/server/slicer/definition.js
Labels: Category: 3DP, Type: Improvement
