Repository Snapmaker/Luban, pull requests merged in 2021-06, with the labels that each got.

#1027 Feature: Add setting guide
  src/app/ui/Pages/HomePage/SettingGuideModal.jsx
  src/app/ui/Pages/HomePage/index.jsx
  src/app/ui/Pages/HomePage/styles.styl
Labels: Type: Feature

#1028 Improvement: Improve main tool bar
  src/app/ui/Layouts/HomeLayout.jsx
  src/app/ui/Layouts/MenuItem.jsx
  src/app/ui/Pages/Cnc.jsx
  src/app/ui/Pages/HomePage/index.jsx
  src/app/ui/Pages/Laser.jsx
  src/app/ui/Pages/Printing.jsx
  src/app/ui/components/SvgIcon/SvgIcon.jsx
  src/app/ui/widgets/CncLaserOutput/Output.jsx
  src/app/ui/widgets/JobType/JobType.jsx
  src/app/ui/widgets/PrintingOutput/Output.jsx
Labels: Type: Improvement

#1037 Improvement: Remove the default density limit in cnc
  src/server/lib/ToolPathGenerator/CncReliefToolPathGenerator.js
Labels: Category: CNC, Type: Improvement

#1032 Fix: Fix bug on route changing and workspace page
  resources/CuraEngine/Config/CncConfig/DefaultCVbit.defv2.json
  resources/CuraEngine/Config/CncConfig/DefaultFEM.defv2.json
  resources/CuraEngine/Config/CncConfig/DefaultMBEM.defv2.json
  resources/CuraEngine/Config/CncConfig/DefaultSGVbit.defv2.json
  resources/CuraEngine/Config/CncConfig/RAcrylicFEM.defv2.json
  resources/CuraEngine/Config/CncConfig/REpoxySGVbit.defv2.json
  resources/CuraEngine/Config/CncConfig/active.defv2.json
  src/app/constants/index.js
  src/app/flux/project/index.js
  src/app/ui/App.jsx
  src/app/ui/Layouts/MenuItem.jsx
  src/app/ui/Layouts/ProjectLayout.jsx
  src/app/ui/Layouts/WorkspaceLayout.jsx
  src/app/ui/Layouts/styles/project.styl
  src/app/ui/Layouts/styles/workspace.styl
  src/app/ui/Pages/Cnc.jsx
  src/app/ui/Pages/HomePage/Begin.jsx
  src/app/ui/Pages/HomePage/QuickStart.jsx
  src/app/ui/Pages/HomePage/index.jsx
  src/app/ui/Pages/Laser.jsx
  src/app/ui/Pages/Printing.jsx
  src/app/ui/Pages/Workspace.jsx
  src/app/ui/utils/renderPopup.jsx
  src/app/ui/views/Cnc3DVisualizer/Canvas/Canvas.jsx
  src/app/ui/views/CncToolManager/CncToolManager.jsx
  src/app/ui/widgets/CaseLibrary/CaseConfig.js
  src/app/ui/widgets/CaseLibrary/index.jsx
  src/app/ui/widgets/CaseLibrary/index.styl
  src/app/ui/widgets/PrintingConfigurations/Configurations.jsx
  src/app/ui/widgets/PrintingMaterial/Material.jsx
  src/app/ui/widgets/WorkspaceVisualizer/Visualizer.jsx
  src/app/ui/widgets/styles.styl
  src/server/services/api/api-cnc-definition.js
Labels: Type: Fix

#1036 Improvement: improve render right widgets
  src/app/flux/cnc/index.js
  src/app/flux/editor/actions-process.js
  src/app/flux/editor/index.js
  src/app/flux/laser/index.js
  src/app/flux/project/index.js
  src/app/flux/widget/WidgetState.js
  src/app/models/ModelGroup.js
  src/app/toolpaths/ToolPath.js
  src/app/toolpaths/ToolPathGroup.js
  src/app/toolpaths/utils.js
  src/app/ui/Layouts/VisualizerLayout.jsx
  src/app/ui/Pages/Cnc.jsx
  src/app/ui/Pages/HomePage/Begin.jsx
  src/app/ui/Pages/HomePage/index.jsx
  src/app/ui/Pages/Laser.jsx
  src/app/ui/Pages/Printing.jsx
  src/app/ui/Pages/Workspace.jsx
  src/app/ui/SVGEditor/SVGCanvas.jsx
  src/app/ui/SVGEditor/SVGLeftBar.jsx
  src/app/ui/widgets/CNCVisualizer/Visualizer.jsx
  src/app/ui/widgets/CncLaserList/ObjectList/ObjectListBox.jsx
  src/app/ui/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx
  src/app/ui/widgets/CncLaserList/styles.styl
  src/app/ui/widgets/CncLaserOutput/Output.jsx
  src/app/ui/widgets/CncLaserShared/VisualizerBottomLeft.jsx
  src/app/ui/widgets/CncLaserToolPath/CreateToolPath.jsx
  src/app/ui/widgets/CncLaserToolPath/index.jsx
  src/app/ui/widgets/CncLaserToolPath/styles.styl
  src/app/ui/widgets/JobType/JobType.jsx
  src/app/ui/widgets/LaserVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingObjectList/PrintingObjectListBox.jsx
  src/app/ui/widgets/PrintingObjectList/styles.styl
  src/app/ui/widgets/PrintingVisualizer/VisualizerBottomLeft.jsx
  src/app/ui/widgets/Widget.jsx
  src/app/ui/widgets/index.js
Labels: Type: Improvement

#1033 Feature: Add uniform top menu
  src/DataStorage.js
  src/app/config/menu/connectionMenu.js
  src/app/config/menu/editMenu.js
  src/app/config/menu/fileMenu.js
  src/app/config/menu/helpMenu.js
  src/app/config/menu/index.js
  src/app/config/menu/settingsMenu.js
  src/app/config/menu/windowMenu.js
  src/app/constants/index.js
  src/app/flux/appbar-menu/index.js
  src/app/flux/index.js
  src/app/index.jsx
  src/app/lib/redux-middleware.js
  src/app/lib/uni-api.js
  src/app/ui/App.jsx
  src/app/ui/App.styl
  src/app/ui/Layouts/AppLayout.jsx
  src/app/ui/Layouts/styles/homepage.styl
  src/app/ui/Layouts/styles/project.styl
  src/app/ui/Layouts/styles/workspace.styl
  src/app/ui/Pages/HomePage/Begin.jsx
  src/app/ui/Pages/Settings/FirmwareTool/FirmwareTool.jsx
  src/app/ui/Pages/Settings/General/General.jsx
  src/app/ui/Pages/Settings/MachineSettings/MachineSettings.jsx
  src/app/ui/Pages/Settings/Settings.jsx
  src/app/ui/Pages/Settings/SoftwareUpdate/SoftwareUpdate.jsx
  src/app/ui/Pages/Settings/SoftwareUpdate/index.js
  src/app/ui/Pages/Settings/SoftwareUpdate/index.styl
  src/app/ui/Pages/Settings/index.styl
  src/app/ui/components/Modal/index.jsx
  src/app/ui/components/SMCanvas/Canvas.jsx
  src/app/ui/views/AppBar/AppBar.jsx
  src/app/ui/views/AppBar/Menu.jsx
  src/app/ui/views/AppBar/Submenu.jsx
  src/app/ui/views/AppBar/appbar.styl
  src/app/ui/views/AppBar/index.js
  src/app/ui/views/AppBar/styles.styl
  src/app/ui/widgets/CNCVisualizer/Visualizer.jsx
  src/app/ui/widgets/CncLaserOutput/Output.jsx
  src/app/ui/widgets/JobType/JobType.jsx
  src/app/ui/widgets/LaserVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingOutput/Output.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
  src/app/ui/widgets/WifiTransport/WifiTransport.jsx
  src/app/ui/widgets/WorkspaceVisualizer/index.styl
  src/electron-app/Menu.js
  src/main.js
Labels: Type: Feature
