Repository Snapmaker/Luban, pull requests merged in 2021-02, with the labels that each got.

#729 Improvement: Support i18n, fix error in some keys and support 3dp transformation menu
  src/app/constants/index.js
  src/app/containers/App.jsx
  src/app/i18n/cs/resource.json
  src/app/i18n/de/resource.json
  src/app/i18n/en/resource.json
  src/app/i18n/es/resource.json
  src/app/i18n/fr/resource.json
  src/app/i18n/hu/resource.json
  src/app/i18n/it/resource.json
  src/app/i18n/ja/resource.json
  src/app/i18n/ko/resource.json
  src/app/i18n/pt-br/resource.json
  src/app/i18n/ru/resource.json
  src/app/i18n/uk/resource.json
  src/app/i18n/zh-cn/resource.json
  src/app/i18n/zh-tw/resource.json
  src/app/images/48x48/icon-move-disable-48x48.png
  src/app/images/48x48/icon-move-disabled-48x48.png
  src/app/images/48x48/icon-move-hover-48x48.png
  src/app/images/48x48/icon-move-normal-48x48.png
  src/app/images/48x48/icon-rotate-disabled-48x48.png
  src/app/images/48x48/icon-rotate-hover-48x48.png
  src/app/images/48x48/icon-rotate-normal-48x48.png
  src/app/images/48x48/icon-scale-disabled-48x48.png
  src/app/images/48x48/icon-scale-hover-48x48.png
  src/app/images/48x48/icon-scale-normal-48x48.png
  src/app/images/48x48/icon-support-disabled-48x48.png
  src/app/images/48x48/icon-support-hover-48x48.png
  src/app/images/48x48/icon-support-normal-48x48.png
  src/app/widgets/CNCPath/Image3dParameters.jsx
  src/app/widgets/CNCPath/ImageProcessMode.jsx
  src/app/widgets/CNCPath/VectorParameters.jsx
  src/app/widgets/CncLaserShared/GcodeParameters.jsx
  src/app/widgets/Enclosure/Enclosure.jsx
  src/app/widgets/LaserParams/ImageProcessMode.jsx
  src/app/widgets/Marlin/Laser.jsx
  src/app/widgets/PrintingVisualizer/VisualizerModelTransformation.jsx
  src/app/widgets/PrintingVisualizer/styles.styl
Labels: Category: 3DP, Type: Improvement, Type: Style

#731 Fix: Need to check that "ports" is empty or not when disconnect from Wi-FI
  src/app/flux/machine/index.js
Labels: Type: Fix

#711 Feature: Add AutoRotate Action for 3d model
  src/app/components/three-extensions/ThreeUtils.js
  src/app/flux/printing/index.js
  src/app/models/Model.js
  src/app/models/ModelGroup.js
  src/app/widgets/PrintingVisualizer/Visualizer.jsx
Labels: Type: Feature

#737 Perf: Improve memory usage of big files in 3dp
  src/app/components/three-extensions/STLBinaryExporter.js
  src/app/components/three-extensions/STLLoader.js
  src/app/flux/printing/index.js
  src/app/models/Model.js
Labels: Type: Perf

#701 Feature: Add air purifier widget
  src/app/constants/index.js
  src/app/flux/machine/Server.js
  src/app/flux/machine/index.js
  src/app/flux/widget/WidgetState.js
  src/app/widgets/Enclosure/Enclosure.jsx
  src/app/widgets/Purifier/Purifier.jsx
  src/app/widgets/Purifier/index.jsx
  src/app/widgets/Purifier/index.styl
  src/app/widgets/Widget.jsx
  src/server/controllers/Marlin/Marlin.js
  src/server/controllers/Marlin/MarlinController.js
  src/server/controllers/Marlin/ScreenController.js
  src/server/controllers/constants.js
  src/shared/lib/DXFParser/DxfParser.js
Labels: Type: Feature

#739 Fix: Fix converted path of SVG Text being sliced
  src/server/lib/svg-convert.js
Labels: Type: Fix

#738 Fix: Fix several element operation bugs
  src/app/flux/editor/index.js
  src/app/models/SVGActionsFactory.js
  src/app/models/SvgModel.js
  src/app/ui/SVGEditor/SVGCanvas.jsx
  src/app/ui/SVGEditor/svg-content/OperatorPoints.js
  src/app/ui/SVGEditor/svg-content/SVGContentGroup.js
  src/app/widgets/CNCPath/CNCPath.jsx
  src/app/widgets/CncLaserShared/TransformationSection.jsx
  src/app/widgets/LaserParams/LaserParameters.jsx
Labels: Type: Fix

#741 Fix: Change style for <Sortable> in laser | cnc
  src/app/containers/Cnc/styles.styl
  src/app/containers/Laser/styles.styl
Labels: Type: Fix

#746 Fix: Fix several bugs for model configuration, wrong text size and wrong tool path size
  src/app/flux/editor/index.js
  src/app/models/SVGActionsFactory.js
  src/server/lib/ToolPathGenerator/CncToolPathGenerator.js
  src/server/lib/ToolPathGenerator/LaserToolPathGenerator.js
Labels: Type: Fix

#752 Build: Preparations for raspberry pi support
  README.md
  package.json
Labels: Type: Build, Type: Docs

#753 Fix: Reset state to "displayModel" when destroy G-code line
  src/app/flux/printing/index.js
Labels: Type: Fix

#756 Fix: Fix reset transformation on multi-selected models (3DP)
  src/app/flux/printing/index.js
  src/app/models/ModelGroup.js
  src/app/widgets/PrintingVisualizer/Visualizer.jsx
Labels: Category: 3DP, Type: Fix

#755 Fix: Fix 3dp printing configuration problems
  resources/CuraEngine/Config/snapmaker2.def.json
  src/app/constants/index.js
  src/app/flux/printing/index.js
  src/server/slicer/definition.js
Labels: Type: Fix

#757 Feature: Add the axial stock to leave of cnc relief image
  src/app/flux/editor/index.js
  src/app/models/ModelInfoUtils.js
  src/app/views/ToolPathConfigurations/cnc/GcodeParameters.jsx
  src/server/lib/ToolPathGenerator/CncReliefToolPathGenerator.js
Labels: Type: Feature

#760 Fix: Fix simulation failure on SVG of relief mode
  src/server/services/task-manager/generateViewPath.js
Labels: Type: Fix

#758 Fix: Remove special chars of uploading file
  src/app/flux/printing/index.js
  src/server/services/api/api-file.js
  src/server/services/api/api-image.js
  src/shared/lib/utils.js
Labels: Type: Fix

#761 Fix: Fix some styles after import the language German and French
  src/app/containers/Header/styles.styl
  src/app/i18n/cs/resource.json
  src/app/i18n/de/resource.json
  src/app/i18n/en/resource.json
  src/app/i18n/es/resource.json
  src/app/i18n/fr/resource.json
  src/app/i18n/hu/resource.json
  src/app/i18n/it/resource.json
  src/app/i18n/ja/resource.json
  src/app/i18n/ko/resource.json
  src/app/i18n/pt-br/resource.json
  src/app/i18n/ru/resource.json
  src/app/i18n/uk/resource.json
  src/app/i18n/zh-cn/resource.json
  src/app/i18n/zh-tw/resource.json
  src/app/styles/sm-parameter.styl
  src/app/widgets/CncLaserShared/GcodeParameters.jsx
  src/app/widgets/Control/Control.jsx
  src/app/widgets/Control/index.styl
  src/app/widgets/PrintingVisualizer/styles.styl
Labels: Type: Fix

#762 Fix: Fix missing dimension of 3DP models in G-code file
  src/app/flux/printing/index.js
  src/app/models/ModelGroup.js
  src/package.json
Labels: Category: 3DP, Type: Fix

#764 Fix: Fix bugs for cnc
  src/app/components/Input/NumberInput.jsx
  src/app/flux/editor/index.js
  src/app/models/SVGActionsFactory.js
  src/app/views/Cnc3DVisualizer/Cnc3DVisualizer.jsx
  src/app/views/Cnc3DVisualizer/Env3Axis.jsx
  src/app/widgets/CNCVisualizer/Visualizer.jsx
  src/app/widgets/CaseLibrary/CaseConfig.js
Labels: Type: Fix

#766 Fix: Fix the problem that STL in CNC editor is too large or too small
  src/app/flux/editor/index.js
  src/app/models/Model.js
  src/app/models/ModelInfoUtils.js
  src/server/lib/MeshProcess/Mesh.js
  src/server/lib/MeshProcess/MeshProcess.js
  src/server/services/api/api-image.js
  src/server/services/task-manager/processImage.js
Labels: Type: Fix

#765 Fix: Fix bugs for 3dp
  src/app/flux/printing/index.js
  src/app/flux/project/index.js
  src/app/models/ModelGroup.js
  src/app/widgets/PrintingOutput/Output.jsx
  src/app/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/widgets/PrintingVisualizer/VisualizerModelTransformation.jsx
Labels: Type: Fix

#767 Fix: Set message box as modal of current window
  src/app/lib/uni-api.js
Labels: Type: Fix

#768 Improvement: Add 4-axis STL parameter "placement"
  src/app/constants/index.js
  src/app/models/ModelInfoUtils.js
  src/app/views/Cnc3DVisualizer/Cnc3DVisualizer.jsx
  src/app/widgets/CNCPath/Image3dParameters.jsx
  src/server/constants/index.js
  src/server/lib/MeshProcess/Mesh.js
  src/server/lib/MeshProcess/MeshProcess.js
  src/server/lib/ToolPathGenerator/MeshToolPath/CncMeshToolPathGenerator.js
Labels: Type: Improvement

#747 Improvement: Improve project file structure
  resources/CuraEngine/Config/CncConfig/Default.def.json
  resources/CuraEngine/Config/CncConfig/active.def.json
  src/app/flux/editor/index.js
  src/app/flux/project/index.js
  src/app/models/Model.js
  src/app/toolpaths/ToolPath.js
  src/app/toolpaths/ToolPathGroup.js
  src/app/ui/SVGEditor/svg-content/SVGContentGroup.js
  src/app/views/ToolPathConfigurations/ToolPathConfigurations.jsx
  src/app/views/ToolPathConfigurations/cnc/CncParameters.jsx
  src/app/views/ToolPathConfigurations/cnc/ToolParameters.jsx
  src/app/views/ToolPathConfigurations/styles.styl
  src/server/services/api/api-file.js
Labels: Type: Refactor

#730 Build: Update dependencies (electron mainly)
  bin/cli
  build/electron-builder.sh
  build/prebuild-prod.sh
  gulp/tasks/app.js
  gulp/tasks/clean.js
  gulp/tasks/server.js
  package-lock.json
  package.json
  webpack.config.app.production.js
  webpack.config.server.production.js
Labels: dependencies

#773 Fix: Fix scale of uploaded images
  package-lock.json
  src/app/flux/editor/index.js
  src/app/models/Model.js
  src/app/models/ModelInfoUtils.js
  src/app/models/SVGActionsFactory.js
  src/app/models/SvgModel.js
  src/app/widgets/PrintingOutput/Output.jsx
  src/app/widgets/PrintingOutput/Thumbnail.jsx
  src/shared/lib/DXFParser/DxfParser.js
  src/shared/lib/utils.js
Labels: Type: Fix

#774 Fix: Disable automatic recovery when double-clicking the project file to start the software
  src/app/containers/App.jsx
  src/app/flux/project/index.js
  src/app/lib/uni-api.js
  src/main.js
Labels: Type: Fix

#777 Fix: Remove special chars of uploading file
  src/server/services/api/api-file.js
Labels: Type: Fix

#778 Fix: Fix bug on dxf size and selection
  src/app/components/SMCanvas/Controls.jsx
  src/app/lib/threejs/ThreeDxfLoader.js
  src/server/lib/editor/dxf-process.js
  src/shared/lib/DXFParser/Parser.js
Labels: Type: Fix

#783 Fix: Fix svg simulation exception
  src/app/lib/renderer/ViewPathRenderer.js
  src/server/lib/ToolPathGenerator/CncToolPathGenerator.js
  src/server/lib/bresenham-line.js
Labels: Type: Fix

#733 Improvement: Make zoom to cursor in 3DP
  src/app/components/SMCanvas/Controls.jsx
  src/app/flux/project/index.js
Labels: Type: Improvement

#781 Improvement: Fix typo on Camera Capture and change style on toolpath
  resources/CuraEngine/Config/CncConfig/Default.def.json
  resources/CuraEngine/Config/CncConfig/active.def.json
  src/app/images/cnc-laser/ic_asterisk_18x18.png
  src/app/images/cnc-laser/ic_drop arrow_18x18.png
  src/app/images/cnc-laser/ic_right arrow_18x18.png
  src/app/views/CncToolManager/CncToolManager.jsx
  src/app/views/CncToolManager/styles.styl
  src/app/views/ToolPathConfigurations/cnc/CncParameters.jsx
  src/app/views/ToolPathConfigurations/cnc/ToolParameters.jsx
  src/app/views/ToolPathConfigurations/styles.styl
  src/app/widgets/LaserCameraAidBackground/ExtractSquareTrace/index.jsx
Labels: Type: Style

#792 Improvement: Add 'javascript-clipper' lib package to replace ‘martinez-polygon-clipping’ and 'polygon-offset' lib package
  package.json
  src/app/lib/renderer/ViewPathRenderer.js
  src/package.json
  src/server/lib/MeshProcess/Polygons.js
  src/server/lib/ToolPathGenerator/CncToolPathGenerator.js
  src/server/lib/ToolPathGenerator/PolygonOffset.js
  src/server/lib/clipper/cLipper-adapter.js
  src/server/lib/clipper/clipper.js
  src/server/services/task-manager/generateViewPath.js
  test/server/lib/ToolPathGenerator/test-polygon-offset.js
Labels: Type: Improvement

#798 Fix: Modify the accuracy of the clipper
  src/server/lib/clipper/cLipper-adapter.js
Labels: Type: Fix

#797 Improvement: Add the 'allowance' of CNC STL
  src/app/views/ToolPathConfigurations/cnc/CncParameters.jsx
  src/app/views/ToolPathConfigurations/cnc/GcodeParameters.jsx
  src/server/lib/MeshProcess/Polygons.js
  src/server/lib/ToolPathGenerator/MeshToolPath/CncMeshLinkageToolPathGenerator.js
  src/server/lib/clipper/cLipper-adapter.js
Labels: Type: Improvement

#799 Fix: Fix model scaling is reversed when the starting position value is less than 0 on 3dp
  src/app/components/SMCanvas/Controls.jsx
  src/app/components/SMCanvas/TransformControls.js
Labels: Type: Fix

#784 Fix: Fix several SVG transformation synchronization bugs
  src/app/flux/editor/index.js
  src/app/models/Model.js
  src/app/models/SvgModel.js
  src/app/ui/SVGEditor/SVGCanvas.jsx
Labels: Type: Fix

#800 Fix: Pick #775 to v3.14
  src/app/components/SMCanvas/Canvas.jsx
  src/app/components/SMCanvas/Controls.jsx
  src/app/flux/editor/index.js
  src/app/flux/printing/index.js
  src/app/lib/uni-api.js
  src/app/widgets/GCode/GCode.jsx
  src/app/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/widgets/PrintingVisualizer/VisualizerModelTransformation.jsx
  src/app/widgets/WifiTransport/WifiTransport.jsx
Labels: Type: Fix
