Repository Snapmaker/Luban, pull requests merged in 2021-01, with the labels that each got.

#684 Fix: Fix stl diameter calculation problem
  src/app/ui/SVGEditor/SVGEditor.jsx
  src/app/views/Cnc3DVisualizer/Cnc3DVisualizer.jsx
  src/app/widgets/CNCVisualizer/Visualizer.jsx
  src/server/lib/MeshProcess/MeshProcess.js
Labels: Type: Fix

#677 Fix: Fix svgParser bug and remove some extra code
  src/app/components/SMCanvas/TransformControls.js
  src/app/models/ModelGroup.js
  src/shared/lib/SVGParser/AttributesParser.js
Labels: Type: Fix

#686 Improvement: Optimize logic code of layflat
  src/app/models/Model.js
Labels: Type: Perf

#685 Fix: Fix connecting wifi manually bug
  src/app/flux/machine/action-connect.js
  src/app/widgets/Connection/WifiConnection.jsx
Labels: Type: Fix

#687 Refactor: SVG Model and elements
  src/app/containers/Header/PageControl.jsx
  src/app/flux/editor/index.js
  src/app/models/Model.js
  src/app/models/ModelGroup.js
  src/app/models/SVGActionsFactory.js
  src/app/models/SvgModel.js
  src/app/ui/SVGEditor/SVGCanvas.jsx
  src/app/ui/SVGEditor/SVGEditor.jsx
  src/app/ui/SVGEditor/svg-content/OperatorPoints.js
  src/app/ui/SVGEditor/svg-content/SVGContentGroup.js
  src/app/widgets/CNCPath/CNCPath.jsx
  src/app/widgets/CNCVisualizer/Visualizer.jsx
  src/app/widgets/CNCVisualizer/VisualizerTopLeft.jsx
  src/app/widgets/CncLaserOutput/Output.jsx
  src/app/widgets/CncLaserShared/TransformationSection.jsx
  src/app/widgets/LaserParams/LaserParameters.jsx
  src/app/widgets/LaserVisualizer/Visualizer.jsx
  src/app/widgets/LaserVisualizer/VisualizerTopLeft.jsx
Labels: Type: Refactor

#696 Improvement: Update i18n translations for zh-cn
  gulp/tasks/i18next.js
  resources/CuraEngine/Config/snapmaker.def.json
  src/app/containers/Cnc/Cnc.jsx
  src/app/containers/DevelopTools/CNC.jsx
  src/app/containers/Settings/FirmwareTool/FirmwareTool.jsx
  src/app/containers/Settings/General/General.jsx
  src/app/containers/Settings/MachineSettings/MachineSettings.jsx
  src/app/i18n/cs/resource.json
  src/app/i18n/de/resource.json
  src/app/i18n/en/resource.json
  src/app/i18n/es/resource.json
  src/app/i18n/fr/resource.json
  src/app/i18n/hu/resource.json
  src/app/i18n/it/resource.json
  src/app/i18n/ja/resource.json
  src/app/i18n/ko/resource.json
  src/app/i18n/pt-br/resource.json
  src/app/i18n/ru/resource.json
  src/app/i18n/uk/resource.json
  src/app/i18n/zh-cn/resource.json
  src/app/i18n/zh-tw/resource.json
  src/app/lib/uni-api.js
  src/app/widgets/CNCPath/Image3dParameters.jsx
  src/app/widgets/CaseLibrary/index.jsx
  src/app/widgets/CncLaserOutput/Output.jsx
  src/app/widgets/Connection/PrintingState.jsx
  src/app/widgets/Control/JogDistance.jsx
  src/app/widgets/LaserCameraAidBackground/ExtractSquareTrace/index.jsx
  src/app/widgets/LaserCameraAidBackground/SetBackground.jsx
  src/app/widgets/LaserParams/config/ConfigGreyscale.jsx
  src/app/widgets/LaserParams/config/ConfigHalftone.jsx
  src/app/widgets/LaserSetBackground/Instructions.jsx
  src/app/widgets/LaserSetBackground/SetBackground.jsx
  src/app/widgets/Marlin/Printing.jsx
Labels: Type: Improvement

#702 Fix: Fix connecting Wi-Fi manually blanks out software
  src/app/widgets/Connection/WifiConnection.jsx
Labels: Type: Fix

#705 Improvement: Update i18n translation for en
  src/app/i18n/cs/resource.json
  src/app/i18n/de/resource.json
  src/app/i18n/en/resource.json
  src/app/i18n/es/resource.json
  src/app/i18n/fr/resource.json
  src/app/i18n/hu/resource.json
  src/app/i18n/it/resource.json
  src/app/i18n/ja/resource.json
  src/app/i18n/ko/resource.json
  src/app/i18n/pt-br/resource.json
  src/app/i18n/ru/resource.json
  src/app/i18n/uk/resource.json
  src/app/i18n/zh-cn/resource.json
  src/app/i18n/zh-tw/resource.json
  src/app/widgets/CNCPath/Image3dParameters.jsx
  src/app/widgets/CNCPath/gcodeconfig/Image3DGcodeParameters.jsx
  src/app/widgets/CNCVisualizer/Visualizer.jsx
  src/app/widgets/CaseLibrary/CaseConfig.js
  src/app/widgets/CncLaserOutput/Output.jsx
  src/app/widgets/JobType/JobType.jsx
  src/app/widgets/LaserVisualizer/Visualizer.jsx
Labels: Type: Improvement

#704 Fix: Remove an extra comma in snapmaker.def.json file
  resources/CuraEngine/Config/snapmaker.def.json
Labels: Type: Fix

#703 Fix: Fix Arrange All Model Action issue with supports
  src/app/models/ModelGroup.js
Labels: Type: Fix

#710 Fix: Fix invert option not working
  src/app/widgets/LaserParams/config/ConfigRasterVector.jsx
Labels: Type: Fix

#697 Fix: Fix picture mismatch in camera capture on A250
  src/app/constants/index.js
  src/app/widgets/LaserCameraAidBackground/ExtractSquareTrace/index.jsx
Labels: Type: Fix

#695 Fix: Fix thumbnail blanks by using ThreeUtil.computeBoundingBox
  src/app/components/SMCanvas/Controls.jsx
  src/app/components/three-extensions/ThreeUtils.js
  src/app/models/ModelGroup.js
  src/app/widgets/CncLaserShared/Thumbnail.jsx
  src/app/widgets/PrintingOutput/Thumbnail.jsx
Labels: Type: Fix

#690 Fix: Fix bugs for 3.14
  src/app/components/SMCanvas/TransformControls2D.js
  src/app/models/ModelGroup.js
  src/app/models/ToolPathModelGroup.js
  src/app/widgets/CaseLibrary/CaseConfig.js
  src/app/widgets/CaseLibrary/index.jsx
  src/server/lib/MeshProcess/Coordinate.js
  src/server/lib/MeshProcess/Mesh.js
  src/server/lib/MeshProcess/MeshProcess.js
  src/server/lib/ToolPathGenerator/CncReliefToolPathGenerator.js
  src/server/lib/ToolPathGenerator/MeshToolPath/CncMeshLinkageToolPathGenerator.js
Labels: Type: Fix

#706 Fix: Fix bugs for parameter retraction_hop_enabled and recent project files
  src/app/lib/normalize-range.js
  src/app/ui/SVGEditor/SVGCanvas.jsx
  src/app/views/CncToolManager/CncToolManager.jsx
  src/app/views/PrintingManager/PrintingManager.jsx
  src/app/widgets/CncLaserObjectList/ObjectListBox.jsx
  src/app/widgets/PrintingObjectList/PrintingObjectListBox.jsx
  src/main.js
Labels: Type: Fix

#714 Fix: Rework on Wi-Fi connection logic (state server, selected server,…
  src/app/flux/machine/Server.js
  src/app/flux/machine/action-connect.js
  src/app/flux/machine/index.js
  src/app/widgets/Connection/WifiConnection.jsx
  src/server/services/socket/WifiServerManager.js
Labels: Type: Fix

#712 Fix: Fix selected model size being reset on ArrangeAllModel and remove unused code
  src/app/components/three-extensions/STLBinaryExporter.js
  src/app/components/three-extensions/ThreeUtils.js
  src/app/flux/printing/index.js
  src/app/models/Model.js
  src/app/models/ModelGroup.js
  src/app/widgets/LaserParams/config/ConfigRasterVector.jsx
Labels: Type: Fix

#716 Improvement: Modify sizes of 4-axis cases
  src/app/flux/cnc/index.js
  src/app/widgets/CaseLibrary/CaseConfig.js
Labels: Type: Style

#718 Improvement: Add STL image density parameter and modify job type laser schematic
  src/app/images/cnc-laser/4axis.png
  src/app/images/cnc-laser/cnc-4axis.png
  src/app/images/cnc-laser/laser-4axis.png
  src/app/widgets/CNCPath/Image3dParameters.jsx
  src/app/widgets/JobType/JobType.jsx
Labels: Type: Fix

#713 Fix: Set the right title after new file
  src/app/flux/project/index.js
Labels: Type: Fix

#720 Fix: Make the value calculated by computeBoundingBox method in ThreeUtils accurate
  src/app/components/three-extensions/ThreeUtils.js
  src/app/models/Model.js
  src/app/models/ModelGroup.js
Labels: Type: Fix

#723 Fix: Change variable in component SecondaryToolbar
  src/app/widgets/CNCVisualizer/Visualizer.jsx
  src/app/widgets/LaserVisualizer/Visualizer.jsx
  src/app/widgets/WorkspaceVisualizer/Visualizer.jsx
Labels: Category: Editor, Type: Fix

#708 Build: Trigger executable builds only when "TRAVIS_TAG" is present in travis config
  .travis.yml
Labels: Type: Build

#719 Fix: Fix moving elements by arrow keys
  src/app/flux/editor/index.js
  src/app/flux/keyboardShortcut/index.js
  src/app/models/Model.js
  src/app/models/SVGActionsFactory.js
  src/app/models/SvgModel.js
  src/app/ui/SVGEditor/svg-content/SVGContentGroup.js
Labels: Category: Editor, Type: Fix
