Repository Snapmaker/Luban, pull requests merged in 2021-12, with the labels that each got.

#1321 Fix: Fix translation error for firmware update on laser
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
Labels: Type: Fix

#1324 Fix: Fix image3d wrong scale after project loaded
  src/app/flux/editor/index.js
  src/app/models/SvgModel.js
Labels: Type: Fix

#1323 Fix: Fix update version profile error
  src/server/DataStorage.js
Labels: Type: Fix

#1326 Fix fix update version profile error
  src/server/DataStorage.js
Labels: Type: Fix

#1329 Refactor: Change English and Chinese translations
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
Labels: Type: Refactor

#1327 Fix: Fix npm dependency conflicts
  .gitattributes
  .github/workflows/build-on-create-release.yml
  gulp/tasks/app.js
  gulp/tasks/server.js
  package-lock.json
  src/shared/lib/DXFParser/DxfArrayScanner.js
Labels: Type: Fix

#1337 Fix: Bugfix v4.1.1 alpha-1
  src/app/flux/editor/index.js
  src/app/flux/laser/index.js
  src/app/models/ModelGroup.js
  src/app/ui/widgets/LaserStackedModel/index.jsx
Labels: Type: Fix

#1333 Fix translation error 4.1.1
  resources/CuraEngine/Config/laser/snapmaker2.def.json
  src/app/constants/copy.js
  src/app/constants/index.js
  src/app/flux/cnc/index.js
  src/app/flux/laser/index.js
  src/app/flux/machine/index.js
  src/app/flux/manager/DefinitionManager.js
  src/app/flux/project/index.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/components/Select/ChangedReactSelect.jsx
  src/app/ui/layouts/AppLayout.jsx
  src/app/ui/views/DefinitionCreator.jsx
  src/app/ui/views/ProfileManager/index.jsx
  src/app/ui/widgets/Connection/SerialConnection.jsx
  src/app/ui/widgets/WifiTransport/WifiTransport.jsx
  src/app/ui/widgets/WorkspaceVisualizer/Visualizer.jsx
  src/server/DataStorage.js
Labels: Type: Fix

#1339 Fix: Fix bug on v4.1.1-alpha.1
  src/app/flux/machine/index.js
  src/app/flux/project/index.js
  src/app/flux/workspace/index.js
  src/app/lib/uni-api.js
  src/app/models/SVGActionsFactory.js
  src/app/toolpaths/ToolPath.js
  src/app/ui/components/SMCanvas/Canvas.jsx
  src/app/ui/views/ToolPathConfigurations/ToolPathFastConfigurations.jsx
  src/app/ui/widgets/WorkspaceVisualizer/Visualizer.jsx
  src/shared/lib/SVGParser/Parser.js
Labels: Type: Fix

#1336 Build: Bump luban engine’s version to 0.7.0
  package.json
  resources/CuraEngine/Config/printing/snapmaker.def.json
  resources/CuraEngine/Config/printing/snapmaker2.def.json
Labels: Type: Feature

#1347 Fix: Fix 3d printing auto saving translation
  src/app/constants/index.js
  src/app/ui/layouts/AppLayout.jsx
Labels: Type: Fix

#1340 Refactor: Debug in ElectronJS
  gulp/tasks/server.js
  src/server/webpack-dev-server.js
Labels: Type: Refactor

#1346 Feature: Add align feature for 3DP
  package-lock.json
  src/app/constants/index.js
  src/app/flux/operation-history/GroupAlignOperation3D.ts
  src/app/flux/operation-history/UngroupOperation3D.ts
  src/app/flux/printing/index.js
  src/app/models/ModelGroup.js
  src/app/models/ThreeBaseModel.ts
  src/app/models/ThreeGroup.ts
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/pages/Printing.jsx
  src/app/workers/LoadModel.worker.js
Labels: Type: Feature

#1379 Docs: Update CI status badge
  README.md
Labels: Type: Docs

#1373 Feature: Add prime tower
  resources/CuraEngine/Config/printing/a150_dual/quality.fast_print.def.json
  resources/CuraEngine/Config/printing/a150_dual/quality.high_quality.def.json
  resources/CuraEngine/Config/printing/a150_dual/quality.normal_quality.def.json
  resources/CuraEngine/Config/printing/a250_dual/quality.fast_print.def.json
  resources/CuraEngine/Config/printing/a250_dual/quality.high_quality.def.json
  resources/CuraEngine/Config/printing/a250_dual/quality.normal_quality.def.json
  resources/CuraEngine/Config/printing/a350_dual/quality.fast_print.def.json
  resources/CuraEngine/Config/printing/a350_dual/quality.high_quality.def.json
  resources/CuraEngine/Config/printing/a350_dual/quality.normal_quality.def.json
  src/app/flux/operation-history/AddOperation3D.js
  src/app/flux/operation-history/DeleteOperation3D.js
  src/app/flux/operation-history/ScaleOperation3D.js
  src/app/flux/printing/index.js
  src/app/flux/project/index.js
  src/app/models/ModelGroup.js
  src/app/models/PrimeTowerModel.ts
  src/app/models/ThreeBaseModel.ts
  src/app/models/ThreeModel.js
  src/app/ui/components/SMCanvas/Canvas.jsx
  src/app/ui/components/SMCanvas/Controls.jsx
  src/app/ui/components/SMCanvas/TransformControls.js
  src/app/ui/widgets/PrintingObjectList/PrintingObjectListBox.jsx
  src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
Labels: Type: Feature

#1369 Feature: Add 3dp group function part 2 and fix bug LU-1888
  .eslintrc.js
  src/app/flux/cnc/index.js
  src/app/flux/editor/actions-process.js
  src/app/flux/editor/index.js
  src/app/flux/laser/index.js
  src/app/flux/operation-history/AddOperation2D.js
  src/app/flux/operation-history/AddOperation3D.js
  src/app/flux/operation-history/AddOperation3D.ts
  src/app/flux/operation-history/DeleteOperation2D.js
  src/app/flux/operation-history/DeleteOperation3D.js
  src/app/flux/operation-history/DeleteOperation3D.ts
  src/app/flux/operation-history/GroupAlignOperation3D.ts
  src/app/flux/operation-history/GroupOperation3D.ts
  src/app/flux/operation-history/MoveOperation3D.js
  src/app/flux/operation-history/MoveOperation3D.ts
  src/app/flux/operation-history/Operation.ts
  src/app/flux/operation-history/RotateOperation3D.js
  src/app/flux/operation-history/RotateOperation3D.ts
  src/app/flux/operation-history/ScaleOperation3D.js
  src/app/flux/operation-history/ScaleOperation3D.ts
  src/app/flux/operation-history/UngroupOperation3D.ts
  src/app/flux/operation-history/VisibleOperation3D.js
  src/app/flux/operation-history/VisibleOperation3D.ts
  src/app/flux/operation-history/index.js
  src/app/flux/printing/actions-base.js
  src/app/flux/printing/index.js
  src/app/lib/manager/WorkerManager.ts
  src/app/models/BaseModel.ts
  src/app/models/ModelGroup.js
  src/app/models/PrimeTowerModel.ts
  src/app/models/SvgModel.js
  src/app/models/ThreeGroup.ts
  src/app/models/ThreeModel.js
  src/app/toolpaths/ToolPath.js
  src/app/toolpaths/ToolPathGroup.js
  src/app/ui/components/SMCanvas/TransformControls.js
  src/app/ui/views/model-item.jsx
  src/app/ui/widgets/CncLaserOutput/Output.jsx
  src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
  src/app/workers/EvaluateSupportArea.worker.ts
  src/server/services/api/api-file.js
  webpack.config.app.development.js
  webpack.config.app.production.js
Labels: Type: Feature

#1382 Improvement: Add extruder parameters in mesh definition file
  src/app/flux/manager/DefinitionManager.js
  src/app/flux/printing/index.js
Labels: Type: Improvement

#1381 Fix: Cherry-pick removing config category commit and bugfixs
  README.md
  package-lock.json
  package.json
  resources/CuraEngine/Config/printing/snapmaker.def.json
  src/app/flux/printing/index.js
  src/app/ui/views/ProfileManager/index.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
  src/app/ui/widgets/WifiTransport/WifiTransport.jsx
  src/app/ui/widgets/WorkspaceVisualizer/Visualizer.jsx
  src/package.json
  src/server/DataStorage.js
  src/server/constants/index.js
  src/server/slicer/definition.js
Labels: Type: Fix

#1388 Fix: Fix bug on defining variables repeatedly and align operation
  src/app/flux/printing/index.js
  src/app/models/ModelGroup.js
  src/app/workers/EvaluateSupportArea.worker.ts
Labels: Type: Fix

#1383 Improvement: Change gcodeline type and extruder selector
  src/app/flux/printing/index.js
  src/app/styles/global-edge-distance.styl
  src/app/ui/components/PreviewType/PreviewTypeBox.jsx
  src/app/ui/views/ProfileManager/SettingItem.jsx
  src/app/ui/views/ProfileManager/index.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerPreviewControl.jsx
  src/app/workers/GcodeToBufferGeometry/GcodeToBufferGeometryPrint3d.js
  src/shared/lib/gcodeToolPath.js
Labels: Type: Improvement
