Repository Snapmaker/Luban, pull requests merged in 2022-10, with the labels that each got.

#1743 Fix: Fix kill server process
  src/main.js
Labels: Type: Fix

#1732 Feature: Feature cnc locking block
  src/app/flux/cnc/index.js
  src/app/flux/editor/actions-process.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/resources/images/cnc-laser/lock-block-a.png
  src/app/resources/images/cnc-laser/lock-block-b.png
  src/app/resources/images/cnc/locking-block-red.svg
  src/app/ui/SVGEditor/PrintableArea.js
  src/app/ui/SVGEditor/SVGCanvas.jsx
  src/app/ui/SVGEditor/SVGEditor.jsx
  src/app/ui/pages/Cnc.jsx
  src/app/ui/pages/CncLaserShared/JobTypeModal.jsx
  src/app/ui/widgets/CNCVisualizer/Visualizer.jsx
  src/app/ui/widgets/CncLaserShared/PrintablePlate/PrintablePlate.jsx
  src/app/ui/widgets/JobType/JobType.jsx
Labels: Type: Feature, v4.5.0

#1698 Improvement: Improvement no longer parser svg viewBox
  src/app/lib/manager/ClippingPoolManager.worker.ts
  src/app/lib/manager/workerManager.ts
  src/app/models/ClipperModel.ts
  src/app/ui/components/SMCanvas/Canvas.jsx
  src/app/ui/layouts/MainToolBar.jsx
  src/package.json
  src/shared/lib/SVGParser/SVGTagParser.js
Labels: Type: Improvement, v4.5.0

#1700 Improvement: Improve to remove auto rotate to worker
  src/app/flux/printing/index.js
  src/app/models/ModelGroup.ts
  src/app/models/ThreeBaseModel.ts
  src/app/models/ThreeGroup.ts
  src/app/models/ThreeModel.ts
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
  src/app/workers/autoRotateModels.ts
Labels: v4.5.0

#1703 Improvement: Improvement error monitoring
  .github/workflows/build-on-create-release.yml
  build/pkgsync.js
  build/set-config.js
  gulp/tasks/app.js
  gulp/tasks/server.js
  package.json
  src/app/index.jsx
  src/app/ui/App.jsx
  src/main.js
  src/package.json
  src/server/index.js
  webpack.config.app.production.js
  webpack.config.server.production.js
Labels: v4.5.0

#1729 Improvement: SACP RTO for luban connect with artisan
  package.json
  src/app/constants/copy.js
  src/app/constants/index.ts
  src/app/flux/machine/Server.js
  src/app/flux/machine/index.js
  src/app/lib/controller.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/styles/sm-flex.styl
  src/app/ui/components/Buttons/button.jsx
  src/app/ui/widgets/Connection/MismatchModal.jsx
  src/app/ui/widgets/Connection/SerialConnection.jsx
  src/app/ui/widgets/Connection/WifiConnection.jsx
  src/app/ui/widgets/Control/Control.jsx
  src/app/ui/widgets/Control/DisplayPanel.jsx
  src/app/ui/widgets/Control/MotionButtonGroup.jsx
  src/app/ui/widgets/Enclosure/Enclosure.jsx
  src/app/ui/widgets/Marlin/CNC.jsx
  src/app/ui/widgets/Marlin/Printing.jsx
  src/app/ui/widgets/WifiTransport/WifiTransport.jsx
  src/app/ui/widgets/WorkingProgress/WorkingProgress.jsx
  src/app/ui/widgets/WorkspaceVisualizer/Visualizer.jsx
  src/package.json
  src/server/constants/index.js
  src/server/services/index.js
  src/server/services/socket/ConnectionManager.js
  src/server/services/socket/sacp/Business.ts
  src/server/services/socket/sacp/SACP-BASE.ts
  src/server/services/socket/sacp/SACP-SERIAL.ts
  src/server/services/socket/sacp/SACP-TCP.ts
  src/server/services/socket/types.ts
Labels: Type: Improvement, v4.5.0

#1742 Feature: Feature 3DP custom editor
  package.json
  src/app/api/index.js
  src/app/flux/operation-history/DeleteOperation3D.ts
  src/app/flux/printing/index.js
  src/app/flux/project/index.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/resources/images/3dp/empty-box.svg
  src/app/styles/global-background.styl
  src/app/styles/global-border.styl
  src/app/styles/global-edge-distance.styl
  src/app/styles/global-layout.styl
  src/app/styles/global-var.styl
  src/app/styles/sm-flex.styl
  src/app/ui/components/Buttons/button.jsx
  src/app/ui/pages/MachineMaterialSettings/machineSettings.jsx
  src/app/ui/pages/Printing.jsx
  src/app/ui/utils/profileManager.jsx
  src/app/ui/views/PrintingManager/PrintingManager.jsx
  src/app/ui/views/ProfileGroupManager/CategorySelector.jsx
  src/app/ui/views/ProfileGroupManager/EditorContent.jsx
  src/app/ui/views/ProfileGroupManager/EmptyBox.jsx
  src/app/ui/views/ProfileGroupManager/index.jsx
  src/app/ui/widgets/PrintingConfigurations/Configurations.jsx
  src/server/services/api/api-file.js
  src/server/services/index.js
  src/server/services/socket/ConnectionManager.js
  src/server/slicer/definition.js
Labels: Type: Feature, v4.5.0
