Repository Snapmaker/Luban, pull requests merged in 2022-07, with the labels that each got.

#1594 Refactor: Optimize gcode preview
  src/app/flux/printing/index.js
  src/app/ui/components/SMCanvas/Canvas.jsx
  src/app/workers/GcodeToBufferGeometry/GcodeToBufferGeometryPrint3d.js
  src/app/workers/GcodeToBufferGeometry/gcodeBufferGeometryToObj3d.js
  src/app/workers/GcodeToBufferGeometry/index.js
  src/app/workers/ShaderMaterial/print3d-shader-meterial.js
  src/app/workers/gcodeToBufferGeometry.ts
Labels: Type: Refactor

#1639 Improvment: Improve zoom in operation and modify pan operation in 3D printing editor
  src/app/flux/editor/index.js
  src/app/ui/components/SMCanvas/Controls.jsx
  src/app/ui/views/Cnc3DVisualizer/Canvas/Controls.jsx
  src/server/services/api/api-image.js
Labels: Type: Improvement

#1649 Build: Bump version to v4.4.0
  package-lock.json
  package.json
  src/app/ui/components/SMCanvas/Controls.jsx
  src/app/ui/widgets/PrintingConfigurations/Configurations.jsx
  src/package.json
Labels: Type: Build

#1651 Fix: Fix model repair bugs
  src/app/constants/copy.js
  src/app/constants/index.ts
  src/app/flux/app-global/index.js
  src/app/flux/editor/index.js
  src/app/flux/printing/index.js
  src/app/lib/modal.jsx
  src/app/models/ModelGroup.ts
  src/app/models/ThreeModel.ts
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/images/logo.svg
  src/app/three-extensions/SVGLoader.js
  src/app/ui/components/Buttons/styles.styl
  src/app/ui/pages/Printing.jsx
  src/app/ui/views/model-item.jsx
  src/app/ui/widgets/PrintingVisualizer/PrintableCube.jsx
  src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerClippingControl.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerPopup.jsx
Labels: Type: Fix

#1641 Improvement: Update i18n translation for Ukrainian
  src/app/resources/i18n/uk/gcode.json
  src/app/resources/i18n/uk/resource.json
Labels: v4.4.0

#1659 Fix: Fix storaging nozzle diameter
  src/app/ui/pages/MachineMaterialSettings/machineSettings.jsx
Labels: Type: Fix

#1666 Fix: Fix bug on ux/ui and update default definition
  resources/CuraEngine/Config/printing/fdmprinter.def.json
  resources/CuraEngine/Config/printing/snapmaker.def.json
  resources/CuraEngine/Config/printing/snapmaker2.def.json
  src/app/flux/machine/index.js
  src/app/flux/printing/index.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/components/Input/NumberInput.jsx
  src/app/ui/components/TipTrigger/index.jsx
  src/app/ui/pages/MachineMaterialSettings/addMaterialModel.jsx
  src/app/ui/pages/MachineMaterialSettings/materialSettings.jsx
  src/app/ui/views/DefinitionCreator.jsx
  src/app/ui/views/ProfileManager/ConfigValueBox.jsx
  src/app/ui/views/ProfileManager/SettingItem.jsx
  src/app/ui/views/ProfileManager/index.jsx
  src/app/ui/views/ProfileManager/styles.styl
  src/app/ui/widgets/PrintingConfigurations/Configurations.jsx
Labels: Type: Fix
