Repository Snapmaker/Luban, pull requests merged in 2022-12, with the labels that each got.

#1775 Fix: Fix connection issues & support/adhesion parameters not taking effect
  babel.config.js
  package-lock.json
  package.json
  src/app/constants/index.ts
  src/app/constants/machines.ts
  src/app/flux/machine/index.js
  src/app/flux/manager/DefinitionManager.js
  src/app/flux/printing/index.js
  src/app/flux/workspace/index.js
  src/app/lib/i18n.js
  src/app/ui/pages/Printing.jsx
  src/app/ui/widgets/Connection/MismatchModal.jsx
  src/app/ui/widgets/Connection/WifiConnection.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/ExtruderOverlay.jsx
  src/server/services/socket/sacp/SACP-BASE.ts
  src/server/services/socket/sacp/SACP-SERIAL.ts
  src/server/services/socket/sacp/SACP-TCP.ts
Labels: Type: Fix

#1776 Fix: Fix dual extruder issues
  resources/CuraEngine/Config/printing/snapmaker_j1/quality.normal_other_quality.def.json
  resources/CuraEngine/Config/printing/snapmaker_j1/quality.normal_tpu_quality.def.json
  resources/CuraEngine/Config/printing/snapmaker_modify_0.def.json
  src/app/constants/preset.ts
  src/app/flux/printing/index.js
  src/app/lib/dialog.js
  src/app/ui/utils/profileManager.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/ChangePrintModeOverlay.jsx
  src/server/services/socket/socket-slice.js
  src/server/slicer/Slicer.ts
  src/server/slicer/definition.js
  src/server/slicer/post-processor.ts
  src/server/slicer/slicer-definitions.ts
Labels: Category: 3DP

#1777 Fix: Fix dual extruder issues
  package-lock.json
  package.json
  src/app/constants/machines.ts
  src/app/flux/manager/PresetDefinitionModel.ts
  src/app/resources/images/machine/snapmaker_j1_dual_extruders.png
  src/app/ui/views/ParamItem.jsx
  src/app/ui/widgets/PrintingConfigurations/Configurations.jsx
  src/package.json
  src/server/lib/image-getPhoto.js
  webpack.config.app.production.js
  webpack.config.server.production.js
Labels: Type: Fix, Category: 3DP

#1781 Fix: Fix G-code read before output stream closes
  package-lock.json
  package.json
  src/app/constants/copy.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/views/ParameterModifier/ParameterModifier.jsx
  src/app/ui/views/ParameterModifier/StackPresetSelector.jsx
  src/package.json
  src/server/slicer/post-processor.ts
Labels: Type: Fix

#1783 Build: Degrade electron to v17.4.11 for macOS performance
  package-lock.json
  package.json
  src/package.json
Labels: Type: Build, dependencies

#1787 Improvement: Update quality defaults & bugfixes
  package-lock.json
  package.json
  resources/CuraEngine/Config/printing/snapmaker_j1/quality.fast_print.def.json
  resources/CuraEngine/Config/printing/snapmaker_j1/quality.high_quality.def.json
  resources/CuraEngine/Config/printing/snapmaker_j1/quality.normal_other_quality.def.json
  resources/CuraEngine/Config/printing/snapmaker_j1/quality.normal_tpu_quality.def.json
  src/app/constants/preset.ts
  src/app/flux/machine/index.js
  src/app/flux/manager/DefinitionManager.js
  src/app/flux/manager/PresetDefinitionModel.ts
  src/app/flux/printing/index.js
  src/app/ui/layouts/styles/maintoolbar.styl
  src/app/ui/pages/MachineMaterialSettings/materialSettings.jsx
  src/app/ui/utils/profileManager.jsx
  src/app/ui/views/DefinitionCreator.jsx
  src/app/ui/views/ParameterModifier/ParameterModifier.jsx
  src/app/ui/views/ParameterModifier/StackPresetSelector.jsx
  src/app/ui/views/ProfileManager/index.jsx
  src/app/ui/views/ProfileManagerForLaserCnc/index.jsx
  src/app/ui/widgets/PrintingConfigurations/Configurations.jsx
  src/package.json
  src/server/slicer/definition.js
Labels: Type: Fix, Category: 3DP

#1789 Fix: Upgrade slicer version
  package-lock.json
  package.json
  src/package.json
Labels: Type: Fix

#1790 Feature: Add Artisan specific start/end G-code
  resources/CuraEngine/Config/printing/a400_dual/machine.def.json
  resources/CuraEngine/Config/printing/a400_single/machine.def.json
  src/app/flux/manager/DefinitionManager.js
Labels: Category: 3DP

#1784 Improvement: Added white space at the end of sentence to the pop-up message when you saved g-code to a file.
  src/app/ui/layouts/AppLayout.jsx
Labels: Type: Improvement

#1791 Build: Split electron builder configuration to separate file
  .github/workflows/build-on-create-release.yml
  electron-builder.yml
  package-lock.json
  package.json
  src/package.json
  webpack.config.app.development.js
  webpack.config.app.production.js
Labels: Type: Build

#1795 Improvement: Update Artisan dual quality presets
  resources/CuraEngine/Config/printing/a400_dual/material.abs.black.def.json
  resources/CuraEngine/Config/printing/a400_dual/material.abs.def.json
  resources/CuraEngine/Config/printing/a400_dual/material.asa.def.json
  resources/CuraEngine/Config/printing/a400_dual/material.nylon.copa.def.json
  resources/CuraEngine/Config/printing/a400_dual/material.nylon.pa6cf.def.json
  resources/CuraEngine/Config/printing/a400_dual/material.other.def.json
  resources/CuraEngine/Config/printing/a400_dual/material.pc.def.json
  resources/CuraEngine/Config/printing/a400_dual/material.petg.black.def.json
  resources/CuraEngine/Config/printing/a400_dual/material.petg.blue.def.json
  resources/CuraEngine/Config/printing/a400_dual/material.petg.def.json
  resources/CuraEngine/Config/printing/a400_dual/material.petg.red.def.json
  resources/CuraEngine/Config/printing/a400_dual/material.pla.black.def.json
  resources/CuraEngine/Config/printing/a400_dual/material.pla.blue.def.json
  resources/CuraEngine/Config/printing/a400_dual/material.pla.def.json
  resources/CuraEngine/Config/printing/a400_dual/material.pla.glow.def.json
  resources/CuraEngine/Config/printing/a400_dual/material.pla.grey.def.json
  resources/CuraEngine/Config/printing/a400_dual/material.pla.red.def.json
  resources/CuraEngine/Config/printing/a400_dual/material.pla.wood.def.json
  resources/CuraEngine/Config/printing/a400_dual/material.pla.yellow.def.json
  resources/CuraEngine/Config/printing/a400_dual/material.pva.def.json
  resources/CuraEngine/Config/printing/a400_dual/material.support.def.json
  resources/CuraEngine/Config/printing/a400_dual/material.tpu.black.def.json
  resources/CuraEngine/Config/printing/a400_dual/material.tpu.yellow.def.json
  resources/CuraEngine/Config/printing/a400_dual/quality.engineering_print.def.json
  resources/CuraEngine/Config/printing/a400_dual/quality.fast_print.def.json
  resources/CuraEngine/Config/printing/a400_dual/quality.high_quality.def.json
  resources/CuraEngine/Config/printing/a400_dual/quality.normal_other_quality.def.json
  resources/CuraEngine/Config/printing/a400_dual/quality.normal_quality.def.json
  resources/CuraEngine/Config/printing/a400_dual/quality.support_custom.def.json
  src/app/lib/caseLibrary.jsx
  src/app/ui/pages/HomePage/CaseConfig.js
  src/server/services/api/api-file.js
Labels: Type: Fix

#1796 Fix: Fix bug for laser camera capture
  src/app/ui/widgets/WifiTransport/WifiTransport.jsx
  src/server/services/socket/sacp/SACP-TCP.ts
Labels: Category: Laser

#1799 Feature: Update slicer version to support macOS 11
  package-lock.json
  package.json
  src/package.json
Labels: Category: 3DP

#1801 Fix: Fix submodule path
  .gitmodules
Labels: Type: Fix

#1802 Build: Bump version to v4.5.0-beta.6
  package-lock.json
  package.json
  src/package.json
Labels: Type: Build

#1803 Feature: Upgrade slicer to support new features
  package-lock.json
  package.json
  src/package.json
Labels: Type: Feature, Category: 3DP

#1805 Fix: Fix Camera Capture (thickness compensation mode) procedure
  src/app/flux/machine/index.js
  src/app/ui/widgets/LaserCameraAidBackground/ManualCalibration/ManualCalibration.jsx
  src/app/ui/widgets/LaserCameraAidBackground/SelectCaptureMode.tsx
Labels: Type: Fix, Category: Laser

#1809 Fix: Fix several bugs related to 4.5.0-alpha.10 build
  package-lock.json
  package.json
  resources/CuraEngine/Config/printing/a150_dual/machine.def.json
  resources/CuraEngine/Config/printing/a150_single/machine.def.json
  resources/CuraEngine/Config/printing/a250_dual/machine.def.json
  resources/CuraEngine/Config/printing/a250_single/machine.def.json
  resources/CuraEngine/Config/printing/a350_dual/machine.def.json
  resources/CuraEngine/Config/printing/a350_single/machine.def.json
  resources/CuraEngine/Config/printing/a400_dual/machine.def.json
  resources/CuraEngine/Config/printing/a400_single/machine.def.json
  resources/CuraEngine/Config/printing/original_single/machine.def.json
  resources/CuraEngine/Config/printing/snapmaker_j1/extruder_0.def.json
  resources/CuraEngine/Config/printing/snapmaker_j1/extruder_1.def.json
  resources/CuraEngine/Config/printing/snapmaker_j1/machine.def.json
  resources/CuraEngine/Config/printing/snapmaker_machine.def.json
  resources/CuraEngine/Config/printing/snapmaker_modify_0.def.json
  src/app/flux/manager/DefinitionManager.js
  src/app/ui/views/ProfileManager/PresetContent.jsx
  src/package.json
  src/server/slicer/definition.js
Labels: Type: Fix

#1812 Fix: Fix several bugs related to material copy/create
  resources/CuraEngine/Config/printing/snapmaker_j1/extruder_0.def.json
  resources/CuraEngine/Config/printing/snapmaker_j1/extruder_1.def.json
  resources/CuraEngine/Config/printing/snapmaker_j1/machine.def.json
  resources/CuraEngine/Config/printing/snapmaker_modify_0.def.json
  scripts/upgrade_modify_0.js
  src/app/flux/manager/DefinitionManager.js
  src/app/flux/printing/index.js
  src/app/ui/utils/profileManager.jsx
  src/app/ui/views/PresetModifier/ParametersTableView.tsx
  src/app/ui/views/PresetModifier/PresetContent.jsx
  src/app/ui/views/PrintingManager/PrintingManager.jsx
  src/app/ui/views/ProfileManager/PresetContent.jsx
  src/app/ui/views/ProfileManager/index.jsx
  src/app/ui/widgets/PrintingConfigurations/ConfigurationView.tsx
  src/server/slicer/definition.js
Labels: Type: Fix, Category: 3DP

#1813 Build: Bump version to beta.8
  package-lock.json
  package.json
  src/package.json
Labels: Type: Build

#1816 Fix: Upgrade i18next scanner to support new grammar and TypeScript
  CONTRIBUTING.md
  docs/Development.md
  docs/Environment-Linux.md
  docs/Environment-Windows.md
  gulp/tasks/i18next.js
  package-lock.json
  package.json
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
Labels: Type: Fix, Type: Improvement

#1817 Fix: Fix eslint errors in code
  gulp/tasks/i18next.js
Labels: Type: Fix

#1822 Fix: Fix bugs for Snapmaker J1 network connections
  src/app/flux/machine/Server.js
  src/server/services/socket/sacp/SACP-TCP.ts
Labels: Type: Fix

#1823 Refactor: Split scene actions out of printing actions
  gulp/tasks/server.js
  package-lock.json
  package.json
  src/app/config/settings.js
  src/app/constants/index.ts
  src/app/flux/operation-history/index.js
  src/app/flux/printing/actions-base.js
  src/app/flux/printing/actions-scene.ts
  src/app/flux/printing/index.js
  src/app/index.jsx
  src/app/lib/log.js
  src/app/lib/log.ts
  src/app/ui/App.jsx
  src/app/ui/views/ParamItem.jsx
  src/app/ui/views/PresetModifier/ParametersQuickSettingsView.tsx
  src/main.js
  src/package.json
  src/server-cli.js
  src/server/DataStorage.js
  src/server/index.js
  src/shared/lib/DXFParser/DxfParser.js
  src/shared/lib/FontManager.js
  src/shared/lib/SVGParser/AttributesParser.js
  tsconfig-server.json
Labels: Type: Refactor

#1825 Improvement: Improve print mode selection overlay & improve prime tower calculation logic
  src/app/api/index.js
  src/app/flux/manager/DefinitionManager.js
  src/app/flux/operation-history/AddOperation3D.ts
  src/app/flux/operation-history/DeleteOperation3D.ts
  src/app/flux/operation-history/GroupAlignOperation3D.ts
  src/app/flux/operation-history/GroupOperation3D.ts
  src/app/flux/operation-history/MoveOperation3D.ts
  src/app/flux/operation-history/RotateOperation3D.ts
  src/app/flux/operation-history/ScaleOperation3D.ts
  src/app/flux/operation-history/ScaleToFitWithRotateOperation3D.ts
  src/app/flux/operation-history/UngroupOperation3D.ts
  src/app/flux/printing/actions-scene.ts
  src/app/flux/printing/index.js
  src/app/flux/project/index.js
  src/app/models/ModelGroup.ts
  src/app/models/PrimeTowerModel.ts
  src/app/models/events.ts
  src/app/scene/Scene.ts
  src/app/scene/scene.logic.ts
  src/app/ui/pages/MachineMaterialSettings/MachineSettings.jsx
  src/app/ui/pages/Printing.jsx
  src/app/ui/views/Cnc3DVisualizer/styles.styl
  src/app/ui/views/ToolPathConfigurations/styles.styl
  src/app/ui/widgets/PrintingConfigurations/ConfigurationView.tsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/ChangePrintModeOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
  src/server/services/api/api-file.js
  src/server/services/index.js
Labels: Category: UX, Category: 3DP, State: Draft

#1831 Refactor: Refactor extruder assignment
  src/app/flux/printing/index.js
  src/app/lib/gaEvent.ts
  src/app/lib/normalize-range.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/styles/global-border.styl
  src/app/styles/global-font.styl
  src/app/ui/SVGEditor/SVGLeftBar.jsx
  src/app/ui/components/Card/Card.tsx
  src/app/ui/components/Card/CardWrapper.jsx
  src/app/ui/components/Card/index.js
  src/app/ui/components/Card/styles.styl
  src/app/ui/components/Dropdown/Dropdown.tsx
  src/app/ui/components/Dropdown/index.js
  src/app/ui/components/Dropdown/index.ts
  src/app/ui/components/Dropdown/styles.styl
  src/app/ui/layouts/AppLayout.jsx
  src/app/ui/pages/PageMode.ts
  src/app/ui/pages/Printing.jsx
  src/app/ui/views/PrintingObjectList/ObjectListCardView.tsx
  src/app/ui/views/PrintingObjectList/ObjectListItem.jsx
  src/app/ui/views/PrintingObjectList/ObjectListView.tsx
  src/app/ui/views/PrintingObjectList/ObjectSvgIcon.tsx
  src/app/ui/views/PrintingObjectList/images/list_ic_3d_18x18.png
  src/app/ui/views/PrintingObjectList/images/list_ic_close_18x18@2x.png
  src/app/ui/views/PrintingObjectList/images/list_ic_open_18x18@2x.png
  src/app/ui/views/PrintingObjectList/index.tsx
  src/app/ui/views/PrintingObjectList/styles.styl
  src/app/ui/views/model-item.jsx
  src/app/ui/widgets/CncLaserList/ObjectList/ObjectListBox.jsx
  src/app/ui/widgets/CncLaserTopRight/VisualizerTopRight.jsx
  src/app/ui/widgets/PrintingConfigurations/ConfigurationView.tsx
  src/app/ui/widgets/PrintingObjectList/PrintingObjectListBox.jsx
  src/app/ui/widgets/PrintingObjectList/index.jsx
  src/app/ui/widgets/PrintingObjectList/styles.styl
  src/app/ui/widgets/PrintingVisualizer/Overlay/ChangePrintModeOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/ExtruderOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/MirrorOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/RotateOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/ScaleOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/SupportOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/TranslateOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerBottomLeft.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerClippingControl.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
  src/app/ui/widgets/PrintingVisualizer/index.jsx
  webpack.config.app.development.js
Labels: Category: 3DP
