Repository Snapmaker/Luban, pull requests merged in 2022-01, with the labels that each got.

#1353 Improvement: Fiexd dependencies version
  build/fiexd-dependencies-version.js
  package-lock.json
  package.json
  src/app/flux/printing/index.js
  src/package.json
Labels: dependencies

#1328 Improvement: Add laser 10w security code for serial port
  src/server/controllers/Marlin/Marlin.js
Labels: Type: Improvement

#1396 Fix: Fix bug on v4.1.3
  src/app/flux/machine/index.js
  src/app/flux/printing/index.js
  src/app/three-extensions/TextSprite.js
  src/app/ui/widgets/PrintingVisualizer/PrintableCube.jsx
  src/app/workers/GcodeToBufferGeometry/GcodeToBufferGeometryPrint3d.js
Labels: Type: Fix

#1410 Fix: Fix 10w-laser start print position error
  src/app/flux/machine/index.js
  src/app/three-extensions/TargetPoint.js
  src/app/ui/components/Select/styles.styl
  src/app/ui/views/ToolPathConfigurations/cnc/ToolSelector.jsx
  src/app/ui/widgets/WifiTransport/WifiTransport.jsx
Labels: Type: Fix

#1409 Fix: Fix loading file bug on laser and cnc
  package.json
  src/app/flux/editor/actions-process.js
  src/app/flux/editor/index.js
  src/app/flux/workspace/index.js
  src/app/models/BaseModel.ts
  src/app/models/ModelGroup.js
  src/app/models/SvgModel.js
  src/app/models/ThreeBaseModel.ts
  src/app/models/ThreeModel.js
  src/app/toolpaths/ToolPath.js
  src/app/ui/SVGEditor/PrintableArea.js
  src/app/ui/SVGEditor/svg-content/SVGContentGroup.js
  src/package.json
  src/server/services/api/api-commands.js
  src/server/services/api/api-events.js
  src/server/services/api/api-file.js
  src/server/services/api/api-macros.js
  src/server/services/api/api-users.js
  src/server/services/configstore/index.js
  tsconfig.json
Labels: Type: Fix

#1393 Fix: Fix UI error in gcode line review
  resources/CuraEngine/Config/printing/a150_dual/quality.fast_print.def.json
  resources/CuraEngine/Config/printing/a150_dual/quality.high_quality.def.json
  resources/CuraEngine/Config/printing/a150_dual/quality.normal_quality.def.json
  resources/CuraEngine/Config/printing/a250_dual/quality.fast_print.def.json
  resources/CuraEngine/Config/printing/a250_dual/quality.high_quality.def.json
  resources/CuraEngine/Config/printing/a250_dual/quality.normal_quality.def.json
  resources/CuraEngine/Config/printing/a350_dual/quality.fast_print.def.json
  resources/CuraEngine/Config/printing/a350_dual/quality.high_quality.def.json
  resources/CuraEngine/Config/printing/a350_dual/quality.normal_quality.def.json
  src/app/constants/copy.js
  src/app/constants/index.js
  src/app/flux/printing/index.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/store/local-storage.js
  src/app/styles/global-border.styl
  src/app/styles/global-edge-distance.styl
  src/app/styles/global-layout.styl
  src/app/styles/global-var.styl
  src/app/ui/components/ColorSelector/ColorSelectorWrapper.jsx
  src/app/ui/components/ColorSelector/index.js
  src/app/ui/components/PreviewType/PreviewTypeBox.jsx
  src/app/ui/views/ProfileManager/SettingItem.jsx
  src/app/ui/views/ProfileManager/styles.styl
  src/app/ui/widgets/PrintingMaterial/Material.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerPreviewControl.jsx
Labels: Type: Fix

#1421 Improvement: Improvement prime tower
  gulp/tasks/i18next.js
  resources/CuraEngine/Config/printing/a150_dual/quality.fast_print.def.json
  resources/CuraEngine/Config/printing/a150_dual/quality.high_quality.def.json
  resources/CuraEngine/Config/printing/a150_dual/quality.normal_quality.def.json
  resources/CuraEngine/Config/printing/a250_dual/quality.fast_print.def.json
  resources/CuraEngine/Config/printing/a250_dual/quality.high_quality.def.json
  resources/CuraEngine/Config/printing/a250_dual/quality.normal_quality.def.json
  resources/CuraEngine/Config/printing/a350_dual/quality.fast_print.def.json
  resources/CuraEngine/Config/printing/a350_dual/quality.high_quality.def.json
  resources/CuraEngine/Config/printing/a350_dual/quality.normal_quality.def.json
  src/app/constants/index.js
  src/app/flux/manager/DefinitionManager.js
  src/app/flux/printing/index.js
Labels: Type: Improvement

#1420 Improvement: Improve to increase the strokewidth of the axis on laser and cnc and add release note
  src/app/lib/uni-api.js
  src/app/ui/SVGEditor/PrintableArea.js
Labels: Type: Improvement

#1423 Fix: CNC/Laser gcodeName & Angel slider bug
  src/app/flux/editor/actions-process.js
  src/app/ui/widgets/LaserParams/config/ConfigHalftone.jsx
  src/app/ui/widgets/WifiTransport/WifiTransport.jsx
Labels: Type: Fix

#1425 Feature: Add files saved modal
  src/app/flux/app-global/index.js
  src/app/flux/index.js
  src/app/flux/project/index.js
  src/app/lib/uni-api.js
  src/app/ui/layouts/AppLayout.jsx
  src/main.js
Labels: Type: Feature

#1412 Feature: Back up data & 3dp profile migrate tip modal
  package.json
  src/app/api/index.js
  src/app/config/menu/settingsMenu.js
  src/app/constants/copy.js
  src/app/flux/printing/index.js
  src/app/flux/setting/index.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/styles/global-font.styl
  src/app/ui/layouts/AppLayout.jsx
  src/app/ui/pages/Printing.jsx
  src/main.js
  src/package.json
  src/server/DataStorage.js
  src/server/services/api/api-profile-definitions.js
  src/server/services/api/api-users.js
  src/server/services/index.js
  src/server/slicer/definition.js
Labels: Type: Feature

#1407 Feature: Add stop area for 3D printing
  src/app/constants/index.js
  src/app/flux/printing/index.js
  src/app/models/ModelGroup.js
  src/app/ui/widgets/PrintingMaterial/Material.jsx
  src/app/ui/widgets/PrintingVisualizer/PrintableCube.jsx
  src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
Labels: Type: Feature, Category: 3DP

#1404 Improvement: Auto preview file when import G code to workspace
  src/app/flux/machine/index.js
  src/app/flux/workspace/index.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/pages/Settings/General/General.jsx
  src/app/ui/widgets/WifiTransport/WifiTransport.jsx
  src/app/workers/GcodeToArraybufferGeometry.worker.js
Labels: Type: Improvement

#1433 Fix: Fix dual extruder ui & i18n label
  package.json
  src/app/flux/printing/index.js
  src/app/models/ModelGroup.js
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/ui/components/Dropdown/dropdown.jsx
  src/app/ui/widgets/PrintingObjectList/styles.styl
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
Labels: Type: Fix

#1432 Fix: Fix serveral bug in v4.2.0
  src/app/constants/index.js
  src/app/flux/printing/index.js
  src/app/lib/check-name.js
  src/app/ui/views/ToolPathConfigurations/ToolPathConfigurations.jsx
  src/server/services/configstore/index.js
  src/shared/lib/SVGParser/AttributesParser.js
  src/shared/lib/SVGParser/Parser.js
  src/shared/lib/SVGParser/TextParser.js
  src/shared/lib/SVGParser/constants.js
Labels: Type: Fix

#1431 Fix: Fix generate gcode button disabled when undo removing in laser & rotation analysis clear supports
  src/app/flux/operation-history/DeleteOperation2D.js
  src/app/flux/printing/index.js
  src/app/ui/widgets/PrintingVisualizer/Overlay/RotationAnalysisOverlay.jsx
Labels: Type: Fix

#1428 Style: Change saved modal styles
  src/app/flux/app-global/index.js
  src/app/flux/project/index.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/styles/global-layout.styl
  src/app/styles/variables.styl
  src/app/ui/layouts/AppLayout.jsx
Labels: Type: Style

#1430 Improvement: 3DP profile category operation support
  src/app/flux/cnc/index.js
  src/app/flux/editor/index.js
  src/app/flux/laser/index.js
  src/app/flux/manager/DefinitionManager.js
  src/app/flux/operation-history/GroupAlignOperation3D.ts
  src/app/flux/operation-history/GroupOperation3D.ts
  src/app/flux/operation-history/UngroupOperation3D.ts
  src/app/flux/printing/index.js
  src/app/lib/hooks/set-state.jsx
  src/app/models/ModelGroup.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/components/Select/ChangedReactSelect.jsx
  src/app/ui/views/CncToolManager/CncToolManager.jsx
  src/app/ui/views/DefinitionCreator.jsx
  src/app/ui/views/LaserPresentManager/LaserPresentManager.jsx
  src/app/ui/views/PrintingManager/PrintingManager.jsx
  src/app/ui/views/ProfileManager/index.jsx
  src/app/ui/views/ToolPathConfigurations/ToolPathConfigurations.jsx
  src/app/ui/views/ToolPathConfigurations/cnc/CncParameters.jsx
  src/app/ui/views/ToolPathConfigurations/cnc/ToolSelector.jsx
  src/app/ui/views/ToolPathConfigurations/laser/PresentSelector.jsx
  src/app/ui/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx
  src/app/ui/widgets/CncLaserOutput/Output.jsx
  src/app/ui/widgets/Macro/Macro.jsx
  src/app/ui/widgets/PrintingMaterial/MaterialWithColor.jsx
  src/app/ui/widgets/PrintingMaterial/styles.styl
  src/app/ui/widgets/WifiTransport/WifiTransport.jsx
Labels: Type: Improvement
