Repository Snapmaker/Luban, pull requests merged in 2022-06, with the labels that each got.

#1606 Refactor: Restore control.js and remove console
  src/app/ui/components/SMCanvas/Controls.jsx
  src/app/ui/widgets/Connection/WifiConnection.jsx
  src/app/ui/widgets/Control/Control.jsx
  src/server/services/socket/sacp/SACP-BASE.ts
Labels: Type: Refactor

#1602 Feature: Add printing worklfow optimize
  src/app/flux/editor/actions-process.js
  src/app/flux/machine/index.js
  src/app/flux/printing/index.js
  src/app/flux/workspace/index.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/pages/Settings/General/General.jsx
  src/app/ui/pages/Settings/General/SubMenuItemWrapper.jsx
  src/app/ui/widgets/Console/Console.jsx
  src/app/ui/widgets/WifiTransport/GCodeParams.jsx
  src/app/ui/widgets/WifiTransport/PreviewToRunJobModal.jsx
  src/app/ui/widgets/WifiTransport/WifiTransport.jsx
  src/app/ui/widgets/WorkingProgress/Loading.jsx
  src/app/ui/widgets/WorkingProgress/WorkingProgress.jsx
  src/server/services/socket/socket-slice.js
  src/server/services/task-manager/Task.ts
  src/server/services/task-manager/TaskManager.ts
  src/server/services/task-manager/workers/generateGcode.js
Labels: Type: Feature

#1605 Fix: Fix getting stuck on generating gcode when processing a large number of toolpaths
  src/app/flux/editor/actions-process.js
  src/app/lib/socket-controller.js
  src/app/models/SvgModel.js
  src/app/toolpaths/ToolPath.js
  src/server/services/api/api-image.js
Labels: bugfix-v4.3.0

#1599 Improvement: Improve to add Error Boundaries for front end widgets and add ga event
  src/app/lib/gaEvent.ts
  src/app/ui/App.jsx
Labels: bugfix-v4.3.0

#1620 Fix: Fix bug on v4.3.0
  src/app/flux/machine/index.js
  src/app/flux/project/index.js
  src/app/models/ThreeModel.js
  src/app/ui/views/PrintingManager/PrintingManager.jsx
  src/app/ui/widgets/Connection/SerialConnection.jsx
  src/app/ui/widgets/Marlin/CNC.jsx
  src/app/ui/widgets/Marlin/Laser.jsx
  src/app/ui/widgets/PrintingConfigurations/Configurations.jsx
  src/server/DataStorage.js
  src/server/services/socket/socket-http.ts
  src/server/services/task-manager/workerManager.ts
Labels: bugfix-v4.3.0

#1626 Feature: Add two new widgets and update antd
  package.json
  src/app/ui/components/Segmented/SmallSegment.jsx
  src/app/ui/components/Segmented/index.jsx
  src/app/ui/components/Segmented/styles.styl
  src/app/ui/components/Stepper/index.jsx
  src/app/ui/components/Stepper/styles.styl
  src/app/ui/components/TipTrigger/index.jsx
  src/app/ui/widgets/Macro/Macro.jsx
Labels: Type: Feature
