Repository Snapmaker/Luban, pull requests merged in 2022-04, with the labels that each got.

#1525 Fix: Retraction switch & Laser multi toolPath slice & UI Z order & switch model color when editing support
  src/app/flux/editor/actions-process.js
  src/app/flux/editor/index.js
  src/app/models/ThreeModel.js
  src/app/store/local-storage.js
  src/app/styles/contextmenu.styl
  src/app/ui/components/Select/ChangedReactSelect.jsx
  src/app/ui/views/ProfileManager/ConfigValueBox.jsx
  src/app/ui/views/ProfileManager/SettingItem.jsx
Labels: Type: Fix

#1524 Fix: Fix several params doesn't work in some case & UI bugs
  src/app/flux/editor/actions-base.js
  src/app/flux/manager/DefinitionManager.js
  src/app/flux/printing/index.js
  src/app/models/SvgModel.js
  src/app/ui/views/ProfileManager/ConfigValueBox.jsx
Labels: Type: Fix

#1519 Fix: Fix saving as logic and improve to add afterOpened hook for project file
  src/app/flux/appbar-menu/index.js
  src/app/flux/editor/index.js
  src/app/flux/operation-history/index.js
  src/app/flux/printing/index.js
  src/app/flux/project/index.js
  src/app/lib/uni-api.js
  src/app/models/ModelGroup.js
  src/app/ui/pages/Printing.jsx
  src/app/ui/views/AppBar/Menu.jsx
  src/app/ui/widgets/LaserVisualizer/Visualizer.jsx
Labels: Type: Fix

#1449 Improvement: Improve the error log of engine
  src/server/slicer/call-engine.js
Labels: State: Postponed

#1533 Improvement: Update language adaptation style
  src/app/constants/index.js
  src/app/resources/i18n/de/resource.json
  src/app/styles/global-edge-distance.styl
  src/app/styles/global-font.styl
  src/app/styles/global-layout.styl
  src/app/styles/global-var.styl
  src/app/styles/sm-flex.styl
  src/app/styles/sm-icon.styl
  src/app/ui/components/Buttons/button.jsx
  src/app/ui/components/Buttons/styles.styl
  src/app/ui/components/PreviewType/PreviewTypeBox.jsx
  src/app/ui/components/Select/styles.styl
  src/app/ui/layouts/MainToolBar.jsx
  src/app/ui/layouts/MenuItem.jsx
  src/app/ui/layouts/ProjectLayout.jsx
  src/app/ui/layouts/WorkspaceLayout.jsx
  src/app/ui/layouts/styles/maintoolbar.styl
  src/app/ui/layouts/styles/project.styl
  src/app/ui/layouts/styles/workspace.styl
  src/app/ui/pages/CncLaserShared/MainToolBar.jsx
  src/app/ui/pages/HomePage/Begin.jsx
  src/app/ui/pages/HomePage/QuickStart.jsx
  src/app/ui/pages/HomePage/index.jsx
  src/app/ui/pages/HomePage/styles.styl
  src/app/ui/pages/Printing.jsx
  src/app/ui/pages/Workspace.jsx
  src/app/ui/views/ProfileManager/SettingItem.jsx
  src/app/ui/views/ProfileManager/index.jsx
  src/app/ui/views/ProfileManager/styles.styl
  src/app/ui/views/ToolPathConfigurations/ToolPathConfigurations.jsx
  src/app/ui/views/ToolPathConfigurations/cnc/CncParameters.jsx
  src/app/ui/views/ToolPathConfigurations/cnc/ToolParameters.jsx
  src/app/ui/views/ToolPathConfigurations/cnc/ToolSelector.jsx
  src/app/ui/views/ToolPathConfigurations/laser/GcodeParameters.jsx
  src/app/ui/views/ToolPathConfigurations/laser/LaserParameters.jsx
  src/app/ui/views/ToolPathConfigurations/laser/PresentSelector.jsx
  src/app/ui/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx
  src/app/ui/widgets/CncLaserList/styles.styl
  src/app/ui/widgets/CncLaserShared/TransformationSection.jsx
  src/app/ui/widgets/Connection/WifiConnection.jsx
  src/app/ui/widgets/Control/Control.jsx
  src/app/ui/widgets/LaserParams/ImageProcessMode.jsx
  src/app/ui/widgets/Marlin/Printing.jsx
  src/app/ui/widgets/PrintingMaterial/styles.styl
  src/app/ui/widgets/PrintingVisualizer/Overlay/ScaleOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/TranslateOverlay.jsx
  src/app/ui/widgets/Purifier/Purifier.jsx
  src/app/ui/widgets/styles.styl
Labels: Type: Style

#1529 Style: Change translateOverlay style
  src/app/styles/global-border.styl
  src/app/ui/widgets/PrintingVisualizer/Overlay/TranslateOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/styles.styl
Labels: Type: Style

#1541 Fix: Fix submodule permission deny
  .gitmodules
Labels: Type: Fix

#1540 Fix: Select dropdown filter unavailable
  src/app/ui/components/Select/ChangedReactSelect.jsx
  src/app/ui/views/ProfileManager/ConfigValueBox.jsx
  src/app/ui/views/ProfileManager/SettingItem.jsx
Labels: Type: Fix

#1539 Fix: Fix eslint error and bump eslint version
  .eslintrc.js
  package.json
  src/app/ui/pages/HomePage/QuickStart.jsx
Labels: Type: Fix

#1532 Improvement: Refactor scale to fit with rotate
  src/app/constants/copy.js
  src/app/flux/operation-history/ScaleToFitWithRotateOperation3D.ts
  src/app/flux/printing/index.js
  src/app/lib/manager/ProgressManager.js
  src/app/lib/manager/workerManager.ts
  src/app/models/ModelGroup.js
  src/app/models/ThreeModel.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/components/SMCanvas/TransformControls.js
  src/app/ui/widgets/PrintingVisualizer/Overlay/ScaleOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
  src/app/workers/scaleToFitWithRotate.js
Labels: Type: Improvement

#1536 Fix: Update 3d camera scale & translate bug
  src/app/ui/components/SMCanvas/Canvas.jsx
  src/app/ui/components/SMCanvas/Controls.jsx
Labels: Type: Fix, Category: 3DP

#1535 Improvement: Update CNC toolpath params
  gulp/tasks/i18next.js
  resources/CuraEngine/Config/cnc/a150_standard/tool.default_CVbit.def.json
  resources/CuraEngine/Config/cnc/a150_standard/tool.default_FEM1.5.def.json
  resources/CuraEngine/Config/cnc/a150_standard/tool.default_FEM3.175.def.json
  resources/CuraEngine/Config/cnc/a150_standard/tool.default_MBEM.def.json
  resources/CuraEngine/Config/cnc/a150_standard/tool.default_SGVbit.def.json
  resources/CuraEngine/Config/cnc/a150_standard/tool.rAcrylic_FEM1.5.def.json
  resources/CuraEngine/Config/cnc/a150_standard/tool.rEpoxy_SGVbit.def.json
  resources/CuraEngine/Config/cnc/a250_standard/tool.default_CVbit.def.json
  resources/CuraEngine/Config/cnc/a250_standard/tool.default_FEM1.5.def.json
  resources/CuraEngine/Config/cnc/a250_standard/tool.default_FEM3.175.def.json
  resources/CuraEngine/Config/cnc/a250_standard/tool.default_MBEM.def.json
  resources/CuraEngine/Config/cnc/a250_standard/tool.default_SGVbit.def.json
  resources/CuraEngine/Config/cnc/a250_standard/tool.rAcrylic_FEM1.5.def.json
  resources/CuraEngine/Config/cnc/a250_standard/tool.rEpoxy_SGVbit.def.json
  resources/CuraEngine/Config/cnc/a350_standard/tool.default_CVbit.def.json
  resources/CuraEngine/Config/cnc/a350_standard/tool.default_FEM1.5.def.json
  resources/CuraEngine/Config/cnc/a350_standard/tool.default_FEM3.175.def.json
  resources/CuraEngine/Config/cnc/a350_standard/tool.default_MBEM.def.json
  resources/CuraEngine/Config/cnc/a350_standard/tool.default_SGVbit.def.json
  resources/CuraEngine/Config/cnc/a350_standard/tool.rAcrylic_FEM1.5.def.json
  resources/CuraEngine/Config/cnc/a350_standard/tool.rEpoxy_SGVbit.def.json
  resources/CuraEngine/Config/cnc/active.def.json
  resources/CuraEngine/Config/cnc/original_standard/tool.default_CVbit.def.json
  resources/CuraEngine/Config/cnc/original_standard/tool.default_FEM1.5.def.json
  resources/CuraEngine/Config/cnc/original_standard/tool.default_FEM3.175.def.json
  resources/CuraEngine/Config/cnc/original_standard/tool.default_MBEM.def.json
  resources/CuraEngine/Config/cnc/original_standard/tool.default_SGVbit.def.json
  resources/CuraEngine/Config/cnc/original_standard/tool.rAcrylic_FEM1.5.def.json
  resources/CuraEngine/Config/cnc/original_standard/tool.rEpoxy_SGVbit.def.json
  resources/CuraEngine/Config/cnc/snapmaker2.def.json
  src/app/constants/index.js
  src/app/resources/i18n/en/resource.json
  src/app/resources/images/cnc/tool-type-ball.jpg
  src/app/resources/images/cnc/tool-type-flat.jpg
  src/app/resources/images/cnc/tool-type-vbit.jpg
  src/app/ui/views/CncToolManager/CncToolManager.jsx
  src/app/ui/views/ProfileManager/ConfigValueBox.jsx
  src/app/ui/views/ProfileManager/SettingItem.jsx
  src/app/ui/views/ProfileManager/index.jsx
  src/app/ui/views/ToolPathConfigurations/ToolPathConfigurations.jsx
  src/app/ui/views/ToolPathConfigurations/cnc/CncParameters.jsx
  src/server/lib/profile/cnc-uniform-profile.js
Labels: Type: Improvement, Category: CNC

#1534 Feature: Add translate and scale control input
  src/app/constants/index.js
  src/app/styles/global-border.styl
  src/app/ui/components/SMCanvas/Canvas.jsx
  src/app/ui/components/SMCanvas/TransformControls.js
  src/app/ui/pages/Printing.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/RotateOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/ScaleOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/TranslateOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingVisualizer/index.jsx
Labels: Type: Feature

#1538 Feature: Add fitViewIn in context menu 3dp
  src/app/models/ModelGroup.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/styles/global-border.styl
  src/app/ui/components/SMCanvas/Canvas.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/SupportOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerBottomLeft.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
Labels: Type: Feature, Category: 3DP

#1505 Improvement: Improvement svg curve draw
  package.json
  src/app/constants/index.js
  src/app/flux/cnc/index.js
  src/app/flux/editor/index.js
  src/app/flux/laser/index.js
  src/app/flux/operation-history/AddOperation2D.js
  src/app/flux/operation-history/DeleteOperation2D.js
  src/app/flux/operation-history/DrawDelete.ts
  src/app/flux/operation-history/DrawLine.ts
  src/app/flux/operation-history/DrawStart.ts
  src/app/flux/operation-history/DrawTransform.ts
  src/app/flux/operation-history/DrawTransformComplete.ts
  src/app/flux/operation-history/OperationHistory.js
  src/app/lib/manager/workerManager.ts
  src/app/lib/shortcut/constants.js
  src/app/models/ModelGroup.js
  src/app/models/SVGActionsFactory.js
  src/app/models/SvgModel.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/styles/global-edge-distance.styl
  src/app/styles/global-layout.styl
  src/app/styles/global-var.styl
  src/app/ui/SVGEditor/SVGCanvas.jsx
  src/app/ui/SVGEditor/SVGEditor.jsx
  src/app/ui/SVGEditor/SVGLeftBar.jsx
  src/app/ui/SVGEditor/SVGSelector.ts
  src/app/ui/SVGEditor/index.styl
  src/app/ui/SVGEditor/svg-content/DrawGroup/CursorGroup.ts
  src/app/ui/SVGEditor/svg-content/DrawGroup/DrawGroup.ts
  src/app/ui/SVGEditor/svg-content/DrawGroup/Line.ts
  src/app/ui/SVGEditor/svg-content/DrawGroup/OperationGroup.ts
  src/app/ui/SVGEditor/svg-content/DrawGroup/Point.ts
  src/app/ui/SVGEditor/svg-content/DrawGroup/constants.ts
  src/app/ui/SVGEditor/svg-content/DrawGroup/index.ts
  src/app/ui/SVGEditor/svg-content/DrawGroup/types.ts
  src/app/ui/SVGEditor/svg-content/OperatorPoints.js
  src/app/ui/SVGEditor/svg-content/SVGContentGroup.js
  src/app/ui/pages/CncLaserShared/MainToolBar.jsx
  src/app/ui/widgets/CNCVisualizer/Visualizer.jsx
  src/app/ui/widgets/CncLaserShared/TransformationSection.jsx
  src/app/ui/widgets/CncLaserShared/VisualizerBottomLeft.jsx
  src/app/ui/widgets/LaserVisualizer/Visualizer.jsx
  src/app/workers/boxSelect.ts
  src/shared/lib/utils.js
Labels: Type: Improvement

#1544 Improvement: Improve gcode preview
  package.json
  src/app/constants/copy.js
  src/app/constants/index.js
  src/app/flux/printing/index.js
  src/app/lib/gcode-viewer/LinePoint.ts
  src/app/lib/gcode-viewer/LineTubeGeometry.ts
  src/app/lib/gcode-viewer/SegmentColorizer.ts
  src/app/lib/gcode-viewer/constants.js
  src/app/lib/gcode-viewer/index.ts
  src/app/lib/gcode-viewer/parser.ts
  src/app/lib/manager/ProgressManager.js
  src/app/models/ModelGroup.js
  src/app/models/ThreeModel.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/widgets/PrintingVisualizer/ModeToggleBtn.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/ScaleOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerPreviewControl.jsx
  src/app/ui/widgets/PrintingVisualizer/styles.styl
  src/app/workers/GcodeToBufferGeometry/gcodeBufferGeometryToObj3d.js
  src/app/workers/GcodeToBufferGeometry/index.js
  src/app/workers/ShaderMaterial/print3d-shader-meterial.js
  src/app/workers/gcodeToBufferGeometry.js
Labels: Type: Improvement

#1547 Fix: Fix fitviewin animation and gcode view slider bug
  src/app/flux/printing/index.js
  src/app/ui/components/SMCanvas/Canvas.jsx
  src/app/ui/components/Slider/SliderWrapper.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerPreviewControl.jsx
Labels: Type: Fix

#1566 Fix: Fix tween error for fit view in
  src/app/ui/components/SMCanvas/Canvas.jsx
Labels: Type: Fix

#1565 Fix : Fix UI 4.3.0
  src/app/styles/global-edge-distance.styl
  src/app/ui/components/Steps/index.js
  src/app/ui/pages/HomePage/styles.styl
  src/app/ui/views/ProfileManager/SettingItem.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/EditSupportOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/ExtruderOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/MirrorOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/RotateOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/ScaleOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/SupportOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/TranslateOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/styles.styl
  src/main.js
Labels: Type: Fix

#1543 Fix: Cancel heartbeat after browser window reload
  src/app/flux/machine/Server.js
  src/app/ui/App.jsx
  src/app/ui/widgets/Connection/WifiConnection.jsx
  src/server/services/socket/ConnectionManager.js
  src/server/services/socket/socket-http.ts
Labels: Type: Fix

#1561 Fix: Fix 3D printing thumbnail size and other bugs
  src/app/flux/editor/index.js
  src/app/flux/machine/Server.js
  src/app/flux/machine/index.js
  src/app/flux/operation-history/ScaleToFitWithRotateOperation3D.ts
  src/app/flux/printing/index.js
  src/app/styles/global-background.styl
  src/app/styles/global-layout.styl
  src/app/styles/global-var.styl
  src/app/ui/components/Buttons/styles.styl
  src/app/ui/components/Select/ChangedReactSelect.jsx
  src/app/ui/views/ProfileManager/SettingItem.jsx
  src/app/ui/views/ToolPathConfigurations/ToolPathFastConfigurations.jsx
  src/app/ui/widgets/Control/Control.jsx
  src/app/ui/widgets/Control/ControlPanel.jsx
  src/app/ui/widgets/Control/DisplayPanel.jsx
  src/app/ui/widgets/Control/JogDistance.jsx
  src/app/ui/widgets/Control/JogPad.jsx
  src/app/ui/widgets/Control/MotionButtonGroup.jsx
  src/app/ui/widgets/Marlin/Laser.jsx
  src/app/ui/widgets/Marlin/Printing.jsx
  src/app/ui/widgets/PrintingMaterial/MaterialWithColor.jsx
  src/app/ui/widgets/PrintingOutput/Thumbnail.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/SupportOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/TranslateOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerBottomLeft.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
  src/app/ui/widgets/WifiTransport/WifiTransport.jsx
  src/app/ui/widgets/WifiTransport/index.styl
  src/server/lib/profile/cnc-uniform-profile.js
  src/server/services/socket/ConnectionManager.js
  src/server/services/socket/socket-http.ts
Labels: Type: Fix

#1564 Fix: Fix svg releated bugs
  src/app/constants/index.js
  src/app/flux/editor/actions-base.js
  src/app/flux/editor/index.js
  src/app/flux/printing/index.js
  src/app/models/ModelGroup.js
  src/app/models/SVGActionsFactory.js
  src/app/models/SvgModel.js
  src/app/resources/i18n/zh-cn/resource.json
  src/app/styles/global-edge-distance.styl
  src/app/toolpaths/ToolPath.js
  src/app/ui/SVGEditor/SVGCanvas.jsx
  src/app/ui/SVGEditor/SVGEditor.jsx
  src/app/ui/SVGEditor/svg-content/OperatorPoints.js
  src/app/ui/SVGEditor/svg-content/SVGContentGroup.js
  src/app/ui/components/SMCanvas/TransformControls.js
  src/app/ui/components/Slider/styles.styl
  src/app/ui/widgets/CNCVisualizer/Visualizer.jsx
  src/app/ui/widgets/CncLaserShared/TransformationSection.jsx
  src/app/ui/widgets/LaserVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/ScaleOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/TranslateOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerPopup.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerPreviewControl.jsx
  src/app/ui/widgets/PrintingVisualizer/styles.styl
  src/app/workers/boxSelect.ts
  src/server/DataStorage.js
  src/server/services/api/api-image.js
  src/server/services/socket/socket-serial.ts
  src/server/slicer/slice.js
Labels: Type: Fix

#1569 Fix: Group state restore & gen-gcode button disabled after project loaded
  src/app/flux/printing/index.js
  src/app/flux/project/index.js
  src/app/models/ModelGroup.js
  src/app/ui/widgets/PrintingOutput/Output.jsx
Labels: Type: Fix

#1572 Refactor: Update i18n
  src/app/constants/copy.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
Labels: Type: Refactor

#1571 Fix: Fix rotate by plane stucked
  src/app/three-extensions/ThreeUtils.js
Labels: Type: Fix

#1580 Fix: Fix out of memory when packing on macOS
  package.json
Labels: Type: Fix
