Repository Snapmaker/Luban, pull requests merged in 2022-02, with the labels that each got.

#1442 Refactor: Change autoupdater modal to custom modal
  src/app/lib/uni-api.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/layouts/AppLayout.jsx
  src/app/ui/pages/Settings/SoftwareUpdate/DownloadUpdate.jsx
  src/main.js
Labels: Type: Improvement

#1439 Improvement: Improve ColorSelector blur interaction
  src/app/ui/components/Popover/index.jsx
  src/app/ui/components/Popover/style.styl
  src/app/ui/views/ProfileManager/SettingItem.jsx
Labels: Type: Improvement

#1416 Improvement: Upgrade electron from 8.x.y to 11.5.0 and improve to render multi toolpath in parallel using workerpool
  package.json
  src/app/flux/editor/actions-process.js
  src/app/flux/editor/index.js
  src/app/lib/check-name.js
  src/app/lib/controller.js
  src/app/toolpaths/ToolPath.js
  src/app/toolpaths/ToolPathGroup.js
  src/app/ui/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx
  src/app/workers/ToolpathRenderer.worker.js
  src/main.js
  src/package.json
  src/server/lib/SocketManager/index.js
  src/server/services/task-manager/TaskManager.js
  src/server/services/task-manager/generateToolPath.js
  src/server/services/task-manager/index.js
  src/server/slicer/call-engine.js
  webpack.config.app.development.js
  webpack.config.app.production.js
Labels: Type: Improvement

#1451 Build: Change electron-rebuild version to fix rebuilding failure on Windows
  package.json
  src/app/ui/views/ToolPathConfigurations/ToolPathFastConfigurations.jsx
  src/app/ui/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx
Labels: Type: Fix, Type: Build

#1437 Fix: Fix 3dp profile category operation support bugs
  resources/CuraEngine/Config/cnc/snapmaker2.def.json
  resources/CuraEngine/Config/laser/snapmaker2.def.json
  src/app/constants/index.js
  src/app/flux/cnc/index.js
  src/app/flux/editor/actions-process.js
  src/app/flux/laser/index.js
  src/app/flux/printing/index.js
  src/app/lib/uni-api.js
  src/app/ui/views/CncToolManager/CncToolManager.jsx
  src/app/ui/views/DefinitionCreator.jsx
  src/app/ui/views/LaserPresentManager/LaserPresentManager.jsx
  src/app/ui/views/PrintingManager/PrintingManager.jsx
  src/app/ui/views/ProfileManager/index.jsx
  src/server/controllers/Marlin/ScreenController.js
  src/server/services/api/api-profile-definitions.js
  src/server/services/task-manager/generateGcode.js
  src/server/slicer/definition.js
Labels: Type: Fix

#1453 Fix: Fix to change virtual-environment to fix Windows packaging on github workflow
  .github/workflows/build-on-create-release.yml
  package.json
Labels: Type: Fix

#1444 Improvment: Improve thread poll
  .babelrc
  build/pkgsync.js
  gulp/tasks/server.js
  gulpfile.babel.js
  package.json
  src/app/flux/editor/index.js
  src/app/flux/machine/Server.js
  src/app/flux/printing/index.js
  src/app/flux/workspace/index.js
  src/app/lib/manager/Pool.worker.js
  src/app/lib/manager/WorkerManager.ts
  src/app/lib/manager/workerManager.ts
  src/app/models/ThreeModel.js
  src/app/ui/App.jsx
  src/app/ui/widgets/CncLaserOutput/Output.jsx
  src/app/workers/GcodeToArraybufferGeometry.worker.js
  src/app/workers/GcodeToBufferGeometry.worker.js
  src/app/workers/LoadModel.worker.js
  src/app/workers/evaluateSupportArea.ts
  src/app/workers/gcodeToArraybufferGeometry.js
  src/app/workers/gcodeToBufferGeometry.js
  src/app/workers/heartBeat.ts
  src/app/workers/loadModel.js
  src/app/workers/toolpathRenderer.js
  src/app/workers/utils/sendMessage.ts
  src/package.json
  src/server/lib/MeshProcess/MeshProcess.js
  src/server/lib/MeshProcess/STLToSvgStack.js
  src/server/lib/SocketManager/index.ts
  src/server/lib/ToolPathGenerator/MeshToolPath/CncMeshToolPathGenerator.js
  src/server/lib/editor/image-process.js
  src/server/lib/global.js
  src/server/lib/logger.ts
  src/server/lib/svg-convert.js
  src/server/services/api/api-image.js
  src/server/services/index.js
  src/server/services/task-manager/Pool.worker.js
  src/server/services/task-manager/Task.ts
  src/server/services/task-manager/TaskManager.js
  src/server/services/task-manager/TaskManager.ts
  src/server/services/task-manager/cutModel.js
  src/server/services/task-manager/generateToolPath.js
  src/server/services/task-manager/index.js
  src/server/services/task-manager/index.ts
  src/server/services/task-manager/processImage.js
  src/server/services/task-manager/utils/sendMessage.ts
  src/server/services/task-manager/workerManager.ts
  src/server/services/task-manager/workers/cutModel.js
  src/server/services/task-manager/workers/generateGcode.js
  src/server/services/task-manager/workers/generateToolPath.js
  src/server/services/task-manager/workers/generateViewPath.js
  src/server/services/task-manager/workers/loadSize.js
  src/server/services/task-manager/workers/processImage.js
  src/server/slicer/call-engine.js
  src/shared/lib/FontManager.js
  webpack.config.server.development.js
  webpack.config.server.production.js
Labels: Type: Improvement

#1450 Improvement: Improve timing of auto-save project environment
  src/app/flux/editor/actions-process.js
  src/app/flux/editor/index.js
  src/app/flux/operation-history/SaveToolPathOperation.js
  src/app/flux/operation-history/index.js
  src/app/flux/printing/index.js
  src/app/flux/project/index.js
  src/app/lib/uni-api.js
  src/app/models/ModelGroup.js
  src/app/models/SVGActionsFactory.js
  src/app/models/ThreeBaseModel.ts
  src/app/models/ThreeGroup.ts
  src/app/models/ThreeModel.js
  src/app/toolpaths/ToolPathGroup.js
  src/app/ui/components/SvgIcon/SvgIcon.jsx
  src/app/ui/layouts/AppLayout.jsx
  src/app/ui/pages/Settings/MachineSettings/MachineSettings.jsx
  src/app/ui/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx
  src/app/ui/widgets/PrintingMaterial/Material.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
  src/server/lib/svg-convert.js
Labels: Type: Improvement

#1405 Feature: Add brandnew model support
  package.json
  src/app/constants/copy.js
  src/app/flux/operation-history/AddSupportsOperation3D.ts
  src/app/flux/operation-history/DeleteSupportsOperation3D.ts
  src/app/flux/printing/index.js
  src/app/lib/controller.js
  src/app/lib/manager/ProgressManager.js
  src/app/models/ModelGroup.js
  src/app/models/PrimeTowerModel.ts
  src/app/models/ThreeBaseModel.ts
  src/app/models/ThreeGroup.ts
  src/app/models/ThreeModel.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/styles/global-border.styl
  src/app/styles/global-edge-distance.styl
  src/app/three-extensions/ThreeUtils.js
  src/app/ui/components/SMCanvas/Controls.jsx
  src/app/ui/components/SMCanvas/TransformControls.js
  src/app/ui/widgets/PrintingVisualizer/Overlay/EditSupportOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/RotationAnalysisOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/SupportOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/styles.styl
  src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
  src/app/workers/evaluateSupportArea.ts
  src/package.json
  src/server/lib/utils.ts
  src/server/services/index.js
  src/server/services/socket/socket-slice.js
  src/server/slicer/slice.js
  src/shared/lib/STL/STLExporter.js
Labels: Type: Feature

#1454 Improvement: Delete loading window & run server in child process
  gulp/tasks/app.js
  src/DataStorage.js
  src/app/ui/App.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
  src/main.js
  src/server-cli.js
  src/server/DataStorage.js
  src/server/index.js
  src/server/webpack-dev-server.js
  webpack.config.app.development.js
Labels: Type: Improvement

#1464 Improvement: Improve to change uv texture to matcap texture
  resources/scenes/scene.json
  src/app/flux/operation-history/ScaleOperation3D.ts
  src/app/flux/printing/index.js
  src/app/three-extensions/STLLoader.js
  src/app/three-extensions/WebGLRendererWrapper.js
  src/app/ui/components/SMCanvas/Canvas.jsx
  src/app/ui/components/SMCanvas/TransformControls.js
  src/app/workers/loadModel.js
Labels: Type: Improvement

#1461 Fix: Model mirror clear support & material incorrect after editing support & model cut progress bar description
  src/app/flux/editor/index.js
  src/app/flux/printing/index.js
  src/app/lib/controller.js
  src/app/lib/manager/ProgressManager.js
  src/app/models/ModelGroup.js
  src/app/models/ThreeGroup.ts
  src/app/models/ThreeModel.js
  src/app/ui/pages/Laser.jsx
  src/app/ui/widgets/Console/Console.jsx
  src/server/services/index.js
  src/server/services/task-manager/Task.ts
  src/server/services/task-manager/TaskManager.ts
  src/shared/lib/SVGParser/AttributesParser.js
Labels: Type: Fix

#1462 Fix: CNC limit size modal
  src/app/ui/components/Cascader/styles.styl
  src/app/ui/widgets/CNCVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
Labels: Type: Fix

#1452 Feature: New arrange models method
  src/app/constants/copy.js
  src/app/flux/app-global/index.js
  src/app/flux/machine/index.js
  src/app/flux/operation-history/ArrangeOperation3D.ts
  src/app/flux/printing/index.js
  src/app/lib/manager/ProgressManager.js
  src/app/lib/manager/workerManager.ts
  src/app/models/ModelGroup.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/store/local-storage.js
  src/app/ui/components/ColorSelector/ColorSelectorWrapper.jsx
  src/app/ui/layouts/AppLayout.jsx
  src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
  src/app/workers/arrangeModels.js
  src/shared/lib/math/Line.js
  src/shared/lib/math/PolygonsUtils.js
  src/shared/lib/math/Vector2.js
  src/shared/lib/math/Vector3.js
  src/shared/lib/nesting/AngleRange.js
  src/shared/lib/nesting/GridProjection.js
  src/shared/lib/nesting/Nest.js
  src/shared/lib/nesting/index.js
Labels: Type: Feature

#1469 Refactor: Change i18n translations
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/widgets/Connection/SerialConnection.jsx
  src/app/ui/widgets/Connection/WifiConnection.jsx
Labels: Type: Refactor

#1470 Fix: Update input ui & send to device button disabled & import null object bug
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/three-extensions/OBJLoader.js
  src/app/ui/components/Select/styles.styl
  src/app/ui/widgets/PrintingMaterial/Material.jsx
  src/app/ui/widgets/PrintingMaterial/styles.styl
  src/app/ui/widgets/PrintingVisualizer/ModelLoader.js
  src/app/ui/widgets/WifiTransport/WifiTransport.jsx
  src/server/services/api/api-image.js
Labels: Type: Fix

#1471 Fix: Fix to destroy gcodeLine and add svg width&height attribute after parsing
  package-lock.json
  package.json
  src/app/flux/manager/DefinitionManager.js
  src/app/flux/printing/index.js
  src/app/ui/views/PrintingManager/PrintingManager.jsx
  src/app/ui/views/ProfileManager/index.jsx
  src/app/workers/GcodeToBufferGeometry/GcodeToBufferGeometryPrint3d.js
  src/package.json
  src/server/services/api/api-profile-definitions.js
  src/shared/lib/SVGParser/Parser.js
Labels: Type: Fix

#1475 Fix: Fix arrange model error
  src/app/flux/app-global/index.js
  src/app/flux/printing/index.js
  src/app/models/ModelGroup.js
  src/app/models/ThreeBaseModel.ts
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/layouts/AppLayout.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
  src/app/workers/arrangeModels.js
  src/shared/lib/nesting/Nest.js
  src/shared/lib/nesting/index.js
Labels: Type: Fix

#1472 Fix: Restore aligned group
  resources/scenes/scene.json
  src/app/flux/editor/index.js
  src/app/flux/operation-history/DeleteOperation3D.ts
  src/app/flux/operation-history/RotateOperation3D.ts
  src/app/flux/operation-history/UngroupOperation3D.ts
  src/app/flux/printing/index.js
  src/app/models/ModelGroup.js
  src/app/models/ThreeGroup.ts
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/three-extensions/WebGLRendererWrapper.js
  src/app/ui/components/SMCanvas/TransformControls.js
Labels: Type: Fix

#1474 Fix: Fix lost model before record
  src/app/flux/operation-history/DeleteOperation3D.ts
  src/app/flux/operation-history/MoveOperation3D.ts
  src/app/flux/printing/index.js
  src/app/models/ModelGroup.js
  src/app/models/ThreeGroup.ts
Labels: Type: Fix
