Repository Snapmaker/Luban, pull requests merged in 2022-08, with the labels that each got.

#1667 Fix: Fix v4.4.0 ux bug
  src/app/flux/printing/index.js
  src/app/styles/global-font.styl
  src/app/ui/components/Dropdown/dropdown.jsx
  src/app/ui/components/Dropdown/dropdown.styl
  src/app/ui/components/Input/NumberInput.jsx
  src/app/ui/layouts/styles/project.styl
  src/app/ui/pages/MachineMaterialSettings/addMaterialModel.jsx
  src/app/ui/pages/MachineMaterialSettings/index.jsx
  src/app/ui/pages/MachineMaterialSettings/machineSettings.jsx
  src/app/ui/pages/MachineMaterialSettings/materialSettings.jsx
  src/app/ui/pages/MachineMaterialSettings/styles.styl
  src/app/ui/views/DefinitionCreator.jsx
  src/app/ui/views/ProfileManager/ConfigValueBox.jsx
  src/app/ui/views/ProfileManager/index.jsx
  src/app/ui/views/ProfileManager/styles.styl
  src/app/ui/widgets/PrintingConfigurations/Configurations.jsx
Labels: Type: Fix, v4.4.0

#1633 Build: Publish to Windows Package Managar (WinGet)
  .github/workflows/winget.yml
Labels: Type: Build

#1676 Fix: Fix version bug
  package.json
  src/app/constants/index.ts
  src/app/flux/cnc/index.js
  src/app/flux/laser/index.js
  src/app/flux/machine/Server.js
  src/app/flux/operation-history/MoveOperation3D.ts
  src/app/flux/printing/index.js
  src/app/flux/project/index.js
  src/app/lib/uni-api.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/styles/global-layout.styl
  src/app/ui/components/Input/NumberInput.jsx
  src/app/ui/layouts/MainToolBar.jsx
  src/app/ui/pages/Cnc.jsx
  src/app/ui/pages/CncLaserShared/MainToolBar.jsx
  src/app/ui/pages/Laser.jsx
  src/app/ui/pages/MachineMaterialSettings/addMaterialModel.jsx
  src/app/ui/pages/MachineMaterialSettings/index.jsx
  src/app/ui/pages/MachineMaterialSettings/machineSettings.jsx
  src/app/ui/pages/MachineMaterialSettings/materialSettings.jsx
  src/app/ui/pages/Printing.jsx
  src/app/ui/views/PrintingManager/PrintingManager.jsx
  src/app/ui/views/ProfileManager/ConfigValueBox.jsx
  src/app/ui/widgets/Connection/WifiConnection.jsx
  src/app/ui/widgets/Console/Console.jsx
  src/app/ui/widgets/PrintingMaterial/styles.styl
  src/app/ui/widgets/PrintingVisualizer/Overlay/SimplifyOverlay.jsx
  src/app/ui/widgets/WifiTransport/PreviewToRunJobModal.jsx
  src/server/services/socket/ConnectionManager.js
  src/server/services/socket/sacp/Business.ts
  src/server/services/socket/sacp/SACP-BASE.ts
  src/server/services/socket/sacp/SACP-TCP.ts
  src/server/services/socket/socket-http.ts
  src/server/slicer/slice.js
Labels: Type: Fix

#1683 Fix: Fix v4.4.0 copywriting
  src/app/api/TaskQueue.ts
  src/app/api/index.js
  src/app/constants/copy.js
  src/app/flux/app-global/index.js
  src/app/flux/printing/index.js
  src/app/lib/controller.js
  src/app/models/ClipperModel.ts
  src/app/models/ModelGroup.ts
  src/app/models/SVGActionsFactory.js
  src/app/models/SvgModel.ts
  src/app/models/ThreeModel.ts
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/pages/Settings/General/General.jsx
  src/app/ui/views/PrintingManager/PrintingManager.jsx
  src/app/ui/views/ProfileManager/ConfigValueBox.jsx
  src/app/ui/widgets/Connection/Connection.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerClippingControl.jsx
  src/app/ui/widgets/WifiTransport/GCodeParams.jsx
  src/app/ui/widgets/WifiTransport/LaserStartModal.jsx
  src/server/lib/ScheduledTasks/index.ts
  src/server/services/index.js
  src/server/services/socket/ConnectionManager.js
  src/server/services/socket/WifiServerManager.js
  src/server/services/socket/sacp/SACP-TCP.ts
  src/server/services/socket/socket-http.ts
  src/server/services/socket/socket-serial.ts
  src/server/services/task-manager/workers/generateToolPath.js
  src/server/services/task-manager/workers/heartBeat.ts
  src/server/slicer/definition.js
Labels: Type: Fix

#1687 Fix: Fix svg text tag parser
  src/app/ui/components/Select/ChangedReactSelect.jsx
  src/app/ui/views/ProfileManager/SettingItem.jsx
  src/app/ui/views/ProfileManager/images/adhesion_type_brim.svg
  src/app/ui/views/ProfileManager/images/adhesion_type_none.svg
  src/app/ui/views/ProfileManager/images/adhesion_type_raft.svg
  src/app/ui/views/ProfileManager/images/adhesion_type_skirt.svg
  src/app/ui/views/ProfileManager/images/infill_pattern_concentric.svg
  src/app/ui/views/ProfileManager/images/infill_pattern_cross.svg
  src/app/ui/views/ProfileManager/images/infill_pattern_cross_3d.svg
  src/app/ui/views/ProfileManager/images/infill_pattern_cubic.svg
  src/app/ui/views/ProfileManager/images/infill_pattern_cubicsubdivn.svg
  src/app/ui/views/ProfileManager/images/infill_pattern_grid.svg
  src/app/ui/views/ProfileManager/images/infill_pattern_gyroid.svg
  src/app/ui/views/ProfileManager/images/infill_pattern_lines.svg
  src/app/ui/views/ProfileManager/images/infill_pattern_quarter_cubic.svg
  src/app/ui/views/ProfileManager/images/infill_pattern_tetrahedral.svg
  src/app/ui/views/ProfileManager/images/infill_pattern_triangles.svg
  src/app/ui/views/ProfileManager/images/infill_pattern_trihexagon.svg
  src/app/ui/views/ProfileManager/images/infill_pattern_zigzag.svg
  src/app/ui/views/ProfileManager/images/model_structure_type_normal.svg
  src/app/ui/views/ProfileManager/images/model_structure_type_vase.svg
  src/app/ui/views/ProfileManager/images/support_pattern_concentric.svg
  src/app/ui/views/ProfileManager/images/support_pattern_cross.svg
  src/app/ui/views/ProfileManager/images/support_pattern_grid.svg
  src/app/ui/views/ProfileManager/images/support_pattern_gyroid.svg
  src/app/ui/views/ProfileManager/images/support_pattern_lines.svg
  src/app/ui/views/ProfileManager/images/support_pattern_triangles.svg
  src/app/ui/views/ProfileManager/images/support_pattern_zigzag.svg
  src/app/ui/views/ProfileManager/images/support_roof_pattern_concentric.svg
  src/app/ui/views/ProfileManager/images/support_roof_pattern_grid.svg
  src/app/ui/views/ProfileManager/images/support_roof_pattern_lines.svg
  src/app/ui/views/ProfileManager/images/support_roof_pattern_triangles.svg
  src/app/ui/views/ProfileManager/images/support_roof_pattern_zigzag.svg
  src/app/ui/views/ProfileManager/images/support_type_buildplate.svg
  src/app/ui/views/ProfileManager/images/support_type_everywhere.svg
  src/app/ui/views/ProfileManager/images/z_seam_type_back.svg
  src/app/ui/views/ProfileManager/images/z_seam_type_random.svg
  src/app/ui/views/ProfileManager/images/z_seam_type_sharpest_corner.svg
  src/app/ui/views/ProfileManager/images/z_seam_type_shortest.svg
  src/app/ui/views/ProfileManager/styles.styl
  src/shared/lib/SVGParser/TextParser.js
Labels: Type: Fix

#1695 Improvement: Improve to add spin icon for profile loading
  src/app/styles/global-layout.styl
  src/app/styles/global-var.styl
  src/app/styles/sm-flex.styl
  src/app/ui/layouts/MainToolBar.jsx
  src/app/ui/layouts/Widget/index.jsx
  src/app/ui/pages/Printing.jsx
  src/app/ui/views/DefinitionCreator.jsx
  src/app/ui/views/ProfileManager/index.jsx
  src/app/ui/widgets/PrintingConfigurations/Configurations.jsx
Labels: Type: Improvement

#1697 Improvement: Update i18n translate
  src/app/resources/i18n/zh-cn/resource.json
Labels: v4.4.0

#1699 Fix: Fix profile overrided with left extruder
  src/app/flux/manager/DefinitionManager.js
Labels: Type: Fix

#1701 Fix: Fix material profile bug
  .github/workflows/winget.yml
  src/app/flux/manager/DefinitionManager.js
  src/app/flux/printing/index.js
  src/server/services/api/api-profile-definitions.js
  src/server/slicer/definition.js
Labels: Type: Fix, v4.4.0

#1677 Improvement: Improvement auto updater
  .github/workflows/build-on-create-release.yml
  package.json
  src/app/ui/layouts/AppLayout.jsx
  src/app/ui/pages/Settings/SoftwareUpdate/DownloadUpdate.jsx
  src/main.js
  src/package.json
Labels: v4.4.0

#1702 Improvement: Update i18n translation for Ukrainian
  src/app/resources/i18n/uk/resource.json
Labels: Type: Improvement, v4.4.0
