Repository Snapmaker/Luban, pull requests merged in 2022-03, with the labels that each got.

#1486 Fix: Fix support overhang angle in 3D printing
  src/app/models/ModelGroup.js
Labels: Type: Fix

#1482 Improvement: Change 3dp printable area three objects
  src/app/ui/widgets/PrintingVisualizer/PrintableCube.jsx
Labels: Type: Feature, Type: Improvement

#1497 Fix: Fix some case of dxf spline parsing
  src/shared/lib/DXFParser/Parser.js
  src/shared/lib/DXFParser/bSpline.js
  src/shared/lib/DXFParser/round10.js
Labels: Type: Fix

#1488 Fix: 3dp gcode temperature invalid
  src/app/flux/printing/index.js
Labels: Type: Fix

#1494 Fix: Fix arrange models error
  src/app/flux/printing/index.js
  src/app/models/ModelGroup.js
  src/app/workers/arrangeModels.js
  src/shared/lib/nesting/Nest.js
Labels: Type: Fix

#1500 Fix: Fix profile manager translation error
  src/app/constants/copy.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
Labels: Type: Fix

#1501 Fix: Fix Laser & CNC delete object error
  src/app/models/ModelGroup.js
  src/app/ui/widgets/PrintingVisualizer/Overlay/SupportOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/Overlay/TranslationOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
Labels: Type: Fix

#1511 Refactor: Unify log format & add error catch on server side
  src/server/DataStorage.js
  src/server/app.js
  src/server/config/settings.base.js
  src/server/services/api/api-file.js
  src/server/services/api/api-image.js
  src/server/services/api/api-profile-definitions.js
  src/server/services/api/api-svg.js
  src/server/services/api/api-users.js
  src/server/services/api/api-utils.js
  src/server/services/index.js
  src/server/services/task-manager/TaskManager.ts
  src/server/slicer/definition.js
  src/server/slicer/slice.js
Labels: Type: Refactor

#1521 Fix: Fix Windows package build by installing VC++ runtime
  .github/workflows/build-on-create-release.yml
Labels: Type: Fix

#1493 Refactor: Refactor to change machine connection code
  src/app/constants/index.js
  src/app/flux/cnc/index.js
  src/app/flux/develop-tools/index.js
  src/app/flux/editor/index.js
  src/app/flux/index.js
  src/app/flux/laser/index.js
  src/app/flux/machine/Server.js
  src/app/flux/machine/action-connect.js
  src/app/flux/machine/action-discover.js
  src/app/flux/machine/index.js
  src/app/flux/project/index.js
  src/app/flux/workspace/index.js
  src/app/index.jsx
  src/app/lib/controller.js
  src/app/lib/manager/workerManager.ts
  src/app/lib/socket-controller.js
  src/app/store.js
  src/app/ui/App.jsx
  src/app/ui/widgets/Connection/SerialConnection.jsx
  src/app/ui/widgets/Connection/WifiConnection.jsx
  src/app/ui/widgets/Console/Console.jsx
  src/app/ui/widgets/Control/Control.jsx
  src/app/ui/widgets/Enclosure/Enclosure.jsx
  src/app/ui/widgets/Enclosure/EnclosureDisplay.jsx
  src/app/ui/widgets/GCode/GCode.jsx
  src/app/ui/widgets/LaserSetBackground/PrintSquareTrace/index.jsx
  src/app/ui/widgets/LaserTestFocus/TestFocus.jsx
  src/app/ui/widgets/Macro/Macro.jsx
  src/app/ui/widgets/Marlin/Laser.jsx
  src/app/ui/widgets/Marlin/Printing.jsx
  src/app/ui/widgets/Marlin/WorkSpeed.jsx
  src/app/ui/widgets/Purifier/Purifier.jsx
  src/app/ui/widgets/WifiTransport/WifiTransport.jsx
  src/app/ui/widgets/WorkingProgress/WorkingProgress.jsx
  src/app/ui/widgets/WorkspaceVisualizer/Visualizer.jsx
  src/server/constants/index.js
  src/server/controllers/Marlin/MarlinController.js
  src/server/controllers/Marlin/ScreenController.js
  src/server/controllers/index.js
  src/server/index.js
  src/server/lib/SocketManager/index.ts
  src/server/lib/contants-utils.js
  src/server/services/api/api-file.js
  src/server/services/index.js
  src/server/services/socket/ConnectionManager.js
  src/server/services/socket/WifiServerManager.js
  src/server/services/socket/socket-http.ts
  src/server/services/socket/socket-serial.js
  src/server/services/socket/socket-serial.ts
  src/server/services/task-manager/workerManager.ts
  src/server/services/task-manager/workers/heartBeat.ts
Labels: Type: Improvement
