Repository Snapmaker/Luban, pull requests merged in 2023-07, with the labels that each got.

#2250 Improvement: Improve Japanese translation
  src/app/resources/i18n/ja/resource.json
Labels: Category: Translations

#2246 Refactor: Refactor laser main page
  src/app/constants/coordinate.ts
  src/app/flux/cnc/index.js
  src/app/flux/editor/actions-process.js
  src/app/flux/editor/index.ts
  src/app/flux/laser/index.js
  src/app/lib/hooks/set-state.tsx
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-CN/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/toolpaths/ToolPath.js
  src/app/ui/App.tsx
  src/app/ui/SVGEditor/PrintableArea.js
  src/app/ui/SVGEditor/SVGCanvas.jsx
  src/app/ui/SVGEditor/SVGEditor.jsx
  src/app/ui/layouts/AppLayout.jsx
  src/app/ui/pages/CncLaserShared/JobTypeModal.tsx
  src/app/ui/pages/HomePage/StartProject.tsx
  src/app/ui/pages/Laser.jsx
  src/app/ui/pages/Workspace.jsx
  src/app/ui/pages/laser-main/LaserMainPage.tsx
  src/app/ui/pages/laser-main/StarterGuide.tsx
  src/app/ui/pages/laser-main/index.ts
  src/app/ui/pages/laser-main/modals/JobSetupModal.tsx
  src/app/ui/pages/laser-main/modals/ProjectOversizeMessage.tsx
  src/app/ui/widgets/JobType/JobType.tsx
  src/app/ui/widgets/JobType/JobTypeState.ts
  src/app/ui/widgets/JobType/index.tsx
  src/app/ui/widgets/LaserVisualizer/Visualizer.jsx
  src/server/services/task-manager/TaskManager.ts
Labels: Type: Refactor, Type: Improvement, Category: Laser, State: Draft

#2254 Refactor: Refactor workpiece & coordinate setup view
  src/app/flux/cnc/index.ts
  src/app/flux/editor/actions-process.ts
  src/app/flux/editor/index.ts
  src/app/ui/SVGEditor/PrintableArea.ts
  src/app/ui/SVGEditor/SVGCanvas.tsx
  src/app/ui/SVGEditor/SVGEditor.tsx
  src/app/ui/SVGEditor/element-utils.ts
  src/app/ui/components/Modal/modal-small.jsx
  src/app/ui/pages/CncLaserShared/JobTypeModal.tsx
  src/app/ui/pages/CncLaserShared/MainToolBar.jsx
  src/app/ui/pages/cnc-main/modals/JobSetupView.tsx
  src/app/ui/widgets/CNCVisualizer/Visualizer.tsx
  src/app/ui/widgets/CncLaserShared/PrintablePlate/GridLine.ts
  src/app/ui/widgets/CncLaserShared/PrintablePlate/PrintablePlate.ts
  src/app/ui/widgets/CncLaserShared/PrintablePlate/index.ts
  src/app/ui/widgets/JobType/JobType.tsx
  src/app/ui/widgets/JobType/JobTypeState.ts
  src/app/ui/widgets/JobType/index.tsx
  src/app/ui/widgets/JobType/styles.styl
  src/app/ui/widgets/LaserVisualizer/Visualizer.jsx
  src/app/ui/widgets/WorkspaceVisualizer/PrintablePlate/GridLine.ts
  src/app/ui/widgets/WorkspaceVisualizer/PrintablePlate/PrintablePlate.ts
  src/app/ui/widgets/WorkspaceVisualizer/PrintablePlate/index.ts
Labels: Type: Refactor, Type: Improvement

#2257 Improvement: Add SM 2.0 dual extruder control
  src/app/constants/index.ts
  src/app/flux/workspace/index.ts
  src/app/lib/controller.ts
  src/app/ui/pages/Workspace.jsx
  src/app/ui/widgets/ConnectionToolControl/PrintToolControl.tsx
  src/server/services/machine/index.ts
  src/server/services/socket/ConnectionManager.ts
  src/server/services/socket/socket-http.ts
Labels: Category: 3DP

#2258 Fix: Fix bug for image white edge
  src/server/lib/editor/image-process.js
Labels: Type: Bug/Bug Fix

#2259 Fix: Update snapmaker-lunar version
  package-lock.json
  package.json
  src/package.json
Labels: Type: Bug/Bug Fix

#2260 Fix: Fix project presets parameter resolve
  package-lock.json
  package.json
  src/app/flux/printing/index.ts
  src/app/flux/project/index.ts
  src/package.json
  src/server/slicer/definition.js
Labels: Type: Bug/Bug Fix

#2261 Fix: Fix G-code starter code for rotary modules (serial port)
  src/server/services/socket/ConnectionManager.ts
Labels: Type: Bug/Bug Fix

#2264 Feature: Add machining functions for ray
  src/app/flux/workspace/Server.js
  src/app/flux/workspace/action-gcode.ts
  src/app/flux/workspace/index.ts
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-CN/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/SVGEditor/PrintableArea.ts
  src/app/ui/layouts/styles/workspace.styl
  src/app/ui/pages/CncLaserShared/ProjectRightView.tsx
  src/app/ui/pages/Workspace.tsx
  src/app/ui/pages/laser-workspace-ray/RayLaserWorkspace.tsx
  src/app/ui/pages/laser-workspace-ray/VisualizerOverlay.tsx
  src/app/ui/widgets/CncLaserShared/PrintablePlate/PrintablePlate.ts
  src/app/ui/widgets/RayMachiningWidget/MachiningView.tsx
  src/app/ui/widgets/RayMachiningWidget/index.tsx
  src/app/ui/widgets/RayUploadWidget/UploadView.tsx
  src/app/ui/widgets/RayUploadWidget/index.tsx
  src/app/ui/widgets/RayUploadWidget/styles.styl
  src/server/constants/index.js
  src/server/services/machine/ConnectionManager.ts
  src/server/services/machine/ProtocolDetector.ts
  src/server/services/machine/channels/SACP-TCP.ts
  src/server/services/machine/channels/SacpUdpChannel.ts
  src/server/services/machine/channels/socket-http.ts
  src/server/services/machine/sacp/Business.ts
Labels: Type: Feature

#2268 Improvement: Update sacp-sdk to 0.1.1
  package-lock.json
  package.json
  src/package.json
Labels: Type: Improvement

#2269 Feature: Add SVG and image composition
  package-lock.json
  package.json
  src/app/models/SVGActionsFactory.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-CN/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/SVGEditor/SVGCanvas.tsx
  src/app/ui/SVGEditor/SVGEditor.tsx
  src/app/ui/SVGEditor/SVGLeftBar.jsx
  src/app/ui/SVGEditor/lib/ImageSvgCompose.ts
  src/app/ui/pages/CncLaserShared/MainToolBar.jsx
  src/server/services/api/api-image.js
Labels: Type: Feature

#2271 Feature: Add control panel for ray machining
  src/app/flux/workspace/index.ts
  src/app/machines/snapmaker-ray.ts
  src/app/ui/widgets/RayMachiningWidget/ControlPanel.tsx
  src/app/ui/widgets/RayMachiningWidget/MachiningView.tsx
  src/app/ui/widgets/RayMachiningWidget/index.tsx
  src/app/ui/widgets/RayMachiningWidget/styles.styl
  src/server/services/machine/ConnectionManager.ts
  src/server/services/machine/ProtocolDetector.ts
  src/server/services/machine/channels/SACP-BASE.ts
Labels: Type: Feature

#2273 Improvement: Improve ray workspace feedback
  package-lock.json
  package.json
  src/app/ui/pages/cnc-main/CNCMainPage.tsx
  src/app/ui/pages/laser-main/LaserMainPage.tsx
  src/app/ui/pages/laser-workspace-ray/modals/MachineNetworkModal.tsx
  src/app/ui/widgets/RayMachiningWidget/ControlPanel.tsx
  src/app/ui/widgets/RayMachiningWidget/MachiningView.tsx
  src/app/ui/widgets/RayUploadWidget/UploadView.tsx
  src/package.json
  src/server/services/machine/ConnectionManager.ts
  src/server/services/machine/ProtocolDetector.ts
  src/server/services/machine/channels/SACP-BASE.ts
  src/server/services/machine/channels/SacpSerialChannel.ts
  src/server/services/machine/channels/SacpUdpChannel.ts
  src/server/services/machine/instances/ArtisanInstance.ts
  src/server/services/machine/instances/RayInstance.ts
  src/server/services/machine/sacp/Business.ts
  src/server/services/socket/machine-handlers.ts
Labels: Type: Improvement

#2274 Refactor: Remove unused code
  src/app/api/index.ts
  src/app/models/SvgModel.ts
  src/app/ui/widgets/CncLaserShared/SvgTrace/TracePreview.jsx
  src/app/ui/widgets/CncLaserShared/SvgTrace/index.jsx
  src/package.json
  src/server/lib/ProcessMode/index.js
  src/server/lib/ProcessMode/process-image.js
  src/server/lib/ToolPathGenerator/CncReliefToolPathGenerator.js
  src/server/lib/ToolPathGenerator/GcodeParser.js
  src/server/lib/ToolPathGenerator/LaserToolPathGenerator.js
  src/server/lib/ToolPathGenerator/index.js
  src/server/lib/editor/dxf-process.js
  src/server/lib/image-trace.js
  src/server/services/api/api-editor.js
  src/server/services/api/api-image.js
  src/server/services/api/api-tool-path.js
  src/server/services/api/index.js
  src/server/services/index.ts
  src/server/services/task-manager/workers/generateToolPath.ts
  src/server/services/task-manager/workers/generateViewPath.js
  src/server/services/task-manager/workers/processImage.js
Labels: Type: Refactor

#2275 Refactor: Refactor job status widget
  packages/luban-platform/index.ts
  packages/luban-platform/src/machine-state/common/WorkflowStatus.ts
  packages/luban-platform/src/machine-state/index.ts
  src/app/connection/controller-events.ts
  src/app/constants/index.ts
  src/app/flux/widget/WidgetState.js
  src/app/flux/workspace/Server.js
  src/app/flux/workspace/index.ts
  src/app/flux/workspace/state.ts
  src/app/lib/controller.ts
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-CN/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/pages/Workspace.tsx
  src/app/ui/pages/laser-workspace-ray/RayLaserWorkspace.tsx
  src/app/ui/widgets/Connection/NetworkConnection.tsx
  src/app/ui/widgets/Connection/SerialConnection.tsx
  src/app/ui/widgets/ConnectionControl/Control.tsx
  src/app/ui/widgets/ConnectionFileTransfer/FileTransferView.tsx
  src/app/ui/widgets/ConnectionToolControl/CNC.tsx
  src/app/ui/widgets/ConnectionToolControl/LaserToolControl.tsx
  src/app/ui/widgets/ConnectionToolControl/PrintToolControl.tsx
  src/app/ui/widgets/ConnectionToolControl/WorkSpeed.jsx
  src/app/ui/widgets/Console/Console.jsx
  src/app/ui/widgets/JobStatusWidget/JobStatusView.tsx
  src/app/ui/widgets/JobStatusWidget/Loading.jsx
  src/app/ui/widgets/JobStatusWidget/index.tsx
  src/app/ui/widgets/JobStatusWidget/modals/StopJobConfirmModal.tsx
  src/app/ui/widgets/LaserTestFocus/TestFocus.jsx
  src/app/ui/widgets/RayMachiningWidget/MachiningView.tsx
  src/app/ui/widgets/WorkingProgress/WorkingProgress.jsx
  src/app/ui/widgets/WorkingProgress/index.jsx
  src/app/ui/widgets/WorkspaceVisualizer/Visualizer.jsx
  src/app/ui/widgets/WorkspaceVisualizer/WorkflowControl.jsx
  src/server/constants/index.js
  src/server/controllers/Marlin/MarlinController.js
  src/server/lib/Workflow.js
  src/server/services/machine/ConnectionManager.ts
  src/server/services/machine/channels/SACP-BASE.ts
  src/server/services/machine/channels/SACP-TCP.ts
  src/server/services/socket/machine-handlers.ts
Labels: Type: Refactor

#2276 Refactor: Refactor machine discover
  src/app/connection/controller-events.ts
  src/app/flux/workspace/action-discover.ts
  src/app/lib/controller.ts
  src/app/ui/pages/laser-workspace-ray/modals/MachineNetworkModal.tsx
  src/app/ui/widgets/Connection/Connection.tsx
  src/app/ui/widgets/Connection/NetworkConnection.tsx
  src/app/ui/widgets/MachineSetting/index.jsx
  src/app/ui/widgets/RayUploadWidget/UploadView.tsx
  src/server/services/index.ts
  src/server/services/machine/ConnectionManager.ts
  src/server/services/machine/MachineDiscoverer.ts
  src/server/services/machine/NetworkedMachineFinder.ts
  src/server/services/machine/channels/SACP-TCP.ts
  src/server/services/machine/channels/socket-http.ts
  src/server/services/machine/channels/socket-serial.ts
  src/server/services/socket/WifiServerManager.js
  src/server/services/socket/discover-handlers.ts
Labels: Type: Refactor

#2277 Feature: Add export machine log modal
  src/app/connection/controller-events.ts
  src/app/constants/index.ts
  src/app/constants/machines.ts
  src/app/flux/workspace/index.ts
  src/app/machines/snapmaker-2-toolheads.ts
  src/app/machines/snapmaker-ray.ts
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-CN/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/pages/laser-workspace-ray/RayLaserWorkspace.tsx
  src/app/ui/pages/laser-workspace-ray/modals/MachineLogModal.tsx
  src/app/ui/widgets/Connection/NetworkConnection.tsx
  src/server/services/machine/ConnectionManager.ts
  src/server/services/machine/ProtocolDetector.ts
  src/server/services/machine/channels/SACP-BASE.ts
  src/server/services/machine/channels/SacpUdpChannel.ts
  src/server/services/machine/channels/socket-http.ts
  src/server/services/machine/instances/ArtisanInstance.ts
  src/server/services/machine/instances/RayInstance.ts
  src/server/services/machine/sacp/Business.ts
  src/server/services/socket/machine-handlers.ts
Labels: Type: Feature

#2279 Feature: Add variable laser power G-code generation
  package.json
  src/app/flux/editor/actions-process.ts
  src/app/models/BaseModel.ts
  src/app/models/ModelInfoUtils.ts
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-CN/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/toolpaths/ToolPath.js
  src/app/toolpaths/ToolPathGroup.js
  src/app/ui/views/ToolPathConfigurations/laser/GcodeParameters.jsx
  src/app/ui/views/ToolPathConfigurations/laser/LaserParameters.jsx
  src/app/ui/widgets/LaserParams/config/ConfigGreyscale.jsx
  src/app/workers/GcodeToBufferGeometry/ToolPathGeometryConverter.ts
  src/app/workers/ShaderMaterial/ToolpathRendererMeterial.js
  src/package.json
  src/server/lib/GcodeGenerator/GcodeGenerator.js
  src/server/lib/ProcessMode/process-image.js
  src/server/lib/jimp/jimp-plugin-greyscale.js
  src/server/services/task-manager/workers/generateToolPath.ts
Labels: Category: Laser
