Repository Snapmaker/Luban, pull requests merged in 2023-08, with the labels that each got.

#2282 Improvement: Improve machine discovery
  src/app/connection/controller-events.ts
  src/app/constants/index.ts
  src/app/flux/workspace/MachineAgent.ts
  src/app/flux/workspace/Server.js
  src/app/flux/workspace/actions-connect.ts
  src/app/flux/workspace/actions-discover.ts
  src/app/flux/workspace/index.ts
  src/app/flux/workspace/state.ts
  src/app/ui/App.tsx
  src/app/ui/widgets/Connection/Connection.tsx
  src/app/ui/widgets/Connection/NetworkConnection.tsx
  src/app/ui/widgets/Connection/SerialConnection.tsx
  src/app/ui/widgets/Connection/index.tsx
  src/server/services/machine/MachineDiscoverer.ts
  src/server/services/machine/network-discover/BroadcastMachineFinder.ts
Labels: Type: Improvement

#2284 Feature: Add firmware upgrade
  src/app/connection/controller-events.ts
  src/app/flux/workspace/index.ts
  src/app/ui/pages/Settings/Download/Download.jsx
  src/app/ui/pages/Settings/Settings.tsx
  src/app/ui/pages/laser-workspace-ray/RayLaserWorkspace.tsx
  src/app/ui/pages/laser-workspace-ray/modals/FirmwareUpgradeModal.tsx
  src/app/ui/widgets/ConnectionFileTransfer/FileTransferView.tsx
  src/app/ui/widgets/RayMachiningWidget/MachiningView.tsx
  src/app/ui/widgets/RayUploadWidget/UploadView.tsx
  src/main.js
  src/server/services/machine/ConnectionManager.ts
  src/server/services/machine/channels/Channel.ts
  src/server/services/machine/channels/SacpChannel.ts
  src/server/services/machine/channels/SacpSerialChannel.ts
  src/server/services/machine/channels/SacpTcpChannel.ts
  src/server/services/machine/channels/SacpUdpChannel.ts
  src/server/services/machine/channels/SstpHttpChannel.ts
  src/server/services/machine/sacp/Business.ts
  src/server/services/socket/discover-handlers.ts
  src/server/services/socket/machine-handlers.ts
Labels: Type: Feature

#2285 Improvement: Improve firmware upgrade modal
  src/app/connection/controller-events.ts
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-CN/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/pages/laser-workspace-ray/modals/FirmwareUpgradeModal.tsx
  src/server/services/machine/ConnectionManager.ts
  src/server/services/machine/channels/Channel.ts
  src/server/services/machine/channels/SacpChannel.ts
  src/server/services/machine/channels/SacpUdpChannel.ts
  src/server/services/machine/sacp/Business.ts
  src/server/services/socket/machine-handlers.ts
Labels: Type: Improvement

#2286 Fix: Remove thumbnail for ray machine
  .editorconfig
  package-lock.json
  src/app/connection/controller-events.ts
  src/app/constants/index.ts
  src/app/flux/workspace/MachineAgent.ts
  src/app/ui/widgets/ConnectionToolControl/WorkSpeed.jsx
  src/app/ui/widgets/RayUploadWidget/UploadView.tsx
  src/server/services/socket/machine-handlers.ts
  src/server/services/task-manager/workers/generateGcode.js
Labels: Type: Bug/Bug Fix

#2290 Fix: Fix tool path origin settings
  src/app/connection/controller-events.ts
  src/app/constants/index.ts
  src/app/flux/editor/actions-process.ts
  src/app/flux/editor/index.ts
  src/app/flux/project/index.ts
  src/app/toolpaths/ToolPath.ts
  src/app/toolpaths/ToolPathGroup.ts
  src/app/ui/pages/cnc-main/modals/JobSetupView.tsx
  src/app/ui/pages/laser-main/modals/JobSetupView.tsx
  src/app/ui/widgets/ConnectionFileTransfer/FileTransferView.tsx
  src/app/ui/widgets/ConnectionToolControl/CNC.tsx
  src/app/ui/widgets/ConnectionToolControl/LaserToolControl.tsx
  src/app/ui/widgets/ConnectionToolControl/PrintToolControl.tsx
  src/app/ui/widgets/Enclosure/Enclosure.jsx
  src/server/constants/index.js
  src/server/services/machine/ConnectionManager.ts
  src/server/services/task-manager/workers/generateToolPath.ts
Labels: Category: Laser

#2291 Improvement: Draw grids for OriginType.Object
  packages/luban-platform/index.ts
  src/app/connection/controller-events.ts
  src/app/scene2d/Workpiece2d.ts
  src/app/toolpaths/ToolPath.ts
  src/app/ui/SVGEditor/SVGCanvas.tsx
  src/app/ui/pages/laser-workspace-ray/modals/FirmwareUpgradeModal.tsx
  src/app/ui/widgets/CncLaserShared/PrintablePlate/PrintablePlate.ts
  src/app/ui/widgets/LaserVisualizer/Visualizer.jsx
  src/app/ui/widgets/RayMachiningWidget/MachiningView.tsx
  src/app/ui/widgets/RayUploadWidget/UploadView.tsx
  src/server/services/machine/ConnectionManager.ts
  src/server/services/machine/channels/Channel.ts
  src/server/services/machine/channels/SacpSerialChannel.ts
  src/server/services/machine/channels/SacpUdpChannel.ts
  src/server/services/machine/sacp/Business.ts
  src/server/services/socket/machine-handlers.ts
  src/shared/lib/FontManager.js
Labels: Type: Improvement

#2292 Fix: Fix SACP serial channel upload file
  src/server/services/machine/channels/SacpSerialChannel.ts
  src/server/services/machine/channels/SacpUdpChannel.ts
Labels: Type: Bug/Bug Fix

#2293 Improvement: Add machine metadata for workflow control
  packages/luban-platform/src/machine-definition/common/machine.ts
  packages/luban-platform/src/machine-definition/index.ts
  src/app/machines/snapmaker-ray.ts
  src/app/ui/widgets/JobStatusWidget/JobStatusView.tsx
  src/server/services/machine/channels/SacpChannel.ts
  src/server/services/machine/channels/SacpSerialChannel.ts
  src/server/services/machine/channels/SacpTcpChannel.ts
  src/server/services/machine/channels/SacpUdpChannel.ts
  src/server/services/machine/instances/RayInstance.ts
  src/server/services/machine/sacp/SacpClient.ts
Labels: Type: Improvement, Category: Laser

#2294 Refactor: Refactor SSTP channel to implement CNC interface
  src/app/connection/controller-events.ts
  src/app/ui/views/PresetModifier/styles.styl
  src/app/ui/widgets/JobStatusWidget/JobStatusView.tsx
  src/server/constants/index.js
  src/server/controllers/Marlin/MarlinController.js
  src/server/controllers/PacketManager.js
  src/server/services/api/api-case-resrouces.js
  src/server/services/api/api-image.js
  src/server/services/machine/ConnectionManager.ts
  src/server/services/machine/channels/Channel.ts
  src/server/services/machine/channels/SacpChannel.ts
  src/server/services/machine/channels/SacpUdpChannel.ts
  src/server/services/machine/channels/SstpHttpChannel.ts
  src/server/services/machine/channels/TextSerialChannel.ts
  src/server/services/machine/instances/RayInstance.ts
  src/server/services/machine/sacp/SacpClient.ts
  src/server/services/socket/machine-handlers.ts
  src/server/services/task-manager/workers/heartBeat.ts
Labels: Type: Refactor, Category: CNC

#2295 Improvement: Optimize user experience on new workspace
  src/app/flux/workspace/index.ts
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-CN/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/pages/laser-workspace-ray/RayLaserWorkspace.tsx
  src/app/ui/pages/laser-workspace-ray/modals/FirmwareUpgradeModal.tsx
  src/app/ui/pages/laser-workspace-ray/modals/MachineLogModal.tsx
  src/app/ui/pages/laser-workspace-ray/modals/MachineNetworkModal.tsx
  src/app/ui/widgets/Connection/HomeModal.tsx
  src/app/ui/widgets/Connection/SerialConnection.tsx
  src/app/ui/widgets/Connection/modals/GoHomeModal.tsx
  src/app/ui/widgets/Connection/modals/SelectMachineModal.tsx
  src/app/ui/widgets/ConnectionControl/MotionButtonGroup.jsx
  src/app/ui/widgets/JobStatusWidget/JobStatusView.tsx
  src/app/ui/widgets/RayMachiningWidget/ControlPanel.tsx
  src/app/ui/widgets/RayMachiningWidget/MachiningView.tsx
  src/app/ui/widgets/RayMachiningWidget/modals/RunBoundaryModal.tsx
  src/server/services/machine/ConnectionManager.ts
  src/server/services/machine/channels/SacpSerialChannel.ts
  src/server/services/machine/channels/SacpUdpChannel.ts
  src/server/services/machine/channels/SstpHttpChannel.ts
  src/server/services/machine/sacp/SacpClient.ts
Labels: Type: Improvement, Category: Laser, Category: Printer Control

#2296 Improvement: Update icons
  package-lock.json
  package.json
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-CN/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/pages/laser-workspace-ray/RayLaserWorkspace.tsx
  src/server/services/machine/ConnectionManager.ts
  src/server/services/machine/channels/SacpTcpChannel.ts
Labels: Type: Improvement

#2299 Fix: Fix job status panel on ray
  src/app/constants/coordinate.ts
  src/app/flux/editor/actions-process.ts
  src/app/flux/editor/index.ts
  src/app/flux/laser/index.ts
  src/app/flux/workspace/index.ts
  src/app/ui/pages/laser-main/modals/JobSetupView.tsx
  src/app/ui/widgets/RayMachiningWidget/MachiningView.tsx
  src/server/services/machine/channels/Channel.ts
  src/server/services/machine/channels/SacpChannel.ts
  src/server/services/machine/instances/RayInstance.ts
  src/server/services/machine/sacp/SacpClient.ts
  src/server/services/task-manager/workers/generateGcode.js
Labels: Category: Printer Control

#2301 Fix: Fix connection issues with ray machine
  src/app/ui/utils/useThrottle.ts
  src/app/ui/widgets/Connection/NetworkConnection.tsx
  src/server/services/machine/ConnectionManager.ts
  src/server/services/machine/channels/Channel.ts
  src/server/services/machine/channels/SacpUdpChannel.ts
  src/server/services/machine/instances/Instance.ts
  src/server/services/machine/instances/RayInstance.ts
Labels: Category: Printer Control

#2302 Chore: Change port to 8889 and baudrate to 460800
  packages/luban-platform/src/machine-definition/common/machine.ts
  src/app/constants/machines.ts
  src/app/flux/workspace/MachineAgent.ts
  src/app/flux/workspace/actions-discover.ts
  src/app/machines/snapmaker-ray.ts
  src/app/ui/widgets/Connection/SerialConnection.tsx
  src/server/constants/index.js
  src/server/controllers/Marlin/MarlinController.js
  src/server/lib/SerialConnection.js
  src/server/services/machine/ConnectionManager.ts
  src/server/services/machine/ProtocolDetector.ts
  src/server/services/machine/channels/SacpSerialChannel.ts
  src/server/services/machine/channels/SacpUdpChannel.ts
  src/server/services/machine/channels/SstpHttpChannel.ts
  src/server/services/machine/channels/TextSerialChannel.ts
Labels: Category: Printer Control

#2300 Fix: Fix bug for workspace laser preview
  package.json
  src/app/constants/index.ts
  src/app/workers/GcodeToBufferGeometry/GcodeToBufferGeometryWorkspace.js
  src/package.json
  src/server/lib/GcodeGenerator/GcodeGenerator.js
  src/server/services/task-manager/workers/generateGcode.js
  src/shared/lib/gcodeToolPath.js
Labels: Type: Bug/Bug Fix

#2306 Fix: Fix connection issues on workspace
  package-lock.json
  package.json
  src/app/connection/controller-events.ts
  src/app/constants/index.ts
  src/app/flux/editor/actions-process.ts
  src/app/flux/workspace/MachineAgent.ts
  src/app/flux/workspace/actions-connect.ts
  src/app/flux/workspace/index.ts
  src/app/flux/workspace/state.ts
  src/app/lib/controller.ts
  src/app/toolpaths/ToolPath.ts
  src/app/toolpaths/ToolPathGroup.ts
  src/app/ui/SVGEditor/SVGCanvas.tsx
  src/app/ui/pages/laser-workspace-ray/modals/MachineNetworkModal.tsx
  src/app/ui/widgets/Connection/NetworkConnection.tsx
  src/app/ui/widgets/Connection/SerialConnection.tsx
  src/package.json
  src/server/services/machine/ConnectionManager.ts
  src/server/services/machine/channels/SacpChannel.ts
  src/server/services/machine/channels/SacpTcpChannel.ts
  src/server/services/machine/channels/SstpHttpChannel.ts
  src/server/services/task-manager/workers/svgClipping.ts
Labels: Category: Printer Control

#2307 Refactor: Refactor laser visualizer to ts
  package-lock.json
  package.json
  src/app/flux/editor/actions-process.ts
  src/app/toolpaths/ToolPathGroup.ts
  src/app/ui/widgets/LaserVisualizer/Visualizer.tsx
Labels: Type: Refactor

#2308 Fix: Fix recognition issues on SM 2.0
  src/app/constants/index.ts
  src/app/flux/machine/index.js
  src/app/flux/workspace/index.ts
  src/app/machines/snapmaker-a150.ts
  src/app/machines/snapmaker-a250.ts
  src/app/machines/snapmaker-a350.ts
  src/app/ui/components/SMCanvas/Canvas.tsx
  src/app/ui/views/ToolPathConfigurations/ToolPathConfigurations.jsx
  src/app/ui/widgets/LaserVisualizer/Visualizer.tsx
  src/server/constants/index.js
  src/server/services/machine/ConnectionManager.ts
  src/server/services/machine/channels/SstpHttpChannel.ts
  src/server/services/machine/instances/SM2Instance.ts
  src/server/services/machine/instances/index.ts
  src/server/services/task-manager/workers/heartBeat.ts
Labels: Type: Bug/Bug Fix

#2309 Fix: Fix project open crash issue
  src/app/flux/cnc/index.ts
  src/app/flux/laser/index.ts
  src/app/flux/project/index.ts
  src/app/ui/pages/CncLaserShared/MainToolBar.jsx
  src/app/ui/widgets/LaserVisualizer/Visualizer.tsx
Labels: Type: Bug/Bug Fix

#2310 Fix: Fix workpiece setting & canvas scales
  package-lock.json
  package.json
  src/app/connection/controller-events.ts
  src/app/constants/index.ts
  src/app/constants/machines.ts
  src/app/flux/editor/index.ts
  src/app/flux/laser/index.ts
  src/app/flux/project/index.ts
  src/app/scene2d/Workpiece2d.ts
  src/app/ui/layouts/AppLayout.jsx
  src/app/ui/pages/laser-main/modals/JobSetupView.tsx
  src/app/ui/pages/laser-workspace-ray/RayLaserWorkspace.tsx
  src/app/ui/pages/laser-workspace-ray/modals/FirmwareUpgradeModal.tsx
  src/app/ui/pages/laser-workspace-ray/modals/MachineControlModal.tsx
  src/app/ui/pages/laser-workspace-ray/modals/MachineLogModal.tsx
  src/app/ui/pages/laser-workspace-ray/modals/MachineNetworkModal.tsx
  src/app/ui/pages/laser-workspace-ray/modals/MachineSettingsModal.tsx
  src/app/ui/widgets/Enclosure/Enclosure.tsx
  src/app/ui/widgets/Enclosure/EnclosureWidget.tsx
  src/app/ui/widgets/Enclosure/index.jsx
  src/app/ui/widgets/Enclosure/index.tsx
  src/app/ui/widgets/LaserVisualizer/Visualizer.tsx
  src/app/ui/widgets/PrintingOutput/Output.tsx
  src/app/ui/widgets/Purifier/Purifier.jsx
  src/app/ui/widgets/RaySetOriginWidget/ControlPanel.tsx
  src/app/ui/widgets/RaySetOriginWidget/SetOriginView.tsx
  src/app/ui/widgets/RaySetOriginWidget/index.tsx
  src/app/ui/widgets/RaySetOriginWidget/modals/RunBoundaryModal.tsx
  src/app/ui/widgets/RaySetOriginWidget/styles.styl
  src/server/controllers/Marlin/MarlinController.js
  src/server/lib/SerialConnection.js
  src/server/services/machine/ConnectionManager.ts
  src/server/services/machine/ProtocolDetector.ts
  src/server/services/machine/channels/Channel.ts
  src/server/services/machine/channels/SacpChannel.ts
  src/server/services/machine/channels/SacpSerialChannel.ts
  src/server/services/machine/channels/TextSerialChannel.ts
  src/server/services/machine/instances/RayInstance.ts
  src/server/services/machine/sacp/SacpClient.ts
  src/server/services/socket/machine-handlers.ts
Labels: Type: Bug/Bug Fix

#2313 Improvement: Add file upload progress
  src/app/connection/controller-events.ts
  src/app/flux/laser/index.ts
  src/app/flux/project/index.ts
  src/app/lib/controller.ts
  src/app/ui/components/Modal/modal-small.jsx
  src/app/ui/widgets/RayUploadWidget/UploadView.tsx
  src/server/services/machine/ConnectionManager.ts
  src/server/services/machine/channels/Channel.ts
  src/server/services/machine/channels/ChannelEvent.ts
  src/server/services/machine/channels/SacpChannel.ts
  src/server/services/machine/channels/SacpSerialChannel.ts
  src/server/services/machine/channels/SacpTcpChannel.ts
  src/server/services/machine/channels/SacpUdpChannel.ts
  src/server/services/machine/sacp/SacpClient.ts
Labels: Type: Improvement
