Repository Snapmaker/Luban, pull requests merged in 2023-05, with the labels that each got.

#2148 Improvement: Add smart fill selection to mesh coloring
  package-lock.json
  package.json
  packages/luban-platform/index.ts
  packages/luban-platform/src/three-extensions/common/GeometryAdjacentFaceGraph.ts
  packages/luban-platform/src/three-extensions/common/geometry/BufferGeometryUtils.ts
  src/app/flux/printing/actions-scene.ts
  src/app/flux/printing/index.ts
  src/app/models/ModelGroup.ts
  src/app/models/ThreeModel.ts
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-CN/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/views/model-operation-overlay/MeshColoringOverlay.tsx
  src/package.json
  src/types/three.d.ts
Labels: Type: Improvement, State: Draft

#2149 Improvement: Update Mesh Coloring Overlay UI
  packages/luban-platform/src/three-extensions/common/GeometryAdjacentFaceGraph.ts
  src/app/flux/printing/actions-preset.ts
  src/app/flux/printing/actions-scene.ts
  src/app/flux/printing/index.ts
  src/app/models/ModelGroup.ts
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-CN/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/styles/global-layout.styl
  src/app/styles/global-var.styl
  src/app/ui/views/model-operation-overlay/MeshColoringOverlay.tsx
Labels: Type: Improvement

#2150 Improvement: Synchronize extruder material color to mesh color attribute
  src/app/flux/printing/actions-mesh.ts
  src/app/flux/printing/actions-scene.ts
  src/app/models/ModelGroup.ts
  src/app/models/ThreeModel.ts
  src/app/three-extensions/STLLoader.js
  src/app/workers/loadModel.ts
Labels: Type: Improvement, Category: 3DP

#2151 Improvement: Optimize smart fill brush
  src/app/constants/copy.js
  src/app/flux/printing/actions-scene.ts
  src/app/lib/manager/ProgressManager.js
  src/app/models/ModelGroup.ts
  src/app/models/ThreeModel.ts
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-CN/resource.json
  src/app/resources/i18n/zh-tw/resource.json
Labels: Category: 3DP

#2153 Improvement: Optimize sphere brush experience
  src/app/models/ModelGroup.ts
  src/app/ui/views/model-operation-overlay/MeshColoringOverlay.tsx
Labels: Type: Improvement, Category: 3DP

#2144 Feature: Add online case library
  package-lock.json
  package.json
  src/app/api/index.js
  src/app/constants/downloadManager.ts
  src/app/flux/app-global/index.js
  src/app/lib/download-mananger.js
  src/app/lib/indexDB/db.ts
  src/app/lib/uni-api.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-CN/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/resources/images/user-case/quick-start.jpg
  src/app/store/local-storage.js
  src/app/ui/App.jsx
  src/app/ui/components/Modal/tileModal.jsx
  src/app/ui/layouts/AppLayout.jsx
  src/app/ui/layouts/MainToolBar.jsx
  src/app/ui/layouts/MenuItem.jsx
  src/app/ui/layouts/ProjectLayout.jsx
  src/app/ui/layouts/styles/project.styl
  src/app/ui/pages/CaseResource/index.jsx
  src/app/ui/pages/HomePage/CaseConfig.js
  src/app/ui/pages/HomePage/CaseLibrary.jsx
  src/app/ui/pages/HomePage/QuickStart.jsx
  src/app/ui/pages/HomePage/index.jsx
  src/app/ui/pages/HomePage/styles.styl
  src/app/ui/pages/PageMode.ts
  src/app/ui/pages/Settings/Download/Download.jsx
  src/app/ui/pages/Settings/Download/index.js
  src/app/ui/pages/Settings/MachineSettings/MachineSettings.jsx
  src/app/ui/pages/Settings/Settings.jsx
  src/app/ui/pages/print-main/PrintMainPage.tsx
  src/app/ui/utils/renderPopup.jsx
  src/app/ui/views/model-operation-overlay/CSDownloadManagerOverlay.jsx
  src/app/ui/views/model-operation-overlay/styles.styl
  src/main.js
  src/package.json
  src/server/services/api/api-case-resrouces.js
  src/server/services/api/api-file.js
  src/server/services/api/index.js
  src/server/services/index.js
Labels: Type: Feature

#2154 Improvement: Optimize mesh coloring enter speed
  src/app/flux/printing/actions-scene.ts
  src/app/lib/manager/ProgressManager.js
  src/app/models/ModelGroup.ts
  src/app/models/ThreeModel.ts
  src/app/three-extensions/STLLoader.js
  src/app/ui/views/model-operation-overlay/MeshColoringOverlay.tsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
  src/app/ui/widgets/PrintingVisualizer/components/SceneShortcuts.tsx
Labels: Type: Improvement, Category: 3DP

#2158 Refactor: Refactor operations and redo/undo
  package-lock.json
  package.json
  src/app/core/CompoundOperation.ts
  src/app/core/Operation.ts
  src/app/core/OperationHistory.ts
  src/app/flux/cnc/index.js
  src/app/flux/editor/actions-process.js
  src/app/flux/editor/index.js
  src/app/flux/laser/index.js
  src/app/flux/operation-history/AddOperation2D.js
  src/app/flux/operation-history/AddOperation3D.ts
  src/app/flux/operation-history/AddSupportsOperation3D.ts
  src/app/flux/operation-history/ArrangeOperation3D.ts
  src/app/flux/operation-history/DeleteOperation2D.js
  src/app/flux/operation-history/DeleteOperation3D.ts
  src/app/flux/operation-history/DeleteSupportsOperation3D.ts
  src/app/flux/operation-history/DeleteToolPathOperation.js
  src/app/flux/operation-history/DrawDelete.ts
  src/app/flux/operation-history/DrawLine.ts
  src/app/flux/operation-history/DrawStart.ts
  src/app/flux/operation-history/DrawTransform.ts
  src/app/flux/operation-history/DrawTransformComplete.ts
  src/app/flux/operation-history/GroupAlignOperation3D.ts
  src/app/flux/operation-history/GroupOperation3D.ts
  src/app/flux/operation-history/MoveOperation2D.js
  src/app/flux/operation-history/MoveOperation3D.ts
  src/app/flux/operation-history/OperationHistory.js
  src/app/flux/operation-history/Operations.js
  src/app/flux/operation-history/RotateOperation2D.js
  src/app/flux/operation-history/RotateOperation3D.ts
  src/app/flux/operation-history/SaveToolPathOperation.js
  src/app/flux/operation-history/ScaleOperation2D.js
  src/app/flux/operation-history/ScaleOperation3D.ts
  src/app/flux/operation-history/ScaleToFitWithRotateOperation3D.ts
  src/app/flux/operation-history/SimplifyModelOperation.ts
  src/app/flux/operation-history/UngroupOperation3D.ts
  src/app/flux/operation-history/VisibleOperation2D.js
  src/app/flux/operation-history/VisibleOperation3D.ts
  src/app/flux/printing/actions-scene.ts
  src/app/flux/printing/index.ts
  src/app/ui/components/Anchor/AnchorUndraggable.jsx
  src/app/ui/components/SMCanvas/Controls.jsx
  src/app/ui/layouts/AppLayout.jsx
  src/app/ui/pages/print-main/PrintMainPage.tsx
  src/app/ui/views/AppBar/AppBar.jsx
  src/app/ui/views/AppBar/AppBar.tsx
  src/app/ui/views/AppBar/appbar.styl
  src/app/ui/views/AppBar/index.ts
  src/app/ui/views/AppBar/styles.styl
Labels: Type: Refactor, State: Draft

#2163 Feature: Add retraction settings for G-code headers
  src/server/slicer/post-processor.ts
Labels: Type: Feature

#2162 Fix: Proper extruders' descriptors for Mesh painting
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-CN/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/views/model-operation-overlay/MeshColoringOverlay.tsx
Labels: Type: Improvement, Category: Translations

#2166 Refactor: Refactor and simplify model operations
  src/app/core/CompoundOperation.ts
  src/app/core/OperationHistory.ts
  src/app/flux/operation-history/GroupAlignOperation3D.ts
  src/app/flux/operation-history/GroupOperation3D.ts
  src/app/flux/operation-history/index.js
  src/app/flux/printing/actions-mesh.ts
  src/app/flux/printing/actions-scene.ts
  src/app/flux/printing/index.ts
  src/app/models/ModelGroup.ts
  src/app/models/ThreeGroup.ts
  src/app/scene/operations/AlignGroupOperation.ts
  src/app/scene/operations/GroupOperation.ts
  src/app/scene/operations/ReplaceSplittedOperation.ts
  src/app/scene/operations/VisibilityOperation.ts
  src/app/scene/operations/index.ts
  src/app/ui/pages/print-main/PrintMainPage.tsx
  src/app/ui/views/PrintingObjectList/ObjectListView.tsx
  src/app/ui/widgets/PrintingVisualizer/components/SceneContextMenu.tsx
Labels: Type: Refactor

#2169 Fix: Fix wrong progress reports
  src/app/flux/app-global/index.js
  src/app/flux/cnc/index.js
  src/app/flux/laser/index.js
  src/app/flux/printing/actions-mesh.ts
  src/app/flux/printing/index.ts
  src/app/lib/manager/ProgressManager.js
  src/app/lib/manager/ProgressManager.ts
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-CN/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/widgets/Connection/NetworkConnection.tsx
  src/server/services/socket/socket-slice.js
  src/server/slicer/Slicer.ts
Labels: Type: Bug/Bug Fix

#2171 Feature: Add J1 extruder temperature control
  package-lock.json
  package.json
  src/app/constants/index.ts
  src/app/constants/machines.ts
  src/app/flux/workspace/index.ts
  src/app/ui/components/EditComponent/EditComponent.tsx
  src/app/ui/components/Modal/index.tsx
  src/app/ui/pages/Workspace.jsx
  src/app/ui/widgets/ConnectionToolControl/PrintToolControl.tsx
  src/package.json
  src/server/services/socket/sacp/SACP-BASE.ts
  src/server/services/socket/sacp/SACP-SERIAL.ts
  src/server/services/socket/sacp/SACP-TCP.ts
Labels: Category: Printer Control

#2172 Fix: Fix null nozzle size in rare cases
  src/app/config/settings.ts
  src/app/constants/machines.ts
  src/app/core/History.ts
  src/app/flux/cnc/index.js
  src/app/flux/index.ts
  src/app/flux/machine/FixedArray.js
  src/app/flux/machine/History.js
  src/app/flux/machine/action-base.ts
  src/app/flux/printing/actions-base.ts
  src/app/flux/printing/actions-scene.ts
  src/app/flux/printing/index.ts
  src/app/flux/workspace/state.ts
  src/app/index.jsx
  src/app/lib/collections/CircularArray.ts
  src/app/lib/collections/index.ts
  src/app/lib/dom-events.js
  src/app/scene/operations/AddOperation3D.ts
  src/app/scene/operations/AddSupportOperation3D.ts
  src/app/scene/operations/ArrangeOperation3D.ts
  src/app/scene/operations/DeleteOperation3D.ts
  src/app/scene/operations/DeleteSupportOperation3D.ts
  src/app/scene/operations/MoveOperation3D.ts
  src/app/scene/operations/RotateOperation3D.ts
  src/app/scene/operations/ScaleOperation3D.ts
  src/app/scene/operations/ScaleToFitWithRotateOperation3D.ts
  src/app/scene/operations/SimplifyModelOperation.ts
  src/app/scene/operations/UngroupOperation3D.ts
  src/app/scene/operations/index.ts
  src/app/ui/App.jsx
  src/app/ui/widgets/Connection/modals/MismatchNozzleModal.tsx
  src/app/ui/widgets/Console/Console.jsx
  src/app/ui/widgets/Console/Terminal.jsx
  src/app/ui/widgets/PrintingVisualizer/components/SceneContextMenu.tsx
  src/app/ui/widgets/PrintingVisualizer/components/SceneShortcuts.tsx
  src/server/services/api/api-file.js
Labels: Type: Bug/Bug Fix

#2175 Fix: Fix SM 2.0 control issues
  src/app/api/TaskQueue.ts
  src/app/api/api-environment.ts
  src/app/api/base.ts
  src/app/api/index.ts
  src/app/flux/project/index.js
  src/app/flux/setting/index.js
  src/app/ui/App.styl
  src/app/ui/App.tsx
  src/app/ui/layout.styl
  src/app/ui/pages/HomePage/CaseLibrary.tsx
  src/app/ui/variables.styl
  src/app/ui/widgets/Connection/NetworkConnection.tsx
  src/app/ui/widgets/ConnectionFileTransfer/FileTransferView.tsx
  src/app/ui/widgets/ConnectionToolControl/PrintToolControl.tsx
  src/app/ui/widgets/PrintingOutput/Thumbnail.jsx
  src/server/services/socket/sacp/SACP-BASE.ts
Labels: Type: Bug/Bug Fix

#2176 Improvement: Add heated bed control for J1 & Artisan
  src/app/ui/pages/Workspace.jsx
  src/app/ui/widgets/ConnectionToolControl/PrintToolControl.tsx
  src/app/ui/widgets/Enclosure/Enclosure.jsx
  src/server/services/socket/sacp/SACP-BASE.ts
  src/server/services/task-manager/workers/generateToolPath.ts
Labels: Category: Printer Control

#2177 Refactor: Refactor three obejcts
  src/app/flux/app-global/index.js
  src/app/flux/printing/actions-scene.ts
  src/app/flux/printing/index.ts
  src/app/flux/workspace/index.ts
  src/app/models/ClipperModel.ts
  src/app/models/ModelGroup.ts
  src/app/models/ThreeBaseModel.ts
  src/app/models/ThreeGroup.ts
  src/app/models/ThreeModel.ts
  src/app/scene/cameras/CombinedCamera.js
  src/app/scene/objects/Grid.js
  src/app/scene/objects/Rectangle.js
  src/app/scene/objects/RectangleGridHelper.jsx
  src/app/scene/objects/RectangleHelper.jsx
  src/app/scene/operations/AddOperation3D.ts
  src/app/scene/operations/DeleteOperation3D.ts
  src/app/scene/operations/ReplaceSplittedOperation.ts
  src/app/scene/operations/UngroupOperation3D.ts
  src/app/scene/three-extensions/Detector.tsx
  src/app/scene/three-extensions/ExtractControls.js
  src/app/scene/three-extensions/FontLoader.js
  src/app/scene/three-extensions/IntersectDetector.js
  src/app/scene/three-extensions/ManualCalibrationControls.js
  src/app/scene/three-extensions/OBJExporter.js
  src/app/scene/three-extensions/OBJLoader.js
  src/app/scene/three-extensions/PLYExporter.js
  src/app/scene/three-extensions/STLBinaryExporter.js
  src/app/scene/three-extensions/STLLoader.js
  src/app/scene/three-extensions/SVGLoader.js
  src/app/scene/three-extensions/TargetPoint.js
  src/app/scene/three-extensions/TextSprite.js
  src/app/scene/three-extensions/ThreeUtils.js
  src/app/scene/three-extensions/TransformControls.js
  src/app/scene/three-extensions/WebGLRendererWrapper.ts
  src/app/ui/components/SMCanvas/Canvas.tsx
  src/app/ui/components/SMCanvas/Peripheral.js
  src/app/ui/components/SMCanvas/TransformControls.js
  src/app/ui/components/SMCanvas/TransformControls2D.js
  src/app/ui/views/Cnc3DVisualizer/Canvas/Canvas.jsx
  src/app/ui/views/Cnc3DVisualizer/CylinderJob.jsx
  src/app/ui/views/model-operation-overlay/RotateOverlay.jsx
  src/app/ui/widgets/CncLaserShared/PrintablePlate/PrintablePlate.jsx
  src/app/ui/widgets/CncLaserShared/SvgTrace/TracePreview.jsx
  src/app/ui/widgets/CncLaserShared/Thumbnail.jsx
  src/app/ui/widgets/LaserCameraAidBackground/ManualCalibration/ManualCalibration.jsx
  src/app/ui/widgets/LaserSetBackground/ExtractSquareTrace/ExtractPreview.jsx
  src/app/ui/widgets/LaserSetBackground/PrintSquareTrace/PrintPreview.jsx
  src/app/ui/widgets/LaserStackedModel/index.jsx
  src/app/ui/widgets/PrintingOutput/Thumbnail.jsx
  src/app/ui/widgets/PrintingVisualizer/ModelExporter.js
  src/app/ui/widgets/PrintingVisualizer/ModelLoader.js
  src/app/ui/widgets/PrintingVisualizer/PrintableCube.jsx
  src/app/ui/widgets/WorkspaceVisualizer/PrintablePlate/PrintablePlate.jsx
  src/app/ui/widgets/WorkspaceVisualizer/Visualizer.jsx
  src/app/workers/autoRotateModels.ts
  src/app/workers/loadModel.ts
  src/app/workers/scaleToFitWithRotate.ts
Labels: Type: Bug/Bug Fix, Type: Refactor

#2178 Fix: Fix color reset & default color & mesh color related prime tower
  src/app/flux/printing/actions-scene.ts
  src/app/models/ModelGroup.ts
  src/app/models/ThreeModel.ts
  src/app/scene/scene.logic.ts
  src/app/scene/three-extensions/TransformControls.js
  src/app/ui/widgets/PrintingOutput/index.tsx
  src/app/ui/widgets/Purifier/Purifier.jsx
  src/app/ui/widgets/Purifier/index.tsx
  src/app/ui/widgets/Purifier/styles.styl
  src/server/services/socket/sacp/SACP-BASE.ts
Labels: Type: Bug/Bug Fix, Category: 3DP

#2185 Refactor: Refactor Toast and Canvas component
  package-lock.json
  package.json
  src/app/flux/editor/actions-process.js
  src/app/flux/printing/index.ts
  src/app/ui/components/SMCanvas/Canvas.tsx
  src/app/ui/components/SMCanvas/Controls.ts
  src/app/ui/components/Toast/index.js
  src/app/ui/components/Toast/index.ts
  src/app/ui/components/Toast/toastContainer.jsx
  src/app/ui/pages/print-main/PrintMainPage.tsx
  src/app/ui/views/toasts/SceneToast.tsx
  src/app/ui/widgets/PrintingOutput/Output.tsx
Labels: Type: Refactor

#2201 Fix: Fis minor issues related to v4.8.0
  package-lock.json
  package.json
  src/app/flux/app-global/index.js
  src/app/flux/printing/actions-mesh.ts
  src/app/flux/printing/actions-scene.ts
  src/app/flux/printing/index.ts
  src/app/models/ModelGroup.ts
  src/app/models/ThreeModel.ts
  src/app/scene/three-extensions/Detector.ts
  src/app/ui/components/SMCanvas/Canvas.tsx
  src/app/ui/components/SMCanvas/Controls.ts
  src/app/ui/views/Cnc3DVisualizer/Canvas/Controls.jsx
  src/app/ui/views/model-operation-overlay/EditSupportOverlay.jsx
  src/app/ui/views/model-operation-overlay/MeshColoringOverlay.tsx
  src/app/ui/views/model-operation-overlay/MirrorOverlay.jsx
  src/app/ui/views/model-operation-overlay/ModelScaleOverlay.tsx
  src/app/ui/views/model-operation-overlay/RotateOverlay.jsx
  src/app/ui/views/model-operation-overlay/SupportOverlay.tsx
  src/app/ui/views/model-operation-overlay/TranslateOverlay.jsx
  src/app/ui/widgets/ConnectionFileTransfer/FileTransferView.tsx
  src/app/ui/widgets/PrintingVisualizer/SceneView.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
  src/app/ui/widgets/PrintingVisualizer/styles.styl
  src/app/ui/widgets/styles.styl
  src/package.json
Labels: Type: Bug/Bug Fix, Type: Refactor
