Repository Snapmaker/Luban, pull requests merged in 2023-04, with the labels that each got.

#2105 Fix: Fix SM Original home state
  package-lock.json
  package.json
  src/package.json
  src/server/controllers/Marlin/MarlinController.js
Labels: Category: Printer Control

#2102 New Crowdin updates
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-CN/resource.json
Labels: Type: Improvement

#2107 Refactor: Refactor 3DP starter guide
  src/app/flux/printing/index.ts
  src/app/ui/App.jsx
  src/app/ui/pages/print-main/Printing.jsx
  src/app/ui/pages/print-main/StarterGuide.tsx
Labels: Type: Refactor, Type: Improvement

#2120 Refactor: Refactor mesh process actions
  src/app/constants/copy.js
  src/app/constants/index.ts
  src/app/flux/printing/actions-mesh.ts
  src/app/flux/printing/index.ts
  src/app/flux/widget/WidgetState.js
  src/app/lib/controller.ts
  src/app/lib/gaEvent.ts
  src/app/lib/manager/ProgressManager.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-CN/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/scene/scene.logic.ts
  src/app/ui/App.jsx
  src/app/ui/layouts/MainToolBar.jsx
  src/app/ui/pages/CncLaserShared/RightView.jsx
  src/app/ui/pages/Workspace.jsx
  src/app/ui/pages/print-main/PrintMainPage.tsx
  src/app/ui/pages/print-main/index.ts
  src/server/controllers/constants.js
  src/server/services/api/api-file.js
  src/server/services/channel-handlers/mesh.ts
  src/server/services/index.js
  src/server/services/socket/ConnectionManager.js
  src/server/services/socket/socket-slice.js
  src/server/services/task-manager/Task.ts
  src/server/services/task-manager/TaskManager.ts
  src/server/services/task-manager/workerManager.ts
Labels: Type: Feature, Type: Refactor, Category: 3DP

#2124 Fix: Fix created quality preset missing property
  src/app/flux/printing/actions-base.js
  src/app/flux/printing/actions-preset.ts
  src/app/flux/printing/index.ts
  src/app/preset-model/common/PresetModel.ts
  src/app/preset-model/common/QualityPresetModel.ts
  src/app/ui/views/PresetModifier/StackPresetSelector.tsx
  src/app/ui/views/PresetModifier/index.tsx
  src/app/ui/views/PresetModifier/modals/CreatePresetModal.tsx
  src/app/ui/views/PresetModifier/usePresetActions.ts
  src/app/ui/widgets/PrintingConfigurationWidget/ConfigurationView.tsx
Labels: Type: Bug/Bug Fix, Category: 3DP

#2126 Fix: Fix unable to generate G-code on right extruder parameter changes
  src/app/flux/printing/index.ts
  src/app/ui/widgets/PrintingOutput/Output.tsx
Labels: Type: Bug/Bug Fix

#2128 Fix: Fix wrong prime tower calculation on no mesh
  src/app/flux/printing/actions-scene.ts
  src/app/models/ModelGroup.ts
  src/app/models/PrimeTowerModel.ts
  src/app/scene/scene.logic.ts
  src/app/ui/widgets/PrintingOutput/Output.tsx
Labels: Type: Bug/Bug Fix

#2129 Feature: Read 3MF with inch unit
  src/shared/lib/3MFLoader.js
  src/shared/lib/3MFLoader0.js
  src/shared/lib/fflate.module.js
  tsconfig-server.json
Labels: Type: Feature, Category: 3DP

#2130 Fix: Fix faceless geometries in the scene
  packages/luban-platform/index.ts
  packages/luban-platform/src/three-extensions/common/mesh-utility.ts
  src/app/ui/components/SMCanvas/Canvas.jsx
  src/app/ui/components/SMCanvas/TransformControls.js
  src/app/ui/widgets/PrintingVisualizer/PrintableCube.jsx
Labels: Type: Bug/Bug Fix

#2131 Fix: Support all units defined in 3MF spec
  src/shared/lib/3MFLoader.js
Labels: Category: 3DP

#2133 Fix: Fix task runner map
  src/app/flux/editor/index.js
  src/app/ui/widgets/CncLaserShared/VisualizerBottomLeft.jsx
  src/server/services/task-manager/TaskManager.ts
Labels: Type: Bug/Bug Fix

#2134 Chore: Freeze v4.7.3 version
  src/app/ui/pages/print-main/PrintMainPage.tsx
Labels: Type: Build

#2135 Refactor: Refactor 3DP Visualizer
  src/app/flux/printing/index.ts
  src/app/ui/pages/print-main/PrintMainPage.tsx
  src/app/ui/widgets/PrintingConfigurationWidget/ConfigurationView.tsx
  src/app/ui/widgets/PrintingMaterial/Material.jsx
  src/app/ui/widgets/PrintingVisualizer/SceneView.jsx
  src/app/ui/widgets/PrintingVisualizer/components/SceneContextMenu.tsx
  src/app/ui/widgets/PrintingVisualizer/index.jsx
  src/app/ui/widgets/PrintingVisualizer/index.tsx
  src/app/ui/widgets/PrintingVisualizer/styles.styl
  src/app/ui/widgets/PrintingVisualizer/useCanvasActions.ts
Labels: Type: Refactor, State: Draft

#2138 Refactor: Refactor Scene shortcuts & shortcut manager
  src/app/flux/printing/index.ts
  src/app/lib/shortcut/ShortcutManager.ts
  src/app/lib/shortcut/constants.js
  src/app/lib/shortcut/constants.ts
  src/app/lib/shortcut/index.js
  src/app/lib/shortcut/index.ts
  src/app/lib/shortcut/manager.js
  src/app/ui/App.jsx
  src/app/ui/SVGEditor/SVGEditor.jsx
  src/app/ui/widgets/PrintingVisualizer/SceneView.jsx
  src/app/ui/widgets/PrintingVisualizer/components/SceneContextMenu.tsx
  src/app/ui/widgets/PrintingVisualizer/components/SceneShortcuts.tsx
Labels: Type: Refactor

#2145 Correct syntax in README.md
  README.md
Labels: Type: Docs
