Repository Snapmaker/Luban, pull requests merged in 2023-10, with the labels that each got.

#2373 Refactor: Upgrade dependencies
  .stylintrc
  babel.config.js
  package-lock.json
  package.json
  src/app/ui/layouts/AppLayout.jsx
  src/main.js
  src/package.json
  src/server/services/api/api-file.js
Labels: Type: Bug/Bug Fix, dependencies

#2372 Improvement: removing gconf2 gconf-service libappindicator1
  electron-builder.yml
Labels: dependencies

#2375 Fix: Fix scale (uniform-scale button) crash
  src/app/flux/printing/index.ts
Labels: Type: Bug/Bug Fix

#2376 Feature: Add ray firmware upgrade via network
  src/app/api/api-i18n.ts
  src/app/api/index.ts
  src/app/communication/socket-events.ts
  src/app/lib/i18n.ts
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-CN/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/styles/global-background.styl
  src/app/ui/pages/global-modals/settings-modal/Settings.tsx
  src/app/ui/pages/laser-workspace-ray/RayLaserWorkspace.tsx
  src/app/ui/pages/laser-workspace-ray/modals/FirmwareNetworkUpgradeModal.tsx
  src/app/ui/pages/laser-workspace-ray/modals/FirmwareUpgradeModal.tsx
  src/server/DataStorage.ts
  src/server/app.js
  src/server/lib/downloadManager.ts
  src/server/services/api/api-i18n.js
  src/server/services/index.ts
  src/server/services/machine/ConnectionManager.ts
  src/server/services/socket/machine-handlers.ts
  src/server/services/socket/online-handlers.ts
Labels: Type: Feature, Category: Printer Control

#2384 Fix: Fix support angle change not working
  package-lock.json
  src/app/flux/printing/actions-scene.ts
  src/app/flux/printing/index.ts
  src/app/models/ModelGroup.ts
  src/app/ui/views/model-operation-overlay/SupportOverlay.tsx
Labels: Type: Bug/Bug Fix

#2385 Fix: Fix frequently check models out of bounds
  src/app/ui/widgets/PrintingVisualizer/SceneView.tsx
Labels: Type: Bug/Bug Fix

#2386 Fix: Fix extruder switch position (without prime tower)
  src/app/flux/printing/actions-scene.ts
Labels: Type: Bug/Bug Fix

#2381 New Crowdin updates
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-CN/resource.json
Labels: Category: Translations

#2387 Feature: Add error report handling for Ray
  src/app/communication/socket-communication.ts
  src/app/communication/socket-events.ts
  src/app/flux/workspace/index.ts
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-CN/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/pages/laser-workspace-ray/MachineMonitor.tsx
  src/app/ui/pages/laser-workspace-ray/RayLaserWorkspace.tsx
  src/app/ui/pages/laser-workspace-ray/modals/FirmwareNetworkUpgradeModal.tsx
  src/server/services/machine/ConnectionManager.ts
  src/server/services/machine/channels/ChannelEvent.ts
  src/server/services/machine/channels/SacpChannel.ts
  src/server/services/machine/instances/ArtisanInstance.ts
  src/server/services/machine/instances/J1Instance.ts
  src/server/services/machine/instances/RayInstance.ts
  src/server/services/machine/sacp/SacpClient.ts
Labels: Type: Feature

#2388 Fix: Fix SM 2.0 HTTP execute G-code reply
  src/app/lib/generateLaserFocusGcode.js
  src/app/lib/uni-api.js
  src/app/ui/widgets/Console/Console.jsx
  src/app/ui/widgets/LaserSetBackground/PrintSquareTrace/index.jsx
  src/electron-app/AutoUpdater.js
  src/main.js
  src/server/index.js
  src/server/services/machine/ConnectionManager.ts
  src/server/services/machine/channels/Channel.ts
  src/server/services/machine/channels/SacpChannel.ts
  src/server/services/machine/channels/SstpHttpChannel.ts
  src/server/services/machine/channels/TextSerialChannel.ts
  src/server/services/task-manager/workers/generateGcode.js
  src/server/slicer/post-processor.ts
Labels: Type: Bug/Bug Fix

#2389 Refactor: Refactor workspace actions
  src/app/flux/cnc/index.ts
  src/app/flux/laser/index.ts
  src/app/flux/printing/index.ts
  src/app/flux/workspace/actions-gcode.ts
  src/app/flux/workspace/index.ts
  src/app/flux/workspace/types.ts
  src/app/ui/pages/laser-workspace-ray/VisualizerOverlay.tsx
  src/app/ui/pages/laser-workspace-ray/modals/FirmwareNetworkUpgradeModal.tsx
  src/app/ui/widgets/ConnectionControl/Control.tsx
  src/app/ui/widgets/ConnectionControl/ControlPanel.jsx
  src/app/ui/widgets/ConnectionControl/ControlPanel.tsx
  src/app/ui/widgets/ConnectionControl/index.tsx
  src/app/ui/widgets/ConnectionToolControl/CNC.tsx
  src/app/ui/widgets/RaySetOriginWidget/SetOriginView.tsx
  src/app/ui/widgets/RayUploadWidget/UploadView.tsx
  src/server/services/machine/ConnectionManager.ts
Labels: Type: Refactor

#2396 Chore: Upgrade dependencies
  package-lock.json
  package.json
  src/package.json
  src/server-cli.js
  webpack.config.app.development.js
  webpack.config.app.production.js
Labels: dependencies
