Repository Snapmaker/Luban, pull requests merged in 2023-02, with the labels that each got.

#1906 Refactor: Update dependencies (webpack, css-loader, -bootstrap)
  package-lock.json
  package.json
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/styles/app.styl
  src/app/styles/bootstrap-btn-select.styl
  src/app/styles/bootstrap-col-height.styl
  src/app/styles/bootstrap-no-gutters.styl
  src/app/styles/bootstrap-override.styl
  src/app/styles/bootstrap-vertical-spacing.styl
  src/app/styles/scaffolding-bootstrap.styl
  src/app/styles/sm-buttons.styl
  src/app/styles/typography.styl
  src/app/styles/vendor.styl
  src/app/ui/components/RepeatButton/index.jsx
  src/app/ui/components/Select/ChangedReactSelect.jsx
  src/app/ui/widgets/Connection/WifiConnection.jsx
  src/app/ui/widgets/Control/ControlPanel.jsx
  src/app/ui/widgets/Control/DisplayPanel.jsx
  src/app/ui/widgets/Control/JogDistance.jsx
  src/app/ui/widgets/Control/JogPad.jsx
  src/app/ui/widgets/Control/KeypadOverlay.jsx
  src/app/ui/widgets/Control/MotionButtonGroup.jsx
  src/app/ui/widgets/Control/index.styl
  src/app/ui/widgets/MachineSetting/machineSetting.jsx
  src/app/ui/widgets/Macro/AddMacro.jsx
  src/app/ui/widgets/Macro/EditMacro.jsx
  src/app/ui/widgets/Marlin/JogDistance.jsx
  src/app/ui/widgets/Marlin/Printing.jsx
  src/app/ui/widgets/Marlin/index.styl
  webpack.config.app.development.js
  webpack.config.app.production.js
Labels: Type: Refactor

#1908 Fix: Fix OSS upload wildcard path
  .github/workflows/build-on-create-release.yml
Labels: Type: Bug/Bug Fix, Type: Build

#1910 Refactor: Upgrade css-loader v3 to v4
  package-lock.json
  package.json
  src/app/styles/app.styl
  src/app/styles/global-var.styl
  src/app/styles/vendor.styl
  webpack.config.app.development.js
  webpack.config.app.production.js
Labels: Type: Refactor, dependencies

#1912 Refactor: Upgrade intro.js v4 -> v5 && Fix introjs.css import
  package-lock.json
  package.json
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/styles/vendor.styl
  src/app/ui/pages/Cnc.jsx
  src/app/ui/pages/Laser.jsx
  src/app/ui/pages/Printing.jsx
  src/app/ui/widgets/LaserCameraAidBackground/ExtractSquareTrace/index.jsx
  src/package.json
Labels: Type: Refactor

#1913 Build: Update Windows/Linux workflow upload method
  .github/workflows/build-on-create-release.yml
  electron-builder.yml
  src/app/styles/sm-flex.styl
  src/app/ui/widgets/Connection/Connection.jsx
  src/app/ui/widgets/Connection/SerialConnection.jsx
  src/app/ui/widgets/Connection/WifiConnection.jsx
  src/app/ui/widgets/Connection/components/MachineModuleStatusBadge.tsx
Labels: Type: Build

#1921 Improvement: Update JP translations
  src/app/resources/i18n/ja/resource.json
Labels: Category: Translations

#1909 Improvement: Ukrainian translation
  src/app/resources/i18n/uk/resource.json
Labels: Category: Translations

#1922 Fix: Fix Linux slicer slicing failure
  package-lock.json
  package.json
  src/package.json
Labels: Type: Bug/Bug Fix, Category: G-code Generator

#1923 Feature: Add log file and log downloads
  src/app/config/menu/helpMenu.js
  src/app/ui/layouts/AppLayout.jsx
  src/server/lib/logger.ts
  src/server/slicer/Slicer.ts
Labels: Type: Feature

#1924 Fix: Fix Artisan hot zone checking
  src/app/flux/manager/DefinitionManager.js
  src/app/models/ModelGroup.ts
  src/app/ui/components/SMCanvas/Canvas.jsx
  src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
Labels: Type: Bug/Bug Fix

#1925 Fix: Fix context menu style
  src/app/styles/vendor.styl
  src/app/ui/components/ContextMenu/index.jsx
Labels: Type: Bug/Bug Fix, Category: UX

#1926 Fix: Fix broken mirror operation
  src/app/models/ModelGroup.ts
Labels: Type: Bug/Bug Fix

#1928 Feature: Add reset configurations menu button
  src/app/config/menu/helpMenu.js
  src/app/constants/copy.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/layouts/AppLayout.jsx
Labels: Type: Feature

#1932 Fix: Fix repaired model not saving in project
  src/app/flux/project/index.js
  src/app/ui/views/repair-model/repair-model-popup.tsx
  src/app/ui/widgets/CNCVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerPopup.jsx
  src/server/slicer/slice.js
Labels: Type: Bug/Bug Fix

#1935 Refactor: Refactor reset configuration files
  src/DataStorage.js
  src/app/api/index.js
  src/app/flux/setting/index.js
  src/app/lib/modal.jsx
  src/app/ui/layouts/AppLayout.jsx
  src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerPopup.jsx
  src/server/DataStorage.js
  src/server/services/api/api-profile-definitions.js
  src/server/services/api/api-users.js
  src/server/services/index.js
Labels: Type: Bug/Bug Fix, Type: Refactor, Category: 3DP

#1937 Fix: Fix redirect for non-english links
  src/app/ui/pages/HomePage/MoreInfo.jsx
Labels: Category: UX

#1938 Feature: Add support interface assignment
  src/app/constants/preset.ts
  src/app/flux/manager/DefinitionManager.js
  src/app/flux/printing/index.js
  src/app/flux/project/index.js
  src/app/models/ModelGroup.ts
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/scene/scene.logic.ts
  src/app/ui/views/PresetModifier/PresetContent.jsx
  src/app/ui/views/PrintingObjectList/ObjectListItem.jsx
  src/app/ui/views/PrintingObjectList/ObjectListView.tsx
  src/app/ui/views/PrintingObjectList/model-extruder-overlay.tsx
  src/server/services/api/api-profile-definitions.js
  src/server/services/socket/socket-slice.js
Labels: Category: 3DP

#1936 Improvement: Ukrainian translation
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
Labels: Category: Translations

#1940 Fix: Fix async clear storage
  src/server/DataStorage.js
  src/server/services/api/api-users.js
Labels: Type: Bug/Bug Fix

#1942 Fix: Quick fix for missing folders
  src/server/DataStorage.js
Labels: Type: Bug/Bug Fix

#1941 Feature: Add engine test
  build/prebuild-dev.sh
  build/prebuild-prod.sh
  resources/engine-test/cube.stl
  resources/engine-test/windows-x64-engine-test.bat
  src/app/config/menu/helpMenu.js
  src/app/ui/layouts/AppLayout.jsx
  src/main.js
Labels: Type: Refactor

#1944 Fix: Fix several bugs related to prime tower
  .gitattributes
  src/app/config/menu/helpMenu.js
  src/app/config/menu/index.js
  src/app/constants/copy.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/scene/scene.logic.ts
  src/app/ui/views/PresetModifier/ParametersQuickSettingsView.tsx
  src/server/DataStorage.js
Labels: Type: Bug/Bug Fix

#1945 Fix: Fix losing selected quality preset from project
  package-lock.json
  package.json
  src/app/flux/project/index.js
  src/package.json
  src/server/services/api/api-file.js
Labels: Type: Bug/Bug Fix, Category: 3DP

#1946 Fix: Fix SM 2.0 single extruder user case
  package-lock.json
  package.json
  src/app/ui/pages/Printing.jsx
  src/package.json
Labels: Type: Bug/Bug Fix, Category: 3DP

#1947 Build: Fix aliyun OSS upload command
  .github/workflows/build-on-create-release.yml
Labels: Type: Build

#1948 Fix: Fix slice process model visibility
  src/app/flux/printing/index.js
Labels: Type: Bug/Bug Fix

#1939 Refactor: Upgrade package-lock.json file
  package-lock.json
  package.json
  src/package.json
  src/server/app.js
Labels: dependencies

#1949 Docs: Update README.md
  README.md
Labels: Type: Docs

#1951 Refactor: Refactor DataStorage & 2 minor bug fixes
  package-lock.json
  package.json
  src/app/flux/printing/actions-scene.ts
  src/app/ui/pages/MachineMaterialSettings/materialSettings.jsx
  src/app/ui/widgets/PrintingConfigurationWidget/PresetInitialization.tsx
  src/package.json
  src/server/DataStorage.ts
  src/server/lib/util-fs/node/index.ts
  src/server/services/api/api-file.js
  tsconfig-server.json
Labels: Type: Bug/Bug Fix

#1950 Fix: Fix jimp failed to read pictures
  package.json
  src/server/lib/jimp/index.js
Labels: Type: Bug/Bug Fix, Category: Laser

#1952 Improvement: Improve selection style of job
  package-lock.json
  package.json
  src/app/ui/widgets/WifiTransport/index.styl
  src/package.json
Labels: Category: UX

#1953 Build: Remove OSS latest.yaml upload
  .github/workflows/build-on-create-release.yml
Labels: Type: Build

#1954 Improvement: Ukrainian translation
  src/app/resources/i18n/uk/resource.json
Labels: Category: Translations

#1955 Improvement: Add string "Open Config Folder" to resource for localization
  src/app/config/menu/settingsMenu.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
Labels: Category: Translations

#1959 Refactor: Upgrade css-loader v4 -> v5
  package-lock.json
  package.json
Labels: Type: Refactor, dependencies

#1961 Refactor: Upgrade url-loader v1 -> v2
  package-lock.json
  package.json
  webpack.config.app.development.js
  webpack.config.app.production.js
Labels: Type: Refactor

#1962 Refactor: Upgrade url-loader v2 -> v3
  package-lock.json
  package.json
  src/app/ui/pages/HomePage/Begin.jsx
  src/app/ui/pages/HomePage/index.jsx
  src/app/ui/widgets/LaserCameraAidBackground/SelectCaptureMode.tsx
  webpack.config.app.production.js
Labels: dependencies

#1963 Refactor: Upgrade url-loader v3 -> v4
  package-lock.json
  package.json
Labels: Type: Refactor, dependencies

#1964 Refactor: Upgrade file-loader v1 -> v6
  package-lock.json
  package.json
Labels: Type: Refactor, dependencies

#1965 Fix: Fix Artisan hot zone detection right after auto rotate
  src/app/models/ModelGroup.ts
  src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
Labels: Type: Bug/Bug Fix, Firmware: Snapmaker Artisan

#1966 Fix: Fix Artisan hot zone detection right after auto rotate (2)
  src/app/models/ModelGroup.ts
  src/app/ui/components/SMCanvas/Canvas.jsx
Labels: Category: 3DP

#1970 Refactor: Upgrade jsonwebtoken v8 -> v9
  package-lock.json
  package.json
  src/package.json
Labels: dependencies

#1971 Fix: Fix material initialization
  src/app/ui/widgets/PrintingConfigurationWidget/PresetInitialization.tsx
Labels: Type: Bug/Bug Fix, Category: 3DP

#1972 Fix: Fix print configuration version compatibility
  .commitlintrc.js
  .cz-conventional-changelog.js
  package-lock.json
  package.json
  src/package.json
  src/server/DataStorage.ts
Labels: Category: 3DP

#1973 Improvement: Update SM 2.0 start code to avoid scratching
  src/app/flux/manager/DefinitionManager.js
Labels: Type: Improvement, Category: 3DP

#1977 Fix: Fix losing selection of preset after material switch
  src/app/ui/widgets/PrintingConfigurationWidget/PresetInitialization.tsx
  src/app/ui/widgets/PrintingVisualizer/PrintableCube.jsx
Labels: Type: Bug/Bug Fix

#1967 Feature: Fix svg text parsing problem and add default font
  src/server/DataStorage.ts
  src/server/services/task-manager/workerManager.ts
  src/shared/lib/FontManager.js
  src/shared/lib/SVGParser/AttributesParser.js
  src/shared/lib/SVGParser/TextParser.js
Labels: Type: Improvement

#1974 Fix: Fix the issue of incomplete disconnection
  src/server/services/socket/socket-http.ts
  src/server/services/task-manager/workers/heartBeat.ts
Labels: Type: Bug/Bug Fix, Category: Printer Control

#1980 Fix: Bring missing preset reset button back
  package-lock.json
  package.json
  packages/luban-platform/src/parameter-resolver/common/parameter-resolver.ts
  src/app/constants/copy.js
  src/app/flux/manager/DefinitionManager.js
  src/app/flux/printing/index.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/views/PresetModifier/PresetModifierModal.jsx
  src/app/ui/views/PresetModifier/ResetPresetModal.tsx
  src/app/ui/views/PresetModifier/StackPresetSelector.tsx
  src/app/ui/views/PresetModifier/usePresetActions.ts
  src/app/ui/widgets/PrintingConfigurationWidget/PresetInitialization.tsx
Labels: Category: 3DP

#1981 Fix: Fix unusable old files migrated from v3.X.Y and v4.1.Y
  src/server/DataStorage.ts
Labels: Type: Bug/Bug Fix

#1983 Fix: Fix crash of diameter mismatch on connection
  packages/luban-platform/src/parameter-resolver/common/parameter-resolver.ts
  src/app/flux/printing/index.js
  src/app/ui/views/PrintingManager/PrintingManager.jsx
  src/app/ui/widgets/Connection/WifiConnection.jsx
  src/server/services/socket/ConnectionManager.js
Labels: Type: Bug/Bug Fix

#1984 Improvement: Save materials from project
  src/app/flux/project/index.js
Labels: Type: Improvement

#1986 Fix: Fix Issue-1179 wrong fonts in some views
  src/app/styles/base.styl
  src/app/styles/global-font.styl
  src/app/styles/global-heading.styl
  src/app/styles/scaffolding.styl
  src/app/styles/typography.styl
  src/app/styles/xterm.styl
  src/app/ui/App.styl
  src/app/ui/SVGEditor/PrintableArea.js
  src/app/ui/components/Buttons/styles.styl
  src/app/ui/components/Tabs/styles.styl
  src/app/ui/components/Widget/index.styl
  src/app/ui/widgets/CncLaserTopRight/styles.styl
  src/app/ui/widgets/WorkspaceVisualizer/index.styl
Labels: Type: Improvement, Category: UX

#1985 Improvement: Improvement: Ukrainian translation
  src/app/resources/i18n/uk/resource.json
Labels: Category: Translations

#1993 Feature: Add model scaling by dimension
  package-lock.json
  package.json
  src/app/flux/printing/index.js
  src/app/ui/components/Buttons/Button.tsx
  src/app/ui/components/Buttons/index.js
  src/app/ui/components/Checkbox/CheckboxWrapper.jsx
  src/app/ui/components/SvgIcon/SvgIcon.jsx
  src/app/ui/views/model-operation-overlay/CancelButton.tsx
  src/app/ui/views/model-operation-overlay/ChangePrintModeOverlay.jsx
  src/app/ui/views/model-operation-overlay/EditSupportOverlay.jsx
  src/app/ui/views/model-operation-overlay/MirrorOverlay.jsx
  src/app/ui/views/model-operation-overlay/ModelScaleOverlay.tsx
  src/app/ui/views/model-operation-overlay/RotateOverlay.jsx
  src/app/ui/views/model-operation-overlay/RotationAnalysisOverlay.jsx
  src/app/ui/views/model-operation-overlay/SimplifyOverlay.jsx
  src/app/ui/views/model-operation-overlay/SupportOverlay.jsx
  src/app/ui/views/model-operation-overlay/TranslateOverlay.jsx
  src/app/ui/views/model-operation-overlay/styles.styl
  src/app/ui/widgets/PrintingVisualizer/Overlay/ScaleOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
Labels: Category: 3DP

#1992 Fix: Default font supporting text input
  src/server/lib/svg-convert.js
Labels: Type: Bug/Bug Fix, Category: Laser

#1994 Refactor: Rename i18n folder zh-cn to zh-CN
  gulp/tasks/i18next.js
  scripts/i18n-export-excel.js
  scripts/i18n-import-cura-translations.js
  scripts/i18n-import-excel.js
  scripts/swap2.js
  src/app/config/settings.js
  src/app/constants/index.ts
  src/app/index.jsx
  src/app/resources/i18n/zh-CN/controller.json
  src/app/resources/i18n/zh-CN/gcode.json
  src/app/resources/i18n/zh-CN/resource.json
  src/app/ui/layouts/AppLayout.jsx
  src/app/ui/pages/HomePage/MoreInfo.jsx
  src/app/ui/pages/HomePage/SettingGuideModal.jsx
  src/app/ui/pages/Settings/General/General.jsx
  src/server/config/settings.base.js
  webpack.config.app-i18n.js
Labels: Category: Translations

#1976 New Crowdin updates
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/zh-CN/resource.json
Labels: Category: Translations

#1999 Fix: Fix parameter calculation for reset operation
  src/app/flux/printing/index.js
  src/app/ui/components/Popover/index.jsx
  src/app/ui/widgets/PrintingConfigurationWidget/ConfigurationView.tsx
  src/server/services/api/api-profile-definitions.js
Labels: Type: Bug/Bug Fix

#2000 Fix: Fix preset reload issue
  packages/luban-platform/index.ts
  packages/luban-platform/src/parameter-resolver/common/parameter-resolver.ts
  src/app/flux/manager/DefinitionManager.js
  src/server/services/configstore/index.js
Labels: Type: Bug/Bug Fix

#1997 New Crowdin updates
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/uk/resource.json
Labels: Category: Translations
