Repository Snapmaker/Luban, pull requests merged in 2023-09, with the labels that each got.

#2315 Build: Fix build script by use npm@^9 instead of latest
  .github/workflows/build-on-create-release.yml
Labels: Type: Build

#2316 Fix: Fix wrong view port of preview canvas
  src/app/constants/coordinate.ts
  src/app/flux/editor/index.ts
  src/app/flux/laser/index.ts
  src/app/ui/components/SMCanvas/Canvas.tsx
  src/app/ui/widgets/CNCVisualizer/Visualizer.tsx
  src/app/ui/widgets/CncLaserShared/PrintablePlate/PrintablePlate.ts
  src/app/ui/widgets/LaserVisualizer/Visualizer.tsx
Labels: Type: Bug/Bug Fix

#2317 Improvement: Replace ray/20w/40w module images
  src/app/machines/snapmaker-2-toolheads.ts
  src/app/machines/snapmaker-ray.ts
  src/app/resources/images/machine/200w_cnc_module.jpeg
  src/app/resources/images/machine/20w_laser_module.jpeg
  src/app/resources/images/machine/40w_laser_module.jpeg
  src/app/resources/images/machine/snapmaker_ray.jpeg
Labels: Type: Improvement

#2318 Build: Change macOS notarize method to use notarytool
  build/entitlements.mac.plist
  build/notarize.js
  package-lock.json
  package.json
  src/app/flux/cnc/index.ts
  src/app/flux/editor/index.ts
  src/app/flux/laser/index.ts
Labels: Type: Build

#2321 Fix: Fix SM 2.0 camera capture wont work
  src/app/constants/index.ts
  src/app/constants/machines.ts
  src/app/flux/laser/index.ts
  src/app/flux/printing/index.ts
  src/app/flux/workspace/index.ts
  src/app/lib/caseLibrary.jsx
  src/app/ui/pages/HomePage/CaseLibrary.tsx
  src/app/ui/pages/Workspace.tsx
  src/app/ui/pages/print-main/PrintMainPage.tsx
  src/app/ui/views/PresetModifier/quality-preset-adjustment.ts
  src/app/ui/widgets/ConnectionToolControl/CNC.tsx
  src/app/ui/widgets/LaserCameraAidBackground/ExtractSquareTrace/ExtractPreview.jsx
  src/app/ui/widgets/LaserCameraAidBackground/ExtractSquareTrace/index.jsx
  src/app/ui/widgets/LaserCameraAidBackground/ManualCalibration/ManualCalibration.jsx
Labels: Type: Bug/Bug Fix, Category: Printer Control

#2322 Fix: Fix several issues
  src/app/constants/copy.ts
  src/app/flux/editor/actions-process.ts
  src/app/flux/laser/index.ts
  src/app/flux/project/index.ts
  src/app/flux/workspace/actions-gcode.ts
  src/app/flux/workspace/index.ts
  src/app/flux/workspace/state.ts
  src/app/machines/snapmaker-artisan.ts
  src/app/models/ModelGroup.ts
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-CN/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/pages/CncLaserShared/MainToolBar.jsx
  src/app/ui/pages/cnc-main/CNCMainPage.tsx
  src/app/ui/pages/laser-main/StarterGuide.tsx
  src/app/ui/pages/laser-main/modals/JobSetupView.tsx
  src/app/ui/pages/laser-workspace-ray/modals/MachineSettingsModal.tsx
  src/app/ui/utils/renderWidgetList.tsx
  src/app/ui/widgets/CncLaserShared/Thumbnail.jsx
  src/app/ui/widgets/PrintingOutput/Thumbnail.jsx
  src/app/ui/widgets/PrintingVisualizer/PrintableCube.jsx
  src/app/ui/widgets/RaySetOriginWidget/ControlPanel.tsx
  src/app/ui/widgets/RaySetOriginWidget/SetOriginView.tsx
  src/app/ui/widgets/RaySetOriginWidget/index.tsx
  src/server/constants/index.js
Labels: Type: Bug/Bug Fix, Category: Printer Control

#2324 Improvement: Add compressing and decompressing notice
  src/app/connection/controller-events.ts
  src/app/lib/controller.ts
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-CN/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/layouts/styles/workspace.styl
  src/app/ui/pages/laser-workspace-ray/RayLaserWorkspace.tsx
  src/app/ui/utils/renderPopup.jsx
  src/app/ui/widgets/RayUploadWidget/UploadView.tsx
  src/server/services/machine/ConnectionManager.ts
  src/server/services/machine/channels/Channel.ts
  src/server/services/machine/channels/SacpChannel.ts
  src/server/services/machine/channels/SacpTcpChannel.ts
  src/server/services/machine/channels/SacpUdpChannel.ts
  src/server/services/machine/instances/ArtisanInstance.ts
  src/server/services/machine/instances/Instance.ts
  src/server/services/machine/instances/RayInstance.ts
  src/server/services/machine/sacp/SacpClient.ts
Labels: Type: Bug/Bug Fix

#2325 Feature: Add enclosure door detection setting
  src/app/ui/pages/laser-workspace-ray/modals/MachineControlModal/MachineControlModal.tsx
  src/app/ui/pages/laser-workspace-ray/modals/MachineSettingsModal.tsx
  src/server/services/machine/ConnectionManager.ts
  src/server/services/machine/channels/Channel.ts
  src/server/services/machine/channels/SacpChannel.ts
  src/server/services/machine/sacp/SacpClient.ts
  src/server/services/socket/machine-handlers.ts
Labels: Category: Printer Control

#2333 Fix: Fix issues & minor improvements
  src/app/flux/workspace/MachineAgent.ts
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-CN/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/pages/CncLaserShared/MainToolBar.jsx
  src/app/ui/pages/cnc-main/CNCMainPage.tsx
  src/app/ui/pages/introContent.jsx
  src/app/ui/pages/laser-main/StarterGuide.tsx
  src/app/ui/pages/laser-workspace-ray/modals/MachineSettingsModal.tsx
  src/app/ui/views/model-operation-overlay/SVGClippingOverlay.tsx
  src/app/ui/widgets/JobStatusWidget/JobStatusView.tsx
  src/app/ui/widgets/RaySetOriginWidget/SetOriginView.tsx
  src/app/ui/widgets/RayUploadWidget/UploadView.tsx
  src/app/ui/widgets/WorkspaceVisualizer/Visualizer.jsx
  src/package.json
  src/server/services/machine/ConnectionManager.ts
  src/server/services/machine/channels/Channel.ts
  src/server/services/machine/channels/SacpChannel.ts
  src/server/services/machine/sacp/SacpClient.ts
Labels: Type: Bug/Bug Fix

#2328 Feature: home page add information flow
  src/app/api/index.ts
  src/app/ui/pages/HomePage/CaseLibrary.tsx
  src/app/ui/pages/HomePage/MoreInfo.jsx
  src/app/ui/pages/HomePage/StartProject.tsx
  src/app/ui/pages/HomePage/index.tsx
  src/app/ui/pages/HomePage/styles.styl
  src/server/services/api/api-case-resrouces.js
  src/server/services/index.ts
Labels: Type: Feature

#2329 Feature: svg shape library
  package-lock.json
  package.json
  src/app/api/index.ts
  src/app/flux/editor/index.ts
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-CN/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/SVGEditor/SVGEditor.tsx
  src/app/ui/SVGEditor/SVGLeftBar.jsx
  src/app/ui/SVGEditor/SVGShapeLibrary/index.tsx
  src/app/ui/SVGEditor/SVGShapeLibrary/styles.styl
  src/app/ui/SVGEditor/lib/ext-shapes.js
  src/app/ui/pages/CncLaserShared/MainToolBar.jsx
  src/app/ui/widgets/LaserVisualizer/Visualizer.tsx
  src/server/services/api/api-online-resources-service.js
  src/server/services/api/index.js
  src/server/services/index.ts
Labels: Type: Feature

#2336 Build: Update package-lock.json to fix dmg-license package
  package-lock.json
Labels: Type: Build

#2338 Fix: Fix project load size
  src/app/constants/copy.ts
  src/app/flux/editor/index.ts
  src/app/flux/project/index.ts
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-CN/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/scene2d/Workpiece2d.ts
  src/app/ui/SVGEditor/SVGCanvas.tsx
  src/app/ui/SVGEditor/SVGEditor.tsx
  src/app/ui/pages/HomePage/StartProject.tsx
  src/app/ui/widgets/LaserCameraAidBackground/ExtractSquareTrace/index.jsx
  src/app/ui/widgets/LaserVisualizer/Visualizer.tsx
  src/server/lib/image-getPhoto.js
  src/server/services/machine/ConnectionManager.ts
  src/server/services/machine/instances/RayInstance.ts
Labels: Type: Bug/Bug Fix

#2340 Fix: Fix project/index import order
  src/app/flux/project/index.ts
Labels: Type: Bug/Bug Fix

#2341 Fix: Fix camera capture and job offset options
  packages/luban-platform/src/machine-definition/common/machine.ts
  src/app/constants/machines.ts
  src/app/machines/snapmaker-a150.ts
  src/app/machines/snapmaker-a250.ts
  src/app/machines/snapmaker-a350.ts
  src/app/machines/snapmaker-artisan.ts
  src/app/ui/SVGEditor/SVGEditor.tsx
  src/app/ui/pages/CncLaserShared/MainToolBar.tsx
  src/app/ui/pages/laser-main/modals/JobSetupView.tsx
  src/app/ui/widgets/CNCVisualizer/Visualizer.tsx
Labels: Category: UX

#2342 Improvement: Add work range limit to Artisan if only left extruder used
  src/app/flux/printing/index.ts
  src/app/lib/numeric-utils.ts
  src/app/ui/views/ProfileManagerForLaserCnc/index.jsx
  src/app/ui/views/ToolPathConfigurations/ToolPathConfigurations.tsx
  src/app/ui/views/ToolPathConfigurations/laser/PresentSelector.jsx
  src/server/lib/numeric-utils.ts
Labels: Type: Improvement, Category: 3DP

#2343 Improvement: Optimize ray wi-fi connection experience
  src/app/ui/components/Buttons/Button.tsx
  src/app/ui/pages/CncLaserShared/MainToolBar.tsx
  src/app/ui/pages/laser-workspace-ray/modals/MachineNetworkModal.tsx
  src/app/ui/widgets/ConnectionFileTransfer/FileTransferView.tsx
Labels: Category: UX, Category: Printer Control

#2346 Fix: v4.9.0 information-flow/svg-shape-lib/svg-img-compose bugs
  src/app/resources/i18n/en/resource.json
  src/app/ui/SVGEditor/SVGShapeLibrary/index.tsx
  src/app/ui/SVGEditor/SVGShapeLibrary/styles.styl
  src/app/ui/pages/CncLaserShared/MainToolBar.tsx
  src/app/ui/pages/HomePage/styles.styl
  src/server/services/api/api-online-resources-service.js
Labels: Type: Bug/Bug Fix

#2349 Fix: Fix job status canStartPrint logic
  src/app/flux/printing/index.ts
  src/app/flux/workspace/MachineAgent.ts
  src/app/ui/widgets/ConnectionFileTransfer/FileTransferView.tsx
  src/app/ui/widgets/WorkspaceVisualizer/WorkflowControl.jsx
Labels: Type: Bug/Bug Fix, Category: Printer Control

#2351 Fix v4.9.0 informationflow-style
  src/app/ui/pages/HomePage/styles.styl
Labels: Type: Style

#2350 Fix: Fix bug for copy
  src/app/models/SvgModel.ts
  src/app/ui/SVGEditor/SVGCanvas.tsx
Labels: Type: Improvement

#2353 Fix: Fix serial connection button state
  src/app/flux/workspace/actions-connect.ts
  src/app/flux/workspace/index.ts
  src/app/ui/widgets/Connection/SerialConnection.tsx
  src/app/ui/widgets/RayUploadWidget/UploadView.tsx
  src/server/services/machine/channels/SacpSerialChannel.ts
Labels: Type: Bug/Bug Fix

#2356 Fix: Fix several minor issues
  src/app/flux/editor/index.ts
  src/app/flux/laser/index.ts
  src/app/flux/workspace/index.ts
  src/app/models/SVGActionsFactory.js
  src/app/ui/components/Input/TextArea.jsx
  src/app/ui/views/Cnc3DVisualizer/Cnc3DVisualizer.jsx
  src/app/ui/widgets/CncLaserList/ObjectList/ObjectListBox.tsx
  src/app/ui/widgets/CncLaserList/ObjectList/model-item.jsx
  src/app/ui/widgets/RaySetOriginWidget/SetOriginView.tsx
Labels: Type: Bug/Bug Fix

#2355 Fix: Home page useEffect update after unmount warning
  src/app/ui/pages/HomePage/CaseLibrary.tsx
  src/app/ui/pages/HomePage/MoreInfo.jsx
Labels: Type: Bug/Bug Fix

#2358 Fix: Fix CNC fixture drawing missing
  src/app/config/menu/helpMenu.ts
  src/app/constants/index.ts
  src/app/flux/editor/actions-process.ts
  src/app/scene2d/Workpiece2d.ts
  src/app/ui/SVGEditor/SVGCanvas.tsx
  src/app/ui/components/Input/TextArea.jsx
  src/app/ui/layouts/AppLayout.jsx
  src/app/ui/pages/HomePage/MoreInfo.jsx
  src/app/ui/views/Cnc3DVisualizer/Cnc3DVisualizer.jsx
  src/app/ui/widgets/WorkspaceVisualizer/PrintablePlate/PrintablePlate.ts
Labels: Type: Bug/Bug Fix

#2359 Fix: Fix minor bugs lead by mismatching identifiers
  src/app/flux/project/index.ts
  src/app/models/ModelGroup2D.ts
  src/app/ui/pages/cnc-main/CNCMainPage.tsx
  src/app/ui/widgets/Enclosure/Enclosure.tsx
  src/server/services/api/api-file.js
Labels: Type: Bug/Bug Fix

#2360 Refactor: Upgrade dependencies
  package-lock.json
  package.json
  src/app/config/settings.ts
  src/app/index.jsx
  src/package.json
  src/server/app.js
Labels: dependencies

#2361 Fix: Fix remain time calculation
  src/server/services/machine/channels/SacpChannel.ts
Labels: Type: Bug/Bug Fix

#2362 Refactor: Upgrade dependencies
  package-lock.json
  package.json
  src/electron-app/Menu.js
  src/main.js
  src/package.json
  src/server/lib/svg-convert.js
Labels: Type: Refactor

#2363 Refactor: Upgrade dependencies (webappengine)
  package-lock.json
  package.json
  src/app/index.jsx
  src/app/lib/user.js
  src/app/ui/layouts/AppLayout.jsx
  src/package.json
  src/server/app.js
  src/server/index.js
Labels: dependencies

#2368 Feature: Update lunar to 1.4.4
  package.json
  src/package.json
Labels: Type: Bug/Bug Fix

#2367 Fix: Fix console log for G-code execution
  package-lock.json
  package.json
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-CN/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/widgets/Console/Console.jsx
  src/app/ui/widgets/RaySetOriginWidget/modals/RunBoundaryModal.tsx
  src/app/ui/widgets/RayUploadWidget/UploadView.tsx
  src/package.json
  src/server/controllers/Marlin/Marlin.js
  src/server/controllers/Marlin/MarlinController.js
  src/server/services/machine/ConnectionManager.ts
  src/server/services/machine/channels/SacpChannel.ts
Labels: Type: Bug/Bug Fix, Category: Printer Control
