Repository Snapmaker/Luban, pull requests merged in 2023-03, with the labels that each got.

#2003 New Crowdin updates
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/zh-CN/resource.json
Labels: Category: Translations

#2010 Improvement: Several improvements on dual extruder and networked printer control
  src/app/constants/machines.ts
  src/app/flux/machine/index.js
  src/app/flux/workspace/index.ts
  src/app/flux/workspace/machine-state.ts
  src/app/machines/snapmaker-j1.ts
  src/app/models/ModelInfoUtils.ts
  src/app/ui/modals/modal-machine-select.jsx
  src/app/ui/pages/print-main/SceneInitialization.tsx
  src/app/ui/widgets/Connection/MismatchModal.tsx
  src/app/ui/widgets/Connection/SerialConnection.jsx
  src/app/ui/widgets/Connection/WifiConnection.jsx
  src/app/ui/widgets/Control/JogDistance.jsx
  src/app/ui/widgets/LaserTestFocus/index.jsx
  src/app/ui/widgets/PrintingVisualizer/PrintableCube.jsx
  src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
  src/app/ui/widgets/WorkspaceVisualizer/Visualizer.jsx
  src/server/services/api/api-file.js
  test/cnc-mesh-slice/main.js
Labels: Type: Bug/Bug Fix, Type: Improvement, Category: CNC, Category: 3DP, Category: Printer Control

#2009 New Crowdin updates
  src/app/resources/i18n/de/resource.json
Labels: Category: Translations

#2028 Docs: Update contributing documents
  CONTRIBUTING.md
  docs/Development.md
Labels: Type: Docs

#2039 Fix: Fix several printer control issues
  src/app/flux/machine/index.js
  src/app/flux/printing/index.js
  src/app/machines/snapmaker-a150.ts
  src/app/machines/snapmaker-a250.ts
  src/app/machines/snapmaker-a350.ts
  src/app/machines/snapmaker-artisan.ts
  src/app/ui/pages/CncLaserShared/MainToolBar.jsx
  src/app/ui/pages/CncLaserShared/RightView.jsx
  src/app/ui/pages/Printing.jsx
  src/app/ui/widgets/Connection/NetworkConnection.tsx
  src/app/ui/widgets/ConnectionControl/Control.tsx
  src/app/ui/widgets/ConnectionFileTransfer/FileTransferView.tsx
  src/app/ui/widgets/Enclosure/EnclosureDisplay.jsx
  src/app/ui/widgets/LaserCameraAidBackground/ExtractSquareTrace/index.jsx
  src/app/ui/widgets/LaserCameraAidBackground/ManualCalibration/ManualCalibration.jsx
  src/app/ui/widgets/LaserCameraAidBackground/ManualCalibration/index.jsx
  src/app/ui/widgets/LaserCameraAidBackground/MaterialThicknessInput.tsx
  src/app/ui/widgets/LaserCameraAidBackground/index.jsx
  src/app/ui/widgets/LaserSetBackground/ExtractSquareTrace/index.jsx
  src/app/ui/widgets/LaserSetBackground/PrintSquareTrace/index.jsx
  src/app/ui/widgets/LaserSetBackground/SetBackground.jsx
  src/app/ui/widgets/Macro/index.jsx
  src/server/constants/index.js
  src/server/services/task-manager/workers/heartBeat.ts
Labels: Type: Bug/Bug Fix, Category: Laser, Category: Printer Control

#2030 New Crowdin updates
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/uk/resource.json
Labels: Category: Translations

#2038 Fix: Fix printing information error after software reconnection
  src/app/ui/widgets/WorkingProgress/WorkingProgress.jsx
  src/server/services/socket/sacp/Business.ts
  src/server/services/socket/sacp/SACP-BASE.ts
Labels: Category: Printer Control

#2020 Feature: Add time estimation configuration
  package.json
  src/app/constants/index.ts
  src/app/models/ModelInfoUtils.ts
  src/app/ui/views/ToolPathConfigurations/ToolPathConfigurations.jsx
  src/app/ui/views/ToolPathConfigurations/ToolPathFastConfigurations.jsx
  src/app/ui/views/ToolPathConfigurations/laser/GcodeParameters.jsx
  src/app/ui/widgets/GcodeGenerator.js
  src/app/ui/widgets/PrintingVisualizer/VisualizerInfo.jsx
  src/package.json
  src/server/lib/GcodeGenerator/GcodeGenerator.js
  src/server/slicer/call-engine.js
  webpack.config.server.worker.development.js
Labels: Type: Improvement, Category: Laser

#2041 Fix: Fix bounding box of print volume
  src/app/flux/printing/index.js
Labels: Category: 3DP

#2044 Feature: Add goHomeOnConnection option to machine
  src/app/flux/workspace/index.ts
  src/app/flux/workspace/state.ts
  src/app/machine-definition/common/machine.ts
  src/app/machine-definition/index.ts
  src/app/machines/snapmaker-original-extended.ts
  src/app/machines/snapmaker-original.ts
  src/app/ui/widgets/Connection/modals/GoHomeModal.tsx
  src/server/controllers/Marlin/MarlinController.js
Labels: Type: Bug/Bug Fix, Firmware: Snapmaker Original, Category: Printer Control

#2046 Fix: Fix Snapmaker Original module status display
  src/app/constants/copy.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-CN/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/widgets/Connection/NetworkConnection.tsx
  src/app/ui/widgets/Connection/SerialConnection.tsx
Labels: Type: Bug/Bug Fix, Firmware: Snapmaker Original, Category: Laser, Category: Printer Control

#2043 Fix: Fix bug for nesting
  src/shared/lib/nesting/GridProjection.js
Labels: Type: Bug/Bug Fix

#2045 Fix: Fix bug for text
  src/server/lib/svg-convert.js
Labels: Type: Bug/Bug Fix, Category: Laser, Category: CNC

#2051 Fix: Fix profile export error
  src/app/ui/views/CncToolManager/CncToolManager.jsx
  src/app/ui/views/LaserPresentManager/LaserPresentManager.jsx
  src/app/ui/views/PresetModifier/StackPresetSelector.tsx
  src/app/ui/views/PrintingManager/PrintingManager.jsx
Labels: Type: Bug/Bug Fix

#2062 Build: Update monorepo build config
  build/pkgsync.js
  gulp/tasks/server.js
  packages/luban-platform/index.ts
  packages/luban-platform/src/machine-definition/common/machine.ts
  packages/luban-platform/src/machine-definition/common/print-base.ts
  packages/luban-platform/src/machine-definition/common/toolhead.ts
  packages/luban-platform/src/machine-definition/index.ts
  src/app/constants/machines.ts
  src/app/flux/manager/DefinitionManager.js
  src/app/flux/printing/index.js
  src/app/flux/workspace/state.ts
  src/app/machines/snapmaker-2-toolheads.ts
  src/app/machines/snapmaker-a150.ts
  src/app/machines/snapmaker-a250.ts
  src/app/machines/snapmaker-a350.ts
  src/app/machines/snapmaker-artisan.ts
  src/app/machines/snapmaker-j1.ts
  src/app/machines/snapmaker-original-extended.ts
  src/app/machines/snapmaker-original-toolheads.ts
  src/app/machines/snapmaker-original.ts
  src/app/scene/scene.logic.ts
  src/app/ui/pages/print-main/SceneInitialization.tsx
  src/app/ui/views/model-operation-overlay/ChangePrintModeOverlay.jsx
  src/app/ui/widgets/Connection/NetworkConnection.tsx
  src/app/ui/widgets/Connection/SerialConnection.tsx
  src/app/ui/widgets/Connection/modals/GoHomeModal.tsx
  src/app/ui/widgets/Connection/modals/MismatchModal.tsx
  src/app/ui/widgets/Connection/modals/SelectMachineModal.tsx
  src/package.json
  tsconfig-server.json
Labels: Type: Build

#2050 New Crowdin updates
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-CN/resource.json
Labels: Category: Translations

#2065 Improvement: Add quality preset adjustment calculation (nozzle size)
  src/app/constants/preset.ts
  src/app/preset-model/common/PresetModel.ts
  src/app/preset-model/index.ts
  src/app/ui/pages/MachineMaterialSettings/MachineSettings.jsx
  src/app/ui/views/ParamItem.jsx
  src/app/ui/views/PresetModifier/PresetAdjustmentView.tsx
  src/app/ui/views/PresetModifier/quality-preset-adjustment.ts
  src/app/ui/views/ProfileManager/PresetContent.jsx
  src/app/ui/widgets/PrintingConfigurationWidget/ConfigurationView.tsx
Labels: Type: Improvement, Category: 3DP

#2066 Fix: Fix start run G-code via serial port
  src/app/flux/workspace/index.ts
  src/app/ui/widgets/WorkspaceVisualizer/Visualizer.jsx
Labels: Type: Bug/Bug Fix, Category: Printer Control

#2069 Fix: Fix auto quality preset selection
  src/app/constants/machines.ts
  src/app/flux/machine/index.js
  src/app/flux/manager/DefinitionManager.js
  src/app/flux/printing/actions-scene.ts
  src/app/flux/printing/index.js
  src/app/ui/pages/MachineMaterialSettings/MachineSettings.jsx
  src/app/ui/pages/MachineMaterialSettings/index.jsx
  src/app/ui/pages/print-main/SceneInitialization.tsx
  src/app/ui/widgets/PrintingConfigurationWidget/ConfigurationView.tsx
Labels: Type: Bug/Bug Fix

#2074 Fix: Fix mismatch nozzle size in rare cases
  src/app/ui/widgets/Connection/NetworkConnection.tsx
Labels: Type: Bug/Bug Fix

#2093 Refactor: Refactor Laser tool control
  src/app/ui/widgets/ConnectionToolControl/Laser.jsx
  src/app/ui/widgets/ConnectionToolControl/LaserToolControl.tsx
  src/app/ui/widgets/ConnectionToolControl/ToolControlView.tsx
Labels: Type: Refactor, Category: Laser, Category: Printer Control

#2094 Refactor: Refactor print tool control
  src/app/ui/components/EditComponent/EditComponent.tsx
  src/app/ui/components/EditComponent/index.ts
  src/app/ui/components/EditComponent/styles.styl
  src/app/ui/widgets/Connection/modals/MismatchNozzleModal.tsx
  src/app/ui/widgets/ConnectionToolControl/CNC.tsx
  src/app/ui/widgets/ConnectionToolControl/JogDistance.jsx
  src/app/ui/widgets/ConnectionToolControl/JogDistance.tsx
  src/app/ui/widgets/ConnectionToolControl/LaserToolControl.tsx
  src/app/ui/widgets/ConnectionToolControl/ParamsWrapper.jsx
  src/app/ui/widgets/ConnectionToolControl/PrintToolControl.tsx
  src/app/ui/widgets/ConnectionToolControl/WorkSpeed.jsx
  src/app/ui/widgets/ConnectionToolControl/components/AttributeContainer.tsx
  src/server/services/socket/sacp/SACP-BASE.ts
  tsconfig.json
Labels: Type: Refactor, Category: Printer Control

#2096 Feature: Fix bug for slicer error
  package.json
  src/app/config/menu/helpMenu.js
  src/app/constants/copy.js
  src/app/constants/index.ts
  src/app/flux/appbar-menu/index.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-CN/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/layouts/AppLayout.jsx
  src/package.json
  src/server/services/index.js
  src/server/services/socket/ConnectionManager.js
  src/server/services/socket/socket-http.ts
Labels: Category: 3DP

#2100 Improvement: Update translations of zh-CN and jp
  docs/Environment-Linux.md
  docs/Environment-Windows.md
  package-lock.json
  package.json
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-CN/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerPopup.jsx
Labels: Type: Improvement, Category: Translations

#2104 Fix: Fix extruder config output
  packages/luban-platform/index.ts
  packages/luban-platform/src/parameter-resolver/common/parameter-resolver.ts
  packages/luban-platform/src/parameter-resolver/index.ts
  src/app/flux/manager/DefinitionManager.js
  src/server/slicer/definition.js
Labels: Type: Bug/Bug Fix
