Repository Snapmaker/Luban, pull requests merged in 2023-01, with the labels that each got.

#1834 Improvement: German translation
  src/app/resources/i18n/de/resource.json
Labels: Category: Translations

#1836 Improvement: Add close button to change print mode overlay
  src/app/ui/widgets/PrintingVisualizer/ModelLoader.js
  src/app/ui/widgets/PrintingVisualizer/Overlay/ChangePrintModeOverlay.jsx
  src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
  src/app/workers/loadModel.ts
Labels: Type: Improvement, Category: 3DP

#1839 Fix: Fix extruder parameter change
  src/app/flux/printing/index.js
  src/app/ui/pages/Settings/SoftwareUpdate/DownloadUpdate.jsx
Labels: Type: Fix

#1840 Improvement: Improve networked printer auto connect
  src/app/flux/machine/Server.js
  src/app/flux/machine/action-connect.js
  src/app/flux/machine/index.js
  src/app/ui/widgets/Connection/WifiConnection.jsx
Labels: Type: Improvement, Category: Communication

#1843 Feature: Parse progress for 3dp slicee
  src/server/slicer/Slicer.ts
  src/server/slicer/slicer-definitions.ts
Labels: Type: Feature

#1845 Refactor: Refactor parameter resolver to split dependency trees
  .eslintrc.js
  babel.config.js
  package-lock.json
  package.json
  packages/luban-platform/index.ts
  packages/luban-platform/package.json
  packages/luban-platform/src/parameter-resolver/common/parameter-context.es5.js
  packages/luban-platform/src/parameter-resolver/common/parameter-context.js
  packages/luban-platform/src/parameter-resolver/common/parameter-resolver.ts
  src/app/flux/manager/DefinitionManager.js
  src/app/flux/printing/index.js
  src/package.json
  src/server/services/api/api-users.js
  src/shared/lib/definitionResolver.js
  src/shared/lib/definitionResolverEs6.js
  webpack.config.app.development.js
  webpack.config.app.production.js
Labels: Type: Refactor

#1854 Fix: Fix machine value resolves at fetching
  package-lock.json
  package.json
  packages/luban-platform/src/parameter-resolver/common/parameter-resolver.ts
  src/app/flux/manager/DefinitionManager.js
  src/package.json
Labels: Type: Fix

#1857 Feature: Add pre-process of area bed heating for Artisan
  src/app/flux/manager/DefinitionManager.js
Labels: Category: 3DP, Firmware: Snapmaker Artisan

#1856 Fix: Fix canvas size (import STL to laser)
  src/app/ui/views/model-item.jsx
  src/app/ui/widgets/LaserStackedModel/Canvas/index.jsx
Labels: Type: Fix

#1861 Fix: Fix wrong resolve value calculation
  packages/luban-platform/src/parameter-resolver/common/parameter-resolver.ts
  src/app/ui/views/PresetModifier/PresetContent.jsx
Labels: Type: Fix

#1862 Improvement: Fix Laser/CNC configuration view scrollbar
  src/app/flux/widget/WidgetState.js
  src/app/ui/layouts/Widget/index.jsx
  src/app/ui/pages/CncLaserShared/RightView.jsx
  src/app/ui/utils/renderWidgetList.jsx
Labels: Category: UX

#1847 Fix: Fix bug for Camera Capture
  src/app/ui/components/Modal/modal.styl
  src/app/ui/components/Modal/styles.styl
  src/server/DataStorage.js
Labels: Type: Fix, Category: Laser

#1867 Refactor: Add create preset to modifier
  src/app/flux/manager/DefinitionManager.js
  src/app/ui/layouts/AppLayout.jsx
  src/app/ui/views/PresetModifier/PresetContent.jsx
  src/app/ui/views/PresetModifier/PresetModifierModal.jsx
  src/app/ui/views/PresetModifier/StackPresetSelector.tsx
  src/app/ui/views/PresetModifier/usePresetActions.ts
  src/app/ui/views/ProfileManager/PresetContent.jsx
  src/app/ui/views/ProfileManager/index.jsx
  src/app/ui/widgets/PrintingConfigurationWidget/ConfigurationView.tsx
Labels: Type: Feature, Type: Refactor, Category: 3DP

#1869 Fix: Fix networked printer issues
  src/app/flux/machine/Server.js
  src/app/flux/machine/action-connect.js
  src/app/flux/machine/index.js
  src/app/flux/workspace/index.js
  src/app/three-extensions/ManualCalibrationControls.js
  src/app/ui/pages/Workspace.jsx
  src/app/ui/widgets/Connection/MismatchModal.jsx
  src/app/ui/widgets/Connection/WifiConnection.jsx
  src/app/ui/widgets/Marlin/Printing.jsx
  src/app/ui/widgets/WifiTransport/WifiTransport.jsx
  src/app/ui/widgets/WorkspaceVisualizer/Visualizer.jsx
  src/server/services/socket/ConnectionManager.js
  src/server/services/socket/socket-http.ts
Labels: Type: Fix, Category: Communication

#1870 Fix: Fix SM 2.0 extruder temperatures (dual)
  src/app/flux/machine/index.js
  src/app/ui/widgets/Marlin/Printing.jsx
Labels: Category: 3DP, Category: Communication

#1873 Fix: Fix project extruder config
  src/app/flux/project/index.js
  src/app/resources/i18n/cs/resource.json
  src/app/resources/i18n/de/resource.json
  src/app/resources/i18n/en/resource.json
  src/app/resources/i18n/es/resource.json
  src/app/resources/i18n/fr/resource.json
  src/app/resources/i18n/hu/resource.json
  src/app/resources/i18n/it/resource.json
  src/app/resources/i18n/ja/resource.json
  src/app/resources/i18n/ko/resource.json
  src/app/resources/i18n/pt-br/resource.json
  src/app/resources/i18n/ru/resource.json
  src/app/resources/i18n/uk/resource.json
  src/app/resources/i18n/zh-cn/resource.json
  src/app/resources/i18n/zh-tw/resource.json
  src/app/ui/views/PresetModifier/ParametersQuickSettingsView.tsx
  src/app/ui/views/PresetModifier/PresetModifierModal.jsx
Labels: Type: Fix

#1864 Build: Add arm64 build for macOS (Draft)
  .github/workflows/build-on-create-release.yml
  electron-builder.yml
  package.json
Labels: Type: Build

#1868 Fix: Fix linux executable by adding --no-sandbox option to electron
  src/main.js
Labels: Type: Fix

#1874 Improvement: Ukrainian translation
  src/app/resources/i18n/uk/resource.json
Labels: Category: Translations

#1885 Fix: Revert SVG bounding box recalculation
  src/app/flux/printing/index.js
  src/shared/lib/SVGParser/Parser.js
Labels: Type: Fix

#1888 Build: Bump version to 4.5.1 alpha
  package-lock.json
  package.json
  src/package.json
Labels: Type: Build

#1890 Fix: Add guard for reading broken preset files
  packages/luban-platform/src/parameter-resolver/common/parameter-resolver.ts
  src/server/slicer/definition.js
Labels: Type: Fix

#1891 Build: Remove Windows ia32 build script
  .github/workflows/build-on-create-release.yml
  .github/workflows/winget.yml
  package.json
Labels: Type: Build

#1893 Fix: Fix display of right extruder temp. change
  src/app/ui/components/Edit/EditComponent.jsx
  src/app/ui/widgets/Marlin/ParamsWrapper.jsx
  src/app/ui/widgets/Marlin/Printing.jsx
Labels: Type: Fix

#1894 Fix: Prevent laser job from working with invalid focal length
  src/server/services/socket/ConnectionManager.js
Labels: Type: Fix, Category: Laser

#1892 Improvement: Update german translation
  src/app/resources/i18n/de/resource.json
Labels: Category: Translations
